###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите торговца Билла.}
{101}{}{Вы видите торговца, выглядящего намного старше вас.}

{200}{}{Привет, путешественник. Я Билл. Чем могу помочь вам?}
{201}{}{С возвращением. Нужно что-нибудь еще?}
{202}{}{Давайте торговать.}
{203}{}{Я слышал, что вы тот, с кем можно поговорить о караванах.}
{204}{}{Неважно. Пока.}

{210}{}{Я заметил много старого оборудования и разных вещей, собранных здесь, в Аббатстве. Может быть, вы находили что-нибудь... особенное за время своего пребывания здесь?}
{211}{}{Ха, и ты тоже заметил это, да? Да, люди в Аббатстве немного увлекаются всем довоенным, особенно это касается технологий. Они образовали что-то вроде культа вокруг этой машинерии. Я сам не всегда понимаю их, но они хорошие люди и платят мне хорошие деньги за все довоенное, что мне удается достать. Но что касается чего-то особенного... Хм-м... [Он смотрит на Маркуса]. Забавно, что вы спросили. Думаю, у меня есть кое-что интересное для вашего друга.}
{212}{}{Ха, и ты тоже заметил это, да? Да, люди в Аббатстве немного увлекаются всем довоенным, особенно это касается технологий. Они образовали что-то вроде культа вокруг этой машинерии. Я сам не всегда понимаю их, но они хорошие люди и платят мне хорошие деньги за все довоенное, что мне удается достать. Но что касается чего-то особенного... Хм-м... [Он осматривает твою команду.] К сожалению, у меня сейчас нет ничего особенного, что вы бы нашли полезным.}
{213}{}{Ну ладно. Давайте лучше посмотрим, что у вас есть на продажу.}
{214}{}{Хорошо. Позвольте мне спросить вас еще кое-что.}
{215}{}{Что например?}
{216}{}{Видите ли, караван прошел здесь не так давно. Говорили, что они пришли с самого юга. Еще говорили, что в дороге на них напали несколько гнусных мутантов. (Обращаясь к Маркусу) Без обид, большой парень. Что бы там ни случилось, они много хвастали о том, как они порешили всех этих мутантиков. Врали, что мутантов было около дюжины, и я назвал тогда их треп дерьмом брамина. Но, как оказалось, у них имелись некоторые доказательства.}

#new for RP 1.3
{217}{}{Да? И что же это?}
{218}{}{Неуклюжий набор мутантской брони, который они умудрились снять с одного из трупов. Конечно же, исходя из того, что я знаю, можно сказать, что сняли они ее с трупа давно умершего мутанта, на которого они наткнулись в пустошах. Но кто знает? Как бы там ни было, они не стремились тащить эту тяжеленную хрень с собой, поэтому они предложили мне ее за бесценок. Я не знал, что я буду с ней делать, но сделка казалась стоящей.}
#end new and begin reordering
{219}{}{Что ж, я уверен, что Маркус мог бы воспользоваться броней. Сколько за нее?}
{220}{}{Это интересно. Но Маркус у нас достаточно крепкий парень, и я не думаю, что нам когда-либо пригодится эта броня. Позвольте мне спросить вас о чем-нибудь другом.}
{221}{}{Ну, эту штуку можно легко переплавить и сделать три или четыре комплекта металлических доспехов. Скажем, $3000.}
{222}{}{У меня достаточно денег.}
{223}{}{Вы знаете, пока я пас. Позвольте мне спросить вас о чем-нибудь другом.}
{224}{}{Отлично! Но эту вещь можно поднять только вдвоем, так что давайте я вам помогу надеть ее на друга прямо сейчас.}
{225}{}{[Готово]}
{226}{}{Эй, она прекрасно подходит!}
#end

{300}{}{Я кое-что знаю. Что бы вы хотели спросить?}
{301}{}{Как часто вы получаете товар?}
{302}{}{Караванщики нанимают охранников?}
{303}{}{Я должен идти.}
{304}{}{Я получаю новую поставку дважды в месяц. Честно говоря, я хотел бы, чтобы они проходили чаще, но мы находимся на малозначимом торговом пути, и мне кажется, это -- лучшее, что мы можем получить.}
{305}{}{Я бы не сказал. Как правило, те караваны, что останавливаются здесь, довольно хорошо оснащены и не заинтересованы в долгой стоянке. Но если вы хотите присоединиться к одному из них, я бы направился в Реддинг или даже спустился на юг до НКР. У них очень активное движение караванов и хорошие помощники всегда нужны.}
{306}{}{Интересно. Можно еще полюбопытствовать?}
{307}{}{Спасибо. Давайте торговать.}
{308}{}{Что ж, спасибо за информацию. Увидимся.}

{400}{}{Нашли все, что нужно?}
{401}{}{Вообще-то, я бы хотел еще раз взглянуть на ваш товар.}
{402}{}{Да, нашел. Увидимся.}

