###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите Хэнка.}
{101}{}{Вы видите жирного монаха.}
{102}{}{Он балуется с дистиллятором.}

{200}{}{Эй, приятель! Огоньку не найдется?}
{201}{}{Ага. [Даете ему свою зажигалку]}
{202}{}{Отлично. Спасибо!}
{203}{}{Чисто из любопытства, что же ты тут делаешь?}
{204}{}{Конечно. Раз ты дал мне прикурить, вот возьми за мой счет.}
{205}{}{[Выпить]}
{206}{}{Я передумал и не хочу алкоголя. Пока.}
{207}{}{[Вы чувствуете тепло и расслабление после глотка ликера]}
{208}{}{Повтори-ка, Хэнк.}
{209}{}{Я ухожу, до свидания.}
{210}{}{]Вдруг вы почувствовали себя хреново, ваше зрение начинает размываться... Вы падаете на землю...]}
{211}{}{[Закончить]}
{212}{}{Нет, извини.}
{213}{}{Снова привет.}
{214}{}{Привет и до свидания.}
{215}{}{Эта уже не будет бесплатной. Эта обойдется тебе в $20.}
{216}{}{Конечно. Вот деньги.}
{217}{}{Не-а, мне уже достаточно. Может быть, в другой раз.}
{218}{}{[Он кладет себе в карман деньги]. Ну что ж, вот выпивка.}

{220}{}{Как успехи в поисках зажигалки?}

{250}{}{Я хотел бы купить алкоголь, который вы здесь делаете.}
{251}{}{Просто проходил мимо. Пока.}
{252}{}{Конечно. $20 за бутылку.}
{253}{}{[Заплатить]}


{300}{}{Куда я положил свою зажигалку?}
{301}{}{Мне нужна зажигалка.}
{302}{}{МОЖЕТ МНЕ КТО-НИБУДЬ ПРИНЕСТИ ЗАЖИГАЛКУ?}
{303}{}{Эй там, привет.}
{304}{}{К сожалению, я не могу разговаривать с вами сейчас.}

{400}{}{О-о-х, посмотри на все эти прекрасные звезды!}

{500}{}{Здрасьте. Что-нибудь нужно?}
{501}{}{Эй, спасибо еще раз за зажигалку. Она лучше, чем моя старая.}

{600}{}{Здесь, в монастыре, мы делаем свой собственный алкоголь! Самый мощный из всех, которых только можно найти в Пустошах.}
{601}{}{Не возражаете, если я попробую?}
{602}{}{Звучит интересно. Мне нужно идти.}

{700}{}{Это очень плохо. Я потерял свою зажигалку и нигде не могу ее найти. Если тебе когда-нибудь попадется в руки зажигалка, я с радостью приму ее в подарок.}
{701}{}{Конечно. Если я найду зажигалку, я дам тебе знать. Пока.}
{702}{}{Извини. Я немного коллекционер и сохраняю все, что могу найти. Пока.}

#dumb dialgoue
{800}{}{За-жи-ал-ка? У меня есть штука, которая делает огонь. Я обжигался уже много раз. [Вы показываете ему зажигалку]}

{810}{}{Да, это то, что мне нужно. Ты не подаришь ее мне?}
{811}{}{Ладна! Мне она все равно ни нравиться.}
{812}{}{Я ни дам.}

{820}{}{Ты теперь тоже не обожгись! Пока!}


