###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите охранника.}
{101}{}{Он, похоже, работает на торговца.}
{102}{}{Поговорите с начальником, если что-то нужно.}
{103}{}{Не доставляй проблем, слышишь?}

