###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите торговца.}
{102}{}{Вы видите торговца, который пытается починить насос.}
{103}{}{Я просто не могу заставить эту вещь работать!}
{104}{}{Похоже, это очень трудно исправить.}
{105}{}{Ну что это за кусок дерьма!}
{106}{}{Ах ты маленький упрямый сукин сын!}
{107}{}{Не могли бы вы оказать мне помощь?}
{108}{}{Может быть, вам больше повезет с этим.}
{109}{}{Привет, спасибо, что починили насос!}
{110}{}{Вы должны сказать главному монаху, что проблема с помпой решена.}
{200}{}{Спасибо за помощь с этой заразой.}


{300}{}{А, ну что за кусок дерь... К-хм, я немного занят сейчас. Вам что-нибудь нужно или вы просто тратите мое время?}
{301}{}{На самом деле да, аббат послал меня. Он сказал, что у вас есть проблемы с насосом.}
{302}{}{Хех, "есть проблемы" явно преуменьшает задачу. Это старая хрень совершенно оборзела. И никак не запустить ее снова.}
{303}{}{Понятно. Тогда я думаю, ничего плохого не случится, если я посмотрю на него.}
{304}{}{Конечно, делай что угодно. Не думаю, что ты сможешь сломать эту штуку еще больше.}
{305}{}{Я не хочу надоедать, но в чем тут проблема?}
{306}{}{Основной насос аббатства пришел в негодность. Чертова штука была на издыхании последние несколько дней и теперь наконец сдохла.}
{307}{}{Я немного технарь, и не возражаете, если я взгляну?}
{308}{}{Ну, я не силен в механике, но возможно я пойму, можно ли тут что-нибудь сделать.}
{309}{}{Конечно, никто вас не останавливает.}
{310}{}{О, извините. Пока.}
{311}{}{Я посмотрю, что могу делать.}

#added in 1.3
{312}{}{Я думаю, что мог бы помочь, но если вы хотите быть в глазах других мудаком, можете заняться им сами.}
{313}{}{Я сказал аббату, что я мог бы помочь, но если вы хотите быть в глазах других мудаком, можете заняться им сами.}

{320}{}{[Он щурится на вас, потом медленно вздыхает]. Извини, друг, просто эта помпа ведет себя как настоящая сука, она забирает все мое время. Я не хотел ругаться на тебя.}
{321}{}{Так в чем представляется проблема?}
{322}{}{Не важно, до свидания.}

{330}{}{Возвращайся и поговори со мной утром.}
#end added

{400}{}{А, это ты снова. Есть успехи?}
{401}{}{Нет, пока нет. Я вернусь к вам, если сумею.}
{402}{}{Вообще-то да. Я заглянул внутрь и, кажется, мотор полностью сдох. Цепи разорваны, так что вам придется раздобыть новый движок, а также кое-какие провода, чтобы подключить все и заставить это работать, ведь старые кабеля уже никуда не годятся.}

{500}{}{Хм... Цепи разорваны у главного двигателя, да? Ну, какие-то рабочие кабеля здесь есть и у меня, но не от конкретно этого двигателя. Я уверен, что в Городе - Убежище есть запчасти. Сходи туда и поговори с Гарри во дворе. Скажите ему, что Дейв послал вас. Черт, мотор у него будет дорого стоить, но он вам должен дать хорошую скидку.}
{501}{}{Я отправлюсь туда прямо сейчас. Скоро вернусь.}

#added in 1.3
{502}{}{Эй, подождите-ка секундочку. Я был рад помочь вам выяснить причину проблемы, но кто сказал, что я готов пересечь Пустошь, чтобы купить для вас дорогостоящий мотор? Если вы хотите моей помощи, это будет вам кое-чего стоить.}
{503}{}{Как насчет того, чтобы вы сами поговорили с Гарри? Я не вам не мальчик на побегушках! Пока.}

{510}{}{Хорошо, я и не ждал, что кто-то сделает эту работу бесплатно. Деталь будет тебе стоить примерно $500, и я думаю, еще сотня сверху за твое беспокойство будет разумно. Вот $600.}
{511}{}{Вот так-то лучше. Я вернусь с деталью.}
#end added

{600}{}{Ну как дела с запчастью? Помпа сама не починится, знаешь ли.}
{601}{}{Никак, пока нету. Я вернусь, когда достану ее.}
{602}{}{Нормально, запчасть у меня.}

{700}{}{Отлично! Хочешь, чтобы я установил это чертову штуку, или сам попробуешь?}
{701}{}{Я думаю, что у меня получится. Отойдите в сторону.}
{702}{}{На самом деле я думаю, что я и так уже сделал достаточно. Идите и меняйте запчасть сами.}

{800}{}{Ладно, отлично. Давай сюда деталь.}
{801}{}{Вот держи.}

{900}{}{Все должно работать.}
{901}{}{Водяной насос был восстановлен.}

#if head monk gives you the quest
{910}{}{[Салфеткой вытирает пот со лба]. Да, что-то нужно?}
{911}{}{Аббат сказал, вам нужна помощь. В чем дело?}
{912}{}{Все в порядке. До свидания.}

