###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{¬ вашей машине закончилось топливо. —ейчас вам бы пригодилс€ небольшой запас батарей.}
