{100}{}{Вы видите техника.}
{101}{}{Вы видите компьютерного техника.}
{102}{}{Вы видите человека в лабораторном халате, с карманным протектором и несколькими авторучками.}

{103}{}{Добрый день, солдат.}
{104}{}{Пожалуйста, ничего не трогайте.}
{105}{}{Вам, служакам, тут делать нечего.}

{106}{}{Вы одеты не по форме. }
{107}{}{Приведите себя в порядок! Арсенал вниз по коридору налево.}
{108}{}{Не стоит тут ходить без формы, можно нарваться на неприятности. Запросите обмундирование.}

{109}{}{Ребята, вы еще кто такие... Тревога! Чужаки!}
{110}{}{Вторжение на базу! Тревога!}
{111}{}{Несколько чужаков! Поднять тревогу!}

{112}{}{Дьявол! Начать резервное копирование.}
{113}{}{Закрыть все секретные операции.}
{114}{}{Включить защиту системы и подключить все пароли службы безопасности.}

{115}{}{Я ученый , а не боец!}
{116}{}{Наведите на врага заостренный конец с лазерным диодом. Потом нажмите спуск.}
{117}{}{На помощь! На помощь! Компьютерная лаборатория!}
