###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите охранника.}
{101}{}{Вы видите часового в силовой броне.}
{102}{}{Вы видите человека в силовой броне необычного вида. На груди незнакомая вам эмблема.}

{103}{}{Нечего докладывать.}
{104}{}{Со мной все в порядке, а вот как насчет тебя?}
{105}{}{А почему ты не на посту, солдат? Незачем тебе тут шататься.}

{106}{}{Ты одет не по форме.}
{107}{}{Лучше доложи сержанту и пойди, получи обмундирование.}
{108}{}{Не стоит тут ходить без формы, можно нарваться на неприятности. Запросите обмундирование.}

{109}{}{Ребята, вы еще кто такие... Тревога! Чужаки!}
{110}{}{Вторжение на базу! Тревога!}
{111}{}{Несколько чужаков! Поднять тревогу!}

{112}{}{Тревога, тревога! Заблокировать базу!}
{113}{}{Взять под охрану все позиции! Тревога!}
{114}{}{Вторжение! Боевая тревога!}

{115}{}{Мы с тобой разберемся!}
{116}{}{Анклав будет править миром!}
{117}{}{Сдохни, чтобы выжил Анклав!}

{200}{}{...задница...}
{201}{}{...да-а, ЛУЧШЕ вали...}
{202}{}{...что за гнусная свинья...}
{203}{}{...да, сэр! ...на хер, сэр!...}

#added by killap - RP
###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{300}{}{Постой. Что ты думаешь что справишься с вертолетом? Не будет регулярных рейсов на несколько дней вперед.}
{301}{}{Nrg?}
{302}{}{Я отдаю себе в этом отчет.}
{303}{}{Мне очень жаль. Я просто посмотрю и уйду.}
{304}{}{Было изменение планов. Я заберу этот вертолет.}

{310}{}{Что? О, я вижу. Смотри, не трогай. Хорошо? Дотронешься снова умрешь.}
{311}{}{(улыбнуться и атаковать.)}
{312}{}{(уйти.)}

{315}{}{Вот дерьмо, похоже, на нас наткнулся злоумышленник. Код КРАСНЫЙ! Я повторяю, код КРАСНЫЙ!}
{316}{}{Как будто это хорошая идея. Тронешь вертолет снова, и я пущу тебе пулю в голову.}

{320}{}{Правильно. И поэтому ты...}
{321}{}{уйду. Извините, что побеспокоил вас.}
{322}{}{доставлю важное сообщение на главную базу.}
{323}{}{Че, правда? А что это за сообщение, скажи.}
{324}{}{Оно супер Совершенно секретное. Я не могу вам сказать.}
{325}{}{Я вам скажу, но абсолютно неприемлемо, если вы раскроете эту информацию кому-либо еще, из-за опасности массовой паники.
 Примите во внимание, что одна из последних поставок рабов заражена неизвестным и высоко смертельным штаммом вируса.
 Я *должен* попасть на базу немедленно, или все наши жизни могут быть потеряны. Теперь перестань тратить мое время, так как это не тот момент, чтобы ерничать.}
{326}{}{Да, я тебе верю. Похоже, на нас наткнулся злоумышленник...}
{327}{}{Черт! Делай что хочешь. Я никогда не выносил сор из избы. Хорошо. Продолжай то что делал.}
{328}{}{Уооу, звучит фигово. Вам лучше идти, я не хочу этого дерьма на моих руках. И не беспокойтесь, я никому не скажу.}
{329}{}{[СДЕЛАНО]}

{400}{}{[После получаса сидения в темном грузовом отсеке, вы чувствуете, что вертиберд приземлится на землю. Моментом позже грузовая дверь открывается и вы видите команду солдат в силовой броне.
 Один из них шагает к вам и обращается к другим.] Срань Господня! Один из этих мутировавших пустынников отсиживался в птичке! ТРЕВОГА! У нас нарушитель!}
{401}{}{[После получаса сидения в темном грузовом отсеке, вы чувствуете, что вертиберд приземлится на землю. Моментом позже грузовая дверь открывается и вы видите команду солдат в силовой броне.
 Один из них шагает к вам и обращается к другим.] Срань Господня! Несколько из этих мутировавших пустынников отсиживался в птичке! ТРЕВОГА! У нас нарушитель!}

{402}{}{[Выпрыгнуть и посмотреть, скольких вы сможете снять, прежде чем они отмудохают вас.]}
{403}{}{[Поднять руки, сдаться и надеяться на лучшее.]}

{410}{}{Ой, похоже что мутантик не собирается устроить драку. Может быть, мы должны привести его к Коммандеру - посмотрим, что он скажет по этому поводу.}
{411}{}{Ой, похоже что мутантик не собирается устроить драку. Может быть, мы должны привести ее к Коммандеру - посмотрим, что он скажет по этому поводу.}
{412}{}{Ой, похоже что мутантики не собираются устроить драку. Может быть, мы должны привести их к Коммандеру - посмотрим, что он скажет по этому поводу.}


###.Magnat.###...Added by 1C. May be: a)for female characters (require proper scripts); or b) absent in English version...########################
#Женский вариант. Добавил Майкл.
{10106}{}{Ты одета не по форме.}
{10107}{}{Лучше доложи сержанту и пойди, получи обмундирование.}
{10108}{}{Не стоит тут ходить без формы, можно нарваться на неприятности. Запросите обмундирование.}
