###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите человека в силовой броне. }
{101}{}{Перед вами начальник базы Наварро.}
{102}{}{Вы видите человека в силовой броне необычного вида. На груди незнакомая вам эмблема.}

{103}{}{Ребята, вы еще кто такие... Тревога! Вторжение на базу!}
{104}{}{У меня нет времени болтать с нижними чинами. Вы свободны.}
{105}{}{Пришло время умирать.}
{106}{}{Ладно.}

{107}{}{Я же говорю, у меня нет времени. Вон из моего кабинета и не возвращайтесь, пока я не пошлю за вами. Свободны!}
{108}{}{Неподчинение прямому приказу старшего по званию -- это измена. У меня нет времени устраивать военный трибунал, так что придется разобраться по-простому. Охрана! Убить этого идиота!}
{109}{}{Ладно.}
{110}{}{Пошел в жопу!}

{111}{}{Ключ там, в шкафчике. Пусть дежурный офицер свяжется со мной, когда ключ будет в безопасности. Свободны!}
{112}{}{Так точно, сэр!}

{113}{}{Да побыстрее, солдат, я не могу торчать тут целый день.}
{114}{}{Так точно, сэр!}

{115}{}{Оставьте в покое мой сейф, не то вам будет очень больно.}
{116}{}{Так точно, сэр!}

{117}{}{На базе тревога, а я вас не узнаю. Предъявите документы, солдат.}
{118}{}{Какие документы?}
{119}{}{Достало!}
{120}{}{Похоже, их у меня нет при себе...}
{121}{}{Документы? Вот где у меня твои документы!}

{122}{}{Неверный ответ, салага. Солдат должен всегда иметь документы при себе. Вам это отлично известно!}
{123}{}{Пошел на хрен.}

{124}{}{Оставьте в покое мой сейф, не то вам будет очень больно.}
{125}{}{Пришло время умирать.}

#added by killap - RP
###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{200}{}{Хорошо, давайте покончим с этим - мне не нравятся вонючие мутанты в моем офисе, от них воняет дерьмом. Вы работаете на Сальваторе?}
{201}{}{Не твое дело, мудак.}
{202}{}{Я не работаю ни на кого.}
{203}{}{А что, если да?}
{204}{}{Да, я работаю на Сальваторе.}
{205}{}{Прежде чем отвечать на любые вопросы, хочу задать несколько собственных.}

# None of your business, asshole
{210}{}{У меня нет времени на эту фигню. Стража! Убейте этого мутанта!}

#I work for no one
{220}{}{Так ты говоришь, ты не более чем бродячая крыса пустыни, которой посчастливилось пробраться в один из наших вертибердов?}
{221}{}{Ага, да, почти правильно... за исключением той части, что я крыса.}
{222}{}{Это верно.}
{223}{}{Нет, я говорю, что все это просто большое недоразумение. Я не знаю, кто вы, ребята, и мне все равно. Так что если вы не возражаете, я двину потихоньку отсюда.}

{230}{}{Хорошо, если ты одиночка, тогда мне не придется тратить свое время с вами. Стража! Убейте этого мутанта!}

{240}{}{Тебе не уйти отсюда живым, мутант. Я не могу рисковать, ты расболтаешь местоположение этой базы всем своим пустынным друзьям, и что тогда? Стража! Убейте этого мутанта!} 

# So what if I do?/ Yeah, I work for the Salvatores.
{250}{}{Скажи мне то, что я хочу знать, и я постараюсь сделать твою смерть быстрой... и относительно безболезненной. Сальваторе послал тебя сюда?}
{251}{}{Ох... нет? Подождите, да. Может быть.}
{252}{}{Нет. Идея спрятаться в летательном аппарате была полностью моей собственной. Гениально, я знаю.}
{253}{}{Да, он думал, что он добьется лучших условий в торговле, отправив меня с тобой. Что за дела, а?}
{254}{}{Прежде чем отвечать на любые вопросы, хочу задать несколько собственных.}

{260}{}{У меня нет времени на эту фигню. Стража! Убейте этого мутанта!}

{270}{}{Должно быть это смешно, мутант? Я думаю, намного смешнее будет мне, когда ты станешь кровоточащим трупом. Стража! Убейте этого мутанта!}

{280}{}{О, вопросы? [Он смеется.] Ну черт, почему бы и нет? В любом случае ты умрешь. Что ты хочешь знать, мутант?}
{281}{}{Почему вы продолжаете называть меня мутант?}
{282}{}{Кто вы, черт возьми, ребята?}
{283}{}{Где я? }
{284}{}{Как я могу получить такую крутую броню?}
{285}{}{Я слышал достаточно.}

{290}{}{Потому что ТЫ МУТАНТ. Конечно, ты может и выглядишь как представитель рода человеческого, но не позволяй одурачить себя. Ты все еще мутант. Ты и все остальные на материке. Все грязные. Следующий вопрос?}
{300}{}{Мы - Анклав - последний оплот истинного человечества на этой проклятой планете. Мы избраны по-прежнему отстаивать честь белог-сине-красного российского флага.
 Это верно, мы истинные патриоты. Мы сожрем лысых орлов и звезды и дерьмовые полосы. Мы все, что осталось от великих Соединенных Штатов Америки. Но нас достаточно.
 Ах, да, нас достаточно, чтобы сделать все правильно. Ты можешь рассчитывать на это, мутант. Следующий вопрос?}
{310}{}{Это Наварро, наша секретная база на материке. Мы сидим прямо на побережье Калифорнии у Тихого океана. Следующий вопрос?}
{320}{}{Только снять ее с моего мертвого тела. Удачи тебе в этом, мутант. Следующий вопрос?}
{330}{}{Хорошо, потому что я чертовски устал тратить свой воздух на вонь от мутанта. В самом деле, вся эта фигня тратит много моего времени, потому что какой-то летающий пидарас не хочет говорить того, что мне нужно. Стража! Убейте этого мутанта!}


