###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы открываете шкаф и находите там ряды файлов и заметок.}
{101}{}{Искать в шкафу.}
{102}{}{Уйти.}
{103}{}{При поиске по записям в шкафу вы заметили тонкий кожаный портфель, тщательно задвинутый далеко вглубь.}
{104}{}{Вытянуть портфель.}
{105}{}{Игнорировать и продолжить поиск.}
{106}{}{Прошло полчаса, а вы так и не нашли ничего важного. Все, что вы узнали, что Чед записывал и документировал каждый момент своей жизни. Оказалось, он довольно скучный парень на самом деле. Но как только вы собрались закрыть ящики, вы услышали кашель у входной двери и звук поворачивающейся ручки...}
{107}{}{Вытянуть портфель.}

