###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите большое воздушное судно.}
{101}{}{Вы видите вертиберд.}

{200}{}{[Вы поднялись в вертиберд и сели в терминал пилота.] Добро пожаловать в ПосейдонНЕТ. Этот терминал ограничивается передачами между вертибердом взвода Анклава и стыковочным доком. Команда?}
{201}{}{Статус.}
{202}{}{Log off.}
{203}{}{Этот вертиберд имеет достаточное количество топлива для полного полета туда и обратно, из форпоста Наварро к стыковочному доку и обратно.
 Все процедуры полностью автоматизированы и вмешательство членов экипажа не требуется. Текущее состояние топлива: Полный.}
{204}{}{Лететь к нефтяной вышке.}
{205}{}{Log off.}
{206}{}{Ошибка. Желтая карточка реактора не установлена. Всем пилотам выдается эта карта как разрешение на взлет.
 Автоматизированный полет не может происходить без присутствия этой карты.}
{207}{}{Вставить карту.}
{208}{}{Дерьмо. Похоже, мне придется найти эту карту.}
{209}{}{Карта принята. Вертиберд активирован.}
{210}{}{Запустить предполетную диагностику.}
{211}{}{Log off.}

{212}{}{Начало системной диагностики... 35% выполнено... 75% выполнено... 100%. Все системы в норме. Проверка на ответ от стыковочного дока...}
{213}{}{[БОЛЬШЕ]}
{214}{}{Нет ответного сигнала из дока. Причина: Спутники не выровнены на автоматическую стыковку с нефтяной вышкой. Пожалуйста, убедитесь, что доку известно о наличии входящего вертиберда.}
{215}{}{Хм... Похоже, мне придется найти способ выровнять спутники.}
{216}{}{Че?}

{220}{}{Вертиберд уже активирован. Команда?}
{221}{}{Запустить предполетную диагностику.}
{222}{}{Log off.}

{230}{}{Тестовый сигнал получен. Получение координат дока... завершено. Самолет готов к взлету.}
{231}{}{Поехали.}
{232}{}{Log off.}

{240}{}{Вертиберд выведен на цель. Время полета составит примерно 6 часов. Желаем Вам приятного полета.}
{241}{}{Вот он - момент истины. Племя в беде, и это подстегивает меня. Мои ноги болят, все мое тело болит, и я не помню, когда в последний раз я ел достойную пищу. Для этого момента мы живем. И нет пути назад. Время показать миру, из чего сделан }
{242}{}{ . Берегись, Анклав!}
{243}{}{Хе-хе... Лети птичка, лети! }
{244}{}{ сегодня неопасный.}

#beat enclave...
{300}{}{[Вы поднялись в вертиберд и сели в терминал пилота.] Добро пожаловать в ПосейдонНЕТ. Этот терминал ограничивается передачами между вертибердом взвода Анклава и стыковочным доком. Команда?}
{301}{}{Статус.}
{302}{}{Log off.}
{303}{}{Этот вертиберд имеет достаточное количество топлива для полного полета туда и обратно, из форпоста Наварро к стыковочному доку и обратно.
 Все процедуры полностью автоматизированы и вмешательство членов экипажа не требуется. Текущее состояние топлива: Пусто.}
{304}{}{Log off.}

