###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите сквоттера.}
{101}{}{Вы видите мужчину в грязи и мерзости.}
{102}{}{Вы видите женщину в грязи и мерзости.}

{103}{}{Эй чувак, мы были здесь первыми. Чего ты хочешь?}
{104}{}{Я хочу, чтобы ты и твои друзья свалили из этого здания. Это к тому, что мама собирается превратить это место в детский дом, чтобы убрать всех эти бездомных детей с улиц.
 И она не может сделать это пока ты здесь.}
{105}{}{[Он беспокоится и поглядывает на своих коллег-скваттеров ища поддержку.] Мы же предлагали Маме сделку. Мы никуда не поедем пока она не заплатит. Так что если вы не принесли
 нам миллион монет, отебитесь.}
{106}{}{Послушай, у Мамы нет таких денег. Даже если она и согласилась на сделку, она никогда не заплатит, так что просто забудь об этом. Почему бы не проявить капельку приличия и не пойти захватить какой-нибудь другой дом? Эти бездомные дети нуждаются в этом чертовом месте гораздо больше, чем вы.}
{107}{}{Да кто ты такой, чтоб говорить кто чего заслуживает? Мы *уже* здесь. И вы не сможете заставить нас уйти!}
{108}{}{Слушай, у вас есть два варианта: Вы можете выйти отсюда на своих ногах, или *Я* могу удалить вас - путем перетаскивания одного трупа за раз.}
{109}{}{[Он обменивается взглядами со своими друзьями скваттерами, потом оглядывается на тебя и трясет головой.] Вы не сможете запугать нас. Никто не вышвырнет нас отсюда. Мы будем бороться за нашу территорию.}
{110}{}{[Он обменивается взглядами со своими друзьями скваттерами, потом оглядывается на тебя и трясет головой.] Ладно, вы сделали свой ход. Не подумай, что мы ненавидим детей или типа того. Черт, большинство из нас сами быти бездомными детьми. Мы просто пытаемся заработать немного денег.Работы тут нет, только или торговать наркотиками или грабить, мы этим не занимаемся. [Вздыхает.] Мы уйдем, но куда? Это место наш дом.}
{111}{}{Я не знаю. Это не моя проблема.}
{112}{}{Я конечно могу пожалеть об этом, но если вы всерьез хотите работать, я уверен, что мама может использовать вашу помощь в ремонте этого места. Она реально милая дама, так что, если вы извинитесь, возможно она даст вам шанс доказать, что вы больше, чем группа ленивых скваттеров. Я поговорю с ней об этом. Но если вы попытаетесь наебать ее, я буду охотиться на вас и заставлю заплатить за это.}
{113}{}{Нах чувак. Я передумал. Мы не уходим. Мы остаемся здесь и деремся.}
{114}{}{[Он обменивается взглядами с другими жильцами и обдумывает твои слова.] Знаете, что? Это вовсе не так уж плохо. Фактически, возможность работать великолепно, если вы действительно уговорите Маму пойти на это. Пока вы поговорите с ней, мы начнем очищать это место. Да, и спасибо за то, что так здорово рассуждаешь о разных вещах.}
{115}{}{Не важно.}

#new for RP 1.3
{116}{}{Она не собирается вам платить. Но я здесь, чтобы предложить Вам новую сделку: Ты и твои друзья уходите отсюда сейчас, и вы сохраняете свою жизнь.}
{117}{}{Ладно, тогда получи пулю. Прощай.}


{120}{}{Это отличная идея. Мы собираемся.}

{200}{}{А?}
{201}{}{Это наша земля.}
{202}{}{Ты тоже хочешь здесь поселиться?}
{203}{}{Есть че поесть?}

{300}{}{Вы видите мужчину в рабочей одежде.}
{301}{}{Вы видите женщину в рабочей одежде.}

{310}{}{Эй, спасибо, что сообщили нам остаться. Мы будем напряженно работать.}
{311}{}{Ты лучший. Убедитсь, что дети держаться подальше от неприятностей.}
{312}{}{Мы сделаем все возможное.}
{313}{}{Пока.}

#third way to finish quest -added after initial creation, but before official release
{350}{}{Где угодно, но не здесь. Яма - большое место, я уверен, вы сможете найти другое место чтобы сдохнуть. А сиротам нужно место чтобы жить, и нет другого здания достаточно большого для всех их. Я уверен, вы сможете найти другое место для жизни. Ну, вы действительно хотите оставить детей жить на улице?}
{351}{}{Нет, вы правы, что это не круто для детей. В любом случае тут крыша протекает . Хорошо, мы будем собирать вещи и переезжать. Мы скваттеры по любому, любой дом достаточно хорош для нас.}
{352}{}{Спасибо. Это будет много значить для них. Будьте осторожны.}
{353}{}{Нах чувак, это не наша проблема. Если мама считает, что ей важно заполучить тех детей с улиц, то она должна раскошелится и поделиться долей своего богатства. Я передумал, мы решили остаться, пока она не заплатит нам. Этот разговор окончен, так что вам лучше уйти.}

{360}{}{Ладно. Не нужно выходить из себя. Я оставлю вас в покое.}
{361}{}{Тогда время очистить это место. (Атакуешь)}

{400}{}{Еще раз спасибо!}
{401}{}{Мы будем напряженно работать.}
{402}{}{Спасибо, что позволили нам остаться.}
{403}{}{Мы не позволим тебе упасть.}

{500}{}{Мы собираем наши вещи и уходим отсюда в ближайшее время.}
{600}{}{Вы очистили здание от скаттеров.}


