###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите головореза.}
{101}{}{Он друг Тайлера.}

{110}{}{Ты здесь, чтобы веселиться?}
{111}{}{*икает* Налейте мне!}
{112}{}{Шлюха вон, если вдруг надумаешь.}

{120}{}{Никто не ломает кайф, когда я рядом.}

{130}{}{Мы показали тем неудачникам... Испортить *икает* такую вечеринку...}
