###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите ребенка.}
{101}{}{Вы видите мальчика. Он выглядит счастливым.}
{102}{}{Вы видите девочку. Она выглядит счастливой.}

{200}{}{Привет, мистер!}
{201}{}{Извините, что пытался обокрасть вас.}
{202}{}{Мне очень нравится здесь.}
{203}{}{Спасибо за помощь Маме!}

{300}{}{Привет, мисс!}
{301}{}{Извините, что пытался обокрасть вас.}
{302}{}{Мне очень нравится здесь.}
{303}{}{Спасибо за помощь Маме!}


