###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите жителя Дыры.}
{101}{}{Вы видите жителя Дыры.}

{200}{}{Здравствуйте и добро пожаловать в... Эй! Это ведь ты помог сделать это место лучше! Народ Дыры действительно ценит твою помощь.}
{201}{}{Это очень приятно. Как чувствуют себя дети?}
{202}{}{С ними все хорошо. Спасибо тебе, что они ушли с улиц и теперь имеют дом. Скваттеры, с которыми ты говорил, также оказывают большую помощь. Еще раз спасибо за все!}
{203}{}{С ними все хорошо. Спасибо тебе, что они ушли с улиц и теперь имеют дом. Еще раз спасибо за все!}
{204}{}{Рад слышать это. Береги себя.}
{205}{}{Здравствуй еще раз! Помочь чем-нибудь?}
{206}{}{Нет, просто осматриваюсь.}

