###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Неполадка биохранилища!}
{101}{}{Уровень 4 - прорыв защиты.}
{102}{}{Уровень 4 - заражение.}
{103}{}{Биозащита уровня 3 прорвана.}
{104}{}{Уровень 3 - прорыв защиты.}
{105}{}{Уровень 3 - заражение.}
{106}{}{Биозащита уровня 2 прорвана.}
{107}{}{Уровень 2 - прорыв защиты.}
{108}{}{Уровень 2 - заражение.}
{109}{}{Биозащита уровня 1 прорвана.}
{110}{}{Уровень 1 - прорыв защиты.}
{111}{}{Уровень 1 - заражение.}

# X minutes and Y seconds to evacuate.
{112}{}{ минута и }
{113}{}{ минуты и }
{114}{}{ минут и }
{115}{}{ секунда до эвакуации.}


###.Magnat.###...Added by 1C. May be: a)for female characters (require proper scripts); or b) absent in English version...########################
{116}{}{ секунды до эвакуации.}
{117}{}{ секунд до эвакуации.}
