###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы наткнулись на собрание важно выглядящих людей. Вы чувствуете в них что-то особенное.}
{200}{}{О нет, только не очередная отсылка к поп-культуре!}
{5000}{}{Здесь нельзя вступать в бой.}


