###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите путешественника.}
{101}{}{Этот человек, кажется, что-то ищет.}


{200}{}{Это работорговец! Убить его!}
{201}{}{Смерть угнетателю!}
{202}{}{Смерть мерзкому работорговцу!}
{203}{}{Долой рабство! Смерть работорговцам!}
{204}{}{Сдохни, бесчеловечный скот!}

{250}{}{Привет!}
{251}{}{Эй, незнакомец!}

{300}{}{Привет! Что ты делаешь в этих краях?}
{301}{}{Я потерялся.}
{302}{}{Слоняюсь тут без дела.}
{303}{}{Ничего особенного. А вы что здесь делаете?}
{304}{}{Ищу, кого бы убить.}
{305}{}{Нет, ничего.}
{306}{}{Ась?}

{307}{}{Э-э, думаю, мне пора. До встречи.}

{310}{}{Хотелось бы мне помочь вам, но я блуждаю здесь уже очень давно и уже толком не знаю, где тут что.}
{311}{}{Почему вы тут бродите?}
{312}{}{Что вы тут делаете?}
{313}{}{Что ж, удачи вам.}

{314}{}{Ладно, удачи вам. Да, кстати, остерегайтесь Дыры. Они там любят продавать людей.}
{315}{}{Дыры?}
{316}{}{Продавать людей?}
{317}{}{Конечно, обязательно. Пока.}

{320}{}{Похоже, людям в этих местах нравится держать у себя рабов. А я пытаюсь этих рабов освободить. И если кто-то из рабовладельцев помрёт в процессе, я не сильно огорчусь.}
{321}{}{А что такого плохого в том, чтобы держать рабов? Я бы прикупил себе парочку, если б знал, где.}
{322}{}{Буду смотреть в оба. Вот ублюдки!}
{323}{}{Убийство нельзя оправдать.}
{324}{}{Вы планируете кое-кого убить? Я вам помогу.}

{330}{}{Правда? Это здорово. Ладно, мне пора отправляться в путь, искать и освобождать рабов.}
{331}{}{Удачи.}

{335}{}{Нет, порой приходится убить нескольких людей, чтобы спасти многих. Чем-то приходится жертвовать. К тому же они рабовладельцы - это, считай, и не люди вовсе.}
{336}{}{Да, вы правы. Ладно, мне пора.}
{337}{}{Правда? А ты для меня труп.}
{338}{}{Конечно. Пока.}

{340}{}{Ах ты ублюдок! Я тебя убью за это!}
{341}{}{Ах ты сука! Я тебя убью за это!}
{342}{}{Или наоборот, если я прикончу тебя раньше!}

{350}{}{Да. Они нападают на небольшие группы людей. Всех, кто останется в живых, продают с аукциона.}
{351}{}{Какой кошмар. Я буду остерегаться их. Спасибо.}

{355}{}{Дыра -- это город. Тамошние жители специализируются на работорговле и прочих гнусностях. Подонок на подонке.}
{356}{}{Спасибо за информацию. Пока.}

{360}{}{Ищу способ остановить работорговлю.}
{361}{}{Что вы имеете в виду?}
{362}{}{О, хорошо. Удачи вам.}
{363}{}{Ага. Пока.}

{370}{}{Займитесь работорговцами. Убивать их просто замечательно. Море крови и удовольствия.}
{371}{}{Клево. Спасибо за информацию.}
{372}{}{Так ты же передо мной. Я лучше тебя прикончу.}
