###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Это мой дом.}
{101}{}{Проклятые бандиты.}
{102}{}{Оставьте нас в покое!}

{200}{}{Это мой дом.}
{201}{}{Проклятые бандиты.}
{202}{}{Оставь нас в покое!}
{203}{}{Ненавижу бандитов.}
{204}{}{У нас нечего красть.}
{205}{}{Не убивай меня.}
{206}{}{С меня хватит.}
{207}{}{Бери что хочешь.}
{208}{}{Пожалуйста, не убивай меня.}
{209}{}{Все равно мне не нравится фермерство.}
{210}{}{Пожалуйста не сжигай дом.}

{220}{}{Не мешай мне.}

{230}{}{Благодарим вас за помощь.}
{231}{}{Я хочу чтобы было больше таких людей, как ты в этом мире.}


###.Magnat.###...Added by 1C. May be: a)for female characters (require proper scripts); or b) absent in English version...########################
{103}{}{Ненавижу бандитов.}
{104}{}{У нас нечего красть.}
{105}{}{Не убивайте меня.}
{106}{}{С меня довольно.}
{107}{}{Берите, что хотите.}
{108}{}{Пожалуйста, не убивайте меня.}
{109}{}{Все равно мне не нравилось ковыряться в земле.}
{110}{}{Пожалуйста, не сжигайте дом.}
