###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите шамана кочевников.}
{101}{}{Кажется, это шаман кочевников.}
{102}{}{Его одежда насквозь пропитана сильным запахом трав.}
{103}{}{Привет, незнакомец. Я шаман этого племени. Я искушен в искусстве исцеления.}
{104}{}{Привет еще раз.}
{105}{}{Мне нужно лечение.}
{106}{}{Ты можешь смешать корень Зандер с цветком Брок?}
{107}{}{Пока.}
{108}{}{Ууга.}
{109}{}{Не шевелись, я осмотрю тебя.}
{110}{}{[Дальше]}
{111}{}{Вот что за недуги я нашёл.} #continue at 136
{112}{}{Ты можешь мне помочь?}
{113}{}{За определенную плату я могу сделать следующее:} # continue at 140
{114}{}{Очисти мое тело от яда, пожалуйста.}
{115}{}{Вылечи меня, пожалуйста.}
{116}{}{Посмотри, можно ли что-то сделать с моей травмой.}
{117}{}{Пока.}
{118}{}{Вы исцелены.}
{119}{}{Вы исцелены.}
{120}{}{Вы исцелены.}
{121}{}{Я снова нуждаюсь в твоей помощи.}
{122}{}{Спасибо; мне стало намного лучше. Пока.}
{123}{}{Мои возможности не безграничны, и тут я больше ничем не могу помочь.}
{124}{}{[Дальше]}
{125}{}{Ты не нуждаешься в таком лечении.}
{126}{}{[Дальше]}
{127}{}{А-а... Тебе знакомы целебные свойства этих двух растений. Всего лишь за} # continue at 150
{128}{}{Пожалуйста, смешай для меня два этих растения.}
{129}{}{Может быть, позже, до встречи.}
{130}{}{[На ваших глазах он аккуратно растирает и смешивает два растения и протягивает вам тщательно отмеренную дозу порошка.]}
{131}{}{Пока.}
{132}{}{Похоже, ты на мели. Заходи позже, когда в кошельке заведутся деньжата.}
{133}{}{[КОНЕЦ]}
{134}{}{У меня нет времени на такую чепуху. Уходи!}
{135}{}{[КОНЕЦ]}
{136}{}{[Отравление]}
{137}{}{[Ранение]}
{138}{}{[Облучение]}
{139}{}{[Травма]}
{140}{}{Вывести яд,}
{141}{}{Исцелить травмированные части тела,}
{142}{}{Лечение $}
{143}{}{Язычник!}
{144}{}{Почему ты нападаешь на нас?}
{145}{}{Я готов отдать жизнь, защищая свое племя!}
{146}{}{Как ты смеешь так платить нам за гостеприимство!}
{147}{}{Убирайся!}
{148}{}{Оставь нас.}
{149}{}{Мы мирное племя.}
{150}{}{Я сделаю тебе целебный порошок.}

