###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите кочевника.}
{101}{}{Здравствуй, ты тут впервые?}
{102}{}{Лучше тебе поговорить с главным.}
{103}{}{По-моему, сегодня не так жарко, как вчера.}
{104}{}{Так как там живётся в городах?}
{105}{}{Язычник!}
{106}{}{Почему ты на нас нападаешь?}
{107}{}{Я отдам жизнь за своё племя!}
{108}{}{Как ты посмел презлым отплатить за предобрейшее!}
{109}{}{Убирайся!}
{110}{}{Оставь нас.}
{111}{}{Мы мирное племя.}

