###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите Старателя.}
{101}{}{Стоять! Обычно я не устраиваю засады на незнакомцев, но у меня кончились припасы, а я не могу оставить свой участок. Поторгуем?}
{102}{}{Конечно.}
{103}{}{Мне нечем торговать. Извините.}
{104}{}{Буууга.}
{105}{}{Что за удар судьбы. Ты не умеешь говорить? Ну, значит, не разболтаешь никому, где мой участок. Давай торговать.}
{106}{}{[Торговать]}
{107}{}{Ладно, убирайся! И не вздумай никому рассказывать про мой участок.}
{108}{}{[Конец]}
{109}{}{Лучше не задерживайся.}
{110}{}{Нам больше не о чем говорить.}
{111}{}{Иди своей дорогой!}
{112}{}{Занимайся своими делами.}
{113}{}{Жаль, что тебе не запретишь рассказывать о том, где мой участок.}
{114}{}{Почему ты идёшь против меня?}
{115}{}{Теперь мне придется тебя убить.}
{116}{}{Мне просто нужны были припасы.}
{117}{}{Можешь забрать мой участок!}
{118}{}{Пощади!}

