###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите грубого человека.}
{101}{}{Вы видите налетчика.}

{200}{}{Это наша земля. Умри!}
{201}{}{Как ты смеешь приходить сюда без спросу!}
{202}{}{Умри, городское племя!}
{203}{}{Твоя смерть принесет мне немного денег.}
{204}{}{Беги, жалкая тварь!}
{205}{}{Вы знаете правила, джентльмены.}
{206}{}{Свидетелей не оставлять.}
{207}{}{Прикройте меня.}
{208}{}{Никого не щадить!}
{209}{}{Босс говорит, пленных не брать.}
{210}{}{Бишоп сказал стрелять непрошеных гостей.}
{211}{}{Пора подзаработать!}


{300}{}{Перед вами Лягушка Мортон.}
{301}{}{Перед вами Жаба Мортон.}
{302}{}{Перед вами Тритон Мортон.}
{303}{}{Перед вами Змей Мортон.}

{305}{}{Убийца моего брата! Я отомщу за него!}
