###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы разведали обнесенный стеной объект, похоже, заброшенный очень давно. Его неухоженная территория теперь кишит плотоядными растениями.}

