###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Ћифт со скрежетом останавливаетс€, вы слышите пошЄлкивание и царапание вокруг вас. ¬переди потрескивает силовое поле, блокиру€ ваш путь.}


