###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите образец из криорезервуаров.}
{101}{}{Вы видите Китсан.}
{102}{}{Ее глаза разного цвета. Один из них коричневый malmbrick, другой ярко-зеленый.}
{103}{}{Вы видите стройную, темноволосую женщину, которая выглядит труднопредсказуемой.}
{104}{}{У нее мягкое лицо и чарующие глаза.}

{150}{}{На это неприятно смотреть.}

{200}{}{Перед вами лежит открытый резервуар с ледяной водой, которая постепенно сливается через длинную, тонкую трубу. Внутри Женщина, совершенно обнаженная, лежит задыхаясь и дрожа. Быстро оглядевшись, вы выхватываете какую-то одежду из соседнего шкафчика и накрываете ее для тепла.}
{201}{}{Ух ты. Это должна была быть долгая отключка. Ты в порядке?}
{202}{}{Д-да, П-П-пресерватор восстановил мою темп т-т-ттемпературу.}
{203}{}{Not all of it, it looks like. }
{204}{}{[Вы ждете некоторое время, чтобы ее зубы перестали стучать. Она восстанавливается гораздо быстрее, чем вы ожидаете и она смотрит на вас с внезапной тяжестью.] Все... кончено?}
{205}{}{Что значит *кончено*? }
{206}{}{Вы имеете в виду Войну?}
{207}{}{Война. Все это ядерное оружие.}
{208}{}{Войну, да.}
{209}{}{Эта война закончилась давным давно. Закончилась почти сразу как началась.}
{210}{}{[Она откидывает мокрые пряди волос с глаз. Вы замечаете, что один глаз коричневый, а другой изумрудно-зеленый.] Кто выиграл?}
{211}{}{Никто.}
{212}{}{[Она тупо смотрит на тебя. На взгляд она очень легкая, особенно для той, кто был просто глыбой льда.]}
{213}{}{Когда 90% мира выжженны до хрустящей корочки, я бы сказал сложно установить явного победителя. Я имею в виду, праздновать победу особо некому.}
{214}{}{Что... Какое сегодня число? Какой год? Это еще 2077-й?}
{215}{}{Черт, нет. [Вы показываете ей дату в календаре вашего Пип-боя.]}
{216}{}{[Она смотрит на мерцающий экран, замороженная во времени, как буд-то она никогда не покидал танка.]}
{217}{}{Ты в порядке?}
{218}{}{Боже мой. Я не верю в это. Я была в этой штуке на протяжении века?!}
{219}{}{Кажется да, типа того. Эй, слушай, не смотри на меня так. У меня нет ничего общего с теми, кто положил тебя туда. Дьявол, даже мой дед тогда уже не был живой. Я просто наткнулся на это место и решил проверить его.}
{220}{}{Ну, ты поможешь мне встать, или думаешь будет лучше, если я продолжу сидеть голая у твоих ног?}
{221}{}{Я как раз собирался. [Вы помогаете ей встать на ноги.]}
{222}{}{Почему ты разбудил меня?}
{223}{}{Без особых оснований.}
{224}{}{У меня есть страшная привычка трогать все, что я встречу. Одно привело к другому.}
{225}{}{Вы говорите, что вы даже не работаете в этом месте?}
{226}{}{Именно это я сказал.}
{227}{}{Тогда, если бы ты не пришел, я бы застряла здесь еще надолго. Может быть, навсегда. [Она натянула одну из рубашек в которые вы завернули ее через голову.] Как сейчас мир там? Ты сказал, что на 90% он был уничтожен?}
{228}{}{Мой мир - пустыня, где каждый день идет борьба за выживание. Большинство людей нашли приют в разрушенных остатках старых городов. Другие, например мои соплеменники, пытаются наладить простое существование в суровой пустыне.
 По правде говоря, пройдут еще века прежде чем мы хотя бы приблизимся к восстановлению.}
{229}{}{Не может быть так плохо, как ты говоришь. [Ее похоже не убедили слова которые ты только что сказал.]}
{230}{}{Ничего похожего на Америку в 2077-ом, это точно.}
{231}{}{[Она натягивает штаны.] Итак, что же теперь?}
{232}{}{Мне никогда не удавалось правильно представить себя. Меня зовут }
{233}{}{. А как твое имя?}
{2330}{}{А как насчет сказать мне свое имя? Я }
{234}{}{Можешь называть меня Китсан.}
{235}{}{Китсан, что вы делали глубоко замороженной в этом танке?}
{236}{}{Я не знаю точно. Они знали, что Война вот-вот должна произойти, и они посадили меня в презерватор как и других.}
{237}{}{У вас есть какие-то подсказки, что это за место?}
{238}{}{Из того, что я знаю, это филиал агентства по охране окружающей среды США. Я была в Аризоне, когда Война началась. Меня взяли сюда немедленно.}
{239}{}{Вы, должно быть, очень важны для них, чтобы они захотели сохранить вас. Были ли вы Избранной, как я?}
{240}{}{Ох, нет вообще-то. Я домохозяйка, замужем за членом городского совета. До этого я писала для различных новостных изданий. Это не то, что ты назвал бы очень интересной жизнью.}
{241}{}{Что с ним случилось, с твоим мужем?}
{242}{}{Я не знаю. Вероятно, он стал одной из миллиардов жертв. Я сомневаюсь, что кто-нибудь из моей семьи прошел через войну. Боже мой, даже если они это сделали, это было так давно... все, кого я когда-либо знала мертвы. [Она кусает губы, и глаза ее начинают мерцать слезами, но она быстро вытирает их и вздыхает, в результате берет себя в руки.]}

#dialogue added 12/31/08
{245}{}{Ну, так вы даете мне выбор... [Ухмылка]}
{246}{}{[Она смотрит на вас без слов.]}
{247}{}{О, я имею в виду, конечно, я помогу тебе. [Вы помогаете ей встать на ноги.]}


#join me
{250}{}{Что ты собираешься делать теперь?}
{251}{}{Я не знаю. Что бы ты сделал, если бы тебя заморозили на протяжении века? Даже медведи не спят так долго. Мир снаружи не тот мир, который я знала. Я не знаю, смогу ли я устоять, увидив во что он превратился.}
{252}{}{Я знаю, там только пустырь, но у тебя впереди еще целая жизнь. Не трать ее здесь. Пойдем со мной и, возможно, мы сможем сделать что-нибудь для пустыни.}
{253}{}{Не похоже что у вас есть много вариантов. Ты можешь сидеть здесь и гнить, или ты можешь пойти со мной. Все зависит от тебя.}


#join success
{260}{}{Знаешь, ты прав. Я могла бы вернуться в заморозку и проспать еще сто лет, но это будет фиговым выходом из положения. Я должна увидеть сама, что стало с миром, и сыграть свою роль в его восстановлении.}
{261}{}{Тогда пойдем. Только сначала съедим по браминскому стейку.}
{262}{}{Не заставляй меня сожалеть об этом.}

#join failure
{270}{}{Забудь об этом. Так было на протяжении более сотни лет. Почему ты думаешь, что мы сможем исправить это сейчас?}
{271}{}{Я вернусь. Может быть, ты изменишь свое мнение.}
{272}{}{Может быть. Но не рассчитывай что это случится. Я просто пойду спать еще на век или около того.}

#2nd chance at join failure
{280}{}{Что если эти машины перестанут работать, а? Ты будешь мертва и никогда не узнаешь, будет ли мир, который взорвал себя снова целым.}
{281}{}{Тогда я буду смотреть на мир со своего места.}
{282}{}{Как ты можешь знать наверняка, что когда-нибудь где-нибудь ты проснешься, особенно после долгово, очень долгово большого сна? Я родом из племени, которое верит в загробную жизнь и пророчества, но с прагматической точки зрения мы все просто набор органических систем, мы думаем, говорим и чувствуем благодаря электричеству и химическим компонентам. Что если нет ничего после смерти - мы шатдаунимся как компьютеры - и это все, что ты получишь?}
{283}{}{Я лучше доверю свой шанс криогенной заморозке, чем бродить по этой пустыне.}
{284}{}{Точно? Ты кажется не вполне уверенной.}
{285}{}{[Китсан размышляет над вашими словами всерьез и долго. Наконец она смотрит на вас.] Я не могу притвориться, что ты не прав. Может быть... может быть, я доверю свой шанс тебе.}
{286}{}{Давайте убираться отсюда. Время оставить эту свалку позади.}

#NPC doesn't join and leaves for good
{287}{}{На самом деле, я думаю, что пойду сама по себе. Я всегда была независимой, поэтому никто никогда не прикрывал меня со спины. Многое изменилось, пока я отсутствовала, и я хотела бы увидеть новый мир. Спасибо за разморозку. Позаботься о себе.}
{288}{}{[Готово]}

#in party
{300}{}{Да?}
{301}{}{Внимательно слушаю.}
{302}{}{Ты что-то хотел?}
{303}{}{Что это такое? Ты как-будто хочешь что-то сказать.}
{304}{}{В чем дело?}
{305}{}{Что-нибудь нужно от меня?}

#past
{310}{}{Китсан, я уверен, тебя бы не заморозили в крио танке безо всякой на то причины. Мне интересно, чем именно ты занималась раньше, до того как тебя положили на лед.}
{311}{}{Почему тебя это заботит? Это все в прошлом.}
{312}{}{Мы вместе вышли на дорогу и мне придется узнать о тебе больше.}
{313}{}{[вздыхает.] Ну, я полагаю, больше нет необходимости в тайне. Просто трудно преодолеть многолетние привычки. Видишь ли, я была рождена шпионкой.}
{3130}{}{Хорошо. Это уже что-то.}
{314}{}{Мой отец был китайцем, но он и его семья не были друзьями китайского правительства. Он родился в Пекине, но получил образование здесь, в Штатах. Когда он вернулся домой и устроился на работу в качестве государственного служащего, он уже был завербован американцами как тайный агент.}
{315}{}{Я не слишком знаком с политикой того времени, но я думаю, что понимаю, о чем ты говоришь: твой отец был китайцем, но тайно шпионил в пользу американцев. А китайцы когда-нибудь подозревали его?}
{316}{}{Мой отец был работал в Министерстве сельского хозяйства тридцать восемь лет.}
{317}{}{Ух, хорошо, я предполагаю, что это "нет". Итак, что дальше?}
{318}{}{Ну, в один прекрасный день, официальная помощница моего отца поймала его на копировании секретных документов.}
{319}{}{Это не могло бы быть хорошо...}
{320}{}{На самом деле, это оказалось не так уж плохо. Она работала по той же схеме, как и мой отец, и через несколько месяцев они поженились.}
{321}{}{У некоторых ребят есть удача, а?}
{3210}{}{Хорошо, теперь я знаю историю жизни твоего отца. Ты не против, если теперь мы послушаем часть о тебе?}
{322}{}{Они родили меня годом позже. Я была воспитана в Китае под личиной патриотки. В школе я писала о том, что Китай стал сильнейшим, когда объединился, и как мы должны были продолжать стремиться к социальному равенству.
 Когда я стала старше, я писала для националистических газет и участвовала в дебатах в поддержку правящей партии.}
{323}{}{Ничего себе, большую часть этих слов я раньше не слышал. Но если я правильно понимаю, ты говоришь, что ты и твои родители обманывали китайцев притворяясь, что вы были лояльны.}
{324}{}{Твои родители наверняка приложили большие усилия, чтобы истинная лояльность вашей семьи остались тайной.}
{325}{}{Все войны основан на обмане. Мои родители любили свою страну. Они просто ненавидели людей, которые сбежали и думали, что здесь стало бы лучше, если придет демократия. Как они видели это - они не предают Китай - они работают против правительства, которому они не верили, и это хорошо для Китая.}
{326}{}{Продолжай.}
{3260}{}{Итак, они были предателями своего народа, но для блага своего народа. Понял.}
{3261}{}{Слушай, я устал слушать о твоих родителях. Как насчет рассказать часть о том, как ты стала шпионкой?}
{327}{}{Я вышла замуж за госслужащего, который работал в китайском министерстве национальной обороны. Я выбрала его потому, что он был наиболее готов говорить о своей работе, когда мы были вместе. Так что я играла роль послушной жены, и в то же время тайно доносила соответствующую информацию до моих американских начальников. Но потом все стало сложнее.}
{328}{}{Как же так?}
{329}{}{Мой отец связался с доктором Рейнардом Малдрейком, старым коллегой, с которым он работал во время своего пребывания в Штатах. Доктора Малдрейка срочно вызвали на закрытое заседание, но у моего отца было плохо со здоровьем в тот момент и он был не в состоянии поехать в Америку. Доктор Малдрейк согласился встретиться со мной вместо отца.}
{330}{}{Так что же случилось?}
{331}{}{Оказалось, Малдрейк был частью совершенно секретного проекта исследовательской компании ВестТек в Южной Калифорнии. Этот проект начался довольно невинно, как попытка найти способ заставить людей вырабатывать иммунитет к Новой чуме,
 но он быстро превратился в нечто более зловещее. Что-то называющееся Форсированный Эволюционный Вирус, или ФЭВ.}
{332}{}{Продолжай.}
{333}{}{У него был потенциал для значительного повышения силы и интеллекта человека, но ФЭВ был опасно нестабильным. Несмотря на это, военные надеялись использовать его для создания армии супер солдат, которые смогли бы раздавить Китай.}
{334}{}{Доктор Малдрейк был против изменения направленности проекта, но держал рот на замке из-за страха за свою жизнь. Но когда он узнал, что военные тестируют вирус на ничего не подозревающих жителях малых американских городов, он понял, что ему придется действовать. Миру необходимо узнать правду.}
{335}{}{И когда он связался с твоим отцом...}
{336}{}{Да. Когда я встретилась с ним, он дал мне голодиск, содержащий запрещенную документацию проекта ФЭВ. Это поставило меня в весьма сложное положение: я могла распространить информацию, содержащуюся на голодиске и предать страну, которой я поклялась в верности, или я могла уничтожить диск и скрыть жестокую правду от народа.}
{337}{}{Срань господня. И не говори...}
{338}{}{Я отправила копии голодиска почти во все крупные новостные агенста мира. Это очень сильно подорвало доверие к американскому правительству. Я помогла миру узнать правду, но я боюсь, что именно я дала толчок для его уничтожения...
 Пошла быстрая эскалация, и через восемь месяцев, бомбы были сброшены.}
{339}{}{Как в конечном итоге ты оказалась в этом резервуаре, где я нашел тебя?}
{340}{}{Американское правительство охотилось на лицо, ответственное за утечку информации. Они, достали меня только незадолго до конца. Они уже готовились меня заморозить, когда завыли первые сирены. Наверное, чтобы сохранить меня - а вдруг я знаю больше секретов, чем рассказала им.}
{341}{}{А ты знаешь?}
{342}{}{Уже не имеет значения, сейчас... Все мертвы...}

#you caused the war
{345}{}{Да что ты могла сделать этим диском?}
{346}{}{То, что я *возможно* вызвала войну. Мир бы взорвал себя рано или поздно, так или иначе. Это был только вопрос времени.}
{347}{}{Может быть, ты должна была воздерживаться от распространения этого небольшого лакомого кусочка информации.}
{348}{}{Я понял твою мысль.}

#you didn't cause the war
{350}{}{Я знаю о чем ты думаешь, но ты не должна винить себя за что-то подобное.}
{351}{}{Всегда проще не брать на себя ответственность.}
{352}{}{Ты не могла знать. Кроме того, были и другие конфликты между "державами". Они бы взорвали друг друга рано или поздно. Это был только вопрос времени.}
{353}{}{Люди худшая из тварей.}
{354}{}{Я не считаю себя плохим.}
{355}{}{Природа пытается стереть нас с Земли на протяжении тысячелетий. Все эти новые болезни, стихийные бедствия. Мы были своего рода эволюционной ошибкой. Может быть, мы появились слишком рано или нас вообще не должно было быть.
 Для этой планете мы сделали больше вреда, чем любой другой живой или мертвый.}
{356}{}{Но мы можем искупить его. У нас есть все возможности для этого.}
{357}{}{У тебя очень хорошо получается выражать свои мысли. Спасибо что выслушал меня. Я чувствую, что могу двигаться дальше.}

#teach me something
{360}{}{Скажи, поскольку ты шпионка, я уверен, что ты очень подкована в маскировке и все такое. Ты можешь меня чему-нибудь научить?}
{361}{}{Да, у меня было немного практики прикрытия, Вскрытия замков и воровства. Позвольте мне показать тебе несколько вещей, которые не пишут в книгах.}
{362}{}{Ну вот и все. И помни, что только практика создает совершенство.}
{363}{}{Эй, спасибо. Я думаю, что самое время нам отправляться.}

#your eyes
{370}{}{Твои глаза...}
{371}{}{Что "глаза"?}
{372}{}{Они разного цвета.}
{373}{}{Это называется по-моему... гетерохромия? У тебя эта болезнь?}
{374}{}{Это не мое естественное состояние. Левый принадлежит не мне. Я потеряла свой в аварии. И я до сих пор не научилась понимать их.}
{375}{}{Что ты имеешь в виду?}
{376}{}{Со времени пересадки я всегда чувствовала, что я видела прошлое в одном глазу и настоящее в другом. Сейчас это сильнее, чем когда-либо. И это помогает мне продолжать.}
{377}{}{У всех нас есть свои пути преодоления стресса.}

#skills
{410}{}{Что тебе нужно знать?}
{411}{}{У меня есть черный пояс по самбо. Я могу забить человека до смерти, если ситуация того потребует. С пистолетами, винтовками и так далее я обращаюсь достойно.}

#distance
{420}{}{Мы должны поговорить о расстоянии между нами.}
{421}{}{Что с ним не так?}
{422}{}{Будь ближе ко мне.}
{423}{}{Хорошо. Я за спиной.}
{424}{}{Не отходи слишком далеко.}
{425}{}{Тебе нужно свое пространство, получи его.}
{426}{}{Давай разойдемся подальше.}
{427}{}{Хорошо. В нас будет труднее целиться.}

#wait
{430}{}{Не слишком долго, или я ухожу без тебя.}
{431}{}{Я буду играть в пасьянс, пока ты вернешься.}
{432}{}{Я уверена, что найду чем заняться, пока ты в отъезде.}

#come back
{440}{}{Все равно ты нужен мне.}
{441}{}{Рада твоему возвращению. Я проводила кастинг, но не смогла найти достойную замену для Вас.}
{442}{}{Скучала по моей компании?}
{443}{}{Почувствовал вину уйдя без меня?}
{444}{}{Я начала думать, что ты не планируешь возвращаться.}
{445}{}{Насчет времени. В Древнем Китае за опоздания вешали или четвертовали.}
{446}{}{Эй. Я как раз думала о тебе.}

#lets go
{450}{}{Ты конечно хорошо провел время без меня.}
{451}{}{Хорошо выйти на дорогу.}
{452}{}{Куда?}
{453}{}{Так, куда пойдем?}
{454}{}{Веди, шкипер.}

#party full
{460}{}{У тебя уже достаточно людей. Тебе не нужно мое сопровождение.}
{461}{}{Может быть, когда ты высвободишь немного места. Я не пойду с такой толпой.}

{462}{}{Готов взять меня с собой?}
{463}{}{Пойдем.}
{464}{}{Нет, еще нет.}

#ch <= 1
{470}{}{О Иисус, ты выглядишь как восставший из ада. Ты бы хоть в зеркало посмотрелся.}

#remove armor
{480}{}{Нет проблем. В ногах без нее легче.}

#hurt
{490}{}{Никогда не чувствовала себя лучше. Давай продолжать идти.}
{491}{}{Бывало и хуже. Всего лишь пара царапин.}
{492}{}{Мне не так уж плохо. Просто несколько ран.}
{493}{}{Плоховато. Больше крови, чем я могу позволить вытекает из меня.}
{494}{}{Мне нужен медик или я не буду в состоянии помогать тебе.}
{495}{}{Не могу больше... оставить меня или отведи к врачу. И быстрее.}

#remove weapon
{500}{}{Если ты настаиваешь. Я все еще могу оторвать голову человеку руками.}

#location floats

#EPA
{1000}{}{Я не могу поверить, что провела более ста лет в этом месте.}

#ARROYO
{1010}{}{Не мой тип места, чтобы родиться, без обид.}

#TEMPLE OF TRIALS
{1020}{}{Это выглядит как захоронение какого-то императора пятнадцатого века.}

#KLAMATH
{1030}{}{Это место все пропахло навозом.}

#TOXIC CAVES
{1040}{}{Я не думаю, что будет разумно идти туда без надлежащей обуви.}

#THE DEN
{1050}{}{Я видела и похуже места, поверь мне. Не то чтобы мне это нравилось.}

#MODOC
{1060}{}{Село. Это мне нравится.}

#GHOST FARM
{1070}{}{Это место выглядит как из занюханного кинофильма.}

#GECKO
{1080}{}{Я прямо чувствую излучение в воздухе.}

#VAULT CITY (OUTER)
{1090}{}{Что это? Должно быть, трудовой лагерь?}

#VAULT CITY (INNER)
{1100}{}{Тем, кто внутри гораздо лучше, чем тем, кто на улице. Мир не сильно изменился.}

#REDDING
{1110}{}{Каким шахтерским городком вы это называете?}

#PRIMITIVE TRIBE
{1120}{}{Не мой тип места, чтобы родиться, без обид.}

#RAIDERS
{1130}{}{Хорошее место, чтобы спрятаться, если менты на хвосте.}

#SIERRA ARMY DEPOT
{1140}{}{Интересно, там еще больше бункеров, чем в ЕРА?}

#NEW RENO
{1150}{}{Самый Большой Маленький город в мире. Бьюсь об заклад.}

#STABLES
{1160}{}{Они здесь могут держать не лошадей...}

#GOLGOTHA
{1170}{}{Смерть везда...}
{1171}{}{Я не хотела бы быть похороненой здесь.}

#BROKEN HILLS
{1180}{}{Мы просто перепрыгнем вперед природы и продолжим развиваться, не так ли?}

#SAN FRANCISCO
{1190}{}{Я не вижу высокого здания со 101 этажем.}

#MILITARY BASE
{1200}{}{Они конечно закрыли это место взрывом.}

#VAULT 13
{1210}{}{Я слышала о таких местах...}

#NEW CALIFORNIA REPUBLIC
{1220}{}{Приятно гулять в городе, который выглядит сплоченным.}

#VAULT 15
{1230}{}{Я слышала о таких местах...}

#ABBEY
{1240}{}{Одно святое место в этой проклятой пустыне.}

#DESERT MAP
{1250}{}{Жарко здесь.}
{1251}{}{Я вся вспотела.}
{1252}{}{Во рту пересохло.}
{1253}{}{Я бы хотела, чтобы это был пляж.}
{1254}{}{Сулик, ты видел как дождик танцует?}

#MOUNTAIN MAP
{1260}{}{Здесь так далеко от цивилизации, насколько возможно.}

#SEASIDE
{1270}{}{Я сомневаюсь, что воду можно будет пить даже если отфильтровать все соли.}
{1271}{}{Вся рыба в этих водах обязана быть каким-то мутантом.}
{1272}{}{Холодно здесь.}
{1273}{}{Сотни долларов любому, кто осмелится пойти искупаться нагишом в этих водах.}

#CAVE
{1280}{}{Я не вижу здесь ни черта.}
{1281}{}{Это место плохо пахнет, и если бы я могла видеть, наверное пахло бы еще хуже.}
{1282}{}{Осторожно. Там, наверное, скрывается что-то уродливое и вонючее.}
{1283}{}{Я слышу летучих мышей?}
{1284}{}{Что мы будем делать, спелеолог?}
{1285}{}{Лучше зажечь свечу, чем проклинать темноту.}

#CITY RUINS
{1290}{}{Война... убила хорошее, что сделали мы.}
{1291}{}{Из пыли в пыль...}
{1292}{}{Я жила когда-то в таком же месте, как это...}

#general floats

{2001}{}{My eyes bug you that much?}
{2002}{}{Я отмокла бы в горячем источнике. Интересно, сохранился ли еще какой-нибудь из них.}
{2003}{}{Я убила, чтобы просто найти кого-то с кем можно поиграть в маджонг.}
{2004}{}{Все едят и пьют. Однако лишь немногие ценят вкус.}
{2005}{}{Этот мир превратился в ад. РЕализованы все тринадцать уровней.}
{2006}{}{Я верю в Бога и Дьявола. Но я держу их на расстоянии.}
{2007}{}{Живем ли мы мечтая, или мы чья-то мечта?}
{2008}{}{Я ненавижу то, что мы сделали для себя.}
{2009}{}{Интересно, сколько нам понадобится, чтобы оправиться от войны.}
{2010}{}{Небо просто создало нас, а земля нашла нам применение.}
{2011}{}{У тебя жажда? Я уверена, да.}
{2012}{}{*зевок*}
{2013}{}{Человек предполагает, а Бог располагает.}

#sulik in party
{2020}{}{Эй, Сулик. Что духи говорят?}

#vic in party
{2030}{}{Хочешь похудеть, Вик? Спроси меня! Уроки тайбо в любое время.}

#miria in party
{2040}{}{Твоя жена чертовски много говорит о себе.}
{2041}{}{Скажи своей деревенской жене перестать ходить за мной.}

#myron in party
{2050}{}{Моя грудь и твои глаза не совместимы, Мирон.}
{2051}{}{Как насчет заткнуться на пару минут, Майрон? Или хочешь чтобы тебя убили?}
{2052}{}{Нет, Майрон. Я не буду спать с тобой, даже если ты построишь Мне машину времени.}
{2053}{}{Слушай, Майрон. Если ты не бкдешь держать руки при себе, я сделаю тебя евнухом.}

#marcus in party
{2060}{}{Эй, Маркус. Устроим арм-рестлинг?}

#k-9 and dogmeat both in party
{2070}{}{У нас достаточно собак, увязавшихся за нами. Нам не нужна еще одна.}

#poisoned
{2100}{}{Ох, я чувствую себя как в аду.}
{2101}{}{Я думаю, что я отравлена...}

#radiated
{2110}{}{Чувствую, во мне что-то не правильно...}
{2111}{}{Я чувствую себя странно...}
{2112}{}{Моя рука. Она светится.}
{2113}{}{Я лиса, а не змея... Почему моя кожа шелушиться?}
{2114}{}{Внутри все горит... Что со мной происходит?}

#broken limb
{2120}{}{Получила перелом, я думаю. Нужно, чтобы ты посмотрел на это.}
{2121}{}{Чую я что-то сломала...}

#blind
{2130}{}{Я почти не вижу, черт возьми.}
{2131}{}{Я ненавижу быть слепой.}

#items used on Kitsune - Nodes 4000

#stimpack
{3000}{}{Лучше.}
{3001}{}{ценю это.}
{3002}{}{Я чувствую себя уже лучше. Спасибо.}
{3003}{}{Спасибо. Мне это было нужно.}
{3004}{}{У тебя достаточно для себя?}

#booze
{3010}{}{сильная штука. Хорошо, что я придержала свой ликер.}
{3011}{}{Не знаю, почему я пью это. Вкус как у чистящей жидкости.}
{3012}{}{Никогда не любила много пить. Но это заморозит боль.}
{3013}{}{Есть что-нибудь еще выпить?}
{3014}{}{Будем надеяться, что я не проснусь в луже моей собственной рвоты.}
{3015}{}{У меня планы сегодня остаться трезвой.}

#psycho
{3020}{}{Дерьмо... Будем надеяться, что нам никогда не придется столкнуться с целой бандой подсевшей на психо.}

#buffout
{3030}{}{Лучше без него. Он основан на столовых клетках с тестостероном.}

#mentats
{3040}{}{Надеюсь, это не превратит меня в идиота как только он прекратит свое действие.}

#jet
{3050}{}{За державу обидно!}
{3051}{}{Таможня дает добро.}
{3052}{}{Штирлиц! А вас я попрошу остаться.}
{3053}{}{Не виноватая я!.. Он сам пришел!}
{3054}{}{Буду бить аккуратно, но сильно.}
{3055}{}{Руссо туристо, облико морале, ферштейн?}
{3056}{}{Пока космические корабли бороздят просторы большого театра...}
{3057}{}{Вы не скажете, сколько сейчас градусов ниже нуля?}
{3058}{}{Тяжело в учебе - легко на работе.}
{3059}{}{Или шашечки или ехать.}
{3060}{}{После первой не закусывают.}
{3061}{}{Попрошу факт продажи родины зафиксировать в протоколе.}
{3062}{}{Песчаный карьер - два человека!}
{3063}{}{Кто не работает тот ест.}
{3064}{}{На халяву пьют даже трезвенники и язвенники.}
{3065}{}{Замуровали, демоны!}
{3066}{}{Куй железо, не отходя от кассы.}
{3067}{}{Кушать подано. Садитесь жрать, пожалуйста.}
{3068}{}{Е видим одну звездочку, две звездочки. Лучше, конечно, пять звездочек.}
{3069}{}{Есть ли жить на Марсе, нет ли жизни на Марсе - это науке неизвестно.}
{3070}{}{Какая гадость эта ваша заливная рыба!}
{3071}{}{Упал, очнулся - гипс.}
{3072}{}{И что это я в тебя такой влюбленный?}
{3073}{}{Муля, не нервируй меня!}
{3074}{}{А казачок-то засланный.}
{3075}{}{Такую личную неприязнь к потерпевшему испытываю, что даже кушать не могу.}
{3076}{}{Ну кто еще хочет попробовать комиссарского тела.}
{3077}{}{Господин назначил меня любимой женой!}
{3078}{}{Восток - дело тонкое.}
{3079}{}{Тебя посодют, а ты не воруй!}
{3080}{}{Я не трус, но я боюсь.}
{3081}{}{Дитям - мороженое, бабе - цветы. Гляди, не перепутай, Кутузов!}
{3082}{}{Комсомолка, спортсменка и просто красавица.}
{3083}{}{У тебя в голове мозги или кю.}
{3084}{}{Не учите меня жить, лучше помогите материально.}
{3085}{}{Хорошо сидим.}
{3086}{}{А в тюрьме сейчас ужин. Макароны.}
{3087}{}{Я не прокурор, чтоб с тобой по душам разговаривать.}
{3088}{}{У вас продается славянский шкаф?}
{3089}{}{Бабу-ягу со стороны брать не будем. Воспитаем в своем коллективе.}
{3090}{}{Барбамбия киргуду.}
{3091}{}{Крылья... ноги... самое главное - хвост!}
{3092}{}{О, тепленькая пошла!}
{3093}{}{Сядем усе.}
{3094}{}{Обозначенный на плане буквами эм и жо.}
{3095}{}{лед тронулся, господа присяжные заседатели.}
{3096}{}{Командовать парадом буду Я!}
{3097}{}{Пилите,Шура,пилите...}
{3098}{}{Кто ж его посадит? Он же памятник!}
{3099}{}{И тебя вылечат. И меня вылечат.}
{3100}{}{А вам не кажется, деточка, что ваше место возле параши.}
{3101}{}{Пасть порву! Моргалы выколю!}
{3102}{}{Шарикову больше не наливать.}
{3103}{}{Борменталь, тебе водки жалко?}
{3104}{}{А хотите я его стукну, и он станет фиолетовым?}
{3105}{}{Губит людей не пиво, губит людей вода!}
{3106}{}{Мы котов вчера душили-душили, душили-душили...}
{3107}{}{Если я встану - ты ляжешь.}
{3108}{}{Иди потренируйся, вон, на кошках!}
{3109}{}{Видно, моя бабушка согрешила с водолазом.}
{3110}{}{Казань брал, Астрахань брал, Ревель брал... Шпака не брал.}
{3111}{}{Меня терзают смутные сомнения...}
{3112}{}{Тостуемый пьет до дна.}
{3113}{}{Да гранаты у него не той системы!}
{3114}{}{Птица Говорун отличается умом и сообразительностью.}
{3115}{}{А вдоль дороги -- мёртвые с косами стоять! И тишина...}
{3116}{}{Желтые штаны - два раза КУ.}
{3117}{}{Скрипач не нужен...}
{3118}{}{Нет такого мужа, который не мечтал бы хоть на час стать холостяком!}

#Don't apply ERSI to specimen == horrible flaming death for specimen
{5000}{}{[Женщина смотрит на ваше лицо, глаза ее вдруг расширяются и она начинает задыхаться.]}
{5001}{}{[конец]}
{5002}{}{Срань господня!}

