# Message file for epac7.ssl 
# Number of nodes: 11

###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите голограмму.}
{101}{}{Вы видите директора по связям с общественностью.}
{102}{}{Голограмма 40011. Она отвечает за все туры и пресс-релизы по ЕРА.}

# Node  0  [Node001]
{200}{}{[Эта привлекательная голограмма женщины встречает Вас приветливой улыбкой.] Привет посетитель, и добро пожаловать в EPA. Как я могу вам помочь? Обед будет подан в кафетерии в середине дня для всех сотрудников компании.}
{201}{}{Что? О, не важно. Кто вы?}
{202}{}{Я должен идти. Пока.}

# Node  1  [Node002]
{210}{}{Я? Я Голограмма 40011, директор по связям с общественностью. Я организую поездки, экскурсии и другие мероприятия, и убеждаю общественность, что это место нормально функционирует день за днем. Экскурсия по музею EPA начнется в ближайшее время. Пожалуйста, проходите когда будете готовы.}
{211}{}{Это похоже на захватывающую работу. До свидания.}
{212}{}{Могли бы Вы мне помочь кое с чем?}

# Node  2  [Node003]
{220}{}{Конечно. Я люблю помогать. Как я могу помочь вам? Туристические брошюры можно найти в главном офисе и в почтовых ящиках по всему EPA.}
{221}{}{Снаружи комплекса есть двери, которые я не могу открыть, не зная пароль. Я бы очень хотел пройти через них и узнать больше о вашем предприятии. Но я не думаю, что вы знаете пароль.}

# Node  3  [Node004]
{230}{}{Конечно я знаю пароль, но, к сожалению, я не могу поделиться с вами. Я понимаю ваш энтузиазм и желание испытать все, что этот большой объект может предложить, но есть правила, которым мы должны следовать для вашей собственной безопасности. Запомните, мы предлагаем экскурсии по нашему комплексу в заранее определенное время.}
{231}{}{О, вы не должны беспокоиться о моей безопасности, я Избранный. Кроме того, когда в последний раз вы видели *настоящих* посетителей? Вы действительно хотите оставить меня разочаровать?}
{232}{}{Хорошо. Прощай.}

# Node  4  [Node005]
{240}{}{Конечно, нет. Но, если я дам вам пароль, это создаст угрозу не только для вас, но я также создам угрозу для всего комплекса. Дети, пожалуйста, не дразните голограммы.}
{241}{}{Как это может угрожать комплексу? Я очень не хочу доломать его, дамочка, но этот комплекс уже прошел ад и вернулся обратно. Кроме сломанных роботов и опасных химических веществ здесь ничего не осталось. И, честно говоря, я не вижу, что может бы еще хуже.}
{242}{}{Тогда забудьте.}

# Node  5  [Node006]
{250}{}{Я... Я не знаю. Я бы нарушила протокол. Но... Возможно, если бы вы смогли помочь мне кое с чем. Посетители, обратите внимание, что синий уровень закрыт, по причине полной неинтересности. Так что нет необходимости любопытствовать.}
{251}{}{Конечно, я мог бы вам помочь. Просто скажите, что вам нужно.}

# Node  6  [Node007]
{260}{}{Ах да, теперь смотрится намного лучше, спасибо. Пароль Abre. Просто говорите четко и дверь будет открыта. Теперь все, пожалуйста...}
{261}{}{Да, мы слышали, у вас уже. Спасибо за код. До свидания.}

# Node  7  [Node008]
{270}{}{Здравствуйте еще раз. Что вам нужно? Комплекс EPA будет закрыт в ближайшем будущем из-за отсутствия персонала.}
{271}{}{Теперь у меня есть больше времени, не могли бы вы сказать мне, что вы здесь делаете?}
{272}{}{Забодьте.}

# Node  8  [Node009]
{280}{}{С возвращением, посетитель. На данный момент экскурсий нет, но если вы подождете, пока пиедут достаточно посетителей, я буду рада устроить тур по ЕРА.}
{281}{}{Я не хочу идти на экскурсию, спасибо. До свидания.}
{282}{}{Интересно могли бы вы сделать что-нибудь для меня?}

# Node  9  [Node010]
{290}{}{Привет. Я немного занята в данный момент разработкой новой программы экскурсий на предстоящий сезон. Не могли бы вы вернуться позже?}
{291}{}{Я хотел бы, но я слишком тороплюсь. Видите ли, мне *действительно* необходим пароль от этих дверей. Не могли бы вы дать мне его?}

# Node  10  [Node011]
{300}{}{Еще раз спасибо за вашу помощь, и пожалуйста, осторожней с паролем, который я дала вам. Помните, это наш маленький секрет. Благодарим Вас за посещение EPA, надеюсь, что у вас остались приятные впечатления.}
{301}{}{Спасибо. Пока.}

{302}{}{Приходите к нам снова когда-нибудь.}
{303}{}{Не забудьте посетить сувенирную стойку ЕРА.}

#added in RP 1.3
{310}{}{Вы думаете, вы смогли бы исправить освещение? Просто неприлично проводить туры по такому тускло освещенному комплексу. Если бы вы могли осветить это место для меня, я дам вам пароль. Пожалуйста,
 не забудьте тщательно вымыть руки после посещения нашего зоопарка.}
{311}{}{Хорошо. Я посмотрю, что я смогу сделать.}
{312}{}{Нет. Я не заинтересован.}

{320}{}{Комплекс все еще тусклый и серый. Вы все еще собираетесь установить фонари, не так ли? Посетители, помните, все пропуска должны быть подписаны до конца тура.}
{321}{}{Не волнуйтесь. Я работаю над этим.}
{322}{}{Я работаю над этим.}

#loop
{330}{}{У нас было бы больше посетителей, если граундс были чистыми.}
{331}{}{Как я должна проводить туры без надлежащего освещения?}
{332}{}{Эти растения убивают всех потенциальных туристов.}
{333}{}{Все эти разбитые роботы *очень* неприглядые.}
{334}{}{10031, вы были бесполезны в течение десятилетий.}
{335}{}{Все, что я хочу, что это место было более презентабельно.}
{336}{}{Уничтожение комплекса не ответ.}

