# Message file for epac2.ssl 

###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите голограмму.}
{101}{}{Вы видите директора по науке.}
{102}{}{Голограмма 00000. Он заботится о научных аспектах EPA.}

{200}{}{01001000 01100101 01101100 01110000 00100000 01101101 01100101 00100001}
{201}{}{Ух, чего?}

{210}{}{01000101 01101100 01100101 01100011 01110100 01110010 01101001 01100011 01100001 01101100 00100000 01110011
 01101000 01101111 01110010 01110100 00101110}
{211}{}{Извините, я вас не понимаю. Пока.}
{212}{}{Интересно. Похоже, вы в состоянии общаться только с помощью двоичных чисел. Кажется, если бы я записал то, что вы говорите, я был бы в состоянии понять это.}

{220}{}{[Через пару часов, вы наконец правильно переводите двоичные числа. Похоже, он говорит: "Помогите! Короткое замыкание."}
{221}{}{Ну, это было интересно декодировать. Увидимся.}
{222}{}{Короткое замыкание в ленточном барабане, да? Давайте посмотрим, смогу ли я вас починить.}

{230}{}{01001000 01100101 01101100 01110000 00100000 01101101 01100101 00100001}
{231}{}{Просто проверка. Увидимся.}
{232}{}{Не беспокойтесь, я работаю над починкой.}

{240}{}{01010010 01100101 01100010 01101111 01101111 01110100 00100000 01101101 01100101 00100001}
{241}{}{Ладно, я сдаюсь. Извините.}
{242}{}{По прежнему не работает? Подождите, дайте мне разобраться.}

{250}{}{[Теперь вы в состоянии расшифровывать сообщения намного быстрее, на этот раз: "Перезагрузка меня!"] О, конечно. [Вы перезагружаете машину создающую голограмму. Чтобы скоротать время, вы свистите на протяжении всей процедуры.]}
{251}{}{[Продолжить.]}

{260}{}{Слава Хоукингу, вы сделали это! Моя ревевая программа повисла и я застрял в двоичном режиме на *годы*. Так давно я не имел удовольствия обмениваться диалогом с другими существами. Вы только подумайте, все это время *один* из моих товарищей мог бы проявить любезность и изучить двоичные коды, но неееееет.}
{261}{}{Нет пробЧ}

{270}{}{У них, видите ли, не было на меня времени. О нет, они были слишком *заняты* предаваясь их бюрократической ерунде. Слишком заняты введением правил друг для друга и спорами, как дураки. И посмотрите, где это застало их: застряли в бесконечной петле в конференц-камере. Ха! Вот вам право на обслуживание.}
{271}{}{Застряли в петле?}
{272}{}{Вообще-то я исправил эту проблему. Нет больше бесконечных циклов.}

{280}{}{Что-что? Ах, да, да, кажется, что какая-то неисправность вызвала мощное магнитное поле, которое стирало их краткосрочную память каждые пару минут, практически поместив их в особый вид ада для голограмм. Но все равно, лучше без них.
 Они приводили бесконечные аргументы, чтобы оставить меня, э-э, я имею в виду, *нас*, отвечать за этот объект. С моим высочайшим интеллектом, и вашим физическим телом, мы могли бы вполне могли создать дуэт.}
{281}{}{Во-первых, почему бы вам не сказать мне, что это за место?}

{290}{}{В самом деле? На мой взгляд, лучше бы без них, но если вы думаете иначе - кто я такой, чтобы жаловаться. С моим высочайшим интеллектом, и вашим физическим телом, мы могли бы вполне могли создать дуэт.}
{291}{}{Во-первых, почему бы вам не сказать мне, что это за место?}

{300}{}{Это агенство по охране окружающей среды, ЕРА. Это федеральный объект, первоначально созданный для химических исследований, очистки и обеспечения защиты окружающей среды, но вскоре ЕРА стало гораздо большим, чем задумывалось!
 Теперь вы стоите в одной из лучших экспериментальных исследовательских учреждений страны. У нас так много интересных вещей в процессе разработки. Конечно, прогресс немного замедлился в последнее время, с падением цивилизации и все такое...}
{301}{}{Это понятно.}
{302}{}{Апокалипсис не оправдание для страдания фигней.}

{310}{}{Да, если бы у меня были трудоспособные помощники, я смог бы наконец добиться несколько большего прогресса в моих исследованиях...}
{311}{}{Какого рода помощь вам нужна?}

{320}{}{Зависит от. Я не думаю, что вы будете чувствовать себя комфортно владея большим экспериментальным пистолетом, не так ли?}
{321}{}{Блин, да я могу!}
{322}{}{Конечно.}
{323}{}{Я думаю, я пасс.}

{330}{}{Ох, я вижу. Это очень плохо. Ну что ж, никаких обид. Я просто подожду, пока следующий человек из плоти и крови забредет в это здание. Это должно случиться еще раз за одно - два столетия. До свидания.}

{340}{}{Здравствуйте еще раз. Я не думаю, что вы пересмотрели мое предложение помочь мне тестировать экспериментальное оружие?}
{341}{}{Нет. Извините.}
{342}{}{Хорошо. Конечно.}

{350}{}{Отлично! Вы идеальный кандидат. Вы видите, стараясь помочь военным стать более "экологически чистыми", я разработал новое оружие, не требующее боеприпасов, потому что оно работает *полностью на свету.
 Я называю его *Солнечный скорчер*. Однако, он еще не испытан под прямыми солнечными лучами, если конечно, вы не согласитесь.}
{351}{}{Так вы просто хотите, чтобы я вышел на улицу и выстрелил из этой штуки? И это все?}
{352}{}{Да, да, дайте мне уже пистолет.}

{360}{}{По существу, да. Конечно, мне нужно знать, насколько хорош он будет в боевой обстановке, так что я был бы благодарен, если Вы сможете найти какую-нибудь мутантскую форму жизни, которую можно было бы эффектно уничтожить моим солнечным скорчером.}
{361}{}{Выйти на улицу и убить кого-нибудь, все понял. Где этот солнечный скорчер?}

{370}{}{Не так быстро, мой друг. Я не хочу, чтобы вы просто и бесцельно стреляли там, снаружи. Мне нужно знать, насколько хорош он будет в боевой обстановке, так что я был бы благодарен, если Вы сможете найти какую-нибудь мутантскую форму жизни, которую можно было бы эффектно уничтожить моим солнечным скорчером.}
{371}{}{Выйти на улицу и убить кого-нибудь, все понял. Где этот солнечный скорчер?}

{380}{}{Он в том шкафчике на стене, рядом с моим проектором. Код доступа 03141879.}
{381}{}{Хорошо, я испробую его и сообщу вам, как он себя поведет.}

{390}{}{Ах, с возвращением. Вы получили шанс проверить Солнечной скорчер?}
{391}{}{Конечно же. Он отправляет всех в ад.}
{392}{}{Конечно же, но этот кусок дерьма сломался сразу после первого выстрела. Я выбросил это в мусор.}
{393}{}{Нет, еще нет.}
{394}{}{Я иду пробовать.}

{400}{}{Отлично! Я очень рад узнать, что он работает, как предполагалось. Спасибо за помощь мне. Почему бы тебе не оставить солнечный скорчер у себя? Лучше пусть он используется, чем лежит здесь и собирает пыль.}
{401}{}{Спасибо!}
{402}{}{Хорошо, потому что я не собирался отдавать его обратно в любом случае.}

{410}{}{О... Я вижу. Я не понимаю, как этот прототип выдержал массированные тестирования в лабораторных условиях... [Он качает головой с сожалением.] Во всяком случае, спасибо за помощь мне.}
{411}{}{Ничего.}
{412}{}{Нет проблем.}

{420}{}{Рад видеть вас снова. Однако вы меня извините, у меня множество проектов, которые требуют моего внимания.}
{421}{}{[Конец.]}

{500}{}{Вы починили Голограмму 00000.}
{510}{}{Вы испытаний солнечный скорчер для директора по науке.}

