# Message file for epac8.ssl 
# Number of nodes: 13

###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите поношенную голограмму.}
{101}{}{Вы видите директора по обслуживанию.}
{102}{}{Голограмма 10031. Он отвечает за все наземное обслуживание в EPA.}

# Node  0  [Node001]
{200}{}{Привет. Не возражаете, если я спрошу, как вам удалось добраться сюда? Лифт на поверхность очень давно сломался.}
{201}{}{Давайте посмотрим... Я использовал веревку, чтобы спуститься через шахту лифта на уровень обслуживания... затем я прополз через вентеляционный канал и очутился на площадке обслуживания роботов...}

# Node  1  [Node002]
{210}{}{Я удивлен, что эта проклятая станция еще не развалилась. Я Голограмма 10031, директор по обслуживанию в EPA. [Он тяжело вздыхает.] Знаю, Знаю, на подземные уровни смотреть страшно. Нет необходимости говорить об этом мне.}
{211}{}{Если вы не довольны тем, как выглядят подземные уровни, почему бы вам не сделать что-нибудь с этим?}
{212}{}{Без шуток. Весь ЕРА замусорен радиоактивной слизью, трупами и плотоядными растениями-мутантами... Серьезно, вы должно быть худший хранитель подземелья.}

# Node  2  [Node003]
{220}{}{Если бы я мог что-то сделать, поверьте мне, я бы сделал. У меня нет физического тела, и проклятые роботы не отвечают на мои голосовые команды. Я на 100% неэффективен в течение нескольких последних десятилетий - и очень жалок.
 Другие голограммы забыли обо мне. Просто еще один бесполезный, я, директор по операциям.}
{221}{}{Может быть, я смогу помочь каким-то образом?}
{222}{}{Это действительно позор. Я должен идти. До свидания.}

# Node  3  [Node004]
{230}{}{Да? Если вы действительно хотите помочь, это было бы здорово. Я гарантирую, что вы получите что-нибудь за ваши хлопоты.}
{231}{}{Договорились. Чем я могу вам помочь?}
{232}{}{Нет, сейчас у меня нет времени.}

# Node  4  [Node005]
{240}{}{Те мутировавшие споры растений распространились за пределы парника и пустили корни во всех подземных уровнях EPA. Если бы вы могли избавиться от этих ублюдков для меня, это было бы большим шагом в правильном направлении.}
{241}{}{Конечно, я мог бы убить все споровые растения для Вас. Я вернусь как только это будет сделано.}
{242}{}{Это довольно легко. Я уже убил их всех.}

# Node  5  [Node006]
{250}{}{Здравствуйте еще раз. Что я могу для вас сделать? *Вздох*}
{251}{}{Вы выглядете довольно мрачным. Что случилось?}

# Node  6  [Node007]
{260}{}{Здравствуйте еще раз. Вы передумали помогать мне? Как я уже говорил, я отблагодарю Вас.}
{261}{}{Почему нет? Мне пока все равно нечего делать.}
{262}{}{Нет, я слишком занят в данный момент. Я вернусь в другой раз.}

# Node  7  [Node008]
{270}{}{Вы сделали то что я просил?}
{271}{}{Да, я убил все растения. ЕРА все еще выглядит похожим на ад, но по крайней мере здесь стало немного безопаснее.}
{272}{}{Нет, еще нет. Я еще вернутсь к вам.}

# Node  8  [Node009]
{280}{}{Огромное вам спасибо! За это я нанимаю вас в качестве моего помощника хранителя подземелья. [Он указывает на ключ на полу у его ног.] Мне удалось уговорить одного полурабочего робота принести это для вас. Теперь у вас есть разрешение на доступ в хранилище.
 Еще раз спасибо.}
{281}{}{[Вы подбираете ключ и кладете его в карман.] Нет проблем. Увидимся.}

# Node  9  [Node010]
{290}{}{Вы выглядите довольно грязно. Все в порядке?}
{291}{}{Да, я в порядке. У меня были некоторые проблемы с мутировавшими растениями по пути сюда, но я о них позаботился.}

# Node  10  [Node011]
{300}{}{Позаботился? Замечательно! За это я нанимаю вас в качестве моего помощника хранителя подземелья. [Он указывает на ключ на полу у его ног.] Мне удалось уговорить одного полурабочего робота принести это для вас. Теперь у вас есть разрешение на доступ в хранилище. Еще раз спасибо.}
{301}{}{О, нет. Это все, что я мог сделать. Не беспокойтесь об этом.}
{302}{}{Спасибо! До свидания.}

# Node  11  [Node012]
{310}{}{Вы ведь сделали мне добро так что берите ключ и все, что захочется или понадобится вам. Это мой способ сказать спасибо за то, что вы сделали.}
{311}{}{О, тогда все в порядке. В любом случае, скажите кто вы? Почему для вас было так важно, чтобы я убил все эти растения?}

# Node  12  [Node013]
{320}{}{Я директор по обслуживанию. Я должен гарантировать, что подземные уровни будут находится в хорошем состоянии, но, как голограмма я ничего не могу сделать сам. Я командовал роботами, которые делали все это за меня. Поскольку большинство из них перестали функционировать, я работал на 100% неэффективно в течение последних нескольких лет. Вы помогли мне больше, чем вы можете себе представить.}
{321}{}{Ладно, нет проблем. Я должен идти.}


{330}{}{Продолжай хорошо работать, помощник.}
{331}{}{Я сейчас работает на 1% эффективности!}
{332}{}{Вы уничтожили мутантов, которые безудержно разрослись по территории EPA.}
{333}{}{Это место целиком занято этими растениями-мутантами.}
{334}{}{Они повсюду.}
{335}{}{А тут еще мантисы...}
{336}{}{Парник лежит в руинах.}
{337}{}{Если только роботы будут реагировать на команды...}
{338}{}{Я знаю, я полностью провалился.}
{339}{}{Я очень извиняюсь за состояние территории.}
{340}{}{Если бы я мог что-то сделать, я бы сделал.}
{341}{}{Может быть, 10001-ый прав. Может быть, мы просто должны уничтожить все это.}

