###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите голограмму.}
{101}{}{Вы видите голограмму.}

{200}{}{Zzzzzt...Привет... zzZzzt..ли..zzzZzzZtt...встать...меня?}
{201}{}{Простите?}
{202}{}{Ладно. Пока.}
{203}{}{Мой...zZzzzt..датчик...ZzzzzzZzt...*искажает*...починишь?}
{204}{}{Извините, но я вас не понимаю. Слишком много статических помех. Я посмотрю, может я смогу это как-то исправить.}
{205}{}{У меня нет на это времени. Пока.}

{300}{}{Ах, спасибо тебе большое за мой ремонт! Я боялся, вдруг придет какой-нибудь гость и будет задавать мне вопросы, на которые я буду не в состоянии правильно ответить из-за статики. Хотя вы первый посетитель, которого я вижу после войны, но все же, *если* я столкнуся бы с кем-то еще, это могло бы быть довольно неловко.}
{301}{}{Нет проблем. А что же это за место?}
{302}{}{[Он улыбается и кажется в восторге от перспективы ответить на все имеющиеся вопросы.] Вы находитесь в агенстве по охране окружающей среды, более известный как EPA. Мы государственный исследовательский институт, который специализируется на тестировании химикатов с целью установить, безопасны ли они для окружающей среды планеты Земля. Но это только верхушка айсберга. Мы здесь выполняли все виды исследований, по крайней мере, пока объект не был покинут из-за войны. Раньше все было совсем не так...}
{303}{}{Интересные. А какова ваша цель здесь?}
{304}{}{Ну, в отличие от других голограмм с которыми вы столкнетесь здесь, я не был создан для выполнения конкретной задачи. Я стою здесь, чтобы отвечать на вопросы посетителей или помогать решать сложные математические задачи, которые человеческий разум не может постичь.}
{305}{}{я вижу. Тогда, возможно, вы могли бы ответить на некоторые вопросы для меня?}

{310}{}{О, я с удовольствием отвечу на Ваши вопросы. Спрашивайте и я отвечу на них в меру своих способностей.}
{311}{}{Я все время вижу указатели на какой-то Голубой уровень. Как я могу получить к нему доступ?}
{312}{}{Я нашел другой путь сюда, но он требует пароль. Вы попадете в него через сервисный лифт.}
{313}{}{Можете ли вы рассказать о некоторых предметах, которые я нашел здесь?}
{314}{}{Забудь. Мне ничего не нужно.}

{320}{}{Да, конечно, главный лифт с поверхности отвезет вас туда, куда вы хотите пройти! Но зачем вы идете через системы вентиляции?}
{321}{}{Тот лифт больше не работает, и единственный способ,который я нашел, через вентиляционные отверстия.}
{322}{}{Ох, я вижу. Тогда это имеет смысл. Но есть еще один способ. Существует сервисный лифт, который останавливается на втором уровне. В него можно попасть из-под мастерской Доктора. Ее вы сможете найти на улице, к востоку от главного входа в EPA. Однако, вам понадобится код доступа, чтобы проникнуть внутрь. Так как я благодарен вам ремонт, я скажу вам код. Код "ЦВЕТОЧНЫЙ ГОРШОК".}
{323}{}{Спасибо. Позвольте мне спросить вас кое-что еще.}
{324}{}{Ох, мне очень жаль, но уровень БЛЮ содержит совершенно секретные исследования. Доступ на этот уровень ограничен... и черт с ним. Вы были столь любезны, что починили меня, поэтому я полагаю, я могу дать вам пароль. Код "ЦВЕТОЧНЫЙ ГОРШОК".}

{330}{}{Я сделаю все возможное. Что вы хотели мне показать?}
{331}{}{Какова цель этого корма для собак?}
{332}{}{Я нашел этот шприц полный неизвестного вещества. Не могли бы вы сказать мне, что он делает?}
{333}{}{Я нашел эту стойку пробирок. Я могу что-нибудь сделать с этим?}
{334}{}{Каковы последствия использования этих препаратов, которые я нашел?}
{335}{}{Я сделал несколько неизвестных химикатов с помощью Мистера Химми! Что с ними можно делать?}
{336}{}{Я нашел немного динамита, который отличается от того, который я встречал. Как его использовать?}
{337}{}{Вообще-то, позвольте меня спросить вас кое-что другое.}

{340}{}{Ну, создателям и дизайнерам этого места всегда нравилось напихать небольших ссылок из фильмов, книг и других таких источников повсюду. Они обнаружили, что это смешно и так же многое другое. Корм для собак является ссылкой	на фильм, но я оставлю вам право выяснить на какой фильм.}
{341}{}{Хорошо. Позвольте мне задать еще вопрос.}

{350}{}{Ну, это основной инструмент для любого химика. Я полагаю, что если вы хотите создать что-то тогда можно было бы использовать их.}
{351}{}{Хорошо. Позвольте мне задать еще вопрос.}

{360}{}{Ах, у вас там очень интересный образец. Боюсь, что я не узнаю его. Пожалуйста, поместите его в контейнер рядом со мной, и я буду счастлив проанализировать это для Вас.}
{361}{}{Хорошо. [Вы размещаете элемент в контейнере и закрываете крышкой.]}
{362}{}{Я вот подумал, можно еще спросить?}
{363}{}{Чтение молекулярного состава жидкости в шприце... закончено. Анализ завершен. Очень интересно! Кажется, этот шприц содержит уникальную сыворотку со следами кошачей ДНК. Похоже, что это экспериментальный препарат, предположительно - для повышения ловкости человека. Конечно, я бы не рекомендовал вам использовать что-либо, не вышедшее из экспериментальной стадии.}
{364}{}{Хорошо. Позвольте мне задать еще вопрос.}

{370}{}{Ах, это должно быть Сannabis, также известный как марихуана, курево и ганджубас, между прочим. Это один из незаконных наркотиков, может вызывать психоактивные эффекты при курении или употреблении внутрь.
 Некоторые из здешних техников когда-то любили покурить, чтобы расслабиться. Если будете курить это, вы должны знать, что она может затуманить ваш ум и снизить время реакции на определенный период времени.}
{371}{}{Хорошо. Позвольте мне задать еще вопрос.}

{380}{}{Ах, у вас там очень интересный образец. Боюсь, что я не узнаю его. Пожалуйста, поместите его в контейнер рядом со мной, и я буду счастлив проанализировать это для Вас.}
{381}{}{Хорошо. [Вы размещаете элемент в контейнере и закрываете крышкой.]}
{382}{}{Я вот подумал, можно еще спросить?}
{383}{}{К сожалению, в моей базе данных нет информации, которая описывает этот предмет. Как и с любым неизвестным веществом, я советую вам соблюдать максимальную осторожность, прежде чем использовать его. Сожалению я не смог помочь в полной мере.}
{384}{}{Хорошо. Позвольте мне задать еще вопрос.}

{390}{}{Это интересная штука. В отличие от другого динамита, который имеет таймер, это динамит контролируется радио триггером. Просто положите динамит где хотите, отойдите и нажмите на курок, чтобы взорвать его. Прекрасная штука, не так ли?}
{391}{}{Определенно. Позвольте мне задать еще вопрос.}

{400}{}{Здравствуйте еще раз. Чем еще я могу вам помочь?}
{401}{}{У меня есть несколько вопросов.}
{402}{}{Забудь. Пока.}

{500}{}{Вы открывать боковую панель эмиттера голограммы и заглядываете внутрь. Вы видите беспорядок среди кабелей и печатных плат.}
{501}{}{Ну, давайте начнем.}
{502}{}{Через некоторое время вы локализовали проблему и устранили ее. Вы закрываете панель и вытираете пот со лба.}
{503}{}{Вы успешно отремонтировали голограмму.}
{504}{}{После нескольких попыток вам все же не удается выяснить, что случилось с голограммой.}
{505}{}{Черт. Это слишком тяжело для меня. Ремонт это не моя сильная сторона.}
{506}{}{Вы не в состоянии отремонтировать голограмму.}
{507}{}{[СДЕЛАНО]}

