# Message file for Toaster.ssl 
# Number of nodes: 7

###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите скучающий серебряный тостер сидящий на столе.}
{101}{}{Вы видите Отважный Маленький Тостер.}
{102}{}{ОМТ, ваш веселый, немного раздражающий компаньон для завтрака.}

# Node  0  [Node001]
{200}{}{Приветики Диддли-даддли! Я Отважный Маленький Тостер, ваш веселый компаньон для завтраков. Но вы можете называть мне просто ОМТ. Скажи, кто-нибудь хочет тост?}
{201}{}{Нет, спасибо, но мне нужна некоторая информация.}
{202}{}{Не сейчас, мне нужно идти.}

# Node  1  [Node002]
{210}{}{Нет проблем! Я офигенно хорош в квантовой механике, субмолекулярной биологии и мелодиях из телесериалов. Спросите меня что-нибудь. Но сначала я хотел бы задать вам вопрос.}
{211}{}{Пожалуйста. Что я могу для вас сделать?}

# Node  2  [Node003]
{220}{}{Вы уверены, что вы не хотите какой-нибудь тост?}
{221}{}{НЕТ! Я не хочу тост. Ни кексов, ни пирожных. Ни булочек, багетов или рогаликов. Ни круассанов, ни пышек, не блинчиков, картофельных чипсов и тортов и, безусловно, никаких дурацких оладьев!!!}

# Node  3  [Node004]
{230}{}{А! Так тебе нужна вафля, чувак!}
{231}{}{Ох, с меня хватит.}
{232}{}{[Вы мотаете головой в отчаянии.] Я должен идти. Я... Я просто должен быть где-то. Где угодно, но не здесь.}

# Node  4  [Node005]
{240}{}{Нет, подожди. Мне очень жаль. Я не просто одержимый прибор для приготовления односторонних тостов. Что я могу для вас сделать?}
{241}{}{Мне просто нужна кое-какая информация об этом месте. Что ты можешь мне сказать?}

# Node  5  [Node006]
{250}{}{Я могу сказать тебе одно: это страшное место где над моими тостами проводили экспертизы. Знаешь ли ты, что прошло больше века, прежде чем я получил удовольствие сделать тост для кого-то? Ты первый потребитель тостов, пришедший сюда после войны, и вот ты меня футболишь. Даже если ты на самом деле запросил тост, я даже не уверен, что готов для выполнения этой задачи. Видишь ли, я чувствую себя немного кастрированным внутри. И это довольно неудобно, правда.}
{251}{}{Это... ну... совсем трагично. Так почему ты здесь?}
{252}{}{Я вижу. Спасибо за твое время.}

# Node  6  [Node007]
{260}{}{Я думаю, что он завез партию противогазов до аварии. Некоторые люди даже говорили, что это было его ошибкой, что в первую очередь вызвало проблемы.}
{261}{}{Итак, почему ты здесь?}
{262}{}{Спасибо за информацию.}

# Node  7  [Node008]
{270}{}{Затем, чтобы сделать ваше утро таким веселым, насколько это возможно! Скажи, после всего уже сказанного, не освободилось ли немного места в твоем желудке для некоторых тостов, в конце концов?}
{271}{}{Я думал, что мы это уже проехали! Я не голоден и никогда не буду. Так почему же ты НА САМОМ ДЕЛЕ здесь?}

# Node  7  [Node008]
{280}{}{Хорошо, не надо кричать. Голод никогда не был хорошим способом начать свой день. Я был создан, как спутник завтрака, но я также мог использоваться на обед или ужин. Не существует времени дня, когда легкий тост повредит. Если ты спрашиваешь почему я сижу здесь с провод свисающим с моего бока, ну, похоже Мистер Хенди не всегда соответствует своему имени - парень начал разрушаться прямо в середине моей ежегодной проверки и технического обслуживания. Конечно, он отключился в боксе техобслуживания и оставил меня висеть.}
{281}{}{Я вижу. Спасибо за твое время.}

{290}{}{Нет проблем. Заходи снова. Может быть, тогда ты будешь голоден.}
{291}{}{Я сомневаюсь в этом. Пока.}

{300}{}{Я знал, что ты вернешься. Они всегда возвращаются. Хочешь какой-нибудь тост?}
{301}{}{Я знал, что ты вернешься. Они всегда возвращаются. И теперь, когда я снова полностью функционален, я могу сделать тост лучше, чем когда-либо. Итак, хочешь какой-нибудь тост?}
{302}{}{Не сейчас. Я должен тебя спросить.}
{303}{}{Нет. Я должен идти.}

{310}{}{Конечно, что бы ты хотел узнать? Я надеюсь, что это про тосты.}
{311}{}{Что это за место?}
{312}{}{Забудь. Пока.}

{350}{}{Эй, ты починил меня! Я знал, что Мистер Хенди просто оставил работу незавершенной. Теперь я чувствую себя лучше, чем когда-либо! Спасибо.}
{351}{}{Конечно, именно это я и сделал. Увидимся позже.}
{352}{}{Теперь держитесь. Если ты не позволишь мне вознаградить тебя тостом, то по крайней мере позволь мне дать тебе небольшой совет. Знаешь, эти игровые автоматы в казино? Я рассчитал метод, который может избавить машины от их денежных средств.
 У меня IQ 6000. Когда я не делаю тосты, я обдумываю подобные вещи. За помощь мне, я скажу тебе эти секретные коды. Просто воспользуйтесь одной из машин, как обычно, и...}
{353}{}{[БОЛЬШЕ]}
{354}{}{...И это все, что нужно делать. Ты будешь богат не затратив времени и будешь есть тосты наполняя свое сердце.}
{355}{}{Спасибо. Я ценю это. Увидимся.}

{400}{}{Вы успешно починили тостер.}
{401}{}{Вы не в состоянии починить тостер.}
{402}{}{Вы уже отремонтировали тостер.}
###.Magnat.###...Added by Killap. Need translation...########################
{403}{}{ successfully repairs the toaster.}
{404}{}{ fails to repair the toaster.}

