# Message file for epac5.ssl 
# Number of nodes: 5

###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите голограмму.}
{101}{}{Вы видите директора по операциям.}
{102}{}{Голограмма 12001. Он руководит операциями в EPA.}

# Node  0  [Node001]
{200}{}{[Эта умная голограмма приветствует вас нервной улыбкой.] Здравствуйте, добро пожаловать EPA. Вы могли заметить, что мы испытываем некоторые трудности, но мы их успешно преодолеем.}
{201}{}{Ух, хорошо. Кто вы?}

# Node  1  [Node002]
{210}{}{Я директор по операциям для EPA.}
{211}{}{О, правильно. [Вы чешете голову] Что это на самом деле означает?}

# Node  2  [Node003]
{220}{}{[Он тревожно смеется.] Это означает то, что я координатор. Заставляю шарики крутиться. Теперь в вашем распоряжении. Я хотел бы принести лучшее людям. Здесь, в охране окружающей среды, самое оно. Честность. Целостность. Спасибо, мы ценим ваше мнение.}
{221}{}{О чем, черт возьми, ты говоришь?}

# Node  3  [Node004]
{230}{}{Я заверяю вас, что мы прилагаем все усилия, чтобы решить все вопросы. У нас было небольшое сокращение штата, но все смотрят в будущее. Я уверен, что все квоты будут достигнуты в установленные сроки.}
{231}{}{Какие квоты? В твоей речи никакого смысла. Ты на самом деле делаешь хоть что-нибудь здесь? Можешь ли ты помочь мне, или нет?}

# Node  4  [Node005]
{240}{}{Это все зависит от вашего мировоззрения. Мои руки связаны по этому вопросу, но я был бы рад помочь вам, если вы можете.}
{241}{}{Забудь об этом. Пока.}
{242}{}{Я сожалею, что вы не могли оказать дополнительную помощь.}
{243}{}{Спасибо за ваше время.}

{244}{}{Я не хочу комментировать.}
{245}{}{Без комментариев.}
{246}{}{Я хотел бы, но я в настоящее время оспариваю первенство.}
{247}{}{Мы будем решать этот вопрос когда дойдем до него.}
{248}{}{Это совещание для обсуждения, а не для действий.}
{249}{}{Я уверен, EPA находится на пути к успеху.}
{250}{}{Проблема релевантности - текущий вопрос.}
{251}{}{Давайте не будем торопиться, иначе мы будем действовать слишком быстро.}
{252}{}{Это звучит адекватно.}
{253}{}{Я понимаю вашу озабоченность.}

