###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите Декса.}
{101}{}{Вы видите красивого, безукоризненно ухоженного мужчину. Под впечатляющими приглаженными волосами, его глаза светятся мудростью... или возможно безумием.}

#good/neutral male intro
{200}{}{[По мере приближения к криогенной камере, вы видите привлекательного голово мужчину лежащего на полу. Он сгибает колени и прижимает их к груди. Несколько мгновений он сидит, бессмысленно глядя вперед, пока его тело трясется и его зубы клацают. Постепенно он, кажется, успокаивается.]}
{201}{}{Ух, привет?}

{210}{}{[Он поворачивает голову к вам, и встает на ноги. Он внимательно наблюдает за вами, а потом оглядывается вокруг, как загнанный зверь. Когда его глаза возвращаются к тебе, они смягчаются и он расслабляется, потому что его воспоминания возвращаются к нему. Он быстро возвращает свое спокойствие, уверенность и хладнокровие, несмотря на свою наготу.] Я не узнаю тебя, приятель. Вы не возражаете, если я оденусь, не так ли?}
{211}{}{Я думаю, вреда не будет-}
{212}{}{Ну, Я-}

{220}{}{Конечно, ты не возражаешь. Спасибо, приятель. [Он шагает мимо вас и открывает шкафчик рядом. Он небрежно одевается в хорошо сшитый костюм и рассовывает содержимое шкафчика раздевалки по карманам. Используя карманный гребешок, он начинает расчесывать и прилизывать свои темные волосы с быстротой и точностью матерого профессионала.] Итак, где же Док?}
{221}{}{Док? Ах, он вероятно где-то здесь. Вообще-то я думаю, что он убежал, поэтому я тоже сваливаю отсюда и желаю вам наверстать упущенное. Пока!}
{222}{}{Это может стать шоком для вас, но вы были заморожены в течение очень долгого времени. Тот, кто был "доком" давно уже мертв. Если он был вашим другом, то я сожалею.}
{223}{}{Я не хочу сразить вас наповал, но вы были во льду *по-настоящему* долго. Я уверен, что ваш друг "док", давным-давно мертв.}
{224}{}{Послушай, мой хорошенький мальчик. Я разморозил твою психотическую задницу не для того, чтобы я мог ответить на ваши вопросы и смотреть, как ты наводишь марафет. Я только позволю тебе прожить достаточно долго, чтобы дать мне полезную информацию которую ты имеешь. Итак, начинай говорить. Чем больше ты сможешь рассказать мне, чем дольше ты проживешь.}

{230}{}{[Его хладнокровное поведение исчезает и глаза его вспыхивают яростью.] Вы думаете, что можете меня запугать? Do you have the first FUCKING CLUE who you're talking to? Иди сюда и я тебе покажу, на что я способен!}
{231}{}{[Готово.]}

{240}{}{[Декс улыбается вам, открывая набор совершенных зубов, продукт довоенной стоматологии, которые выглядят странно для вас во всей их жемчужно-белой симметрии.] Док, друг мой? [Он поднял бровь.] Ты не знаешь, кто я, не так ли?}

{241}{}{Ух, не совсем. Я вроде бродил вокруг этого странного объекта, охотился за вещами, и просто так случилось, что я разморозил тебя. Почему тебя заморозили тут?}
{242}{}{Ну, в соответствии с этим компьютером, вы Декс, самовлюбленный, социопатичный убийца из довоенной эпохи. Я только разморозил вас, чтобы я мог прибить вас, как больную собаку.}
{243}{}{Ух, не совсем. Я уверен, что ты совершенно нормальный парень, которого хранили в замороженном состоянии по совершенно нормальным, без злых задумок, причинам. Черт возьми, откуда я знаю? Я вроде бродил вокруг этого странного объекта, охотился за вещами, и просто так случилось, что я разморозил тебя.}

{250}{}{[Декс еще раз окидывает взглядом комнату и камеры.] Это место действительно превратилось в дерьмо. Как долго вы говорить я здесь находился?}
{251}{}{Ну как минимум в течение ста пятидесяти лет после Великой Войны, которая положила конец Древним... *вашему* народу.}

{260}{}{Великая Война? Древние? Как насчет избавить меня от этой загадочной фигни и рассказать мне, что случилось?}
{261}{}{Великой Войной мои люди называют конец вашего мира. Когда пламя пожаров сыпалось с неба и выжегало земли. Вы найдете мир совершенно не похожим, на тот, что вы знали.}

{270}{}{Вот дерьмо, так что они на самом деле сбросили бомбы, да? Я думаю, проект Убежище в конце концов был не просто бесполезной тратой денег налогоплательщиков.}
{271}{}{Подождите. Вы знаете о священных убежищах?}

{280}{}{Знаю о них? Черт, я жил у самого Чикагского Убежища. Я даже смотрел как они достраивали его. Тогда, конечно, они начали делать эти чертовы упражнения... [Он останавливается и рассматривает вас с удовольствием.] Вам действительно надо это, не так ли?}
{281}{}{РАССКАЖИ МНЕ БОЛЬШЕ ОБ УБЕЖИЩАХ!}
{282}{}{Ну, видите, я выбран своим народом, чтобы попытаться найти Убежище. Там я надеюсь получить ГЕКК и использовать его мощь, чтобы спасти мою деревню от уничтожения. Все, что вы сможете рассказать мне об Убежищах могло бы помочь мне в моих поисках.}
{283}{}{Ну, видите, я выбран своим народом, чтобы попытаться найти Убежище. Рискуя своей жизнью в бесчисленных приключениях, Я наконец нашел священное 13-е. Однако мне любопытно, что еще вы знаете об этих строениях.}

{290}{}{Я тебе вот что скажу, приятель. Ты должен помочь мне найти эти убежища, и мне нужен человек, чтобы показать мне тропы, так сказать, в этом твоем безумном мире. Так что же ты скажешь... партнер?}
{291}{}{Хм, твои знания старины могут оказаться весьма полезными для меня... Но, ну, честно говоря, я, прочитал о тебе вон в том компьютере, и я не уверен, что ты из тех парней с которыми я захочу путешествовать.}
{292}{}{У меня нет времени, чтобы "показывать вам тропы". Я уверен, что вы будете заботиться только о себе, "приятель".}
{293}{}{Я говорю по рукам... партнер.}
{294}{}{Я не думаю, что слишком охотно пойду разгуливать в пустыню с психотическим убийцей. Лучше вы сами по себе, "приятель". Не беспокойтесь, я уверен что у вас все будет прекрасно. [Усмехаясь.]}

{300}{}{Эй, притормози. Позволь мне угадать, ты прочитал что я какой-то сумасшедший убийца, верно? Ну приятель, у меня для тебя два слова: Дерьмо. Собачье. Не покупайся на это.}
{301}{}{Но это не имеет никакого смысла, зачем они лгут насчет тебя?}
{302}{}{Дерьмо это то, что извергается из уст твоих, и я думаю, что время мне заткнуть тебя навсегда.}

{310}{}{Эй, я знаю, похоже чтов этом вообще нет смысла, но ты ходил вокруг этого места? Не большого смысла в создании этого места. Кто знает, что происходит в умах этих траханых ученых. }
{311}{}{Хм... два очка тебе. Я не говорю, что я тебе верю... но я полагаю, что могу по крайней мере выслушать тебя.}
{312}{}{Да, без шуток. Продолжай...}

{320}{}{Ладно. Видите ли, все это часть их "экспериментов". Эти ебаные сумасшедшие врачи делали какие-то тесты "чистого человеческого зла" или какого-то похожего дерьма. Они вводили мне воспоминания маньяка, чтобы посмотреть, как они отразятся на личности обычного человека. По крайней мере, это максимум, что я смог понять.}
{321}{}{Ну... если это правда, то это ужасно. Но во-первых, что заставило их выбрать тебя в качестве испытуемого?}
{322}{}{Эй чувак, это на самом деле отстой. Во всяком случае, это все в прошлом. Те мудаки ученые давно мертвы и не будут досаждать тебе больше. Пойдем со мной, свалим из этого места.}

{330}{}{Хех, видите, самое смешное, что *Я* на самом деле пришел к *ним*. Ответил на их объявление в котором говорилось, что они заплатят много баксов здоровому испытуемому. Мне нужны были деньги, и, ну, это оказалось самой большой ошибкой в моей жизни. Я даже не могу рассказать каким ужасам я подвергался. [Его глаза мерцают слезами, когда он размышляет. Вздыхает глубоко и вытирает слезы.] Во всяком случае, спасибо приятель, наконец я свободен от этого кошмара.}
{331}{}{Ха. Что ж, я рад, что смог помочь... наверное.}
{332}{}{На самом деле, мудак, твой кошмар только начинается, потому что я не верь ни одному твоему слову.}

{340}{}{Так как насчет моего предложения, приятель? Можем ли мы стать партнерами? Я тебя не задержу оказавшисть в команде и я могу позаботиться в себе в бою. Черт, я бы спокойно пошел соло, но у меня ни малейшего понятия, какое сумасшедшее дерьмо таится снаружи. Все что я знаю, первое дерево на которое я помочусь может открыть рот и откусить мне яйца.}
{341}{}{Хорошо, ты можешь путешествовать со мной, но я буду внимательно следить за тобой. Второе - ты даже не думать зайти за линию, иначе я тебя урою.}
{342}{}{Да, я полагаю, мы могли бы стать партнерами. Добро пожаловать в команду, Декс.}
{343}{}{Это была чертовски хорошая история, и вы не плохой актер, что делает вас еще более опасным. Я думаю, я сделаю пустыне одолжение и удалю вас, прежде чем вы можете принести вред.}


#dialogue added 12/28/08
#did not read bio
{350}{}{[Декс усмехается и его глаза расфокусируются. Через некоторое время он начинает говорить, стараясь не встречаться с вашим взглядлм.] Я был одним из их больных экспериментов. Они делали... страшные вещи со мной.
 [Он качает головой, потом смотрит на вас с новой улыбкой.] Я бы не хотел говорить об этом... Меня Декс зовут, кстати.}
{351}{}{Жаль слышать это, Декс. Во всяком случае, это все в прошлом. По настоящему *далеком* прошлом.}
{352}{}{Смотри Декс, я мог бы тебе помочь, но я хотел бы знать, с кем я имею дело. Что именно они делали с тобой?}

{360}{}{[Декс еще раз окидывает взглядом комнату и камеры.] Это место действительно превратилось в дерьмо. Как долго вы говорить я здесь находился?}

{370}{}{Хорошо, тебе правда нужно знать? Прекрасно. В основном эти сумасшедшие ебаные врачи делали какие-то тесты на "чистое человеческое зло" или какого-то похожего дерьма. Они вводили мне воспоминания маньяка, чтобы посмотреть, как это повлияет на личность такого порядочного, законопослушного парня, как я. По крайней мере, это максимум, что я смог понять.}
{371}{}{Я вижу. Итак, как же это *влияет* на тебя? }
{372}{}{Я не знаю, это дало мне только ночные кошмары, хорошо? Послушай, я был заморожен фиг знает, как долго, и я не в настроении для ебаного допроса. Ты почти такой же плохой, как Док...
 Ты говоришь, он мертв? Как долго я был заморожен? Это место выглядит дерьмово.}


#good/neutral female intro
{400}{}{[По мере приближения к криогенной камере, вы видите привлекательного голово мужчину лежащего на полу. Он сгибает колени и прижимает их к груди. Несколько мгновений он сидит, бессмысленно глядя вперед, пока его тело трясется и его зубы клацают. Постепенно он, кажется, успокаивается.]}
{401}{}{Ух, привет?}

{410}{}{[Он поворачивает голову к вам, и встает на ноги. Он внимательно наблюдает за вами, а потом оглядывается вокруг, как загнанный зверь. Когда его глаза возвращаются к тебе, они смягчаются и он расслабляется, потому что его воспоминания возвращаются к нему. Он быстро возвращает свое спокойствие, уверенность и хладнокровие, несмотря на свою наготу.] Эй, куколка, я знаю, что я довольно привлекателен, но здесь прохладно. Вы не возражаете, если я оденусь?}
{411}{}{Я думаю, вреда не будет-}
{412}{}{Ну, Я-}

{420}{}{Конечно, ты не возражаешь. Спасибо, детка. [Он шаги мимо вас, нежно похлопывая вашу попу, и открывает шкафчик рядом. Он небрежно одевается в хорошо сшитый костюм и рассовывает содержимое шкафчика раздевалки по карманам. Используя карманный гребешок, он начинает расчесывать и прилизывать свои темные волосы с быстротой и точностью матерого профессионала.] Я не думаю, что я видел тебя раньше, куколка, и я сомневаюсь, что я забыл бы такое лицо как у вас. Я Декс, но я уверен вы это уже знаете. Не возражаете, если я спрошу вас?}
{421}{}{Я }
{422}{}{. Но вы должны знать, у меня есть строгое правило не встречаться с посторонними, которых я разморозила. Похоже вы были во льду последние полтора века. я буду считать что рука соскользнула и случайно ударила по моей заднице.
 Но если это случится еще раз, я вырву твой член с корнем, понял?}
{423}{}{Меня зовут }
{424}{}{. Приятно встретиться с вами, Декс. Я не могу себе представить, каково проснуться после заморозки на сто пятьдесят лет.}
{425}{}{Да, мне не все равно, ты змей подколодный. Я разморозила тебя только для того, чтобы удавить тебя, как больную собаку.}
{426}{}{Забудь об имени. Как насчет снять одежду и показать мне, из чего сделан довоенный мужчина...}

{430}{}{[Он улыбается и начинает раздеваться.] Ты мой тип женщины. Приготовься отведать Декса, герцога секса.}
{431}{}{[Продолжить.]}

{440}{}{[После сексуального марафона на полу камеры, вы оба лежите в изнеможении. Декс держит небольшой предмет рядом с вашим ртом.] Покричи для меня, детка. [Как только вы понимаете что это оторваное человеческое ухо, вы чувствуете лезвие проткнуло вашу грудь. Вы кричите, когда вытащил лезвие и снова вонзил...]}
{441}{}{[Конец.]}

{450}{}{Эй, погоди, погоди. Вернемся чуть назад, милая. Ты только что сказала сто пятьдесят лет? [Он качает головой в знак недоверия.] Это бля невероятно. [Он проверяет свое отражение.] Но ты должна признать, я выгляжу чертовски хорошо для своего возраста. [Он улыбается вам, показывая набор совершенных зубов, продукт стоматологии довоенного времени, что выглядит странно для вас во всей их жемчужно-белой симметрии.]}

#read the bio
{451}{}{Конечно, некоторые девушки могут найти вас привлекательным, но я с трудом могу смотреть сквозь пальцы на то, что вы хладнокровнй псих - убийца.}
{452}{}{Да, ты очень привлекателен, но честно говоря, я немного нервничаю, говоря с вами после того, что я прочитала про психа - убийцу.}
{453}{}{Ладно, это тошно. Давай посмотрим, как хорошо ты будешь выглядеть после того как я сделаю пару дырок в твоем лице.}

#did not read the bio
{454}{}{Не плохо для ледяного человека. Почему вас заморозили там?}
{455}{}{Эх, ты не мой тип. Во всяком случае, почему тебя заморозили там?}
{456}{}{Ладно, это тошно. Давай посмотрим, как хорошо ты будешь выглядеть после того как я сделаю пару дырок в твоем лице.}

{460}{}{Ладно, где ты взяла это дерьмо о том, что я "псих убийца"?}
{461}{}{Не пытайтесь надуть меня. Я читала о вас на этом компьютере.}
{462}{}{Вон в том компьютере были кое-какиео данные на вас, и в нем есть некоторые очень страшные вещи.}
{463}{}{Я это чувствую. Вас выдает эта дрожь.}
{464}{}{Не пытайтесь надуть меня. Я знаю таких людей.}

{470}{}{А, ну это имеет смысл. Не беспокойтесь, это не то, о чем вы думаете. Я объясню все чуть позже. Но прежде всего, вы не могли бы рассказать мне, что, черт возьми, произошло, как давно они заморозили меня? Я имею в виду что это место дерьмово выглядит, как буд-то я герой какого-то научно-фантастического приключенческого рассказа.}
{471}{}{Ну как минимум сто пятидесят лет, после Великой Войны, которая положила конец Древних... *твоему* народу...}

{475}{}{Великая Война? Древние? Как насчет избавить меня от этой загадочной фигни и рассказать мне, что случилось?}
{476}{}{Великой Войной мои люди называют конец вашего мира. Когда пламя пожаров сыпалось с неба и выжегало земли. Вы найдете мир совершенно не похожим, на тот, что вы знали.}

{480}{}{Вот дерьмо, так что они на самом деле сбросили бомбы, да? Я думаю, проект Убежище в конце концов был не просто бесполезной тратой денег налогоплательщиков.}
{481}{}{Подождите. Вы знаете о священных убежищах?}

{490}{}{Знаю о них? Черт, я жил у самого Чикагского Убежища. Я даже смотрел как они достраивали его. Тогда, конечно, они начали делать эти чертовы упражнения... [Он останавливается и рассматривает вас с удовольствием.] Вам действительно надо это знать, не так ли, детка?}
{491}{}{РАССКАЖИ МНЕ БОЛЬШЕ ОБ УБЕЖИЩАХ!}
{492}{}{Ну, видите, я выбран своим народом, чтобы попытаться найти Убежище. Там я надеюсь получить ГЕКК и использовать его мощь, чтобы спасти мою деревню от уничтожения. Все, что вы сможете рассказать мне об Убежищах могло бы помочь мне в моих поисках.}
{493}{}{Ну, видите, я выбран своим народом, чтобы попытаться найти Убежище. Рискуя своей жизнью в бесчисленных приключениях, Я наконец нашел священное 13-е. Однако мне любопытно, что еще вы знаете об этих строениях.}

{500}{}{Я тебе вот что скажу, детка. Ты должна помочь мне найти эти убежища, и мне нужен человек, чтобы показать мне тропы, так сказать, в этом твоем безумном мире. Так что же ты скажешь... партнерша?}
{501}{}{Я говорю по рукам... партнер.}
{502}{}{Хм, твои знания старины могут оказаться весьма полезными для меня... Но, ну, честно говоря, я, прочитала о тебе вон в том компьютере, и я не уверена, что ты из тех парней с которыми я захочу путешествовать...}
{503}{}{Я не думаю, что слишком охотно пойду разгуливать в пустыню с психотическим убийцей. Лучше уж вы сами по себе, "детка". Не беспокойтесь, я уверена что у вас все будет прекрасно. [Усмехаясь.]}

{510}{}{Эй, я уже сказал тебе, я могу объяснить. Все, что ты читала про меня полная фигня. Не верь ни единому слову.}
{511}{}{Эй, я уже сказал тебе, я могу объяснить. Эти злые флюиды от меня являются результатом экспериментов, которые ученые проводили на мне.}
{512}{}{Но это не имеет никакого смысла, что с тобой сделали?}
{513}{}{Дерьмо. Я думаю, время мне заткнуть твой рот.}
{514}{}{Но это не имеет никакого смысла, зачем они лгут насчет тебя?}
{515}{}{Дерьмо это то, что извергается из уст твоих, и я думаю, что время мне заткнуть тебя навсегда.}

{520}{}{Эй, я знаю, похоже чтов этом вообще нет смысла, но ты ходил вокруг этого места? Не большого смысла в создании этого места. Кто знает, что происходит в умах этих траханых ученых.}
{521}{}{Хм... два очка тебе. Я не говорю, что я тебе верю... но я полагаю, что могу по крайней мере выслушать тебя.}
{522}{}{Да, без шуток. Продолжай...}

{530}{}{Ладно. Видите ли, все это часть их "экспериментов". Эти ебаные сумасшедшие врачи делали какие-то тесты "чистого человеческого зла" или какого-то похожего дерьма. Они вводили мне воспоминания маньяка, чтобы посмотреть, как они отразятся на личности обычного человека. По крайней мере, это максимум, что я смог понять.}
{531}{}{Ну... если это правда, то это ужасно. Но во-первых, что заставило их выбрать тебя в качестве испытуемого?}
{532}{}{Ах ты бедненький! Ну, ну, теперь все в прошлом. Те ужасные люди давно мертвы и не смогут повредить тебе снова. Пойдем со мной, и мы уберемся из этого места.}

{540}{}{Хех, видишь, самое смешное, что *Я* на самом деле пришел к *ним*. Ответил на их объявление в котором говорилось, что они заплатят много баксов здоровому испытуемому. Мне нужны были деньги, и, ну, это оказалось самой большой ошибкой в моей жизни. Я даже не могу рассказать каким ужасам я подвергался. [Его глаза мерцают слезами, когда он размышляет. Вздыхает глубоко и вытирает слезы.] Во всяком случае, спасибо, }
{541}{}{. Наконец я свободен от этого кошмара.}
{542}{}{Ха. Что ж, я рада, что смогла помочь... наверное...}
{543}{}{На самом деле, мудак, твой кошмар только начинается, потому что я не верь ни одному твоему слову.}

{550}{}{Так как насчет моего предложения, детка? Можем ли мы стать партнерами? Я тебя не задержу оказавшисть в команде и я могу позаботиться в себе в бою. Черт, я бы спокойно пошел соло, но у меня ни малейшего понятия, какое сумасшедшее дерьмо таится снаружи. Все что я знаю, первое дерево на которое я помочусь может открыть рот и откусить мне яйца.}
{551}{}{Хорошо, ты можешь путешествовать со мной, но я буду внимательно следить за тобой. Второе - ты даже не думать зайти за линию, иначе я тебя урою. }
{552}{}{Да, я полагаю, мы могли бы стать партнерами. Добро пожаловать в команду, Декс.}
{553}{}{Это была чертовски хорошая история, и вы не плохой актер, что делает вас еще более опасным. Я думаю, я сделаю пустыне одолжение и удалю вас, прежде чем вы можете принести кому-нибудь вред.}

#did not read the bio
{554}{}{Я скажу договорились... партнер. }
{555}{}{Ну, ваши знания старины могут оказаться весьма полезными для меня... Я полагаю, мы договорились.}
{556}{}{У меня нет времени, чтобы "показывать тебе тропы". Я уверен, что ты будешь в порядке сам по себе, "детка".}

#dialogue added 12/28/08
#Non-evil female, did not read the bio
{560}{}{Декс усмехается и его глаза расфокусируются. Через некоторое время он начинает говорить, стараясь не встречаться с вашим взглядлм.] Я был одним из их больных экспериментов. Они делали... страшные вещи со мной.
 [Он качает головой, потом смотрит на вас с новой улыбкой.] Во всяком случае, я бы лучше поговорил о тебе, детка.}
{561}{}{Ну, ладно, вот... Я родилась и выросла в деревне Арройо. Моя мать староста, и мы прямые потомки легендарного Жителя Убеж-}
{562}{}{Послушай, Декс, я могла бы вам помочь, но я хотела бы знать, с кем я имею дело. Что именно они делали с тобой?}

{570}{}{Вау, это правда интересно, детка, и я не могу ждать, чтобы услышать больше о тебе. Честно. Но прежде всего, вы не могли бы рассказать мне, что, черт возьми, произошло, как давно они заморозили меня? Я имею в виду что это место дерьмово выглядит, как буд-то я герой какого-то научно-фантастического приключенческого рассказа.}

{580}{}{Ладно, тебе и правда надо это знать? Отлично. Эти ебаные сумасшедшие врачи делали какие-то тесты "чистого человеческого зла" или какого-то похожего дерьма. Они вводили мне воспоминания маньяка, чтобы посмотреть, как они отразятся на личности обычного человека. По крайней мере, это максимум, что я смог понять.}
{581}{}{Я вижу. Итак, как же это *влияет* на тебя?}
{582}{}{Я не знаю, это дало мне только ночные кошмары, хорошо? Послушай, милая, я был заморожен фиг знает как долго, и я не в настроении для ебаного допроса. Я ответил на твои вопросы, а теперь как насчет рассказать мне о том, что тут произошло, после того как они положить мне в лед. Я имею в виду что это место дерьмово выглядит, как буд-то я герой какого-то научно-фантастического приключенческого рассказа.}


#evil male intro
{600}{}{[По мере приближения к криогенной камере, вы видите привлекательного голово мужчину лежащего на полу. Он сгибает колени и прижимает их к груди. Несколько мгновений он сидит, бессмысленно глядя вперед, пока его тело трясется и его зубы клацают. Постепенно он, кажется, успокаивается.]}
{601}{}{Ох, эй...}

{610}{}{[Он поворачивает голову к вам, и встает на ноги. Он внимательно наблюдает за вами, а потом оглядывается вокруг, как загнанный зверь. Когда его глаза возвращаются к тебе, они смягчаются и он расслабляется, потому что его воспоминания возвращаются к нему. Он быстро возвращает свое спокойствие, уверенность и хладнокровие, несмотря на свою наготу.] Я не узнаю тебя, приятель. Вы не возражаете, если я оденусь, не так ли?}
{611}{}{Я думаю, вреда не будет-}
{612}{}{Ну, Я-}

{620}{}{Конечно, ты не возражаешь. Спасибо, приятель. [Он шагает мимо вас и открывает шкафчик рядом. Он небрежно одевается в хорошо сшитый костюм и рассовывает содержимое шкафчика раздевалки по карманам. Используя карманный гребешок, он начинает расчесывать и прилизывать свои темные волосы с быстротой и точностью матерого профессионала.] Итак, где же Док?}
{621}{}{Чтоб меня... Где бы он ни был, он давно мертв. Видите ли, вы делали вид, что вы - эскимо довольно ДОЛГОЕ время.}
{622}{}{Послушай, мой хорошенький мальчик. Я разморозил твою психотическую задницу не для того, чтобы я мог ответить на ваши вопросы и смотреть, как ты наводишь марафет. Я только позволю тебе прожить достаточно долго, чтобы дать мне полезную информацию которую ты имеешь. Итак, начинай говорить. Чем больше ты сможешь рассказать мне, чем дольше ты проживешь.}

{630}{}{Так ли это? [Он рассматривает тебя с любопытством.] Вас я точно здесь раньше не видел, приятель, но вы решили освободить меня, и я хотел бы знать, почему. Я полагаю, вы знаете, кто я?}
{631}{}{Да, ты Декс, не так ли? Если то, что я прочитал о тебе правда, то ты дьявольский сукин сын. Мне это нравится.}
{632}{}{Ну, в соответствии с данными этого компьютера, ты Декс, самовлюбленный, социопатичный убийца времен Великой Войны. Я разморозил тебя только чтобы прибить, как больную собаку.}
{633}{}{Не знаю, но вы источаете эти злые флюиды, это я одобряю.}

{640}{}{[Его спокойное прохладное поведение исчезает, и глаза вспыхивают яростью.] Вы думаете, что можете меня запугать? Do you have the first FUCKING CLUE who you're talking to? Иди сюда, я тебе покажу, на что я способен!}
{641}{}{[Готово.]}

{650}{}{[Декс улыбается вам, открывая набор совершенных зубов, продукт довоенной стоматологии, которые выглядят странно для вас во всей их жемчужно-белой симметрии.] Я понял, что-то мне в тебе нравится. У тебя хороший вкус.
 Не думаю, что ты также фанат Короля?}
{651}{}{Ух.... [бегающий взгляд.]}
{652}{}{О да, я люблю... а, как ты его назвал, Король? Да, я большой поклонник.}

{660}{}{Забудь, приятель. [Декс окидывает взглядом комнату и камеры.] Это место дерьмово выглядит. Как долго я был заморожен?}
{661}{}{Примерно в течение ста пятидесяти лет после Великой Войны, которая положила конец Древним... *вашему* народу.}

{665}{}{Великая Война? Древние? Как насчет избавить меня от этой загадочной фигни и рассказать мне, что случилось?}
{666}{}{Великой Войной мои люди называют конец вашего мира. Когда пламя пожаров сыпалось с неба и выжегало земли. Вы найдете мир совершенно не похожим, на тот, что вы знали.}

{670}{}{Вот дерьмо, так что они на самом деле сбросили бомбы, да? Я думаю, проект Убежище в конце концов был не просто бесполезной тратой денег налогоплательщиков.}
{671}{}{Стой. Ты знаешь об убежищах?}

{680}{}{Знаю о них? Черт, я жил у самого Чикагского Убежища. Я даже смотрел как они достраивали его. Тогда, конечно, они начали делать эти чертовы упражнения... [Он останавливается и рассматривает вас с удовольствием.] Вам действительно надо это, не так ли?}
{681}{}{РАССКАЖИ МНЕ БОЛЬШЕ ОБ УБЕЖИЩАХ!}
{682}{}{Ну, видите, я выбран своим народом, чтобы попытаться найти Убежище. Там я надеюсь получить ГЕКК и использовать его мощь, чтобы спасти мою деревню от уничтожения. Все, что вы сможете рассказать мне об Убежищах может сделать мою работу в аду гораздо проще.}
{683}{}{Ну, видите, я выбран своим народом, чтобы попытаться найти Убежище. Рискуя своей жизнью в бесчисленных приключениях, Я наконец нашел свое 13-е убежище. Однако мне любопытно, что еще вы знаете об этих строениях.}

{690}{}{Я тебе вот что скажу, приятель. Ты должен помочь мне найти эти убежища, и мне нужен человек, чтобы показать мне тропы, так сказать, в этом твоем безумном мире. Так что же ты скажешь... партнер?}
{691}{}{Дьявол, нет необходимости убеждать меня. Я буду рад видеть нас вместе просто чтобы посмотреть твою работу из первых рук.}
{692}{}{Я не знаю, Декс. Скажем так, я позволю тебе пойти со мной, и мы вернемся в отдаленное безопасное поселение. Оказавшись там, откуда я знаю, что ты не попробуешь перерезать мне горло при первом удобном случае?}

{700}{}{Я могу ответить, что ты не святой, так что я мог бы спросить тебя то же самое. Но отвечу на твой вопрос, я не убил бы тебя потому что это бы наебкой. Я буду честным, }
{701}{}{, Я не наебываю никого и ничего, кроме себя. Может мир и затрахал, как ты говоришь, но я вытащил свой самый самый счастливый билет. Это так просто.}
{702}{}{Достаточно справедливо. Пойдем.}
{703}{}{Я с тобой, Декс. Я никогда не имел намерения брать тебя с собой. Я просто думал, что я получу немного удовольствия перед дроблением твоего черепа.}

#evil female intro
{800}{}{[По мере приближения к криогенной камере, вы видите привлекательного голово мужчину лежащего на полу. Он сгибает колени и прижимает их к груди. Несколько мгновений он сидит, бессмысленно глядя вперед, пока его тело трясется и его зубы клацают. Постепенно он, кажется, успокаивается.]}
{801}{}{Ох, эй...}

{810}{}{[Он поворачивает голову к вам, и встает на ноги. Он внимательно наблюдает за вами, а потом оглядывается вокруг, как загнанный зверь. Когда его глаза возвращаются к тебе, они смягчаются и он расслабляется, потому что его воспоминания возвращаются к нему. Он быстро возвращает свое спокойствие, уверенность и хладнокровие, несмотря на свою наготу.] Эй, куколка, я знаю, что я довольно привлекателен, но здесь прохладно. Вы не возражаете, если я оденусь?}
{811}{}{Я думаю, вреда не будет-}
{812}{}{Ну, Я-}

{820}{}{Конечно, ты не возражаешь. Спасибо, детка. [Он шаги мимо вас, нежно похлопывая вашу попу, и открывает шкафчик рядом. Он небрежно одевается в хорошо сшитый костюм и рассовывает содержимое шкафчика раздевалки по карманам. Используя карманный гребешок, он начинает расчесывать и прилизывать свои темные волосы с быстротой и точностью матерого профессионала.] Я не думаю, что я видел тебя раньше, куколка, и я сомневаюсь, что я забыл бы такое лицо как у вас. Я Декс, но я уверен вы это уже знаете. Не возражаете, если я спрошу вас?}
{821}{}{Меня зовут }
{822}{}{. Но вы должны знать, у меня есть строгое правило не встречаться с посторонними, которых я разморозила. Похоже вы были во льду последние полтора века. я буду считать что рука соскользнула и случайно ударила по моей заднице.
 Но если это случится еще раз, я вырву твой член с корнем, понял?}
{823}{}{Я }
{824}{}{. Приятно встретиться с вами, Декс. Я не могу себе представить, каково проснуться после заморозки на сто пятьдесят лет.}
{825}{}{Да, мне не все равно, ты змей подколодный. Я разморозила тебя только для того, чтобы удавить тебя, как больную собаку.}
{826}{}{Забудь об имени. Как насчет снять одежду и показать мне, из чего сделан довоенный мужчина.}

{830}{}{[Улыбается и начинает раздеваться.] Ты мой тип женщины. Приготовься отведать Декса, герцога секса.}
{831}{}{[После сексуального марафона на полу камеры, вы оба лежите в изнеможении. Вы лукаво показываете Дексу на его спрятанный нож. Вы быстро хватаете его за гениталии.]}
{832}{}{Тронешь нож, и я сделаю тебя Безчленным герцогом. Кроме того, зачем портить хорошую вещь? Вдвоем нам может быть еще веселей, вместе.}
{833}{}{Я... я думаю, что я влюбился. [Декс присоединился к вашей группе.]}

{840}{}{Эй, погоди, погоди. Вернемся чуть назад, милая. Ты только что сказала сто пятьдесят лет? [Он качает головой в знак недоверия.] Это бля невероятно. [Он проверяет свое отражение.] Но ты должна признать, я выгляжу чертовски хорошо для своего возраста. [Он улыбается вам, показывая набор совершенных зубов, продукт стоматологии довоенного времени, что выглядит странно для вас во всей их жемчужно-белой симметрии.]}
{841}{}{Конечно, некоторые девушки могут найти вас привлекательным, но я с трудом могу смотреть сквозь пальцы на то, что вы хладнокровнй псих - убийца.}
{842}{}{Ладно, это тошно. Давай посмотрим, как хорошо ты будешь выглядеть после того как я сделаю пару дырок в твоем лице.}
{843}{}{Конечно, некоторые девушки могут найти вас привлекательным, но я уверена, что они будут чувствовать убийственные психологические вибрации.}

#did not read the bio
{844}{}{Не плохо для ледяного человека. Почему тебя заморозили там?}
{845}{}{Эх, ты не мой тип. Во всяком случае, почему тебя заморозили там?}
{846}{}{Ладно, это тошно. Давай посмотрим, как хорошо ты будешь выглядеть после того как я сделаю пару дырок в твоем лице.}

{850}{}{Ну, они обычно не видят меня с этой стороны, пока уже не слишком поздно. Но так или иначе... [ДЕкс окидывает взглядом комнату и камеры.]
 Это место дерьмово выглядит. Сколько я тут пробыл?}
{851}{}{Примерно сто пятидесят лет, после Великой Войны, которая положила конец Древних... *твоему* народу....}

{855}{}{Великая Война? Древние? Как насчет избавить меня от этой загадочной фигни и рассказать мне, что случилось?}
{856}{}{Великой Войной мои люди называют конец вашего мира. Когда пламя пожаров сыпалось с неба и выжегало земли. Вы найдете мир совершенно не похожим, на тот, что вы знали.}

{860}{}{Вот дерьмо, так что они на самом деле сбросили бомбы, да? Я думаю, проект Убежище в конце концов был не просто бесполезной тратой денег налогоплательщиков.}
{861}{}{Стой. Ты знаешь об убежищах?}

{870}{}{Знаю о них? Черт, я жил у самого Чикагского Убежища. Я даже смотрел как они достраивали его. Тогда, конечно, они начали делать эти чертовы упражнения... [Он останавливается и рассматривает вас с удовольствием.] Вам действительно надо это, не так ли?}
{871}{}{РАССКАЖИ МНЕ БОЛЬШЕ ОБ УБЕЖИЩАХ!}
{872}{}{Ну, видишь, я выбрана своим народом, чтобы попытаться найти Убежище. Там я надеюсь получить ГЕКК и использовать его мощь, чтобы спасти мою деревню от уничтожения. Все, что ты сможешь рассказать мне об Убежищах может сделать мою работу в аду гораздо проще.}
{873}{}{Ну, видишь, я выбрана своим народом, чтобы попытаться найти Убежище. Рискуя своей жизнью в бесчисленных приключениях, Я наконец нашла свое 13-е убежище. Однако мне любопытно, что еще ты знаешь об этих строениях.}

{880}{}{Я тебе вот что скажу, детка. Ты должна помочь мне найти эти убежища, и мне нужен человек, чтобы показать мне тропы, так сказать, в этом твоем безумном мире. Так что же ты скажешь... партнер?}
{881}{}{Дьявол, нет необходимости убеждать меня. Я буду рада видеть нас вместе просто чтобы посмотреть на твою работу из первых рук.}
{882}{}{Я не знаю, Декс. Скажем так, я позволю тебе пойти со мной, и мы вернемся в отдаленное безопасное поселение. Оказавшись там, откуда я знаю, что ты не попробуешь перерезать мне горло при первом удобном случае?}

#did not read bio
{883}{}{Я скажу договорились... партнер.}
{884}{}{Ну, ваши знания старины могут оказаться весьма полезными для меня... Я полагаю, мы договорились.}
{885}{}{У меня нет времени, чтобы "показывать тебе тропы". Я уверен, что ты будешь в порядке сам по себе, "детка".}

{890}{}{Я могу ответить, что ты не святой, так что я мог бы спросить тебя то же самое. Но отвечу на твой вопрос, я не убил бы тебя потому что это бы наебкой. Я буду честным, }
{891}{}{, Я не наебываю никого и ничего, кроме себя. Может мир и затрахал, как ты говоришь, но я вытащил свой самый самый счастливый билет. Это так просто.}
{892}{}{Достаточно справедливо. Пойдем.}
{893}{}{Я с тобой, Декс. Я никогда не имел намерения брать тебя с собой. Я просто думал, что я получу немного удовольствия перед дроблением твоего черепа.}

{900}{}{Мы вернемся к этому через секунду. Но прежде всего, вы не могли бы рассказать мне, что, черт возьми, произошло, как давно они заморозили меня? Я имею в виду что это место дерьмово выглядит, как буд-то я герой какого-то научно-фантастического приключенческого рассказа.}

#in party

#male
{1000}{}{Что скажешь?}
{1001}{}{[Декс смотрит на вас из под бровей.] Что-то случилось?}
{1002}{}{Поговори со мной.}
{1003}{}{[Декс улыбается.] В чем дело, приятель?}
{1004}{}{Тебе что-то нужно?}
{1005}{}{Что Декс может для тебя сделать?}

#female
{1010}{}{Что скажешь?}
{1011}{}{[Декс смотрит на вас из под бровей.] Что-то случилось, детка?}
{1012}{}{Поговори со мной, крошка.}
{1013}{}{[Декс улыбается.] В чем дело,, куколка?}
{1014}{}{Тебе что-то нужно? Что угодно? [Декс усмехается.]}
{1015}{}{Что может для тебя сделать Декс, детка?}

#waiting
{1100}{}{Мы готовы ехать?}
{1101}{}{Мы расстаемся или как?}
{1102}{}{Ты готов? У меня зуд к движению.}
{1103}{}{Итак, ты понял, что со мной лучше, а?}
{1104}{}{Мы идем? Я не привык ждать других.}
{1105}{}{Пойдем. Я был заморожен на протяжении ста пятидесяти лет. Мне не терпится двигаться.}
{1106}{}{Я сгораю от нетерпения здесь.}

#party was initially full, waiting...
{1110}{}{Вы готовы взять меня с собой?}
{1111}{}{Пойдем.}
{1112}{}{Нет, пока нет.}

#questions...
{1200}{}{Итак, что ты можешь рассказать мне об убежищах?}
{1201}{}{Итак, теперь ты вспомнил что-нибудь об убежищах?}
{1202}{}{Можешь рассказать что-нибудь полезное о времени до начала Великой Войны?}

{1210}{}{Ну, посмотрим... Ох. Знаешь, мой разум еще немного затуманен в некоторых вещах. Ты должен спросить меня позже.}
{1211}{}{Хмм. Ладно.}

{1220}{}{Убежища... Убежища... Нет, еще нет.}
{1221}{}{Хмм. Ладно.}

{1230}{}{Да, действительно, я помню... Блин, снова забыл.}
{1231}{}{Хмм. Ладно.}

{1240}{}{Well, I used to live by the Chicago Vault. Does that help?}
{1241}{}{Do you know if it had a G.E.C.K.?}
{1242}{}{I'm sure it did. I'm pretty sure they all did.}
{1243}{}{Alright, now we're on to something. Can you tell me where this Vault is located?}
{1244}{}{No problem. It's about 2,000 miles in that direction. [Dex points eastward.]}
{1245}{}{Oh. Well then. Never mind.}

{1250}{}{Был один человек, великий человек, поэтому мы называли его "Король". Он был красивым мужчиной, с безупречным стилем, удивительными волосами и голосом из золота.
 Просто направив свой таз он мог оплодотворять каждую женщину на виду. Он почитался как бог среди людей в мире. Он был моим отцом.}
{1251}{}{Интересно...}

{1260}{}{Были бессмертные, которые жили среди нас тайно. Они должны были сражаться друг с другом насмерть мечами, пока не останется только один который получит "премии".}
{1261}{}{Подожди. Если они были бессмертны, как они убивали друг друга?}
{1262}{}{Они могли быть убиты через обезглавливание. Когда один бессмертный обезглавливал друга, ускоряя развязку, сила убитого бессмертного переходила к победителю.}
{1263}{}{Что именно ты имеешь в виду под "силой"?}
{1264}{}{Ух, сила махача? Механическая сила? Я не знаю, это воспоминание вроде расплывчатое...}
{1265}{}{Интересно...}

{1270}{}{Существовали гигантские ящерицы, некоторые больше многоэтажных зданий, люди ездили на них. Мы называли их динозавры, и они были известны как лучшие друзья человека.}
{1271}{}{Ого, у тебя тоже был такой?}
{1272}{}{Конечно. Я ездил на T-Рексе, наиболее злобном ящере из всех. Только мой был еще более злобный потому что у него были крылья. В принципе, это был дракон.}
{1273}{}{Интересно...}

{1280}{}{В 2011 году состоялось Пробуждение и спящие магические существа, такие как орки, эльфы, тролли и Гномы вернулись в мир, наряду с магией. Магия и технология столкнулись в темный мире корпоративных войн, в тени огромных городов...}
{1281}{}{Вау, и что случилось с волшебными существами?}
{1282}{}{Я думаю, они получили свое, когда падали бомбы. Кроме того, похоже у вас еще есть несколько гномов, троллей и зомби в окрестностях.}
{1283}{}{Интересно...}

{1290}{}{Был такой гигантский зеленый ящер, назывался Годзилла. Годзилла разрывался между терроризированием Японии и сохранением своей задницы от гигантских космических пришельцев.
 Существовала еще одна неистовая гигантская ящерица, называется Tarrasque. Я думаю, они были двоюродными братьями или что-то вроде того...}
{1291}{}{Вау, что с ними случилось?}
{1292}{}{Годзиллу вывезла Ferris Bueller. Что касается Tarrasque, мы послали гигантский боевых роботов против него. Робот, пилотируемый твоим покорный слугой, ударил Tarrasque так сильно, что она распалась на тысячи маленьких Tarrasques, разбросанных по всей Калифорнии.}
{1293}{}{Интересно...}

{1300}{}{Земля была полна горячими женщинами и я установил мировой рекорд по сумме сексуальных партнеров, которые у меня были.}
{1301}{}{Я вижу. Знаешь, Декс, некоторые из этих вещей о которых ты говоришь, немного... потусторонние. У меня странное чувство что не все это правда.}
{1302}{}{Эй, а где ТЫ был тогда? Нет, тебя еще и в проекте не было. Так кто же здесь довоенный эксперт? Так поверь мне, все это правда. Но если ты не веришь мне, то я больше
 не буду рассказывать тебе историю.} 
{1303}{}{Хм. Это плохо, потому что до сих пор они были очень полезны.}

#distance
{1400}{}{Только скажи, где ты хочешь меня.}
{1401}{}{Просто скажи, где ты хочешь меня, детка.}
{1402}{}{Нет проблем. Я не хочу, чтобы ты нервничал. [Декс усмехается.]}
{1403}{}{Конечно. Если вы считаете, нужно держать глаз на меня, я в порядке с этим..}
{1404}{}{Конечно. Я понимаю, что трудно сосредоточиться, когда я слишком близко. [Декс усмехается]}
{1405}{}{[Декс поднимает брови и подмигивает.]}
{1406}{}{Это не проблема.}

#put weapon away
{1500}{}{Почему? Вы не доверяете мне оружие? [Смеется.] Конечно отложу, если оно останется в пределах досягаемости.}

#remove armor
{1600}{}{Ух, конечно. Но здесь не очень хорошее место, знаешь, что-то я немного струсил...}
{1601}{}{Ладно. [Декс снимает свою броню и начинает снимать свою одежду. Он останавливается, когда он видит вас глазеющую на него.] Ты посылаешь мне смешанные сигналы, куколка. Дексу не хочется играть. Это просто доспехи.}

#weapons you can use
{1700}{}{Ну, я могу делать чудесные вещи с ножами. Это как искусство. Есть особенные пути для лезвия в плоть, понимаешь что я имею в виду?}
{1701}{}{Ух... Да, конечно. Что еще ты можешь использовать? И будь менее жутким на этот раз.}
{1702}{}{Ну, мой дядя был одним из кадровых военных. Он обучил меня использовать пистолеты и SMGs, я даже получал игрушки в виде прототипов энергетического оружия, они даже работали! Он думал, что я пойду по его стопам и стану марионеткой дяди Сэма, но я... Скажем так, я пошел по другому пути.}
{1703}{}{Звучит хорошо. Что еще?}
{1704}{}{Я иногда бить морды старым добрым кулачным способом. Когда я был подростком, некоторое время я пробовал свои силы в каратэ, но они продолжали кормить меня всем этим дерьмом " быть более дисциплинированным", поэтому я сказал им отъебитесь. Что тебе еще нужно знать?}
{1705}{}{Это хватит. Спасибо.}

#heal
{1800}{}{Мне хорошо идти.}
{1801}{}Бывало и лучше, но я могу с этим справиться.}
{1802}{}{Я плохо себя чувствую.}
{1803}{}{Мне кажется, я слышу зов Короля. Я вижу свет...}

#wait for me
{1900}{}{Нет проблем. Но ты будешь чувствовать себя намного менее спокойно без меня рядом. Просто сказал...}
{1901}{}{Конечно. Я заберу тебя позже.}
{1902}{}{Да, я подожду. Но если ты не вернешься, тогда я начну искать тебя, и это не будет приятным сюрпризом, когда я найду.}
{1903}{}{Ладно, только надеюсь ты не выкидываешь меня, чтобы освободить место для других придурков. Потому что я обещаю тебе, я лучше их во всех мыслимых отношениях.}
{1904}{}{Нет проблем.}
{1905}{}{Нет проблем, детка.}
{1906}{}{Alright, as long as you aren't just ditching me to make room for some other jerk. Because I promise you I'm better than them in every conceivable way.}
{1907}{}{Я для тебя слишком горячий и беспокойный? Я понимаю.}

#gear
{2000}{}{Хорошо, что насчет этого?}
{2001}{}{Слушай, я знаю, что был заморожен долгое время, но поверь мне, все находится в отличном рабочем состоянии. Если ты хочешь, Я докажу тебе это прямо здесь, прямо сейчас. [Декс прекращает, когда видит вас смеющимся]
 О, я вижу, моя *другая* передача. Что насчет этого?}

#party full
{2010}{}{Здесь немного тесно. Дай мне знать, если откроется вакансия.}

#ch <= 1
{2020}{}{Ни в коем случае я с тобой не пойду. Ты уродливый ублюдок.}

#rejoined
{2030}{}{Ну давай.}
{2031}{}{После перерыва мы снова в пути.}

#life story
{3000}{}{Итак, расскажешь свою историю?}
{3001}{}{Что, прям историю моей жизни? Слушай, я знаю, что очень увлекательно рассказываю, но я не хочу стоять и разговаривать вечно. Мой рот получите пересох, а вокруг воды не наблюдается, просто сейчас не очень подходящее время. Но я полагаю, я мог бы выдать короткую версию, если ты действительно хочешь знать... На самом деле, я люблю говорить о себе, поэтому я оставлю выбор за тобой. Хочешь короткий рассказ или версия с подробными коментариями?}
{3002}{}{Просто дай мне краткий обзор.}
{3003}{}{Позволь услышать подробный вариант.}
{3004}{}{Не надо, я потерял интерес.}

#quick summary
{3010}{}{Ладно, в основном, с самой юности, я любил убивать проституток. Я мог бы рассказать о своем детстве и своих дерьмовых родителях и попытаться проанализировать, почему мне нравилось это делать, но мне не нужны оправдания. Я делал это просто потому, что я мог и это весело. К шестнадцатилетию я проводил свои дни в качестве популярного в школе сердцееда, а ночи - как Чикагский убийца работающих молодых девушек.}
{3011}{}{Ага. Продолжай.}
{3012}{}{И вот однажды я поймал свою подругу изображающей животное о двух спинах (making the beast with two backs (с) Шекспир) с другим парнем. Я убил их, предал то место огню, а затем уехал из Чикаго. Следующие 10 лет я путешествовал по стране, соблазнял девушек и резал их. Когда они наконец поймали меня, мой след дал мне известность.}
{3013}{}{Так, и что потом?}
{3014}{}{Так вот, одна из моих новых поклонников, Элис, помогла мне бежать. Три недели вдвоем мы неистовствовали и убивали по стране, пока нас, наконец, не положили в перестрелке. Затем, по каким-то причинам, Человек решил сшить меня обратно и делать все эти тесты на мне. Так я попал в EPA, где ты меня и нашел.}
{3015}{}{Спасибо за рассказ.}

#detailed summary
{3020}{}{Давай начнем... Моя мама была шлюхой и дружила с наркотиками, а мой папа был мерзкий пьяный ублюдок. К счастью, мой дед был хорош для старика. Познакомил меня с музыкой Короля. К сожалению, он заразился Новой чумой когда мне было семь. Потом, когда мне было десять, я смотрел из шкафа, как мой папа забил маму насмерть за то, что она забыла покормить нашу собаку, Капитана Робени.}
{3021}{}{Это не приятное начало. Продолжай.}
{3022}{}{Сучке надо было помнить о кормлении Капитана. Продолжай.}
{3023}{}{Итак, они забрали моего папу далеко и отправили меня жить с тетей и дядей. Видишь ли, я был немного скандалист, даже тогда, и мой дядя, будучи человеком военным, думал что он сможет превратить меня в убийцу Красного
 Солдата, как сына, которого он потерял. Это был его лучший шанс, но я упрямый сукин сын.}
{3024}{}{Ага. Продолжай.}
{3025}{}{В общем, мы много переезжали, пока я учился в средней школе, и в итоге мы наконец поселились в Чикаго. Вот тогда я и начал выходить тайком ночью и резать проституток. Я убивал их с тех пор, как помню, но потрошение окрестностей не сравнить с реальным делом, ну ты понимаешь.}
{3026}{}{Конечно.}
{3027}{}{Некоторые из них были очень сладкие, по большей части. Я хочу сказать, я чертовски ненавидел дядю и тетю, но в школе я был мистер "Популярность". Каждый парень хотел быть моим другом и каждая девка на которую я смотрел была готова разостлаться для меня. За исключением одной девки, Вики. Она тоже подрабатывала. Удивительно, я знаю, но я обхаживал ее и в конце концов она стала моей девушкой.}
{3028}{}{И все это время ты подрабатывал серийным убийцей?}
{3029}{}{Меня не волнует твоя возлюбленная из средней школы. Забудь о рассказе.}
{3030}{}{Ага. [Декс улыбается.] Это было днем. Я был действительно счастлив, веришь? После того как мы отучились, у Вики и меня было наше собственное местечко для двоих, и все козыри на руках. Но эта сука ушла и погубила все дело своими интригами у меня за спиной.}
{3031}{}{Как она посмела?}
{3032}{}{Я поймал ее с поличным, и я потерял ее. Шлюха увидела настоящую жестокость. Она была небрежна и не было возможности просто скрыть это. Поэтому я предал это место огню и отправился в путь. Много путешествовал, уложил в постель много девочек и оставил большую часть из них трупами. Разве это была плохая жизнь? Я занимался этим лет десять, но закон наконец догнал меня.}
{3033}{}{Ой. А что тогда?}
{3034}{}{Затем меня посадили, был суд и немного цирка от СМИ. Девушкам нравилось, потому что я был голубой мечтой, а всем остальным нравилось, потому что это было отвлечение от новостей о жертвах Новой Чумы и политики.
 Поэтому думаю, что я показал им настоящее шоу.}
{3035}{}{Что ты сделал?}
{3036}{}{Ну, тогда я заполучил много поклонников, в частности, классную куколку по имени Алиса. Она сказала, что она меня любит и будет делать все для меня. И во время моего заключения, она помогла мне сделать в нем перерыв. Это была большая задумка, но нам повезло достаточно, чтобы осуществить ее... Потом дела пошли совсем сумасшедшие... Ты уверен, что никогда не слышал обо всем этом?}
{3037}{}{Я уверен, ты продолжай.}
{3038}{}{Никогда не слышал, а теперь уже не хочу. Забудь об этом, скучный рассказ.}
{3039}{}{Ну, когда я был с Алисой, было отчасти трудно вернуться обратно к моим старым способам соблазнения женщин с последующей их нарезкой на куски. Вместо этого, мы начали серийные убийства всех, кого было удобно.
 Не важно молод или стар ты, у нас были равные возможности убийц. Но такие безрассудные убийства было легко отслеживать. Через три недели они нас загнали в угол. Они ранили меня и вышибли мозги Алисе.}
{3040}{}{Я вижу. Что потом?}
{3041}{}{Потом я собрался помереть, но эти федералы (G-Men) вмешались и взяли меня в оборот. Они собрали меня обратно на сто процентов, потом начали проводить эти тесты на мне, пытаясь выяснить что заставляет меня быть таким, какой я есть... В любом случае, об остальном ты можешь догадаться, а мое горло пересохло от разговора. Черт, я надеялся избежать этого.}
{3042}{}{Спасибо за рассказ.}

#give bonus
{3100}{}{Можешь дать мне какой-нибудь совет?}
{3101}{}{Совет? Какого типа совет?}
{3102}{}{Ну, я уверен, что у тебя есть какие-нибудь навыки.}
{3103}{}{О, у меня *все виды* навыков. Но если ты ищешь совет... [Он смотрит поверх тебя, затем кивает.] Хорошо, черт возьми. Я дам тебе несколько советов, которые положат баб к твоим ногам. Первое, что тебе нужно сделать, это...}
{3104}{}{Ты хочешь увидеть мои навыки? Я покажу тебе их в любое время, дорогуша. Но если ты ищешь совет... [Он смотрит поверх тебя, затем кивает.] Хорошо, черт возьми. Я дам тебе несколько советов, после которых мужики будут есть из твоих рук. Первое, что тебе нужно сделать, это...}
{3105}{}{Вот и все. Только не рассказывай другим людям эти секреты.}
{3106}{}{Спасибо.}

#floats

#general
{4000}{}{Чувак, мне нравится пост-ядерное будущее.}
{4001}{}{Давай. Давай кого-нибудь изнасилуем.}
{4002}{}{Давай найдем несколько молодых дам, чтобы... эээ... восхищаться!}
{4003}{}{Будем искать более половые сношения...}
{4004}{}{Ты когда-нибудь пробовал просто бросить девушку на кровать, разрезать ее и вскрыть? Я говорю тебе, это абсолютная красота!}
{4005}{}{Мне правда нужно кого-нибудь скоро прирезать...}
{4006}{}{Ты думал трупы ужасны в постели, но ты будешь удивлен.}
{4007}{}{[поет] В заросшем парке... стоит старинный дом... Забиты окна... И мрак царит извечно в нем! [поет]}
{4008}{}{[поет] Я за ней не уследил... В том моя вина... Но скажите, Правда вкусная она!?![поет]}
{4009}{}{Ты откопал мой костюм? Это сладкое дитя было сделано в Гранд-Рапидс, штат Мичиган.}
{4010}{}{Итак... где в пустоши можно достать гель для волос?}
{4011}{}{Я знаю, это звучит немного грубо, но не пробовали ли вы обжаренные во фритюре яичники?.}
{4012}{}{[Достает из кармана гребень и причесывает волосы.]}

#hurt
{4020}{}{Эй! Я бля кровью тут истекаю!.}
{4021}{}{Ох цувак, мне что-то нехорошо...}
{4022}{}{Отведи меня у ебаному доктору.}
{4023}{}{Ты будешь просто стоять там и смотреть на меня истекающего кровью до смерти или ты собираешься сделать что-нибудь с этим?}

#radiated
{4030}{}{Я чувствую себя немного странно...}
{4031}{}{Эй, я чувствую себя немного радиоактивным. Если это не даст мне суперсилу, то мне что-то ссыкотно...}

#give drug
{4040}{}{Ты знаешь, ты плохое на меня влияешь.}
{4041}{}{Я стараюсь держаться подальше от таких вещей. Но если ты настаиваешь...}
{4042}{}{Мое тело храм, но я полагаю, что один раз это не повредит.}
{4043}{}{Если это мне повредит, я тебя покоцаю.}

#give health drug
{4045}{}{Я чувствую себя лучше.}
{4046}{}{Намного лучше.}

#push
{4050}{}{Эй! Не трожь прическу.}
{4051}{}{Эй, не разрушай совершенство.}

#had sex
{4060}{}{Это совсем по-другому, пока их кровь все еще теплая.}
{4061}{}{Я надеюсь, что вы приняли к сведению.}
{4062}{}{Девушки стали довольно причудливые после конца света... Я так думаю.}
{4063}{}{...и именно поэтому малышки называли меня "Дексом, герцогом секса".}

#poisoned
{4070}{}{Я чувствую тошноту. Я думаю, что я отравлен.}
{4071}{}(Я чувствую, что придется вырвать мои кишки.}

{4080}{}{Я не могу двигать этой конечностью. Мне нужно к врачу.}
{4081}{}{Я думаю, что я потерял чувствительность этой конечности. Это плохо?}

{4090}{}{Как-то все очень размыто. Куда все уходят?}
{4091}{}{Я думаю, что кровь вытекает из моих глаз.}

#sulik float
{4100}{}{Итак, татуировки на лице, да? Я думаю, если бы я был уродлив, как кость в носу, я бы тоже покрылся татуировками.}
{4101}{}{Йоу, морда татушная! Ты из рода людоедов? Может быть, мы могли бы обменяться рецептами или типа того.}
{4102}{}{Я чувствую ваш приятель Сулик не слишком хорошо нам помогает. Ты когда-нибудь думал о продаже парня за наличку?}

#vic float
{4110}{}{Серьезно, что это за коренастый лысый чувак? Ты держишь его из жалости, что ли?}
{4111}{}{Вик, я слышал, что у тебя мужественная дочь. Ты должен отвести меня к ней.}

#Miria float
{4120}{}{Мириа, сладенькая, нам действительно нужно разок провести время тет-а-тет.}
{4121}{}{Так, дай я угадаю, мы будем с Мирией по очереди, верно?}
{4122}{}{[подмигивает Мирии.]}
{4123}{}{[улыбается Мирии.]}
{4124}{}{Мириа, тебе нужен человек из той же лиги, что и ты. Человек типа меня.}
{4125}{}{[Машет ножом на Мирию. Усмехается.]}

#davin float
{4130}{}{Я говорю, мы сделаем дырку в голове Дэвина и положим его в канаву.}
{4131}{}{А если, гипотетически, Дэвину кто-то перережет горло во сне, ночью... Никто не будет о нем скучать, верно?}

#cassidy float
{4140}{}{Эй Кэссиди, тебе точно стоит попробовать Психо. Я слышал, что от этого могут даже повторно вырасти волосы.}
{4141}{}{Почему ты не сказал, что это пойло немного крепче, Кэссиди? Похоже, годы сделали его только лучше.}
{4142}{}{Жалко видеть, как кто-то, такой же старый, как Кэссиди, пытается цепляться за жизнь. Если бы я был на его месте, я засунул бы ствол ружья в рот и просто положить ей конец.}

#lenny float
{4150}{}{Допустим, мы скинем в канаву ходячий труп...}
{4151}{}{Ладно, эта шутка о привлечении Ленни в команду немного затянулась, как ты думаешь?}
{4152}{}{Как к дьяволу я должен подцеплять девочек, если тут торчит Ленни?}

#marcus float
{4160}{}{Э, ну, Маркус, когда ты снова станешь мягким воспитанным физиком?}
{4161}{}{Эй, Маркус, нет ли у тебя на примете какого-нибудь города, где ты мог бы осесть?}

#myron float
{4170}{}{Держись там Майрон, я уверен, что когда-нибудь твои яйца отвалятся.}
{4171}{}{Любопытный мальчик-придурок, дрыгается в моем стиле.}
{4172}{}{Майрон как гигантский прыщ, просто ждет, чтобы выскочить.}

#goris float
{4180}{}{По крайней мере, у Гориса есть порядочность.}
{4181}{}{Хорошо замаскировался, Горис. Ты выглядишь как типичный горбатый урод.}

#town floats
#arroyo
{4200}{}{Мне любопытно увидеть, на кого похожи эти племенные женщины.}

#new reno
{4210}{}{Шлюхи... шлюхи везде... Мне нравится это ебаное место.}

#vault city
{4220}{}{Это место просто просит устроить безпорядки.}

#ncr
{4230}{}{Здесь слишком много полицейских. Я говорю, мы под наблюдением.}

#broken hills
{4240}{}{Боже, сколько уродов. Мы не должны оставаться здесь дольше, чем нужно.}

#gecko
{4250}{}{Мы теряем здесь время. Зомби-девочки - это не ко мне. Я вообще не люблю смотреть на мертвых девченок... только если они не умерли с моей помощью.}

#modoc
{4260}{}{Какого черта мы все еще теряем время здесь? Серьезно?}

#modoc
{4270}{}{Я не думаю, что хочу тратить еще больше времени в этой локации.}

#Don't apply ERSI to specimen == horrible flaming death for specimen
{5000}{}{[Он поворачивает голову к вам, и встает на ноги. Потом он смотрит на тебя, глаза его вдруг расширяются и он начинает задыхаться.}
{5001}{}{[конец]}
{5002}{}{Срань господня!}

