###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите сержанта Кэт Джулс.}
{101}{}{Вы видите красивого негра с довольно выраженными клыками. Он движется с постоянной развязностью и самодовольным выражением на его лице.}

{200}{}{[По мере приближения к криогенной камере, вы видите худово, голого негра, валяющегося на полу. Его мускулистое тело, все еще дрожит от ледяной воды. Он смотрит, как вы подходите.]}
{201}{}{Кто вы?}

{210}{}{[Встет и отряхивается досуха, как мокрое животное, человек смотрит на тебя и ухмыляется, обнажая странно острые передние зубы!] Кто *Я*? А кто *Вы*? Вы похожи на хорошо вооруженного бродягу.}
{211}{}{[Встет и отряхивается досуха, как мокрое животное, человек смотрит на тебя и ухмыляется, обнажая странно острые передние зубы.] Кто *Я*? Да я всего лишь сержант Жулс, самый красивый солдат на этой базе!}
{212}{}{Я }
{213}{}{. Но как тебя зовут?}
{214}{}{Не будь дерзким со мной. Что это за место?}
{215}{}{Я вижу. Ну, сержант Джулс, что тут происходит вокруг?}
{216}{}{Как же ты выжил? Доктор говорил, что он был единственным выжившим.}

{220}{}{сержант Джулс меня зовут, но вы можете называть меня Кот. Я самый быстрый и самый красивый солдат на этой базе.}
{221}{}{Да, как скажете. Итак, что тут происходит вокруг?}

{230}{}{Вы имеете в виду Доктора Ц? Почему он забыл обо мне? Черт, он помогал мне работать над этими формами, *ИСКУССТВО* [Он обводит свое тело].}
{231}{}{Да, как скажете. Итак, что же с этим местом?}
{232}{}{Я думаю, что мы говорим про двух разных людей... Итак, что происходит вокруг?}

{240}{}{Это правительственный объект, насколько я знаю. Они выполняли все виды совершенно секретных исследований. Но... [Он оглядывает комнату.] Здесь ужасно тихо. Где все?}
{241}{}{Ну, вероятно это будет шоком для тебя, но вы были заморожены на протяжении века или дольше. Мир больше не тот. Они сбросили бомбы и Земля замолчала. Общество до сих пор пытается восстановить себя из пепла.}

{250}{}{[сержант Джулс смотрит на тебя с поднятой бровью.] Ты не шутишь, да? Ну, тогда получается что они все последовали вслед за миром. Черт. Догадываюсь что мне повезло, что меня вытащили из военных и привезли сюда.}
{251}{}{Вы были в армии?}

{260}{}{Ага. Я был экспертом по энергитическому оружию. И очень проворный. Я служил уже около года прежде чем был переведен сюда. Жаль, я никогда не увижу никого из моих друзей еще раз. Я хотел бы хотя бы попрощаться.}
{261}{}{Мне очень жаль.}
{262}{}{Мне очень жаль что вы всех потеряли, но вы должны идти дальше. Погрязнув в собственных страданиях далеко не уедешь.}

{270}{}{Да, не все мы. Что мне теперь делать-то?}
{271}{}{Я думаю, вы правы. Что же мне теперь делать-то?}
{272}{}{Ну, я мог бы взять вас компаньоном. Хотите присоединиться ко мне?}
{273}{}{Ну, мне пора идти. Желаю удачи вам выбраться отсюда.}

{280}{}{Эй, почему бы и нет! Я покажу вам, что Кот тот еще.}
{281}{}{Звучит хорошо. Пойдем.}
{282}{}{Как скажешь.}

{2900}{}{Мне в первую очередь нужно найти какую-нибудь одежду. [Оглядевшись, Кот идет к шкафчику, открывает его и заглядывает внутрь.] Это не мой стиль, но я думаю они подойдут. [Он быстро надевает одежду.] Хорошо, я готов идти.}
{2901}{}{[Конец]}

{290}{}{Не беспокойтесь об этом старом кашаке. Я найду свое место в этом мире. Теперь отойди в сторону, и пусть Кот делает свое дело.}
{291}{}{[Конец]}

#past
{300}{}{Итак, как вы попали в криокамеру? И что случилось с вашим зубами?}
{301}{}{Я когда-то охранял одну из лабораторий генетики. Они возились с человеческой и кошачьей ДНК. Пытались сделать что-то, взяв лучшее из обоих видов, как я полагаю. И вот, когда ваш покорный слуга служил там,
 [Кот сверкает всей своей зубастой улыбкой.] они набирали добровольцев для одного из своих проектов. Он был для разведчиков и подобных специальностей, они должны были сделать нас более гибкими и быстрыми. Мне понравилось, что у меня будет этот *хищный взгляд*. Во всяком случае, они дали мне этот шанс, забрали меня в лабораторию и Следующее, что я увидел, что у меня были эти зубы, и я чувствовал себя.... острее? Типа хищника.}
{302}{}{Продолжай.}
{303}{}{Ну, видимо эксперимент пошел не по плану и то что они засунули в меня не очень хорошо стыкуется с моей системой. Я не знаю, что они имели ввиду, поскольку я чувствую себя лучше, чем когда-либо. Они решили бросить меня в крио морозильник, пока они не поняли, что делать со мной.}
{304}{}{И потом я вас оттаял. Похоже, вы мне немного должны.}
{305}{}{Да, ты спас меня. В свою очередь, может быть, я смогу сохранить твое чувство стиля, обезьяна.}
{306}{}{Обезьяна? Должно быть, это говорит кошачье ДНК. Это все, что мне нужно знать на данный момент.}

#teach
{310}{}{Поскольку вы были в армии, думаете смогли бы вы научить меня чему-нибудь?}
{311}{}{Я мог бы научить вас кое-чему об энергетическом оружии и других больших пушках. Теперь вы должны запомнить...}
{312}{}{[Продолжить.]}
{313}{}{Ну вот и все. Это должно помочь вам расплавить этих мутантов, которые поджидают вас на пути.}
{314}{}{Спасибо.}

#party was full when first tried to recruit
{390}{}{Вы готовы взять меня с собой?}
{391}{}{Пойдем.}
{392}{}{Нет, пока нет.}

#in party
{400}{}{Нужно что-то?}
{401}{}{Кот может быть полезен?}
{402}{}{Да?}

#skills
{410}{}{Что вам нужно знать?}
{411}{}{Ну, меня обучалт использовать обычную военную экипировку. Винтовки, пистолеты, SMG и тому подобное. Я предпочитаю лазерное оружие, оно мне нравится больше. В нем есть стиль! Но если вы дадите мне несколько кастетов или один из тех силовых кулаков, я смогу наброситься на любых плоскостопых головорезов, прежде чем они узнают, кто их ударил!}

#distance
{421}{}{Что с ним не так?}
{422}{}{Ладно. Я прямо за тобой.}
{423}{}{Fine by me.}
{424}{}{В любом случае я лучше работаю соло.}

#wait
{430}{}{У меня кончилось терпение, так что поспеши обратно.}
{431}{}{Я не любитель ждать. Не оставляй меня слишком на долго.}

#come back
{440}{}{Мы идем?}
{441}{}{Время вам вернуться.}

#lets go
{450}{}{Это хорошо, быть на марше снова. Моим ногам нужно движение.}
{451}{}{Время нам снова сделать что-нибудь вместе.}

#remove armor
{460}{}{Конечно, в любом случае она выглядит как дерьмо. А есть такая же синего цвета?}

#unwield weapon
{470}{}{Ладно, но это *мои* блестящие штучки. И если ты попытаешься забрать их, возможно, придется тебя пристрелить.}

#hurt
{480}{}{Я чувствую себя на высшем уровне.}
{481}{}{Всего несколько царапин, не о чем беспокоиться.}
{482}{}{В армии я видел и похуже.}
{483}{}{Зови медика. Я быстро подыхаю.}
{484}{}{Теперь у меня кровотечение из всего...}

#ch <= 1
{490}{}{О боже, ты урод. Ты давно смотрел на себя в зеркало? Я сваливаю отсюда.}
{491}{}{Малыш, ты реально урод. Я сваливаю отсюда.}

#party full
{500}{}{Не поймите меня неправильно, хорошо держаться вместе, но вы набираете слишком много народу. Возвращайтесь, когда у вас будет меньше людей.}
{501}{}{Не поймите меня неправильно, хорошо держаться вместе, но вы набираете слишком много народу. Возвращайтесь, когда у вас будет меньше людей. А пока вы освобождаете мне место, я собираюсь найти какую-нибудь одежду.
 [Оглядевшись, Кот идет к шкафчику, открывает его и заглядывает внутрь.] Это не мой стиль, но я думаю они подойдут. [Он быстро надевает одежду.] Хорошо, дайте мне знать, когда будете готовы.}

#poisoned
{510}{}{Я съел испорченную рыбу или что-то еще? Я чувствую себя отравленным.}

#radiated
{520}{}{Я чувствую, что я сгораю. Должно быть это радиационное отравление.}

#broken limb
{530}{}{Вы ожидаете, что в моих силах выполнить это со сломанной конечностью?}

#blind
{540}{}{Кто выключил свет? Я думаю, что-то случилось с моими глазами.}

#generic floats
{600}{}{Кто-то может сказать, что я довольно мелкий парень, но мелкий парень с великолепный задницей.}
{601}{}{В армии всегда было: "Кот сделай это, Кот сделай то." Я что, собачка?}
{602}{}{[Поет] Бай зе вэй, ХАУ МАЧ ИС ЗЕ ФИШЬ???? На-на-на-на... [Поет]}

#location floats
#New Reno
{700}{}{ДАМЫ! Дамы, по одной ЗА РАЗ, пожалуйста!}
#Military Base
{710}{}{У меня нюх на неприятности, и он вопит как сирена на ядерную атаку!}
#Redding
{720}{}{Добыча ЗОЛОТА? Это где они выкапывают блестящие вещи?}
#EPA
{730}{}{Я думаю, не лучше ли нам оставить это место?}

#NPC floats
#Myron
{800}{}{Мне было достаточно сумасшедших умных задниц! Можем ли мы оставить этого жирного маленького идиота?}
#Sulik
{810}{}{Зачем тебе кость, неандерталец?}
#Lenny
{820}{}{По крайней мере, я не до конца такой как ВЫ, Ленни!}
#Marcus
{830}{}{По крайней мере, я не до конца такой как ВЫ, Маркус!}

#Don't apply ERSI to specimen == horrible flaming death for specimen
{5000}{}{[Встет и отряхивается досуха, как мокрое животное, человек смотрит на тебя, его глаза вдруг расширяются и он начинает задыхаться.]}
{5001}{}{[Конец]}
{5002}{}{Срань господня!}


