# Message file for epac9.ssl 
# Number of nodes: 18

###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите большой компьютер.}
{101}{}{Вы видите Мистера Химми!}
{102}{}{Большой компьютер для разработки наркотиков.}

# Node  0  [Node001]
{200}{}{Привет пользователь! Я фармацевт будущего, Мистер Химми! Как я могу вам помочь?!}
{201}{}{Что ты умеешь?}

# Node  1  [Node002]
{210}{}{Я делаю наркотики! Все виды наркотиков! Когда жизнь собьет вас с ног придет Мистер Химми чтобы поднять вас! Как работает Мистер Химми?! Очень просто! Все что вам нужно - это научное ноу-хау и необходимые ингредиенты, а затем просто отдыхай до готовности! Продолжи! Дай мне попробовать! И детки, не забудьте спросить маму или папу разрешения, прежде чем играть с Мистером Химми!}
{211}{}{Хорошо, давай попробуем.}
{212}{}{Может быть позже.}

# Node  2  [Node003]
{220}{}{Хорошо! Давайте делать наркотики! Что вы хотите создать?!}
{221}{}{Стимпак}
{222}{}{Суперстимпак}
{223}{}{Яд}
{224}{}{Противоядие}
{225}{}{Аптечку}
{226}{}{Докторскую сумку}
{227}{}{Баффаут}
{228}{}{Ментат}
{229}{}{Психо}
{380}{}{Рад-X}
{381}{}{Рад-Эвей}
{382}{}{Что-нибудь особенное}
{383}{}{Ничего}


# Node  3  [Node004]
{230}{}{Отличный выбор! Чтобы сделать стимпак, пожалуйста принисите мне: один цветок Брока, один корень Зандера и один пустой шприц! Юм-Юм!}
{231}{}{Сделать стимпак.}
{232}{}{Сейчас у меня нет этих вещей.}
{233}{}{Вернуться в меню.}

# Node  4  [Node005]
{240}{}{Отличный выбор! Чтобы сделать супер стимпак, пожалуйста принисите мне: одной обыкновенный стимпак, один фрукт и одну Нука Колу! Юм-Юм!}
{241}{}{Сделать супер стимпак.}

# Node  5  [Node006]
{250}{}{Отличный выбор! Чтобы сделать психо, пожалуйста принисите мне: одну коробку Ментата, один Баффаут, один фрукт и один стимпак! Юм-Юм!}
{251}{}{Сделать психо.}

# Node  6  [Node007]
{260}{}{Отличный выбор! Чтобы сделать психо, пожалуйста принисите мне: одну аптечку, один фрукт и одну бутылку спиртного! Юм-Юм!}
{262}{}{Сделать ментат.}
{263}{}{Выход.}

# Node  7  [Node008]
{270}{}{Отличный выбор! Чтобы сделать докторскую сумку, пожалуйста принисите мне: один рюкзак, один стимпак, одну аптечку, один пустой шприц и одно противоядие! Юм-Юм!}
{272}{}{Сделать докторскую сумку.}

# Node  8  [Node009]
{280}{}{Отличный выбор! Чтобы сделать аптечку, пожалуйста принисите мне: один стимпак, один пустой шприц, одно противоядие и один Рад-Эвей! Юм-Юм!}
{282}{}{Сделать аптечку.}

# Node  9  [Node010]
{290}{}{Отличный выбор! Чтобы сделать яд, пожалуйста принисите мне: один пустой шприц, один хвост скорпиона и одну Нука Колу! Юм-Юм!}
{292}{}{Сделать яд.}

# Node  10  [Node011]
{300}{}{Отличный выбор! Чтобы сделать баффаут, пожалуйста принисите мне: одну аптечку, одну бутылку пива и одну Нука Колу! Юм-Юм!}
{302}{}{Сделать баффаут.}

# Node  11  [Node012]
{310}{}{Отличный выбор! Чтобы сделать Рад-Х, пожалуйста принисите мне: одну аптечку и одну Нука Колу! Юм-Юм!}
{312}{}{Сделать РАд-Х.}

# Node  12  [Node013]
{320}{}{Отличный выбор! Чтобы сделать Рад-Эвей, пожалуйста принисите мне: одну Нука Колу, один пустой шприц и один стимпак! Юм-Юм!}
{322}{}{Сделать Рад-Эвей.}

# Node  13  [Node014]
{330}{}{Отличный выбор! Чтобы сделать противоядие, пожалуйста принисите мне: один хвост скорпиона и одну бутылку спиртного! Юм-Юм!}
{331}{}{Сделать противоядие.}

# Node  14  [Node015]
{340}{}{О, мальчик! Особый запрос! Что особенного Мистер Химми! может сделать для вас сегодня?!}
{341}{}{Марихуану.}
{342}{}{Химикаты Доктора.}

{343}{}{У моего друга Кэссиди проблемы с сердцем. Можете ли вы сделать что-нибудь для него?}
{344}{}{ингибитор экологического синдрома отказа.}

# Node  15  [Node016]
{350}{}{Сегодня Ваш счастливый день! В моих резервуарах достаточно химических веществ, чтобы сделать это! Хотели бы Вы, чтобы Мистер Химми! сделал их для вас?!}
{351}{}{Создать.}
{352}{}{Вернуться в главное меню.}

# Node  16  [Node017]
{360}{}{Ой-ой! Извините, но у меня больше нет химических веществ, необходимых для создания этого!}

# Node  17  [Node018]
{370}{}{Выбор сделан! Это было весело! Пожалуйста, заберите продукцию из машины! Спасибо за использование Мистера Химми! Давайте когда-нибудь сделаем еще наркотиков!}

{371}{}{Дополнительно.}

{375}{}{Мистеру Химми нравится помогать! Я могу создать вещество, называемое нитроглицерин, который будет контролировать нарушения сердечного ритма и предотвращать сердечные приступы!}

{390}{}{Сегодня Ваш счастливый день! В моих резервуарах достаточно химических веществ, чтобы сделать одну партию ERSIs! Хотели бы Вы, чтобы Мистер Химми! сделал их для вас?!}
{391}{}{Создать.}
{392}{}{Выйти.}

