###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите дверь.}
{101}{}{Вы видите электронную дверь.}
{102}{}{Вы видите электронную дверь с управлением и голосовой активации блокировки.}
{200}{}{Код подтверждения:}
{201}{}{XY104FD}
{202}{}{BFN12}
{203}{}{Открыть}
{204}{}{Пшеница}
{205}{}{Abre}
{206}{}{ЗАКОНЧИТЬ}
{300}{}{Неправильный код двери. Блокировка двери. Пожалуйста, свяжитесь с Директором по связям с общественностью для переопределения кода.}
{301}{}{ЗАКОНЧИТЬ}
{400}{}{Подтвердить Замещение кода.}
{401}{}{Exit.}
{402}{}{Эта электронная дверь заблокирована.}
{403}{}{Открывание дверей. Спасибо и приятного дня.}
{404}{}{[ЗАКОНЧИТЬ]}

{500}{}{Здесь нет замка, чтобы вставить отмычку.}

