###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите компьютер.}

#general interaction
{150}{}{Пожалуйста, выберите опцию ниже.}
{151}{}{Информация}
{152}{}{Доступ для сотрудников}

{160}{}{Пожалуйста, выберите опцию ниже.}
{161}{}{Понизить силовое поле}
{162}{}{НАЗАД]}

{170}{}{Для понижения силовых полей, пожалуйста, введите пароль доступа. (Если пароль утерян или забыт, обратитесь к Голограмме 40011, директор по связям с общественностью.)}
{171}{}{ABRE}
{172}{}{[НАЗАД]}

{180}{}{Спасибо. Силовые поля в настоящее время отключены.}
{181}{}{[СДЕЛАНО]}


#petting zoo
{200}{}{Добро пожаловать в зоопарк ЕРА! Здесь вы будете иметь удовольствие лицезреть эти уникальные существа, которые выглядят как ужасно деформированные люди!
 Все это потому, что эти уродливые звери появились в результате захватывающих экспериментов, где наши блестящие ученые пытались сращивать ДНК человека и животных!}
{201}{}{[Подробнее.]}
{210}{}{В теории, эта новая наука в один прекрасный день позволит нам создать "супер человека". Представьте себе американского солдата с зоркостью орла, скоростью гепарда, и силой обезьяны! Представьте себе, как этот "супер солдат" будет вселять страх в сердца коммуняк! Это звучит как фантастика, но скоро это может стать фактом!}
{211}{}{[Подробнее.]}
{220}{}{Существа, которых вы видите здесь - это результаты экспериментов, которые не совсем увенчались успехом. Вместо эвтаназии этой мерзости, мы подумали, что было бы весело поместить их в зоопарк. Не волнуйтесь, несмотря на ужасающий вид, Они вряд ли будут атаковать, если они сыты. Мы рады сообщить, что за весь прошлый год было только три жертвы среди посетителей!}
{221}{}{[Logoff.]}


#Wanamingos
{300}{}{Добро пожаловать на новую выставку! Эти странно выглядящие существа со щупальцами, которых вы видите в этой клетке, похожи на пришельцев из космоса, но они не инопланетяне.
 На самом деле, они были сделаны прямо здесь, в Америке! Как вы уже догадались, эти ребята не были созданы матерью-природой, они были сделаны по науке!}
{301}{}{[Подробнее.]}
{310}{}{Это верно, эти страшные чудовища были разработаны американскими учеными в сверхсекретной лаборатории, как Новейшие оружие в войне за свободу.
 Их мощные щупальца и острые зубы были специально разработаны наводить страх на врагов Америки. Их щупальца также отлично копают, поэтому коммунисты не будут в безопасности даже в своих подземных бункерах! Кроме того, кожа этих свирепых убийц настолько толстая, что пули с трудом проникают через нее!}
{311}{}{[Подробнее.]}
{320}{}{Вы смотрите на будущее биологической войны! Но не беспокойтесь, эти порочные машины смерти не смогут достать вас, так как они надежно заперты в пределах их безопасной клетки.
 Вы должны извинить нас за слабое освещение но эти ребята счастливы, когда живут в прохладном, темном месте. Надеюсь, что вы не хотите, чтоб они рассердились, не так ли?}
{321}{}{[Logoff.]}

#spore plants
{400}{}{Здесь можно увидеть растения, не похожие ни на однодругое, что вы видели раньше! Этот захватывающий новый вид, полученный от Венеры-Летающей-Ловушки, был специально разработан нашими блестящими учеными, чтобы иметь возможность выжить в мире, разрушенном в результате ядерной войны. Почему мы хотели так сделать? Это элементарно!}
{401}{}{[Подробнее.]}
{410}{}{Ученые считают, что после глобальной ядерной войны большая часть Земли станет бесплодной пустошью. Растительной жизни будет трудно выжить в этой суровой новой среде.
 Теперь представьте себе, что мы, пережившие апокалипсис в безопасности наших убежищ Vault-Tec, обнаружим, что вся растительность мертва! Я имею ввиду, что не будет больше листьев салата для мамы и газона для игр Билли и Ровера.}
{411}{}{[Подробнее.]}
{420}{}{звучит ужасно, не так ли? Но не волнуйтесь. Эти новые растения могут быть ответом на эту проблему. Вместо зависимости от плодородной почвы и количества осадков, они в состоянии производить питательные вещества, убивая и поедая животных, так же, как люди! Все через чудеса науки!}
{421}{}{[Logoff.]}


