###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Здравствуйте, добро пожаловать в Агентство по охране Земли, как правило нас называют EPA! Для Вашего удобства, этот терминал подсветит различных цветом области, которые составляют наш замечательный исследовательский объект. Пожалуйста, выберите уровень, о котором вы хотели бы получить больше информации.}
{101}{}{подуровень ОРАНЖЕВЫЙ}
{102}{}{подуровень КРАСНЫЙ}
{103}{}{подуровень ЖЕЛТЫЙ}
{104}{}{подуровень ИНДИГО}
{105}{}{подуровень ФИОЛЕТОВЫЙ}
{106}{}{подуровень ЗЕЛЕНЫЙ}
{107}{}{подуровень ГОЛУБОЙ}
{108}{}{Подуровень оранжевый содержит конференц-залы, где все принимаются все решения, кафе, где подается вкусная еда, и там хранятся некоторые опасные химические вещества.}
{109}{}{Подуровень Красный является базой нашей службы безопасности (ведите себя хорошо!) и небольшим, но информативный музеем. Кроме того, не забудьте купить закуски и осмотреть комнату исполнения наказаний!
 [ВНИМАНИЕ: Камеры исполнения могут быть непригодными для детей в возрасте до четырех лет.]}
{110}{}{Подуровень Желтый питает энергией наши удивительные новые голограммы, и еще там вы найдете прибор, создающий ваши любимые наркотики для каждого, Мистера Химми!
 [Примечание: Из-за ограниченний по размеру хранилища, мы поместили некоторые опасные химические вещества в той области, поэтому будьте осторожны!]}
{111}{}{Подуровень Индиго - там наши блестящие ученые проводят Совершенно секретные исследования! Звучит интересно, не правда ли? Помните, что любой несанкционированый посетитель обнаруженный на этом уровне будет расстрелян на месте.
 Поэтому родители, не позволяйте вашим детям бродить без присмотра.}
{112}{}{Подуровень Фиолетовый содержит ядро памяти, которая хранит данные о EPA и других вещах, которые не представляют большого интереса для посетителей. Извините!
 Однако, он напрямую соединен с подуровнем Желтый, который содержит более интересные вещи, например фармацевта будущего, Мистера Химми!}
{113}{}{Подуровень Зеленый выводит на уровень, который содержит дендрарий, исследования биологического оружия, увлекательных новых существ, и любимый всеми детьми, наш уникальный зоопарк.}
{114}{}{Подуровеня Blue не существует. Если кто-то сказал такое вам, тогда они грязные лжецы и, скорее всего, люди, сочувствующие коммунистам. Пожалуйста, сообщите о них в наш отдел безопасности на юге Красного подуровня, они смогут разобраться соответствующим образом. Спасибо что делать то что должны, как гордый американец!}
{115}{}{Возврат в главное меню.}
{116}{}{Спасибо за использование поиска локаций.}
{117}{}{[СДЕЛАНО]}
{118}{}{Вы видите компьютер.}
{119}{}{Вы видите поисковик локаций EPA.}
{120}{}{Вы видите компьютер с подробной информацией об уровнях EPA.}

