###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите модифицированный Авто-Док.}
{101}{}{Этот Авто-Док похоже были модифицирован для выполнения экспериментальных изменений внешнего вида.}

{200}{}{[машины обнаруживает вас, когда вы подходите.] Добро пожаловать, испытуемый. Спасибо за ваше тело, пожертвованное для науки. Пожалуйста, встаньте внутрь меня, и мы можем начать.}
{201}{}{Стоп, я никогда не говорил, что я добровольно что-то жерствую. Теперь, прежде чем я куда-то встану, почему бы вам не сказать мне, чем вы тут занимаетесь?}
{202}{}{[Пожать плечами.] Хорошо. [Встать в устройство.]}
{203}{}{Вы меня путаете с кем-то еще. Пока.}

{300}{}{С возвращением, испытуемый. Пожалуйста, встаньте внутрь меня, и мы можем начать.}
{301}{}{Прежде чем я куда-то встану, почему бы вам не сказать мне, чем вы тут занимаетесь?}
{302}{}{[Пожать плечами.] Хорошо. [Встать в устройство.]}
{303}{}{Я так не думаю. Пока.}

{400}{}{Я прототип новейшей технологии Авто-Док, разработанный доктором Вудом. Я специализируюсь в экстремальных модификациях тела - полный макияж. Не нужно нервничать, мои пациенты умирают значительно реже, чем у предыдущих прототипов. Не стесняйтесь, встаньте внутрь меня, и мы можем начать.}
{401}{}{Ты не прикоснешься ко мне. Пока.}
{402}{}{Я бы с удовольствием, но мне действительно нужно идти. Извините.}
{403}{}{Хорошо. [Встать в устройство.]}

{410}{}{Пожалуйста, сделайте свой выбор. Так как я ранний прототип, я могу только предложить Вам только ограниченный выбор. Извините.}
{411}{}{Изменить пол.}
{412}{}{Изменить расу. (В настоящее время только белый в негра или наоборот).}
{413}{}{Изменить прическу (в настоящее время только короткую на длинную и наоборот [только для персонажей Мужчин!]).}
{414}{}{Я передумал, у меня действительно нет времени для этого сейчас. Пока.}

#gender
{500}{}{Эта процедура займет четыре недели для вас, чтобы восстановиться и имеет 50% вероятности смерти. Вы хотите начать прямо сейчас?}
{501}{}{Давайте сделаем это.}
{502}{}{Да. Наконец, я смогу стать человеком, который всегда был внутри меня.}
{503}{}{Эх, может быть, позже. Пока.}
{504}{}{Позвольте мне выбрать другую процедуру.}
{505}{}{Черт, нет! Я сваливаю!}

#race
{510}{}{отличный выбор. Эта процедура займет для вас две недели чтобы восстановиться и имеет 25% вероятности смерти. Вы хотите начать прямо сейчас?}
{511}{}{Давайте сделаем это.}
{512}{}{Да. Наконец, я смогу стать человеком, который всегда был внутри меня.}
{513}{}{Эх, может быть, позже. Пока.}
{514}{}{Позвольте мне выбрать другую процедуру.}
{515}{}{Черт, нет! Я сваливаю!}

#hair style
{520}{}{отличный выбор. Эта процедура займет один день для Вас чтобы восстановиться и будет иметь всего 1% вероятности смерти. Вы хотите начать прямо сейчас?}
{521}{}{Давайте сделаем это.}
{522}{}{Да. Наконец, я смогу стать человеком, который всегда был внутри меня.}
{523}{}{Эх, может быть, позже. Пока.}
{524}{}{Позвольте мне выбрать другую процедуру.}
{525}{}{Черт, нет! Я сваливаю!}

{600}{}{Поздравляем! Эксперимент оказался успешным. Спасибо, и наслаждайтесь новым собой.}
{601}{}{[Выйти.]}

{700}{}{Мне очень жаль, но что-то ужасно неправильно пошло с процедурой. Приносим свои извинения за доставленные неудобства, но спасибо Вам огромное за жертву во имя науки.}
{701}{}{О, дерьмо...}

