###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите функциональный компьютер.}
{101}{}{Вы видите ботанический терминал EPA.}

{200}{}{Добро пожаловать в ботанический терминал EPA. Пожалуйста, выберите один из следующих вариантов.}
{201}{}{доступ к информационной базе данных.}
{202}{}{доступ к храненилищу семян.}
{203}{}{Log off.}


{210}{}{Существуют две базы данных, доступных для просмотра. Пожалуйста, сделайте свой выбор ниже.}
{211}{}{доступ к файлам по посевам.}
{212}{}{доступ к файлам по ботанике.}
{213}{}{доступ к файлам о животных и биологических испытаний.}
{214}{}{назад.}

{220}{}{Севооборот позволяет избежать снижения плодородия почвы, так как выращивание культур же повторно в том же месте в конце концов истощает почву по отдельным питательным веществам.
 Урожай, который вымывает из грунта один вид питательных веществ следует в течение следующего сельскохозяйственного сезона заменить на другую культуру, что вернет питательные вещества в почву или по крайней мере изменит соотношение питательных веществ.}
{221}{}{[БОЛЬШЕ]}
{222}{}{Севооборот также используется для борьбы с вредителями и болезнями, которые могут накапливаться в почве в течение долгого времени. Растения в рамках одной семьи, как правило, реагируют на аналогичные вредители и патогенные микроорганизмы. Регулярно измененяя место посадки, циклы вредителей могут быть сломаны или ограничены.}
{223}{}{назад}

{230}{}{Целью ботаники является научное исследование жизни растений. Как и другие биологические формы жизни, растения могут быть изучены с различных точек зрения, от молекулярной и вплоть до самих отдельных растений.
 Хорошее понимание растений имеет важное значение для нашего будущего, как это позволяет нам:

 -Производить продовольствие, чтобы прокормить растущее население.
 -Понимать фундаментальные жизненные процессы.
 -Производить медикаменты и материалы для лечения заболеваний и патологий.
 -Понимать экологические изменения более четко.

 Остальная информация представленя в различных диаграммах, графиках и фотографиях с классификацией растений.}

{231}{}{Скачать информацию голодиск.}
{232}{}{назад}

{240}{}{Этот объект был площадкой для различных экспериментах на животных и растительных формах жизни. Всестороннее тестирование проводилось над растительной формой жизни, известной как СПОР РАСТЕНИЙ и некоторыми животными, формами, известными как кентавры, флоатеры и радскорпионы.}
{241}{}{Читать об экспериментах над спорами.}
{242}{}{Читать о споровых растениях.}
{243}{}{Читать о кентаврах и флоатерах.}
{244}{}{Читать о радскорпионах.}

{250}{}{Различные эксперименты были проведены, чтобы вырастить новые споры жизни. Некоторые из этих попыток были успешны и результаты теперь можно увидеть растущем и здоровом состоянии в дендрарии.
 Резервуары для хранения в настоящее время содержат образцы семян, по-прежнему доступных для дальнейшего тестирования.}
{251}{}{Споры растений мутировали от некоторых генов от растений. Дополнительное тестирование показало, что растение вполне агрессивно и имеет две формы атаки.
 Одной из них являются споры, которыми оно плюет в своих врагов. Другая форма - укус зубастой пастью. Предлагается соблюдать большую осторожность при работе с этими формами жизни.}
{252}{}{По результатам исследований, кентавры по всей видимости, является побочным продуктом Форсированного Эволюционного Вируса (ФЕВ). Они, кажется, смесь собаки, кошки, брамина и других животных. FEV не единственная причина мутаций, однако, радиация судя по всему, тоже сыграла свою роль.
 Они, кажется, предпочитают жить в тяжелых условиях излучающей окружающей среды и так же сами облучают все вокруг них.}
{253}{}{[БОЛЬШЕ]}
{254}{}{Происхождение и этимология флоатеров неизвестны, но они, как считается, связаны с кентаврами, с которыми они часто встречаются. Они тоже по всей видимости являются результатом FEV.
 Дополнительное тестирование показало, чтобы они полностью защищены от повреждения электричеством.}
{255}{}{Радскорпионы являются чрезвычайно большими версиями североамериканского императорского скорпиона, мутировавшими от радиации. Вопреки первоначальным ожиданиям, их яд превратился более мощный,
 не разбавленный. Они ведут ночной образ жизни и чувствительны к свету. Дальнейшая проверка показала, что образцы яда из их хвостов могут быть использованы для создания противоядия.}
{256}{}{назад}
{257}{}{Различные эксперименты были проведены, чтобы вырастить новые споры жизни. Некоторые из этих попыток были успешны и результаты теперь можно увидеть растущем и здоровом состоянии в дендрарии.
 Резервуары для хранения сейчас не содержат образцов семян, доступных для дальнейшего тестирования.}


{260}{}{Текущий контейнер хранения EPA докладывает: есть семена, оставшиеся в резервуарах один и два.}
{261}{}{Текущий контейнер хранения EPA докладывает: есть семена, оставшиеся в резервуаре два.}
{262}{}{Текущий контейнер хранения EPA докладывает: есть семена, оставшиеся в резервуаре один.}
{263}{}{Текущий контейнер хранения EPA докладывает: нет семян ни в одном из резервуаров.}
{264}{}{доступ в резервуар один.}
{265}{}{доступ в резервуар два.}
{266}{}{назад}

{270}{}{Резервуар Один докладывает - осталось пять пакетов из программы расширения продуктов питания США. Семена растений кукурузы были генетически модифицированы для защиты от болезней и насекомых.}
{271}{}{Резервуар Два докладывает - осталось два пакета семян, из одинаковых или разных семей. Ни одно исследование не было проведено и результаты прорастания семян неизвестны.}
{273}{}{Получить семена.}

{280}{}{Сбор образцов семян... Успешно собрано 5 пакетов генетически модифицированных семян кукурузы. Перемещение пакетов в Контейнер для сбора... успех... Закрытие контейнер для хранения... успех.}
{281}{}{Сбор образцов семян... Успешно собрано 2 пакета неизвестных семян. Перемещение пакетов в Контейнер для сбора... успех... Закрытие контейнер для хранения... успех.}

{290}{}{Загрузка базы данных по Ботанике на голодиск... 75% завершено... Готово. Пожалуйста, удалите диск. Вернуться в меню.}
{291}{}{назад}

