###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{¬ы видите старый, ржавый вентил€тор.}
{101}{}{¬ы можете легко застопорить этот вентил€тор каким-нибудь куском металла.}
{102}{}{ћеталлический шест заклинил вентил€тор.}

{200}{}{¬ы заклиниваете шест в вентил€торе. ¬ы слышите скрежет металла и вентил€тор останавливаетс€. ќн издает клацающий звук, пыта€сь прокрутить свои застр€вшие лезви€.}

