###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{200}{}{Шкафчик не поддается. Необходимо ввести код.}
{201}{}{Вы вводите код и шкафчик распахивается.}

