###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Добро пожаловать к управляющему компьютеру роботов EPA. Что вы хотите сделать?}
{101}{}{Командовать роботами.}
{102}{}{Выполнить диагностическую проверку.}
{103}{}{Уйти.}
{104}{}{!ОШИБКА! !ОШИБКА! Возникшая проблема прекращает последовательность!}
{105}{}{Вернуться в главное меню}
{106}{}{Диагностическая проверка... ошибка платы соединения.... секция четыре... отсутствует контакт.}
{107}{}{Готово}
{108}{}{У вас нет возможности исправить эту машину}
{109}{}{Вы управляете ремонтом компьютера и выводите машину обратно в оперативный режим.}
{110}{}{Добро пожаловатьк управляющему компьютеру роботов EPA. Вы больше не имеете авторизованного доступа на использование этих файлов. Прерывание последовательности.}
{111}{}{Закончить}
{112}{}{БИП!}
{113}{}{БИП!}
{114}{}{Бззззз..}

