###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите компьютер.}
{101}{}{Вы видите музейный компьютер EPA.}

{200}{}{Добро в музей ЕРА! Этот терминал будет проецировать фильм с помощью новой голографической технологии!
 Фильмы развлекательные и информационные смотреть страшно, но возможно это реальность пост-ядерного мира.}
{201}{}{[Посмотреть фильм.]}
{202}{}{[Logoff.]}

{210}{}{[терминал высвечивает голограмму высокого очкарика в лабораторном халате. Он волнуется и дарит вам приветливую улыбку.]
 Здравствуйте, я доктор Калеб, и я представлю вам этот голографический видео обзор пост-Холокостной Америки.}
{211}{}{[Подробнее.]}

{220}{}{[Вокруг доктора Калеба материализуется гостиная, где семья, похоже, расслабляется перед ужином. Доктор Калеб гладит по голове семейного пса, а потом улыбается тебе.]
 Знакомьтесь, это Симпсоны. Они типичная американская семья. Папа курит трубку, мама читает свою кулинарную книгу, а малышы Билли и Сюзи играют перед сном. Они думают, что все будет просто отлично. Они игнорируют предупреждающие сирены, думая, что это просто еще одна тренировка. Ой, а что это такое?}
{221}{}{[Подробнее.]}

{230}{}{[через заднее окно, вы видите большие бомбы, падающие на землю, взрываются и создают огромное грибовидное облако, затем следует ослепительный свет.
 Как только свет исчезает, вы видите доктора Калеба, стоящего теперь в сожженых руинах гостинной, с семьей скелетов.] Ой-ой! Похоже, коммунисты долбанули большой штукой, и Симпсоны не были в полной безопасности, как они думали. Теперь, чему мы можем научиться из ошибки семьи Симпсонов?}
{231}{}{[Подробнее.]}

{240}{}{Правильно! В случае ядерной войны, вы захотите, чтобы ваши семьи были безопасности, в убежище производства компании Ваулт-Tec. Ваулт-Tec построила 122 общественных убежища для нашего великого народа, так что свяжитесь с ближайшим к вам. Думаю вы догадаетесь, что место в них очень ограничено, поэтому зарезервируйте место для себя сегодня же, иначе *ваша* семья в конечном итоге будет выглядеть как эти Симпсоны. [Доктор Калеб гладит голову скелета собаки. Череп отделяется от тела, падает на пол и разбивается.
 Выскакивает робот Мистер Хенди и заметает фрагменты черепа.]}
{241}{}{[Подробнее.]}

{250}{}{Похоже, Мистер Хенди собирается завершить свою работу насовсем, если он планирует убрать *этот* беспорядок. [Доктор Калеб смеется, изображение исчезает и заменяется текстом.]
 Спасибо за просмотр. Это учебное видео было создано для всех прекрасных людей в Vault-Tec. Vault-Tec, послежнее слово Америки в производстве домов.}
{251}{}{[Logoff.]}

