###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите функциональный компьютер.}
{101}{}{Вы видите совершенно секретный терминал ЕРА по исследованиям и развитию.}

{102}{}{Добро пожаловать на совершенно секретный терминал ЕРА по исследованиям и развитию. Ошибка инициализации процедуры быстрого доступа. Пожалуйста, ищите что-либо конкретное.}
{103}{}{поиск чего-нибудь важного.}
{104}{}{выход из системы.}
{105}{}{Через 30 минут просеивания всех файлов, которые вы нашли четыре из них, которые могут оказаться полезными. Пожалуйста, сделайте выбор.}
{106}{}{Доступ к журналу истории FEV.}
{107}{}{доступа к файлам по лечению эпилепсии.}
{108}{}{Продолжать поиск.}
{109}{}{Пожалуйста, сделайте выбор.}

{110}{}{Так как продолжает нарастать напряженность между США и Китаем, страх вселился в умы наших военных чинов. Они боятся того, что китайцы развернут биологическое оружие против американских войск. Как результат, ВестТек, основной высокотехнологический оборонный подрядчик, был нанят, чтобы развивать такое же направление. Это привело к исследованиям Вест Тека по Пан-Иммунитетному Вирусному Проекту (ПВП) с целью создания иммунитета у солдат к реструктуризации их ДНК.
 В ходе тестирования ПВП в 2076, у испытуемых наблюдались ненормальное побочные эффекты. Подопытные животные стали резко расти, и их активность мозга увеличилась.}
{111}{}{[БОЛЬШЕ]}
{112}{}{Видя потенциал есть, армия быстро захватили проект и переименовали его в FEV: Форсирующий Эволюционный Вирус. Не довольствуясь просто иммунитетом к болезням,
 FEV потенциально мог превращать солдат в аномально сильных и интеллектуальных "суперменов". После тестирования на животных исследование достигло своего логического завершения, и исследовательский центр FEV был перенесен на свое текущее местоположение на военную базу Марипоса. Там мы узнали, что тестирование продолжится на следующем уровне, когда они начали совершенно секретное тестирование на военных заключенных. Мы с нетерпением ожидаем результатов этих захватывающих экспериментов.}
{113}{}{Назад.}

{120}{}{Один из наших исследователей, доктор Ходкин, сделал удивительное открытие в своих последних исследованиях процессов словесных ответов человеческого мозга.
 Как оказалось, повторяя серию букв с правильными интонациями, слушатель может излечиться от большого числа неврологических заболеваний, таких, как аутизм или эпилепсия.
 В этот журнал включены точные сочетания букв (и надлежащих ударений), используемых доктором Ходкиным в своих экспериментах. Это замечательная новость, и это начало дальнейших исследований в лечении хронических неврологических расстройств.}
{121}{}{Это может быть полезно. Запомнить строку и искать что-нибудь другое.}


{130}{}{Вы не найдете больше ничего интересного.}
{131}{}{Вы до сих пор не нашли ничего более интересного.}
{1311}{}{Не сдавайся. Что-нибудь обязательно будет найдено.}
{132}{}{Может быть, если вы поищете немного больше, вы сможете найти что-нибудь?}
{133}{}{Может быть, еще один поиск?}
{134}{}{После долгих болезненных поисков, вы наткнулись на скрытый файл.}
{135}{}{Название файла: Проект массового фторирования.}
{136}{}{В продолжение усилий сделать граждан Соединенных Штатов более управляемыми, добавить фторид натрия во все доступные источники питьевой воды немедленно.
 Долгосрочные эффекты при тестировании показали, что подопытные становятся все более "глупыми и послушными." Кроме того, было отмечено, что фторид натрия вызвал
 небольшое повреждение определенной части мозга, вследствие чего для пострадавшего становилось более трудным защищать свою свободу и заставляя их стать более послушными власти.}
{137}{}{[БОЛЬШЕ]}
{138}{}{В наших последних экспериментах, мы выбрали военного чиновника, генерал Дж. Риппера, как подопытного. Первоначально он не знал о наших намерениях, но теперь, похоже, его устраивает такое положение вещей.
 Он стал одержим фразой о "драгоценных телесных жидкостях" и избегает пить любое вещество, если он не знает, откуда оно возникло. Он даже прекратил свои сексуальные контакты, так как он опасается, что женщины найдут "сущности жизни."}
{139}{}{Назад.}


#new in RP 1.3
{150}{}{Модификация пола.}
{151}{}{Вирус-Ладена фруктовых мух.}
{160}{}{Доктор Глен Вуд добился прорыва в его исследованиях по модификации пола. Он утверждает, что это будет революция наших возможностей в шпионаже.
 С помощью очень простой процедуры, мужчина может стать женщиной, или наоборот. Доктор Вуд настаивал, что он первым пройдет радикальную трансформацию.
 После завершения операции, он просил, чтобы его или ее, называли Глендой.}
{170}{}{Мутировавшие плодовые мушки в настоящее время успешно переносят вирус. Однако, прежде чем распространить их на территории иностранных государств, было решено, что мы сначала высадим плодовых мух на небольшие изолированные общины Америки, где мы сможем контролировать эффекты вне лабораторной среды.
 Жертвы среди гражданского населения - это ужасная, но необходимая плата. Кроме того, любой настоящий американец с большой честью откажется от своей жизни на благо нашей великой нации.}


{200}{}{Вы узнаете об истинных намерениях фторирования воды.}

{311}{}{Whirrrr....}
{312}{}{БИП!!}
{313}{}{Кланк...}

