###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите генератор голограмм.}
{102}{}{Генератор голограмм. НЕ ТРОГАЙТЕ ЕГО!}

