###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Управляющий компьютер комнаты заморозки. Выберите опцию.}
{101}{}{История.}
{102}{}{Затребовать испытуемого.}
{103}{}{[Закончить]}
{104}{}{Комната заморозки. Три человека были запечатаны в этих камерах до войны, каждый по конкретно определенным причинам. Субъекты остаются запечатанными и не знают о своем окружении. Записи журнала доступны для каждого субъекта.}
{105}{}{Вернуться в главное меню.}
{106}{}{ВНИМАНИЕ: длительное время в глубокой заморозке изменяет химические процессы организма. Без надлежащего применения химикатов к телу испытуемого при выходе из камеры, они могут страдать от ERS (Экологического Синдрома Отказа).
 Для обеспечения безопасности субъекта, настоятельно рекомендуем поместить канистру Ersi (ингибитор Экологического синдрома отказа) в распределитель, прежде чем продолжить.}
{107}{}{О, замечательно. Я только разбужу груду костей.}
{108}{}{Нет, возврат в главное меню.}
{109}{}{Затребовать испытуемого.}
{110}{}{Затребовать испытуемого.}
{111}{}{Затребовать испытуемого.}
{112}{}{Спасибо за использование управляющего компьютера комнаты заморозки.}
{113}{}{Вы видите большой компьютер.}
{114}{}{Вы видите управляющий компьютер компьютер комнаты заморозки.}
{115}{}{Вы видите компьютер, который используется для регулирования всего, связанного с ваннами заморозки.}

{116}{}{Поместить канистру Ersi в распределитель.}
{117}{}{Все равно продолжить.}

{118}{}{Ингибиторы Экологического синдрома отказа были успешно применены для образца. Частота сердечных сокращений образца кажется нормальной. Пожалуйста, перейдем к криокамере для восстановления.}
{119}{}{ПРЕДУПРЕЖДЕНИЕ: Ингибиторы Экологического синдрома отказа не были применены к образцу. Состояние образца неизвестно. Пожалуйста, перейдем к криокамере для восстановления.}
{120}{}{Хм, может быть, я должен пойти посмотреть, смогу ли я найти один из этих Ersi канистры. Там же быть где-то здесь, чтобы получить эти химические вещества ...}

{200}{}{Читать записи в журнале.}

{210}{}{Пожалуйста, выберите объект.}
{211}{}{Объект A.}
{212}{}{ОбъектB.}
{213}{}{ОбъектC.}
{214}{}{Назад.}

{220}{}{запись журнала #87983: Это наконец произошло. Они направили свое ядерное оружие на нас, и мы запустили наши ракеты в них. Военные чины не вдаются в подробности, но вероятно, уже настал Судный день. Радиосвязь нарушена на неопределенное время.
 Хорошо, что я привык к этому месту. У меня нет иллюзий относительно нового вида поверхности.}
{221}{}{[Подробнее]}
{222}{}{Они привели женщину для заморозки. Не сказали зачем, только что это совершенно секретные дела. Она была совсем красавица. Милая китаяночка, и было что-то в ее глазах. Она уложила двоих секретных агентов, когда они вышли на нее.
 Застала их врасплох и скинула их обоих с одной из часовен Иисуса Христа. Ее глаза выглядят очень усталыми. Третьему удалось скрутить ее. Не похоже, что она хотела провести оставшуюся часть ее жизнь здесь, если бы она смогла убить их всех, так или иначе.
 Она была без сознания, а они готовит ее бак. Прямо рядом с психопатом Патриком. Какой позор. Я бы хотел узнать ее получше. Доктор Дэвид Кимбл, 10/23/2077}

{230}{}{запись в журнале # 81977: ДЕкстер "Декс" Патрик довольно интересный образец. Он самовлюбленный, ненавидящий женщин социопатичный убийца, склонный к некрофилии и каннибализму. Он холоден сердцем до крайности, не видно никакого раскаяния за его жертвы, в числе которых все от невинных детей до пожилых людей и инвалидов. Его предпочтительной целью были привлекательные молодые женщины, которые он обычно соблазнял и затаскивал в постель прежде, чем жестоко их избить.}
{231}{}{[Подробнее.]}
{232}{}{Несмотря на его антиобщественное поведение, он остается удивительно общительным, даже очаровательным. В самом деле, похоже он завлек несколько женщин-сотрудников, несмотря на то, что они знали о многочисленных злодеяниях которые он совершил.
 Количество подтвержденных жертв Декса на данный момент 68, хотя он хвастался, что их фактическое число можно записать только тремя цифрами. Хотя Декс оказался навязчивым лгуном, мне все еще трудно сомневаться в обоснованности его претензий.}
{233}{}{[Подробнее.]}
{234}{}{Похоже, единственная эмоциональная привязанность Декса это рок-н-ролльный идол середины 20-го века, которым он восхищается как образцом для подражания и, возможно, даже считает его отцом. Он также показал нездоровую привязанность к разорваным человеческим ушам, которые мы определили как принадлежащие Вики Сафрон, возлюбленной Декса из школы, ставшей одной из его первых жертв. Он утверждает, что держит ухо в кармане чтобы Вики слышала крики всех его жертв.}
{235}{}{[Подробнее.]}
{236}{}{Я думаю, Декстера решили заморозить на будущее, так как правительство перенаправляет средства с нашего проекта на цели дальнейшего развития военных формирований, и моя команда теперь раскидывается по другим местам. Пусть это будет отмечено,
 Я считаю, что это ужасный непродуманный шаг, так как наши исследования о природе человеческого зла развиваются очень быстро, и я верю мы находимся вблизи громадного прорыва, который будет гораздо более ценным для нашего правительства, чем производство кучи "жестяных костюмов". Но я отвлекся.}
{237}{}{[Подробнее.]}
{238}{}{Декс будет оставаться замороженным тут, пока власть имущие не придут в себя и не возродят этот проект огромной важности. Я только надеюсь, я все еще буду здесь, чтобы возобновить свою работу, когда этот день придет. Доктор Дастин С. Делней,
 04/13/2075}

{240}{}{запись в журнале # 80052: сержант Кристофер "Кот" Джулс был назначен в военнизированное подразделение безопасности EPA с 17/02/2074. До этого он был прикомандирован к разведывательному подразделению 205-й воздушно-десантной. Сержант имеет впечатляющие навыки боя, и является одним из самых подкованных в энергитическом оружии и борьбы с невооруженным противником в своей части. Однако эти достижения омрачаются очень длинной историей обвинений в очень мелких кражах,
 неправильном ношении униформы и крайним высокомерием к начальникам.}
{241}{}{[Подробнее]}
{242}{}{сержант Джулс был привлечен в качестве испытуемого на проект Повышение Человеческой Чувствительности 10/05/2075 в обмен на удаление некоторых из этих докладов из своих файлов. Осложнения возникли из-за начальных проб и сержант Джулс был отключен для безопасности себя и окружающих.}
{243}{}{[Подробнее]}
{244}{}{Прошло несколько дней и сержант Джулс по-видимому в добром здравии, но он заполучил удлиненные клыки и кое-какие эксцентричные характеристики в дополнение к цели проекта улучшения рефлексов и повышению сенсорных возможностей.
 Я сохранил несколько отчетов командующего, запрашивающего дополнительное финансирование, но, увы, кажется, есть те, кто не желает продолжения моего проекта. Это просто позор, так как образцы тканей и психологических отчетов сержанта Джулса указывают лишь на незначительные увечья и на тенденцию к несколько сниженой продолжительности концентрации внимания. Помимо этого, он прекрасно подходит для службы и на самом деле, он стал более способными, чем раньше в результате лечения.
 До увеличения финансирования на этот проект, сержант Жюль останется в анабиозе. Доктор. Р. Д. Крайтон, 11/04/2075}


###.Magnat.###...Added by Killap. Need translation...########################
{300}{}{Choose a subject:}
{301}{}{Sergeant Christopher "Cat" Jules}
{302}{}{Dexter "Dex" Patrick}
{303}{}{Kitsune}

