###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Генератор имеет повреждения платы. Может быть, вы могли бы собрать запасные части на какой-нибудь свалке.}
{101}{}{Вы видите генератор.}
{102}{}{Вы видите генератор освещения EPA.}
{103}{}{Вы видите генератор, который управляет освещением в EPA.}
{104}{}{После долгих поисков, вы находите плату с несколькими поврежденными частями. Может быть, если вы обнаружите какую-нибудь свалку для разбора, вы сможете найти запасные части.}
{105}{}{Так вот в чем проблема проблема!}
{106}{}{Вы заменили вышедшие из строя детали и вернули генератор обратно в оперативный режим.}
{107}{}{Вы не можете найти ничего плохого. Он просто не работает.}
{108}{}{Это работает. С ним ничего делать не надо.}
{109}{}{Кажется с этим генератором что-то не так.}

{200}{}{*виррр*}
{201}{}{*бзззз*}


