###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{¬ы нажимаете на курок, но ничего не происходит.}
{101}{}{¬ы нажимаете на курок и взрываете динамит.}

