###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Хранилище данных и техническое обслуживание. Выберите опцию.}
{101}{}{Запустить диагностическую проверку.}
{102}{}{[СДЕЛАНО]}
{103}{}{Запуск проверки... Инициирование... Компиляция... Спасибо за терпение во время этой процедуры... Завершено. Хранилище данных работает на 84% эффективности.
 Ошибки подключения к этому мэйнфрейму вызваны магнитными катушками работающими на высокой мощности. В результате магнитное поле возможно вызывает помехи в работе других устройств, если не починить. Конец проверки.}
{1030}{}{Запуск проверки... Инициирование... Компиляция... Спасибо за терпение во время этой процедуры... Завершено. Хранилище данных работает на 100% эффективности. Спасибо и хорошего дня. Конец проверки.}
{104}{}{[СДЕЛАНО]}
{105}{}{Вы видите компьютер}
{106}{}{Вы видите компьютер хранилища данных EPA.}
{107}{}{Вы видите компьютер, который обеспечивает правильность и безопасность данные, хранящихся в EPA.}
{108}{}{Понял!}
{109}{}{Вы устранили проблему магнитных катушек.}

