# Message file for epai1.ssl 
# Number of nodes: 1

###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите брошюру.}
{101}{}{}
{102}{}{Это вступительный листок выдается в начале экскурсии.}

# Node  0  [Node001]
{200}{}{Добро пожаловать в ЕРА! Во время осмотра нашего учреждения, пожалуйста не волнуйтесь при виде полупрозрачных людей блуждающих по залам. Они не призраки - они наши новые дружелюбный сотрудники - голограммы!
 Думайте о них, как о компьютерных программах в человеческой форме через магию и чудеса науки! Они будут рады ответить на любые интересующие Вас вопросы, поэтому, пожалуйста, не стесняйтесь обращаться к ним. ВНИМАНИЕ!
 Голограммы проецируются через кристаллическую суспензию с анти-гравиметрическими свойствами. Они могут быть крайне нестабильными, если их задеть, поэтому, пожалуйста, ради вашей собственной безопасности,
 не пытайтесь коснуться голограммы. Спасибо и приятного просмотра!}
{201}{}{КОНЕЦ}
{202}{}{Вам нужно сначала положить это в инвентарь.}

