###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Бьюсь об заклад, я мог бы протиснуться сквозь этот вентилятор. Он выглядит более изношенным, чем другие, и, наверное, его будет проще заклинить.}

