###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{К какому уровеню вы хотели бы получить доступ?}
{101}{}{К Голубому уровню}
{102}{}{К Фиолетовому уровню}
{103}{}{[Выйти.]}

