###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите неусыпного стража Ши.}
{101}{}{Этот хмурый человек, кажется, охраняет моторную лодку. Он относится к своему делу очень серьезно.}

{200}{}{[Он глядит на вас подозрительно.] Помочь вам с чем-то?}
{201}{}{Нет. Все в порядке. Пока.}
{202}{}{Мне было просто интересно что вы делаете.}
{203}{}{У вас там очень хорошая лодка. А она все еще работает?}
{204}{}{Моя ехать на металлической рыбе?}

{210}{}{Не твое дело, аутсайдер. Отвали.}
{211}{}{Плохой выбор слов, мудак. Они станут твоими последними.}
{212}{}{Я могу понять намек. Не нужно лезть в бутылку. Пока.}
{213}{}{Как скажешь, приятель.}

{220}{}{[Он смотрит на вас как будто вы самое тупое существо какое можно себе представить. Он медленно качает головой.] Вы не ездить на металлической рыбе. Вы идти. Вы идти, или я стреляю. Понятно?}
{221}{}{Оки, бай бай!}
{222}{}{Вы скупердяй. Меня тошнит от скупердяя!}

{230}{}{[охранник берется за оружие и смотрит на вас без слов.]}
{231}{}{Можно одолжить лодку на минутку?}
{232}{}{Я просто проверял, ты такой же мудак как и раньше?. Да, похоже что да. Пока.}
{233}{}{Извините, я думал, что вы, ну, кто-то другой. Пока.}
{234}{}{Я надеюсь, вы знаете, как пользоваться этой штукой, потому что я планирую забрать эту ебаную лодку, так или иначе.}

{240}{}{[Он смотрит на вас как будто вы самое тупое существо какое можно себе представить. Он медленно качает головой.] Нет. Уходи сейчас же. Спросишь меня еще раз и я сделаю тебе больно.}
{241}{}{Хорошо, я ухожу. Пока.}
{242}{}{Точно сделаешь?}

{250}{}{Отойди оттуда!}
{251}{}{Дотронешься снова, и я тебя убью.}
{252}{}{Я тебя предупреждал!}

