###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите докера. Он смотрит как вы подходите.}
{101}{}{Вы видите меланхоличного докера. Его полные печали глаза смотрят как вы подходите.}

{200}{}{[Бормочет про себя.] Ах, какие зверства сделал бедный Мэнг в прошлой жизни, чтобы заслужить такое несчастье? Теперь лаовай пришел ко мне, и что хорошего из этого вышло? Ничего, конечно. Ничегошеньки...}
{201}{}{Почему вы не оставите бедного Мэнга в покое? [Бормочет про себя.] Не то чтобы я когда-либо знал мир. Или, если бы знал, то давно бы забыл, как далекую мечту...}
{202}{}{Ух, я кажется застал вас в неудачное время. Пока.}
{203}{}{Что у тебя за проблемы, Бормотун?}
{204}{}{Я заметил, вы кажется чем-то расстроены. Мне интересно, может я смогу помочь.}

{210}{}{Моя проблема? [Горько смеется.] лаовай, вы не хотите узнать мою проблему. Чтобы услышать мою скорбь, нужно забыть смех ребенка и теплые объятия любимого человека. Нет, поверьте мне, вы не захотите посмотреть на мой личный ад.}
{211}{}{Я был свидетелем многих ужасных вещей в свое время. Я уверен, что какой бы ни была проблема, я смогу справиться с этим.}
{212}{}{Вы думаете, *ваши* проблемы сложные? Бьюсь об заклад, они не *сравняться* с вещами, которые я пережил.}
{213}{}{Я извиняюсь, может это слишком грубо для вас, но может стоит поговорить об этом. Если вы готовы говорить, то я готов слушать.}
{214}{}{Ладно, мистер Мелодрама, я собираюсь уйти, прежде чем вы вгоните меня в депрессию. Пока.}

{220}{}{Хорошо. Вы хотите знать, в чем моя проблема. Я вам скажу. Два года назад у моего брата, который очень похож на меня, был роман с подружкой местного лидера банды. Главарь банды, узнал об этом, и мой брат бежал из города.}
{221}{}{Ох, нууу- }

{230}{}{О, нет! Я еще не закончил. Потом моя красавица оставила меня, потому что я уже не "настоящий мужчина" и не мог удовлетворить ее. Затем она вышла замуж за моего соседа, который также является моим начальником.}
{231}{}{Хахаха! Срань Господня, да ты неудачник. Почему бы тебе не сделать себе услугу и просто не покончить с этим?}
{232}{}{Я, ну, ничего себе, я не знаю, что сказать. Это страшная история.}
{233}{}{Я сожалею, что так случилось с вами, Мэнг. Жизнь может быть жестокой, но она всегда может стать лучше. Если бы я был на твоем месте, я бы переехал куда-нибудь еще и нашел другую работу. В противном случае ты никогда не сможешь двигаться дальше.}

{240}{}{Да. Да, это то, что я должен был сделать давно. Это единственный способ сохранить ту немногую честь, что у меня осталась. Спасибо, лаовай. [Он достает нож и садится в позу. Вы наблюдаете, как он быстро делает себе харакири.]}
{241}{}{[СДЕЛАНО]}

{250}{}{Да. Это я вас предупреждал. Теперь, позвольте мне жить. Мне больше нечего вам сказать.}
{251}{}{[СДЕЛАНО]}

{260}{}{Может быть, вы правы. Всю моя жизнь, я ничего не знал, кроме Ши. Но здесь для меня не осталось ничего, кроме печали. Да, я думаю, я выйду в мир и буду ковать свою новую судьбу. Даже если пустыне нечего мне предложить, кроме быстрой смерти, это лучше чем оставаться здесь. Спасибо тебе, лаовай.}
{261}{}{Удачи, Мэнг. Надеюсь, что ваша судьба улучшится.}
{262}{}{Перед началом сборов, мне интересно, смогли бы вы ответить на вопрос или два для меня?}

{270}{}{Почему нет? Я разрываю все связи с Ши. Их секреты теперь ничего не значат для меня. Спрашивайте что пожелаете.}
{271}{}{Что вы можете рассказать мне о том охраняемом катере там? }
{272}{}{Ничего. Удачи в вашей новой жизни, Мэнг.}

{280}{}{Ши использует катер для доступа к нашему спящему защитнику, подлодке.}
{281}{}{Что ты можешь рассказать мне о подлодке?}

{290}{}{Ши-Хуан-Ти это подводная лодка, которую привели наши предки в это место из далеких земель. После Великой войны она потеряла мощность и села на мель в бухте Сан-Франциско. Капитан Йе Ли и его экипаж добрались до этого города и создали то, что стало обществом Ши.}
{291}{}{Ты называл его "спящим защитником". Что ты подразумевал под этим?}

{300}{}{Как спящий дракон, храп которого может еще произвести смертельный огонь - подлодка неподвижна, но не беспомощна. Ши работали над этим в тайне, делая тайные поездки на субмарину под покровом ночи.}
{301}{}{Так, скажем, *гипотетически*, если этот большой танкер который пристыкован здесь, попробует поднять паруса...}

{310}{}{Тогда... БУМ!}
{311}{}{Попался. Я не думаю, что вы знаете, как я могу разоружить ее?}

{320}{}{Только техники Ши знают такие вещи. Я рассказал вам все, что знаю.}
{321}{}{Спасибо, Мэнг. Удачи вам в вашей новой жизни.}

{330}{}{Теперь пришло время начать заново...}

{350}{}{Оставь меня, лаовай.}

{400}{}{Вы убедить Мэнга двигаться дальше по своей жизни.}


