#looks/descriptions
###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите охранника в свободной одежде, осторожно скучающего.}
{101}{}{Вы видите охранника дока. Он необычно хорошо вооружен.}
{102}{}{Вы видите охрану катера.}

#touched motor boat without permission
{150}{}{Эй! Отойди оттуда!}
{151}{}{Даже не думай об этом. Это твое последнее предупреждение.}
{152}{}{Я предупреждал тебя, лаовай, сейчас умрешь!}

#Main dialogue

#Greeting
{200}{}{Что вы хотите, лаовай?}
{201}{}{Это вы опять. Что такое, чего вы хотите, лаовай?}
{202}{}{Что ты охраняешь?}
{203}{}{Мне нужно использовать катер.}
{204}{}{Ничего. Пока.}

#what are you guarding?
{210}{}{Все. Не пытайтесь меня рассмешить.}
{211}{}{Разве вы не можете быть более конкретным?}

#be more specific
{220}{}{Нет. Теперь уходи, внешний.}
{221}{}{Хорошо. Пока.}
{222}{}{Никто не указывает мне, что делать. Чувак, ты труп! }

#I need to use the motor boat
{230}{}{Отвали. Ты не имеешь права использовать моторную лодку, черт возьми, ты лаовай, а не Ши.}
{231}{}{Слушай, я нахожусь в отчаянном положении. Если вы не позволите мне использовать эту моторную лодку, то все мое племя может умереть.}
{232}{}{Вообще-то, я почетный член Ши. Я был нанят в команду обслуживания подводной лодки из-за моего опыта в… подводнологии. Вот мой пароль...}
{233}{}{Я не думаю, что вы понимаете, кого оскорбили. Время умирать, засранец.}
{234}{}{Хорошо, я собираюсь... Шииииишшь, некоторые люди...}

#Listen, I might not be Shi...
{240}{}{[Он смотрит на вас долгим взглядом, затем вздыхает.] Смотри, никто не пройдет на эту лодку, не зная правильный пароль. Вы знаете, как вы только что сказали мне. [Усмехается.] Кен Ли снимет мне голову за это...}
{241}{}{Спасибо, друг. И не волнуйтесь, я не скажу ни слова об этом никому.}

#I won’t speak a word of this anyone
{250}{}{Я надеюсь нет, но для нашей общей пользы... Дайте мне знать, когда вы будете готовы использовать лодку. Вы не сможете взять с собой никого, так как это будет привлекать слишком много внимания. Вам придется пойти на это в одиночку.}
{251}{}{Я хотел бы использовать лодку прямо сейчас.}
{252}{}{Не сейчас.}

#I'm a member of the Shi...
{260}{}{[охранник слушает пароль и кивает.] Я думаю, вы на самом деле специалист. Хм, Ши должно быть, отчаянно пытаются нанимать сторонних... Во всяком случае, вы рано. Разве они не сказали вам, что техники не покидают порт до полуночи? Ты можешь подождать остальных здесь, если хочешь.}
{261}{}{Мне действительно нечего пока делать, так что я согласен...}
{262}{}{Я вернусь позже.}

#Use motor boat now
{270}{}{Просто используй швартовочные крюки и затащи веревку на лодку. Не слишком долго там, я не хочу попасть в неприятности.}
{271}{}{Понял. Пока.}
{272}{}{Кажется несложно. До свидания.}

#Player wasn't initially ready to go with the tech team
{280}{}{Готовы присоединиться к команде техников?}
{281}{}{Да, я готов к работе.}
{282}{}{Нет, еще нет.}

{290}{}{Разве ты не видишь, что я занят?}

#dumb dialogue
{300}{}{мне ехать на металлической рыбке-рыбке?}
{310}{}{[Он смотрит на вас как будто вы самое тупое существо какое можно себе представить. Он медленно качает головой.] Вы не ездить на металлической рыбе. Вы идете. Вы идете, или я стреляю. Понял?}
{311}{}{Оки, бай-бай!}
{312}{}{Вы скупердяй-человек. Меня тошнит от скупердяя-человека!}

{500}{}{Вы рассказываете свою историю о получении доступа к моторной лодке.}



