#Targeting Console Techie

###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите человека в смешной пижаме. Он, кажется, занят.}
{101}{}{Вы видите техника подводной лодки Ши.}

{150}{}{Ох, что вы делаете, разнюхиваете или типа того?}
{151}{}{Вы какой-то шпион?}

{200}{}{Могло бы быть легче, если бы я лучше знал китайский...}
{201}{}{I / O Error!? Как система наведения смогла получить ошибку ввода / вывода!?}
{202}{}{001100010010011110100001101101110011? Где тут моя таблица кодов ошибкок...}
{203}{}{Я надеюсь база данных IFF еще работает. Тогда будет намного проще.}

{300}{}{Что вы хотите, лао вай? Разве вы не видите, я пытаюсь перенастроить систему наведения?}
{301}{}{Я сам здесь именно для этого. У меня есть новые спецификации для этой систему, проверенные императором лично. Можете ввести их?
 Вы, кажется, разбираетесь в этой подсистеме.}
{302}{}{Вот поэтому я и здесь, я могу помочь вам с настройкой системы. Кажется, связь между подсистемой морской навигации и IFF транспондером
 наконец-то прервалась, так что вы должны найти обходной путь. Не возражаете, если я помогу?}
{303}{}{Извините, что беспокою вас.}

{310}{}{О, я так долго ждал эти новые спецификации! Вы должны были быть здесь еще неделю назад, когда я работал над тем, что осталось от боевой базы данных.
 Теперь я должен взламывать и открывать ее снова... Ну что ж, такова жизнь техника, я полагаю.}
{311}{}{Удачи. Я посмотрю, что еще надо починить.}

{320}{}{Я не знаю вас! И все что я знаю о лао вай, вы можете бы быть каким-то иностранным шпионом, желающим отключить эту подводную лодку, чтобы ваш план путешествовать по иностранным морям мог быть завершен без торпед с нашей лодки! Я уверен, что Кен Ли никогда не пропустил бы на Ши-Хуан-Ти чужака с плохими намерениями, так что извините, но я не могу принять эти координаты, только если я получу их от нашего лидера лично.}
{321}{}{Ну, я могу по крайней мере помочь вам с настройкой подводной лодки? У меня есть некоторый опыт работы с древними компьютерными системами, достаточный, чтобы понять, почему 200-летняя система на вакуумных лампах может отказаться подчиняться своему хозяину.}
{322}{}{Ладно, извините, что беспокою вас.}

{330}{}{Я думаю, я могу принять вашу помощь, вот, попробуйте. [Технолог Ши позволяет вам подключиться. После нескольких минут самостоятельного ознакомления с пользовательским интерфейсом, вы начинаете работать. Через несколько минут вам не только удалось перенастроить параметры наведения, так что субмарина теперь не потопит танкер, но и удалить неисправность в системе, перекрыв техникам легкий доступ к подсистеме.]}
{331}{}{Ну вот и все. Я починил систему. Она не должна больше доставлять вам проблемы. Надеюсь, это поможет вам в вашей работе.}

{340}{}{Спасибо за вашу помощь, трудно найти хорошего компьютерного техника в наши дни.}

{350}{}{Извините, но нет. Вы можете нарушить что-нибудь и мы потеряем доступ к подсистеме, и я *не* собираюсь наводить множество торпедных модулей на цели вручную. Так что, если у вас нет ничего *важного* для меня, пожалуйста, позвольте мне вернуться к моей работе.}
{351}{}{На самом деле есть. У меня есть новые параметры наведения для торпед, проверенные императором, ух, лично. Вы компьютерный мастер, поэтому я думаю, я могу доверить вам это.}
{352}{}{Извините, что беспокою вас.}

{360}{}{Нет, мне не нужна помощь или какие-либо новые данные. Я здесь, чтобы работать, а вы отвлекаете меня от дела, так что уйдите или тебя *вынесут* прочь!}
{361}{}{Извините, что беспокою вас.}

{370}{}{Эй, я занят.}
{371}{}{извините, я работаю.}

{400}{}{Вы обманули техников и отключили подводную лодку.}

