###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите старую консоль.}
{101}{}{Похоже, что эта консоль управляет системой запуска и загрузки торпед. Как и все остальное на субмарине, она проржавела насквозь и еле-еле работает.}

{200}{}{Эта подсистема, если отключится, должна остановить загрузку новых запасных торпед в аппараты. Отключение не должно быть слишком сложным - металл буквально разваливается, и вы можете четко видеть вакуумные трубки.}

{210}{}{Как вы и думали - металл легко поддается и консоль вскоре демонтирована. Эта субмарина не сможет перезарядить трубы торпедных аппаратов в ближайшее время.}
{211}{}{Вы не в состоянии отключить систему.}

{212}{}{*beep*}
{213}{}{*beeboop*}

