###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите торпеды.}
{101}{}{Это опасное на вид оружие заполнено до краев взрывчатыми веществами. Оболочки изъедены коррозией и кажется винты могут отвалиться в любую секунду.}

{200}{}{Несмотря на внешность, эта торпеда все еще мощное оружие. Свободный винт фактически является неотъемлемой частью собственной навигационной системы, придавая торпеде беспрецедентную маневренность. Похоже, вам нужно сломать корпус для ее отключения.}
{210}{}{Благодаря двум столетиям упадка, ржавую двигательную установку легко разобрать. Спустя несколько мгновений, она снова собрана, но на этот раз торпеда полностью обездвижена.}
{211}{}{Проржавевшая двигательная установка доставляет слишком много проблем. Гайки застряли, и вы не можете четко определить, как отсоединить винт не разрезав себя.}

{220}{}{Вы установили взрывчатку вблизи нескольких фугасных торпед. Убраться отсюда поскорее может быть хорошей идеей.}
