###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{¬ы видите старую консоль.}
{101}{}{—илова€ консоль почти полностью разрушена. ѕровода торчат во все стороны, скреплены клейкой лентой, а монитор состо€ни€ кажетс€ лопнул. Ёто сооружение едва держитс€.}

{200}{}{¬ы изучаете консоль и оборванные кабели. ѕохоже, любой кто немного разбираетс€ в ремонте (или с большим навыком работы ломом) может полностью отключить подсистему питани€.}

{210}{}{ онсоль быстро сдаетс€ и аварийный генератор умирает. Ѕез энергии, подводна€ лодка не представл€ет никакой угрозы.}
{211}{}{¬ы не в состо€нии отключить генератор энергии.}

{212}{}{*beep*}
{213}{}{*beeboop*}
