###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите охранника в свободной одежде, осторожного и скучающего.}
{101}{}{Похоже он не хочет сейчас быть здесь.}

{150}{}{Что вы здесь делаете, разнюхиваете?}
{151}{}{Вы какой-то шпион?}

{200}{}{Эта штука вгоняет меня в дрожь.}
{201}{}{Хватит тратить мое время, лао вай.}

