###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Этот люк выглядит странно - в отличие от остальной части судна, он относительно не ржавый и имеет сложный замок.}

{200}{}{Вы боретесь с люком, но в конце концов вам удается его вскрыть. Осколки разбитого замка хрустят под твоими ботинками.}
{201}{}{Вы стараетесь, но люк просто не двигается с места. Может быть, взрывчатка поможет.}
{202}{}{Похоже, люк можно открыть, если применить достаточную силу. Маркус может помочь с этим.}

{210}{}{Эй, Маркус, ты можешь помочь мне открыть этот люк?}
{211}{}{Конечно, только отведи меня к нему.}
{212}{}{*hrrrgnnnr*}
{213}{}{Супермутант пытается тянуть люк. На мгновение кажется, как будто у него сейчас вылезут кишки, но именно тогда замок ломается, засоренная башня с кусочками сломанного замка.}

{220}{}{Вы возитесь с замком некоторое время и открываете его. Вскрытие замков определенно больше, чем просто хобби для Вас.}
{221}{}{Вы возитесь с замком, но в конечном итоге сдаетесь. Должен быть другой способ, чтобы открыть люк.}

{230}{}{Взрыв открывает люк и срывает замок, а так же оглушает Вас.}

