###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{¬ы видите старую консоль.}
{101}{}{ѕохоже, это стара€ консоль управлени€ наведением торпед. Ѕольшинство мониторов лопнуло или отсутствуют, только один едва функционирует.
 ¬рем€ от времени на мерцающем экране по€вл€ютс€ случайные биты данных.}

{200}{}{ќперационна€ система, кажетс€, была повреждена, так как она не правильно отвечает на ваши команды. ¬ы можете упор€дочить систему с научным подходом.}

{210}{}{Ќескольколькими дополнительными командами система разворачиваетс€ и начинает вести себ€ должным образом. ≈ще несколькими нажати€ми клавиш системы управлени€ торпедами отключаютс€ и взвод€тс€ дл€ подрыва через минуту после выхода из трубы. Ќаука!}
{211}{}{¬ы возитесь с системой в течение нескольких минут, но это слишком сложно дл€ вас. ѕохоже, вы должны найти другой способ отключени€ торпед.}

{212}{}{*beep*}
{213}{}{*beeboop*}


