###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Стой, житель пустыни! Мы ищем врагов Анклава. Пожалуйста, идентифицируйте себя.}
{101}{}{Все ненавидят Анклав. Руки вверх!}
{102}{}{Анклав? Никогда не слышали о них. Я всего лишь простой путешественник.}

{103}{}{Это достаточно для меня. Убейте его.}
{104}{}{О, это будет весело!}

{105}{}{[Прищурив глаза] Почему я должен тебе верить? Ты в непосредственной близости от Геско. Ты можешь бы быть одним из тех, кого мы ищем.}
{106}{}{Может быть. Но, как я сказал, я никогда не слышал об Анклаве. Мне нужно идти.}
{107}{}{Ну ладно, я сдаюсь. Давай потанцуем!}

{108}{}{Ладно, отмазался. А ты когда-нибудь был в Геско?}
{109}{}{Да, конечно был. Очаровательное место. Великолепные компьютерные системы!}
{110}{}{Нет, никогда там не был. А что?}

{111}{}{ЛАдно, я тебе верю. Отходим. Поиск по области. Мы должны найти этого человека.}
{112}{}{Нет. Я тебе не верю. Это тот кто нам нужен, ребята!}
{113}{}{[ЗАКОНЧИТЬ]}

{114}{}{Почему вы не верите мне? Что я должен сделать чтоб доказать?}

{115}{}{Кто-то взломал компьютерную сеть Анклава из реактора Посейдон Ойл. Мы пытаемся разыскать его.}
{116}{}{Вломился куда?!? Ну, это не про меня. Я дикарь. Я даже не знаю, как использовать - как же вы это называете? - Ком-пу-тель.}

#added by killap - RP 1.3
{200}{}{Геско? Черт, нет, это место ближе чем нужно. Разве вы не знаете, что там у них уродливые засранцы-упыри? Еще хуже, что я должен следить за моим дядей Ленни. А почему ты спрашиваешь?}
{201}{}{Ургх?}
{202}{}{Моя убивать злодеев!}

