###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы вышли на большую равнину неподалеку от Гекко. Некоторые люди здесь носят высокотехнологичные доспехи.}

