###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите колодец.}
{101}{}{Может вы и ошибаетесь, но когда вы смотрите вниз, вы чувствуете тепло, подымающееся из темноты.}
{102}{}{Вы делаете большой глоток колодезной воды. Она необычно теплая.}
{103}{}{Вы делаете большой глоток колодезной воды. Ее вкус лучше, чем раньше.}

