###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите охранника хабологиста.}
{101}{}{Он выглядит крепким и хорошо вооруженным.}

{200}{}{Halt! Это частная собственность Церкви Хабологии. Что вам здесь надо?}
{201}{}{Я пришел грабить это место. Я слышал отсюда можно забрать много богатств.}
{202}{}{Не беспокойся брат, потому что мы родственные души. Я тоже в объятиях церкви Хабологии.}
{203}{}{Да? [Он осматривает вас снизу вверх.] Тогда вы не будете возражать, если я расспрошу вас о нашей вере.}
{204}{}{[Он жестоко усмехается.] Ты смелый. Мне это нравится. Давай посмотрим, какой ты смелый, когда я оставлю твое кровоточащее тело в пыли.}
{205}{}{Спрашивай. Я готов.}
{206}{}{Расспросить, да? Знаешь, что? Забудь это - соврал я. Давай махаться.}

{220}{}{Кто был основателем Церкви?}
{221}{}{Церковь считает, что жизнь, вселенная, и все остальное может выражаться символом чего?}
{222}{}{В контексте церкви, что подразумевается под термином "Просвещение"?}

{230}{}{Герберт Дженц}
{231}{}{Дик Хаббел}
{232}{}{Хуан Крус}
{233}{}{AHS-9}
{234}{}{Хуго Ричардсон}

{240}{}{Круга.}
{241}{}{Денег.}
{242}{}{Роворота колеса.}
{243}{}{Рога Одина.}
{244}{}{Рыбы.}

{250}{}{пополнение телесное сущности.}
{251}{}{состояние полной эйфории.}
{252}{}{состояние будет достигнуто, когда ищущий разовьет божественное понимание истинной природы вещей.}
{253}{}{состояние достигнуто, когда ищущий получит много знаний он становится неотъемлемой частью вселенной и выйдет из этой земной жизни.}
{254}{}{окончательное достижение на духовном пути, когда ограниченное чувство "я" сливается с высшим "Мы".}

{260}{}{Все верно. Только хабологист может иметь такую мудрость. Я приветствую вас, и прошу у вас прощения. Могу ли я спросить, зачем вы пришли сюда? Очень немногие из наших членов знают об этом месте.}
{261}{}{Ха! Неправильно. Верный и проверенный метод викторины безопасности работает каждый раз. Теперь надо избавить мир от тебя, самозванец!}

{270}{}{Меня попросил AHS-9 проверить все пожертвования. Он хочет убедиться, что здесь все в порядке.}
{271}{}{Я пришел, чтобы сделать пожертвование.}

{280}{}{О, я не знал, что вы были направлены с таким заданием. В этом случае, вы можете свободно войти. Позвольте мне открыть эту дверь для Вас.}
{281}{}{[Он хмурится.] Хм, мне никогда не говорили о каких-либо проверках...}
{282}{}{Спасибо. Увидимся.}
{283}{}{Слушай, для проверки меня лично инструктировал AHS-9. Он просил, чтобы я искал конкретный артефакт, который был подарен в последнее время. Он имеет решающее значение для достижения звезды Отца.}
{284}{}{Мне больно от твоей лжи. Я думаю, пришло время удалить еще один сорняк из этого мира.}

{290}{}{Но не обязательно, чтобы пожертвование было сделано сдесь. Вы можете пойти сделать это в любой из наших церквей.}
{291}{}{Я знаю это, но AHS-9 рассказал мне, что новобранцы имеют право проверить вещи, прежде чем сделать значительный вклад.}
{292}{}{[Он хмурится.] Хм, мне никогда не говорили о каких-либо проверках...}
{293}{}{О, я вижу. Это понятно. Вы можете свободно войти, только не шныряйте вокруг слишком долго.}
{294}{}{Слушайте, я собираюсь дать порядочную сумму денег для Церкви. Я хочу убедиться, что мое пожертвование будет в безопасти и использовано надлежащим образом.}

{300}{}{Здравствуйте еще раз.}
{301}{}{Я надеюсь, что все в порядке.}

#dumb dialogue added in RP 2.x
{400}{}{Моя хочет внутрь.}
{410}{}{[Он странно смотрит на вас.] Ну, тогда вам понадобится пароль.}
{411}{}{Моя пускает газы, а не слова (PASS WORD :) .}
{412}{}{Моя хочет внутрь!}
{420}{}{Слушай, у меня нет на это времени. Тебя явно не должно быть здесь, так что давай пароль, или пожалеешь.}
{421}{}{Буга до свидания!}
{422}{}{Моя хочет внутрь. Ты умереть сейчас.}

{430}{}{Последний шанс. Уходи сейчас же или умри.}
{431}{}{Я вас предупреждал!}

