###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите усталого человека, одетого в кожаную броню.}
{101}{}{Перед вами (x), охранник каравана.}
{102}{}{Вы видите усталого, покрытого пылью человека в кожаной броне. Судя по уверенной походке и тому, что от него воняет браминами, это наверняка охранник каравана.}

{103}{}{Чем могу служить?}
{104}{}{Гым?}
{105}{}{Моя тут работать!}
{106}{}{Кто вы?}
{107}{}{Что ты можешь рассказать мне о Чеде?}

{108}{}{Идиотам не подаю. Прости, дружище, найди кого-нибудь другого и играйся.}
{109}{}{::принюхивается::}

{110}{}{Я (x). Я охраняю караван.}
{111}{}{Что ты можешь рассказать мне о Чеде?}
{112}{}{Спасибо. Пока.}

{113}{}{Чед хороший парень. Крутой босс, но честный. Если ты хорошо работаешь, внакладе не останешься.}
{114}{}{Кто вы?}
{115}{}{Спасибо. Пока.}

{116}{}{Спасибо. Нет, правда. Спасибо за то, что мы остались без премии. Чед надувал только тех, с кем мы торговали; он помогал нам, а из-за тебя все теперь пропало. Скотина.}
{117}{}{Пока.}

{118}{}{Это враг! Умри!}
{119}{}{Упс.}

###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{120}{}{[понизил голос и оглядывается.] Должно быть. Вообще-то, я был охранником на последней транспортировке урана в Геско, и я услышал как Чад спорит с их упырем.
 По-видимому, Брокен Хиллс недавно поднял цены на уран, и упырь был не слишком счастлив. Тогда я услышал, как Чад объяснял ему что наши последние поставки урановой руды маленькие и долго идут из-за забастовки, но дело в том, что у нас никогда не было забастовки.}
{121}{}{В самом деле? Тогда почему вы не сообщили Маркусу?}

{122}{}{Ты спятил? Чад самый мощный парень в этом городе, и у него много друзей. Если я попытаюсь подсидеть его, множество людей возненавидят меня. Черт, возможно меня даже убьют.}
{123}{}{Хм, возможно, я мог бы сообщить Маркусу. Я не планирую остаться здесь долго в любом случае.}

{124}{}{Эй, делайте то, что вы должны сделать, только не затаскивайте меня в это дело. Считайте, что у нас никогда не было этого разговора, хорошо?}
{125}{}{Нет проблем. Пока.}

{126}{}{Да, и еще одна вещь. Я знаю, Чад ведет учет всех проведенных сделок. Он своеобразный записывающий маньяк. Вообще-то, парень, я уверен, он даже ведет учет всех денег, которые он, стырил. Проблема в том, что он держит все взаперти в своем доме на другом конце города, и просто так вы записи не получите, там комплексная система и замок слишком сложный.
 Опять же, у нас не было этого разговора.}
{127}{}{Я найду способ. Спасибо за дополнительную информацию.}

{128}{}{Комплексная система? Как я смогу попасть в дом?}
{129}{}{[Макс напряженно думает.] Ладно, слушай. Ты похож на того кому я могу доверять. Дверь в дом Чада заблокирована с помощью самых передовых неэлектронных замоков есть - эта штука настоящая красота.
 Я знаю, так как я разработал эту штуку. Видите ли, прежде чем я был охранником караванов, я был взломщиком. Теперь, так как я предполагаю, тебе будет необходимо попасть в этот дом, позвольте мне объяснить, как взять такой тип замков.}
{130}{}{(Минут пять Макс объясняет принципы работы своих замков.) Этого должно быть достаточно, чтобы получить доступ. С помощью этой информации, даже новичок может взять любой из этих замков.
 Теперь будьте осторожны. Да, и у нас никогда не было этого разговора.}
{131}{}{Не волнуйтесь. Спасибо за дополнительную информацию.}

{200}{}{Вы узнаете о последних кражах Чада из караванов в Геско.}


###.Magnat.###...Added by 1C. May be: a)for female characters (require proper scripts); or b) absent in English version...########################
#Женские реплики, Андрей
{10108}{}{Идиотам не подаю. Прости, подруга, найди кого-нибудь другого и играйся.}
