###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите охранника хабологиста.}
{101}{}{Вы видите хорошо вооруженного человека с жестоким взглядом.}

{110}{}{Вы видите хабологиста.}
{111}{}{Он смотрит на различное компьютерное оборудование перед ним.}

{200}{}{Мы лояльны к AHS-9.}
{201}{}{Звезда Отца заботится о всех нас.}
{202}{}{Это скучно, но это наша работа, следить за пожертвованиями.}
{203}{}{Приветствую друг.}

{300}{}{Не забудь что-нибудь.}

