###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите усталого охранника хабологиста.}
{101}{}{Он выглядит довольно скучно.}

{200}{}{(смотрит на вас со скукой) Эй. Что привело ваш путь сюда?}
{201}{}{Я здесь, чтобы облегчить вам дежурство. Я со следующей смены охраны.}
{202}{}{Эштон послал меня к вам. Он сказал, что нужно проверить с вами последние большие пожертвования.}

{210}{}{Аве, мужик - Эй, постой! Я никогда не видел вас раньше. Что вы здесь делаете?}
{211}{}{Я новичок. Я недавно был переведен сюда.}
{212}{}{Да, мне было поручено убить Вас.}

{220}{}{Черт возьми. У меня нет времени на это дерьмо, моя смена почти закончилась.}
{221}{}{Смотри, он кажется очень пьяный. Я не заставлю себя ждать.}

{230}{}{Ах, черт возьми. Хорошо. Смотри за вещами, пока я отойду. Я вернусь через несколько минут.}
{231}{}{Не проблема.}

{240}{}{Новичок, да? Мы получаем таких здесь время от времени. Довольно скучная работа обеспечивать безопасность здесь, если вы конечно спросите меня.
 Это лучше, чем заниматься рекрутированием, поэтому я не жалуюсь. Хорошо иметь вас на борту.}
{241}{}{Спасибо. Итак, я бы не стал держать Эштона в ожидании, раз уж я пришел.}
{242}{}{Я ценю приветствие. Так вы заинтересованы смениться пораньше?}

{250}{}{Конечно блин, почему нет? Ничего захватывающего не происходит здесь в любом случае. Увидимся.}
{251}{}{береги себя.}

{260}{}{Новобранец? Фигня. Подкрепления сюда слишком редки. Похоже, у нас тут крыса. Какая удача!}

{300}{}{Что за нахуй! Эштон никогда не хотел меня видеть. Я не знаю, какого черта происходит, но нет записей о вас, направленном сюда. Как мне кажется, мы заполучили злоумышленника прямо в руки
 - Скоро будет мертвый злоумышленник}

{400}{}{Уооу, что, черт возьми, вы думаете сделать!? Попытаетесь обокрасть нас, прямо на моих глазах... Срань господня, ты тупица. Наконец-то я кого-нибудь убью.}

{401}{}{Уооу, что, черт возьми, вы думаете сделать!? Это частная собственность, так что не прикасайтесь к этой вещи. Это первое и последнее предупреждение.}

{402}{}{Я вас предупреждал. Пытаетесь обокрасть нас, прямо на моих глазах... Срань господня, ну ты тупица. Наконец-то я кого-нибудь убью.}

