###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите человека с мощным оружием.}
{101}{}{Вы видите члена торгово-оборонительного отряда Брокен Хиллс.}
{102}{}{Вы видите человека с мощным оружием, покрытого дорожной пылью.}
{103}{}{Слушай, еще одна банда этих романтиков с большой дороги -- и в следующий раз я надену динамитный пояс.}
{104}{}{Конечно, в караванах нам бы не помешала помощь.}
{105}{}{Эх-хо-хо... Патруль Единства, тоже мне. Как достало.}
{106}{}{Потом вижу - дикарь тащится, и... ладно, проехали.}
{107}{}{Еще раз услышу шуточку про "Радужный патруль", точно кого-нибудь убью.}
{108}{}{Я боюсь, что если бандиты станут еще чуточку злее, через год мы все будем мертвы.}
{109}{}{Из какой занюханной деревни берутся такие, как ты?}
{110}{}{Угостишь выпивкой рабочего человека?}
{111}{}{Я слишком устал от работы в караване, чтобы болтать.}
{112}{}{Если тебе нужно что-нибудь -- поговори с Биллом, снабженцем.}
{113}{}{Тебе не кажется, что все наши попытки цивилизовать пустоши не очень-то приближают нас к нашей цели?}
{114}{}{Достали меня все эти трения между людьми и мутантами. Мы разве не должны подавать пример?}
{115}{}{Чего надо? Не видишь, что ли -- я отдыхаю!}
{116}{}{Когда отправляется следующий караван?}
{117}{}{Патруль, патруль, патруль... и это все, что мне достается здесь.}
{118}{}{Думаю, мне не помешает вздремнуть.}
{119}{}{Я заслуживаю повышения. Это опасная работа.}

###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{200}{}{Вам помочь?}
{201}{}{Да, я ищу хозяина каравана.}
{202}{}{Мне было интересно, если бы я мог бы задать вам несколько вопросов о Чаде.}
{203}{}{Кто ты?}
{204}{}{Нет, спасибо.}
{205}{}{В таком случае, вы захотите поговорить с Биллом, экипировщиком Брокен Хиллс. Он находится внутри вон того здания.}
{206}{}{У меня есть еще вопросы.}
{207}{}{Спасибо. Пока.}
#About Chad...
{208}{}{У вас есть вопросы, может быть, у меня есть ответы. Чего вы хотите знать?}
{209}{}{На кого он похож?}
{210}{}{Можно ли ему доверять?}
{211}{}{Где он получает свои деньги?}
{212}{}{Какова его история?}
{213}{}{Забудьте об этом. Увидимся позже.}

{214}{}{Я? Я }
{215}{}{. Я охраняю караваны Билла. Что-нибудь еще?}

{216}{}{На кого похож? Ну, он дружелюбный, но жестокий. Он хороший хозяин, и, как правило справедлив к нам.
 Он не относиться к нам плохо или типа того, если вы это имели в виду. Есть еще вопросы?}
{217}{}{Ну, он немного скрытный, я думаю, но ведь так и большинство людей в эти дни. Другие вопросы?}
{218}{}{Я всегда отчасти предполагал, что он привез их с собой - и довольно много. О таких вещах обычно не спрашивают, вы же знаете. Есть еще вопросы?}
{219}{}{Я не знаю его истории. Я имею ввиду, что почти все из охраны каравана - карьеристы, которые прибыли сюда работать. Он другой, он должен был быстро освободить какое - нибудь новое место.. Еще вопросы?}
{220}{}{Да.}
{221}{}{Нет.}
{222}{}{Все в порядке, увидимся позже.}
{223}{}{Пока.}

{300}{}{Хатч}
{301}{}{Старк}
{302}{}{Дарин}
{303}{}{Миша}
{304}{}{Гарри}
{305}{}{Джейк}
{306}{}{Метт}
{307}{}{Тед}
{308}{}{Клей}
{309}{}{Скотт}
{310}{}{Престон}
{311}{}{Эдди}
{312}{}{Джон}
{313}{}{Макс}

{400}{}{Тауни}
{401}{}{Ким}
{402}{}{Урс}
{403}{}{Сьюзан}
{404}{}{Синди}
{405}{}{Джен}
{406}{}{Лизу}
{407}{}{Баффи}
{408}{}{Хезер}
{409}{}{Кейти}
{410}{}{Лори}
{411}{}{Мери}
{412}{}{Джули}
{413}{}{Сару}

{450}{}{Вы видите }
{451}{}{, охранника каравана.}

