###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите человека, одетого в робы.}
{101}{}{Вы видите Эштон. Он главный здесь.}
{102}{}{У него ухмылка на лице.}

{200}{}{Привет. Меня зовут Эштон, и Я отвечаю за все здесь. Вы были посланы сюда для усиления безопасности?}
{201}{}{Да, собственно, это так.}
{202}{}{Нет, я был послан AHS-9, чтобы проверить все.}

{210}{}{Отлично! Никогда не бывает слишком много охраны для того, что мы храним здесь, говорю я. Хорошо, что ты здесь.}
{211}{}{В самом деле? Это... интересно. Вы можете посмотреть вокруг, конечно. Я уверен, вы увидите, что все в порядке.}

{220}{}{Спасибо. Что именно мы храним здесь?}
{221}{}{Ну, хорошо. Увидимся.}

{230}{}{Как вам конечно известно, все пожертвования церкви хабологии за последние несколько десятилетий хранятся здесь - и я должен сказать, это большая тайна.
 Некоторые пожертвования малы, другие довольно большие. Мы получаем все виды вещей, оружие и боеприпасы, ювелирныя изделия и антиквариат, и даже несколько старых автомобилей.
 К примеру, только несколько месяцев назад, актер Дон Раволта пожертвовал подлинный спортивный мотоцикл Харлей 20-го века - лучшее из своего времени.
 Черт, церкви была даже пожертвована рабочая гаубица. Однако наши основные пожертвования это деньги - много и много денег.}

{240}{}{Впечатляет. Кажется, что Церковь сама по себе живет хорошо.}
{241}{}{Да, конечно, - и не зря. Рекламные кампании и огромные космические челноки не дешево стоят, вы знаете.}

{242}{}{Да, я могу себе представить. А насколько велико это место?}
{243}{}{Я знаю, что вы имеете в виду. Ну, мне пора. Пока.}

{250}{}{Строение где мы стоим старше бункера, построенного, вероятно, для частного использования, а не военного. Есть два уровня ниже нас. 
 Прямо под нами жилая территория - там несколько кроватей, ванная комната, тренажеры, оборудование для обеспечения безопасности. А еще ниже то, что я называю "убежище".}
{251}{}{Убежище?}
{252}{}{Это не *убежище* на самом деле, я просто так назвал. Это скорее комната для хранения, полная товаров. Вот где мы держим все пожертвования. Она охраняется весь день, каждый день.}

{260}{}{Интересно. Ну, я пойду, посмотрю вокруг. Увидимся позже.}

{270}{}{Так насколько велико это место?}

{300}{}{Здравствуйте еще раз. Помочь вам с чем-нибудь?}
{301}{}{Нет, просто смотрю. Пока.}

