###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы открываете шкаф и находите стопки файлов и заметок.}
{101}{}{Обыскать комод.}
{102}{}{Уйти.}
{103}{}{При поиске по записям в комоде, вы заметили тонкий кожаный портфель тщательно глубоко задвинутый.}
{104}{}{Вытянуть портфель.}
{105}{}{Игнорировать и продолжить поиск.}
{106}{}{30 минут проходят, и вы не находите ничего важного. Все, что вы узнали, это то, что Чад записывал и документировал каждый момент своей жизни.
 Он довольно скучный парень на самом деле. И когда вы собираетесь закрыть ящики, вы слышете кашель от входной двери и ручка поворачивается...}
{107}{}{Вытянуть портфель.}
{108}{}{Внутри портфеля вы находите документированные целые годы работы по обкрадывания караванов Чадом.}
{109}{}{Ничего себе, это действительно показывает как Чад тырил деньги. Видимо, он готовится покинуть город, лучше показать Маркусу все это.}
{110}{}{30 минут проходят, и вы не находите ничего важного. Все, что вы узнали, это то, что Чад записывал и документировал каждый момент своей жизни.
 Он довольно скучный парень на самом деле.}

