###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{¬ы видите дерев€нную дверь.}
{101}{}{Ёта дверь сделана из цельного куска дерева.  ажетс€, там встроен новый замок.}

{102}{}{Ёта дверь плотно закрываетс€.}
{103}{}{»спользу€ технологию, которую вы узнали от ћакса, вы тщательно заглушили спусковой механизм и легко взломали дверь.}
{104}{}{Ётот замок чем-то отличаетс€. ¬ы решили оставить его в покое.}

{105}{}{¬ы собираетесь приступить к работе по вскрытию замков, когда вы замечаете маленькиц спусковой механизм в замке.
 ѕри срабатывании, вы больше никогда не были бы в состо€нии взламывать двери. ¬ы умело удал€ете его, а затем за несколько секунд взламываете дверь.}

#added in RP 2.1
{106}{}{Ёто даже не оставит царапин на двери.}

