###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите прочную металлическую дверь.}
{101}{}{Этот тип дверей используется в банковских сейфах. Она выдержит несколько взрывов динамита. Она заперта.}
{102}{}{Этот тип дверей используется в банковских сейфах. Она выдержит несколько взрывов динамита. Она не заперта.}

#added in RP 2.1
{110}{}{Взрыв расшатывает дверь. Хотя петли сильно ослабли, дверь остается на месте.}
{111}{}{Дверь разносит на куски. От нее ничего не осталось.}

