###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{¬ы вошли в заброшенный район, усе€нный мертвой растительностью.  ѕеред вами стоит большой, хорошо укрепленный бункер.}

