# 0. QUICK LOOK
###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите Крадущуюся Тень.}
###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{101}{}{Вы видите Тень-Что-Ходит.}

# 0. LOOK
###.Magnat.###...Original 1C translation. Need no correction...########################
{150}{}{Вы видите мускулистого дикаря с черными татуировками на лице. Он молча смотрит на вас.}
{151}{}{Вы видите Крадущуюся Тень. Его лицо густо покрыто ритуальными татуировками.}

# 1. CLICK ON HIM (WTG) -- if he tells you to go away, or you exit dialog early, this is all that will be displayed
{200}{}{Он просто молча смотрит на вас.}
{201}{}{Он молча смотрит на вас.}

# WABBITS
{300}{}{Тссс... я охочусь на кволиков.}

#added by killap - expansion
#[Node001]
###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{400}{}{[Он смотрит на вас недоверчивым взглядом.] Кто идет?}
{401}{}{Меня зовут }
{402}{}{. Кто ты?}
{403}{}{У меня задание от Vault City. Кто ты?}
{404}{}{Мое имя не имеет значения. Я пришел, чтобы предупредить тебя. Ты находишься в большой опасности!}
{405}{}{Я твое возмездие. Приготовься присоединиться к своим предкам!}
{406}{}{Я француз. Почему вы думать, у меня это возмутительно акцент? [Смотрите на него осуждающе.]}
{407}{}{Не важно. Извините, что беспокою вас.}

#[Node002]
#From [Node001]
{410}{}{Ты говоришь с Идущим в Тени. Зачем ты пришел сюда?}
{411}{}{Я пытаюсь остановить рейдерские атаки на Город Убежище, и у меня есть основания полагать, что это база рейдерских операций. Что ты знаешь о рейдерах?}
{412}{}{Я был послан Городом из-за рейдеров, для нападения на них.}
{413}{}{Мне было просто интересно что это за место, но я уже ухожу.}
{414}{}{Я хочу попрактиковаться в стрельбе, а вы похоже стали бы превосходной движущейся мишенью.}

#[Node003]
#From [Node002]
{420}{}{Идущий В Тени не знает никаких рейдеров. Идущий В Тени знает только несколько Рейнджеров, которые хотят освободить рабов из Города Убежища, такого ужасного места. [Он дает описание человека, которое соответствует одному из налетчиков.]}
{421}{}{Это они сказали тебе, что они Рейнджеры? На много миль вокруг нет ни одного Рейнджера, они лгут.}
{422}{}{Рейнджеры? Это не Рейнджеры. Просто посмотрите на их одежду. Ты пешка в их игре. Они просто используют тебя.}
{423}{}{Послушай, я был послан Городом убежищем, чтобы найти рейдеров. Эти люди соответствуют описанию.}
{424}{}{Хорошо. Я думаю, что надо идти.}
{425}{}{Я тебе не верю. Умри, ты, злой человек!}

#[Node004]
#From [Node003]
{430}{}{Почему они лгут Идущему В Тени?}
{431}{}{А ты бы помог им, если бы они сказали, что они были налетчиками, нападавшими на мирных людей, и что они ни капли не заботились о помощи кому-нибудь в Городе Убежище?}
{432}{}{Я не знаю. Это жесткий мир. Люди постоянно охотятся на себе подобных.}
{433}{}{Чтобы хорошо посмеяться, наверное. Ты выглядишь настолько глупым, чтобы верить всему.}

#[Node005]
#From [Node004]
{440}{}{Идущий В Тени никогда не будет помогать делать зло. [Он смотрит на вас подозрительно.] Но почему Идущий В Тени должен доверять тому, что ты говоришь?}
{441}{}{[рассказать ему о вашем племени.]}
{442}{}{Потому что я Рейнджер, самый настоящий. [Показать ему свой значок.]}
{443}{}{Потому что я знаю, на кого эти рейдеры работают, и он совсем не хороший человек. [Показать ему данные с голодиска]}
{444}{}{Я не знаю. Извини, что трачу твое время.}
{445}{}{Ты и не должен, я убью тебя в любом случае.}

#[Node006]
#From [Node005]
{450}{}{[Идущий В Тени кажется смотрит на вас иначе, более доверчивм взглядом.] Теперь Идущий В Тени знает, что ты говоришь истину. Идущий В Тени доверяет тебе.}
{451}{}{Ну, что ты собираешься делать теперь?}
{452}{}{У тебя есть идеи, почему эти рейдеры атакуют Город?}
{453}{}{Это смешно, я лгал тебе все время. Как тебе это, идиот?}

#[Node007]
#From [Node006]
{460}{}{Нет, я не знаю. Только знаю, что они обманом заставили Идущего В Тени помогать им.}
{461}{}{Ну, что ты собираешься делать теперь?}
{462}{}{Не слышал ли ты, как они произносят какие-нибудь имена или что-нибудь подобное?}
{463}{}{Ну, ничего, я просто убью их всех. И я думаю, что для разминки я сначала убью тебя...}

#[Node008]
#From [Node007]
{470}{}{Хм ... Может быть. Когда некоторые из них пошли получать больше шумного, странного оружия... [Он делает жест, как буд-то использует винтовку]... они упоминали имя... Бишоп. Да, они говорили о человеке по имени Бишоп.}
{471}{}{Понятно. Ну, спасибо, Идущий В Тени, ты был очень полезен.}
{472}{}{Хорошо. Теперь, когда у меня есть информация, я хочу просто раздавить эту кучку вредителей, начиная с тебя...}

#[Node009]
#From [Node008]
{480}{}{Идущий В Тени благодарит тебя, Идущему В Тени не нравится заблуждаться.}
{481}{}{Всегда пожалуйста. Что же теперь?}
{482}{}{О, действительно? А вот я, думаю, что использовал тебя как всех остальных. Ты такой же идиот, как и все...}

#[Node010]
#From [Node009]
{490}{}{Идущий В Тени больше никому не помогает. Идущий В Тени пойдет домой, и не будет показываться злым людям на пути.}
{491}{}{Хорошо. Это должно остановить злых людей от причинения вреда невинным в Городе-Убежище.}

#[Node011]
#From [Node010]
{500}{}{Идущий В Тени благодарит тебя, друг, за открытие всей правды. Может духи покажут тебе путь.}
{501}{}{И тебе.}

#[Node012]
#From [Node001]
{600}{}{[Его лицо темнеет.] Это злое место. Зачем Идущему В Тени слушать того, кто пришел из злого Города?}
{601}{}{Тени - это все, что останется от тебя, если ты не будешь слушаться.}
{602}{}{Я пришел не для того, чтобы слушать. Я пришел сюда, чтобы сделать тебя мертвым.}

#[Node013]
#From [Node012]
{610}{}{[Он осторожно изучает тебя.] Идущий В Тени будет слушать. Теперь, почему ты здесь?}
{611}{}{Город-Убежище находится под сильным огнем, а охранники не смогли выяснить, кто на самом деле атакует и каковы их намерения.}
{612}{}{Ну, я не много могу сказать тебе, так что пусть мои кулаки говорят за меня.}

#[Node014]
#From [Node013]
{620}{}{А почему Идущий В Тени должен думать, что это плохо? Они получат то, чего они заслуживают, а Идущий В Тени с удовольствием, когда победит, освободит их "слуг".}
{621}{}{Так ты поддерживаешь тех, кто нападает на них?}
{622}{}{Ну, я не думаю, что позволю тебе прожить достаточно долго, чтобы это произошло.}

#[Node015]
#From [Node014]
{630}{}{Идущий В Тени покажет им путь в Город Убежище и обратно. Идущий В Тени очень важен для них, необходим для них, чтобы найти путь.}
{631}{}{Ну что ж, тогда я просто убью тебя, и нападения должны прекратиться.}
{632}{}{Ты имеешь в виду *был* важен, не так ли? Я пытаюсь сказать, что ты умерешь сейчас же, от моей руки.}

#[Node016]
#From [Node015]
{640}{}{[Страх медленно заполняет его лицо, и он начинает отступать.] Пожалуйста, нет! Идущий В Тени не хочет умирать!}
{641}{}{Тогда покинь это место и этих люди, на совсем. Я буду считать до десяти, и если ты не уйдешь, ты присоединишься к твоим предкам на небесах. РАЗ...}
{642}{}{Слишком поздно, мой милый дикарь. Ты присоеденишься к своим предкам через... 12 секунд.}

#[Node017]
#From -- any failure
{800}{}{Идущий В Тени тебе не верит. Идущий В Тени прервет разговор. До свидания.}
{801}{}{[Конец]}
{802}{}{Не поворачивайся ко мне спиной, дикарь. Я говорю с тобой.}

#[Node018]
#From -- any failure
{810}{}{Как ты смеешь угрожать Идущему В Тени. Уходи сейчас же.}
{811}{}{[Уйти]}
{812}{}{[Атаковать]}

#[Node019]
#From -- a threaten failure
{700}{}{(дикарь тихо смотрит на вас)}
{701}{}{[Смотреть в глаза]} #20% chance to work
{702}{}{[Атаковать]}
{703}{}{Меня зовут }
{704}{}{. Кто ты?}
{705}{}{У меня задание от Vault City. Кто ты?}
{706}{}{Мое имя не имеет значения. Я пришел, чтобы предупредить тебя. Ты находишься в большой опасности!}
{707}{}{Не важно, я уже ухожу.}
{708}{}{Я не хочу больше говорить с тобой, ты пустоголовый корм для скота! Я срать на тебя хотел! Твоя мать была хомяком, от твоего отца пахло бузиной!}

#[Node020]
#From [Node019]
{710}{}{(дикарь продолжает тихо смотреть на вас)}
{711}{}{[Смотреть в глаза]} #10% chance to work
{712}{}{[Атаковать]}
{713}{}{Меня зовут }
{714}{}{. Кто ты?}
{715}{}{У меня задание от Vault City. Кто ты?}
{716}{}{Мое имя не имеет значения. Я пришел, чтобы предупредить тебя. Ты находишься в большой опасности!}
{717}{}{Не важно, я уже ухожу.}
{718}{}{Я не хочу больше говорить с тобой, ты пустоголовый корм для скота! Я срать на тебя хотел! Твоя мать была хомяком, от твоего отца пахло бузиной!}

#[Node021]
#From [Node020]
{720}{}{(дикарь продолжает тихо смотреть на вас. Очевидно он становится нетерпеливым.)}
{721}{}{[Смотреть в глаза]} #0% chance to work
{722}{}{[Атаковать]}
{723}{}{Меня зовут }
{724}{}{. Кто ты?}
{725}{}{У меня задание от Vault City. Кто ты?}
{726}{}{Мое имя не имеет значения. Я пришел, чтобы предупредить тебя. Ты находишься в большой опасности!}
{727}{}{Не важно, я уже ухожу.}
{728}{}{Я не хочу больше говорить с тобой, ты пустоголовый корм для скота! Я срать на тебя хотел! Твоя мать была хомяком, от твоего отца пахло бузиной!}

#dumb dialog
#[Node022]
{850}{}{Кто идет?}
{851}{}{Тссс... Я охочусь.}
{852}{}{ХеееХеее! ХеХе... Хе... У тебя красивое личико, как на фотографии... Хеее!}

#path 4
#[Node023]
#From [Node001]
{900}{}{Идущий В Тени не понимает. Что ты имеешь в виду?}
{901}{}{Ты в огромной опасности! Просто скажите, что ты здесь делаешь. Мне нужно знать, говорю ли я с нужным человеком.}
{902}{}{Ух, злые духи идут за тобой.}
{903}{}{Опасность в том, что я здесь, чтобы убить тебя.}

#[Node024]
#From [Node023]
{910}{}{Идущий В Тени разведчик. Идущий В Тени водит этих Рейнджеров через горы. Воины могут потеряться, если они не знают пути через горы.}
{911}{}{Тогда это действительно ты! Моя Старейшина послала меня сказать тебе, что что-то страшное постигнет тебя.}
{912}{}{Это они сказали тебе, что они Рейнджеры? На много миль вокруг нет ни одного Рейнджера, они лгут.}
{913}{}{Рейнджеры? Это не Рейнджеры. Просто посмотрите на их одежду. Ты пешка в их игре. Они просто используют тебя.}

#[Node025]
#From [Node024]
{920}{}{Что!? Идущий В Тени понимает. Почему старейшина говорила такие вещи?}
{921}{}{Послушай меня! Наша Старейшина предвидела твою смерть. Когда в следующий раз ты оставишь эту пещеру, чтобы провести этих людей через горы, ты не вернешься живым. Ты должен уйти отсюда сейчас же или злые духи заберут тебя.}
{922}{}{Ты сомневаешься в словах Старейшины?}

#[Node026]
#From [Node025]
{930}{}{П-почему... Почему Идущий В Тени должен тебе верить? Как старейшина может предвидеть такие события?}
{931}{}{Ну... Она разок смотрела этот фильм раз... Нет, нет... Ух, она играла в эту видеоигру... MMMMM... Да! Она называется Фал-...}
{932}{}{Она пила этот напиток, он пахл очень сильно, и яркие грезы пришли к ней.}
{933}{}{Кость в ее носу. Так она общается с нашими предками.}

#[Node027]
#From [Node026]
{940}{}{Ты лжешь. Это не похоже на переговоры с духами. Теперь Идущий В Тени увидит, как язык лжеца сочетается по вкусу с его любимым соусом Брока.}
{941}{}{[СДЕЛАНО]}

#[Node028]
#From [Node026]
{950}{}{Ох, тогда ты точно говоришь правду. Идущий В Тени знает силу духов. Что теперь делать Идущему В Тени?}
{951}{}{Ну, я говорил с ними, и они сказали мне, что они тебя очень не любят. Они попросили меня убить тебя.}
{952}{}{Ты должен уйти отсюда навсегда и никогда не водить этих людей снова. духи злятся на тебя за проведение этих мужчин через горы. Молись духам ежедневно и только тогда их гнев смягчится.}

#[Node029]
#From [Node028]
{960}{}{Идущий В Тени подчиняется. [Идущий В Тени бежит к лестнице, ведущей наружу]}
{961}{}{Приветствую тебя, Бегущий В Тени.}

#convince SWW to leave
{1000}{}{Вы подорвали силы рейдеров. Они больше не будут в состоянии совершать налеты в регионе.}
{1001}{}{Подождать день или два, и я уверен, что эти рейдеры уйдут из этого места. Тогда я смогу осмотреть все в поисках информации.}


###.Magnat.###...Added by 1C. May be: a)for female characters (require proper scripts); or b) absent in English version...########################
# 1. CLICK ON HIM (WTG)
