###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Ёто странно. Ќа этих браминах разные знаки. ѕохоже, что кто-то неловко поставил новое клеймо поверх того, что было до этого.}

