###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите деревянную дверь.}
{101}{}{Дверь, похоже, заперта на крепкий замок.}
{102}{}{Дверь незаперта.}

