###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы входите в туннелели под районом Трапперов. Запах крысиного помета очень сильный.}
{101}{}{Взрыв повреждает поддерживающие распорки и лавина породы сыпется сверху. Пока это происходит, вы слышите громкий треск и эхо по всей пещере. Вы смотрите вокруг и видите, что другие столбы поддержки ослабли и начинают уступать.}
{103}{}{Вы поймали в ловушку Крысиного Короля! Без выхода, голод - это все, что осталось для его удовольствия.}
{104}{}{Мне лучше выйти из-под этих поддержек, прежде чем меня задавит или зажмет в ловушке.}
{105}{}{Другая опора сминяется и лавина породы сходит вниз.}

