# 0. LOOK (WTG)
###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите Монте Три Карты.}
###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{101}{}{Вы видите раздающего.}

# 0. LOOK (WTG)
###.Magnat.###...Original 1C translation. Need no correction...########################
{150}{}{Вы видите высокого, очень худого старика с дочерна загорелым лицом. Он настолько худой, что кажется, будто он сделан из хвороста.}
{000}{}{Вы видите Монте Три Карты. Он осматривает улицу, вас и кивает.}
{000}{}{Вы видите Монте Три Карты. Он осматривает улицу, вас и кивает.}

# 1. FLOAT (MONTE_BEATEN] (WTG)
{200}{}{Не понимаю, как это меня угораздило проиграть...}
{000}{}{Просто проходи мимо... Монте сегодня не работает.}
{000}{}{Неужели я спрятал не ту карту?}
{000}{}{Как этому глупому дикарю удалось все время выбирать верную карту?}

# 3. FLOAT [FALLOUT2 = ENCLAVE_DESTROYED] (WTG)
{205}{}{Э-э-эй! Герой! Ты в порядке, ты ничего.}
{000}{}{::Показывает вам два больших пальца::}
{000}{}{::Улыбается, кивает::}
{000}{}{А ты молодец, герой. Ты молодец.}

# 4. FLOAT [NO CARDS] (WTG)
{215}{}{Где, черт дери, мои карты? Они ТОЛЬКО ЧТО здесь были.}
{000}{}{Чертов домовой, уже и до моих игральных карт добрался.}

# 5. FLOAT [GENERIC] (WTG)
{220}{}{Эй, приятель, даже не думай ходить в казино. Сыграй лучше с Монте.}
{000}{}{Хочешь испытать удачу, приятель? Лучшие ставки во всем Нью-Рино! Ну давай...}
{000}{}{Эй, приятель. Тебе, похоже, сегодня повезет, подходи сюда.}
{000}{}{Кто-нибудь хочет сыграть? Деньги за бесплатно, деньги за бесплатно!}
{000}{}{Подходи и играй. Только вчера один парень выиграл у меня 50 монет. Все очень просто.}
{000}{}{Все очень просто. Отгадай, где дама, где красная дама, и ты выиграл. Вот так все просто.}
{000}{}{У тебя аллергия на легкие деньги? Тогда подходи сюда.}
{000}{}{Сегодня выигрывают все... ты тоже хочешь выиграть?}
{000}{}{В казино одни жулики, обдирают тебя как липку... Монте - честный игрок, с ним все по правилам.}
{000}{}{Хочешь испытать удачу, леди? Лучшие ставки во всем Нью-Рино! Ну давай...}
{000}{}{У тебя аллергия на легкие деньги, леди? Тогда подходи сюда.}
{000}{}{Эй, леди. Тебе, похоже, сегодня повезет, подходи сюда.}
{000}{}{Эй, леди, даже не думай ходить в казино. Сыграй лучше с Монте.}

# 7. PLAYING CARDS GONE (WTG)
{000}{}{(Старик улыбается, и вокруг его глаз образуются морщинки.) Хочешь сыграть, герой?}

# 8. INTRO (WTG)
{000}{}{(Монте улыбается, и вокруг его глаз образуются морщинки.) Хочешь сыграть, друг мой?}
{000}{}{(Монте улыбается, и вокруг его глаз образуются морщинки.) Хочешь сыграть, девочка?}
{000}{}{(Монте улыбается, и вокруг его глаз образуются морщинки.) Хочешь сыграть, герой?}
{000}{}{Если Монте Три Карты встречаешь, то в три карты с ним и играешь. 20 монет кидай и сразу приступай.}
{000}{}{Твоя жулик. Твоя нечестно играть.}
{000}{}{Ланна вот бабки, моя не знать скоки 20, вота куча.}
{000}{}{Э, моя рада слова но моя не хотеть с тобой ниче делать... пока-а-а.}
{000}{}{Хиляй отсюда}
{000}{}{Я не буду играть с таким жуликом, как ты.}
{000}{}{Э, к чему приступать?}
{000}{}{Я знаю правила игры. Вот 20 монет. Давай сыграем.}
{000}{}{Монте Три Карты, а? Ты кладешь три карты рубашкой наверх, перетасовываешь их, а я выбираю карту. Если это правильная карта (которой она быть никак не может, так как ты спрятал ее в руку, пока мешал карты), значит, я выигрываю. Нет, спасибо, приятель.}
{000}{}{Монте Три Карты, а? Ты кладешь три карты рубашкой наверх, перетасовываешь их, а я выбираю карту. Если это правильная карта (которой она быть никак не может, так как ты спрятал ее в руку, пока мешал карты), значит, я выигрываю. Нет, спасибо, приятель.}
{000}{}{Не сегодня, спасибо.}
###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{248}{}{Трех-Карточный Монте? Ты кладешь три карты рубашкой вниз, перемешиваешь и я выбираю одну. Если я угадал - чего не может быть, так как ты их подменил - то я выиграл. Нет, спасибо.}
{249}{}{Трех-Карточный Монте? Ты кладешь три карты рубашкой вниз, перемешиваешь и я выбираю одну. Если я угадал - чего не может быть, так как ты их подменил - то я выиграл. Нет, спасибо.}
###.Magnat.###...Original 1C translation. Need no correction...########################
{250}{}{К чему приступать? К игре, конечно!}

# 9. UH, GET DOWN TO WHAT? (8)
{000}{}{Видишь... (показывает тебе три карты) одна из них - дама. Я кладу их рубашкой вверх, перетасовываю, а затем ты говоришь, где дама. Если это и правда дама, ты выигрываешь.}
{000}{}{Так все просто, приятель.}
{000}{}{Так все просто, леди.}
{000}{}{Я не буду играть с таким жуликом, как ты.}
{000}{}{Не мог бы ты повторить правила?}
{000}{}{Кажется, все и правда довольно просто. Давай сыграем. Вот 20 монет.}
{000}{}{Не сегодня, спасибо.}
###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{258}{}{Не сегодня.}

# 10.  PLAYING, BASIC CHEATING (8, 9, 11)
###.Magnat.###...Original 1C translation. Need no correction...########################
{260}{}{(Вы выкладываете деньги. Монте кивает, показывает вам карты, затем переворачивает их рубашкой вверх и в течение нескольких секунд мешает их.)}
{000}{}{Итак... которая из них дама, приятель?}
{000}{}{Итак... которая из них дама, леди?}
{000}{}{(Вы думаете, что это левая карта.)}
{000}{}{(Вы думаете, что это карта посередине.)}
{000}{}{(Вы думаете, что это правая карта.)}
{000}{}{(Вы не знаете. Слишком уж быстро он тасовал карты.)}
{000}{}{Дева слева}
{000}{}{Картинка в серединке}
{000}{}{Пава справа}
{000}{}{Та, что слева.}
{000}{}{Та, что справа.}
{000}{}{Та, что посередине.}

# 11.  PLAYING, LOST (10, 12, 15)
{280}{}{(Монте переворачивает карту. Это двойка пик.)}
{000}{}{Прости, приятель, на этот раз не повезло. Но ты был так БЛИЗКО.}
{000}{}{Прости, девушка, на этот раз не повезло. Но ты была так БЛИЗКО.}
{000}{}{И у тебя явно есть способности. Хочешь еще раз попробовать?}
{000}{}{Твоя жулик. Твоя нечестно играть.}
{000}{}{Ланна вот бабки, моя не знать скоки 20, вота куча.}
{000}{}{Не-а. ПЛОХОЙ игра ПОКА-А.}
{000}{}{Я не буду играть с таким жуликом, как ты.}
{000}{}{Конечно, вот 20 монет.}
{000}{}{Нет, спасибо.}

# 12.  PLAYING, NOTICE MONTE CHEATING (8, 9, 11, 14)
{300}{}{(Вы выкладываете деньги. Монте кивает, показывает вам карты, затем переворачивает их рубашкой вверх. В это время он прячет в руку одну из карт, проделав это так быстро, что вы едва успеваете заметить. Затем в течение нескольких секунд он мешает карты.)}
{000}{}{Итак... которая из них дама, приятель?}
{000}{}{Итак... которая из них дама, леди?}
{000}{}{Твоя прятать в рукав. Твоя жулик.}
{000}{}{Дева слева}
{000}{}{Картинка в серединке}
{000}{}{Пава справа}
{000}{}{Ах ты чертов ЖУЛИК. Ты спрятал эту карту в рукаве, вот что. Отдай мне мои деньги, а не то через пять минут здесь будет лежать твой труп.}
{000}{}{Та, что у тебя в рукаве.}
{000}{}{Та, что слева.}
{000}{}{Та, что справа.}
{000}{}{Та, что посередине.}

# 13. YOU GODDAMN CHEATER . . . (8, 9, 11, 12, 15)
{320}{}{ЧТО ты сказал, приятель?}
{000}{}{ЧТО ты сказала, леди?}
{000}{}{Ты обвиняешь меня в жульничестве?}
{000}{}{Ага. Моя ЗНАТЬ твоя жулик.}
{000}{}{Не-а! Не-а! Не сердись. Моя пошел.}
{000}{}{Да.}
{000}{}{Пошло все к черту. Подавись своими деньгами. Ноги моей тут больше не будет.}

# 14. YES (13)
{330}{}{Послушай, у меня нет времени успокаивать неудачников. Ты платишь деньги, ты получаешь возможность выиграть. Хочешь СЫГРАТЬ - пожалуйста. Но если ты собираешься при каждом проигрыше так скулить, лучше убирайся!}
{000}{}{МОЯ ТВОЯ ЛОМАЙ БАШКА!}
{000}{}{Не-а! Не-а! Не сердись. Моя пошел.}
{000}{}{С меня хватит. Ты покойник.}
{000}{}{Хорошо, хорошо. Прости меня. Вот 20 монет. Давай сыграем еще раз.}
{000}{}{Пошло все к черту. Подавись своими деньгами. Ноги моей тут больше не будет.}

# 15. PLAYING, SWITCH BUT NOT COMPLETE, MONTE CHEATING (8, 9)
{340}{}{(Вы выкладываете деньги. Монте кивает, затем кидает карты на землю и несколько секунд их перетасовывает.)}
{000}{}{Итак... которая из них дама, приятель?}
{000}{}{Итак... которая из них дама, леди?}
{000}{}{(Монте использует свою обычную колоду! Вам нужно выкрасть другую его колоду, чтобы завершить подмену.)}
{000}{}{Твоя прятать в рукав. Твоя жулик.}
{000}{}{Э...Дева слева}
{000}{}{Э...Картинка в серединке}
{000}{}{Э...Пава справа}
{000}{}{Ах ты чертов ЖУЛИК. Ты спрятал эту карту в рукаве, вот что. Отдай мне мои деньги, а не то через пять минут здесь будет лежать твой труп.}
{000}{}{Та, что у тебя в рукаве.}
{000}{}{Э, та, что слева.}
{000}{}{Э, та, что справа.}
{000}{}{Э, та, что посередине.}

# 16. PLAYING, CHEATED MONTE (8, 9, 17)
{360}{}{(Вы выкладываете деньги. Монте кивает, показывает вам карты, затем переворачивает их рубашкой вверх и в течение нескольких секунд мешает их.)}
{000}{}{(Вы выкладываете деньги. Монте мнется.) Э... ну хорошо... (Монте кладет карты на землю и начинает их мешать.)}
{000}{}{Итак... которая из них дама, приятель?}
{000}{}{Итак... которая из них дама, леди?}
{000}{}{(Монте использует крапленую колоду. Выбирайте любую карту, и вы выиграете.)}
{000}{}{Лево! Лево!}
{000}{}{Право! Право!}
{000}{}{Серединка! Серединка!}
{000}{}{Ну, я не знаю... та, что слева.}
{000}{}{Хммм... может быть, та, что справа?}
{000}{}{Боже, понятия не имею... Кажется, та, что посередине.}

# 17. PLAYING, WON (16)
{375}{}{(Монте переворачивает карту. Это дама червей. От шока он застывает на месте.) А?.. Кхе. Э...}
{000}{}{наверное, ты выиграл, приятель.}
{000}{}{наверное, ты выиграла, леди.}
{000}{}{(Он с большой неохотой отдает вам деньги.)}
{000}{}{Еще раз! Еще раз!}
{000}{}{Пасиб, моя ща пошел.}
{000}{}{Мы будем еще раз играть или как? Давай, Монте. Я только начинаю входить во вкус.}
{000}{}{Что ж, спасибо, Монте. Увидимся.}

# 18. PLAYING, DON'T HAVE ANY MORE CASH (16)
{385}{}{(Монте переворачивает карту. Это дама червей. Он в шоке.) А?... Хе... э...}
{000}{}{наверное, ты выиграл, приятель.}
{000}{}{наверное, ты выиграла, леди.}
{000}{}{Но у меня больше нет денег... (Жалобно на вас смотрит) Чем еще я могу тебе помочь?}
{000}{}{Ниче. Моя просто хотеть ЭКСПА. Пока-пока.}
{000}{}{Что у тебя ЕСТЬ?}
{000}{}{Может, ты знаешь что-то, что мне пригодится?}
{000}{}{Забудь, Монте. На сегодня мы с тобой квиты.}

# 19. WHAT HAVE YOU *GOT?* (18)
{400}{}{(Кажется, его задели за живое.) Э... ну, у меня есть кое-что... но оно стоит НАМНОГО больше, чем тебе удалось выиграть... но все равно...}
{000}{}{Ну? И что же это?}
{000}{}{Если для тебя это стоит больше, чем смерть на Голгофе за неуплаченный должок, это твои проблемы. Но советую тебе как следует над этим подумать.}

# 20. WHY DON'T YOU GIVE ME SOME INFO? (18, 44)
###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{404}{}{Эх.....это зависит от того, что ты хочешь узнать.}
###.Magnat.###...Original 1C translation. Need no correction...########################
{405}{}{Э... хмм... зависит от того, что ты хочешь знать.}
{000}{}{Ты знаешь, кто кинул младшего Райта? Кто устроил ему передоз винта?}
{000}{}{Тебе известно, где можно найти типа по имени Красавчик Ллойд?}
{000}{}{Ты знаешь, где моя машина, Монте?}
{000}{}{Ничего не хочешь мне сказать, что мне следовало бы знать?}

# 21. O.D. ON JET (20)
{415}{}{Э... что ж... послушай, я тебе этого не говорил, но я ставлю на Ренеско, этого засранца, который заведует аптекой в западном районе. Я точно не знаю, продавал ли он парню СПЕЦИАЛЬНО, но он что-то знает. Это все, что я тебе скажу.}
{000}{}{Хорошо, Монте. В таком случае мы в расчете.}

# 22. PRETTY BOY (20)
{420}{}{Э... что ж... (похоже, в нем происходит какая-то внутренняя борьба) ...послушай, я тебе этого не говорил, но на твоем месте я бы проверил подвал Десперадо.}
{000}{}{Хорошо, Монте. В таком случае мы в расчете.}

# 23. KNOW WHERE MY CAR IS? (20)
{425}{}{(Прищуривает глаза и наклоняется поближе к вам.) На твоем месте я бы спросил старого доброго Хулио у входа в город. Мимо него ничего не пройдет... а если и пройдет, значит, это его рук дело, если ты меня понимаешь.}
{000}{}{Хорошо, Монте. В таком случае мы в расчете.}

# 24. GOT ANYTHING YOU THINK I SHOULD KNOW? (20)
{430}{}{Ну... ты знаешь Элдриджа, который заведует оружейным магазином в западном районе? Он говорит, что может усовершенствовать любое оружие, хотя я никогда не видел его за работой. Возможно, тебе стоит осмотреть его заведение повнимательнее... но я тебе этого не говорил.}
{000}{}{Хорошо, Монте. В таком случае мы в расчете.}

# 25. MONTE_BEATEN (WTG)
{435}{}{(Монте нахмуривается при виде вас.) Слушай, я сегодня не играю, ладно? Уходи.}
{000}{}{Можно мне купить эту карточку, что ты показывал мне раньше?}
{000}{}{Мне нужна кое-какая информация...}
{000}{}{Хорошо, Монте. Я уйду... но вернусь, учти.}

# 26.  CAN I BUY THAT CARD? (25, 27)
{440}{}{Не-а. Я с ней ни за что не расстанусь. Точка. Это же НАСТОЯЩАЯ довоенная реликвия... маленький кусочек истории. НИ ЗА ЧТО.}
{000}{}{Ты делаешь мне ЕЩЕ ОДНО предложение? Я же тебе говорил: не продается.}
{000}{}{Как насчет тысячи монет? У меня есть они при себе. Они твои в обмен на эту карточку.}
{000}{}{Даже за 750 монет?}
{000}{}{Как насчет 500 монет?}
{000}{}{250 монет хватит?}
{000}{}{Хорошо. У меня еще остались к тебе вопросы...}
{000}{}{Тогда проехали, Монте. Я ухожу.}

# 27.  NOPE. (26)
{450}{}{Глухота напала, что ли? Этой суммы недостаточно даже для того, чтобы заинтересовать меня.}
{000}{}{Может, я предложу другую сумму?..}
{000}{}{У меня есть еще вопросы...}
{000}{}{Тогда проехали, Монте. Я ухожу.}

# 28.  OKAY. (26)
{460}{}{Ну, она мне не НАСТОЛЬКО дорога. Она твоя, приятель. (Он оглядывается по сторонам, затем нагибается, стаскивает ботинок и отворачивает каблук. Изнутри он достает игральную карту.) Держи. Береги ее.}
{000}{}{У меня есть еще вопросы...}
{000}{}{Спасибо, Монте. Всегда приятно иметь с тобой дело.}

# 29.  WHY DON'T YOU GIVE ME SOME INFO? (25, 26, 27, 28, 30, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43)
{465}{}{(Нахмуривается) Буду я говорить или нет, зависит от того, что ты захочешь узнать. И это будет стоить тебе недешево.}
{000}{}{Ты знаешь, кто кинул младшего Райта? Кто устроил ему передоз винта?}
{000}{}{Тебе известно, где можно найти типа по имени Красавчик Ллойд?}
{000}{}{Ты знаешь, где моя машина, Монте?}
{000}{}{Ничего не хочешь мне сказать, что мне следовало бы знать?}
{000}{}{Тогда проехали, Монте. Я ухожу.}

# 30.  O.D. ON JET, BUYING INFO (29, 31, 42)
{475}{}{Клянусь Голгофой, ни за что я даже не ЗАИКНУСЬ. Отвали.}
{000}{}{Послушай, это дело приносит одни неприятности. Оставь его в покое, хорошо?}
{000}{}{Ты делаешь мне еще одно предложение? Слушай, повторяю еще раз: НЕ БУДУ.}
{000}{}{Тысяча монет. Ну как? У меня деньги с собой.}
{000}{}{Даже за 750 монет?}
{000}{}{Как насчет 500 монет?}
{000}{}{250 монет хватит?}
{000}{}{Э... Голгофа?}
{000}{}{У меня есть еще вопросы...}
{000}{}{Тогда проехали, Монте. Я ухожу.}

# 31.  O.D. ON JET, NO DEAL (30)
{490}{}{(Качает головой.) Ни за что. Разговоры на эту тему могут закончиться чьей-то смертью, и не исключено, что моей. Забудь об этом.}
{000}{}{А если я предложу тебе это...}
{000}{}{У меня есть еще вопросы...}
{000}{}{Тогда проехали, Монте. Я ухожу.}

# 32.  O.D. ON JET, BOUGHT INFO (30)
{495}{}{Э... ну... это же куча денег. (Облизывает губы. Кажется, внутри него происходит отчаянная борьба.... но борьба недолгая.) Послушай, я тебе этого не говорил...}
{000}{}{Понятно. Продолжай.}

# 33.  LLOYD, BUYING INFO (29, 34)
{500}{}{(Недобро усмехается) Может, я и знаю что-нибудь, а может, и нет. Назови свою цену.}
{000}{}{Хорошо... поговорим о цене.}
{000}{}{Как насчет тысячи монет? У меня есть они при себе.}
{000}{}{Даже за 750 монет?}
{000}{}{Как насчет 500 монет?}
{000}{}{250 монет хватит?}
{000}{}{У меня есть еще вопросы...}
{000}{}{Тогда проехали, Монте. Я ухожу.}

# 34. PRETTY BOY, NOPE (33)
{510}{}{Ха! Да на это и ведро говна не купишь. Забудь об этом.}
{000}{}{А если я предложу тебе это...}
{000}{}{У меня есть еще вопросы...}
{000}{}{Тогда проехали, Монте. Я ухожу.}

# 35. PRETTY BOY, SURE (33)
{515}{}{Во-о-от это по-нашему. (Злобно ухмыляется.) Слушай, я тебе этого не говорил, но на твоем месте я бы проверил подвал Десперадо на Девичьей улице. Там очень много "крыс", ну ты меня понимаешь.}
{000}{}{У меня есть еще вопросы...}
{000}{}{Ясно. Спасибо.}

# 36. KNOW WHERE MY CAR IS? (29, 37)
{520}{}{(Пожимает плечами) Может, я и знаю что-нибудь, а может, и нет. Назови свою цену, и возможно, я расскажу тебе что-нибудь.}
{000}{}{Хорошо... поговорим о цене.}
{000}{}{Как насчет тысячи монет? У меня есть они при себе.}
{000}{}{Даже за 750 монет?}
{000}{}{Как насчет 500 монет?}
{000}{}{250 монет хватит?}
{000}{}{У меня есть еще вопросы...}
{000}{}{Тогда проехали, Монте. Я ухожу.}

# 37. KNOW WHERE MY CAR IS? NO (36)
{530}{}{(Прищуривает глаза, наклоняется поближе к вам.) За такие деньги я ничего не знаю.}
{000}{}{А если я предложу тебе это...}
{000}{}{У меня есть еще вопросы...}
{000}{}{Тогда проехали, Монте. Я ухожу.}

# 38. KNOW WHERE MY CAR IS? YES (36)
{535}{}{Вот это дело... (Прищуривает глаза и наклоняется поближе к вам.) На твоем месте я бы спросил старого доброго Хулио у входа в город. Мимо него ничего не пройдет... а если и пройдет, значит, это его рук дело, если ты меня понимаешь.}
{000}{}{У меня есть еще вопросы...}
{000}{}{Хорошо, Монте. Спасибо.}

# 39. GOT ANYTHING YOU THINK I SHOULD KNOW? (29)
{540}{}{(Пожимает плечами) Я многое слышу, многое вижу. За 200 монет, возможно, я могу поделиться своим опытом, если ты меня понимаешь.}
{541}{}{Вот 200 монет.}
{000}{}{Я дам тебе 150.}
{000}{}{100 монет или ничего.}
{000}{}{У меня есть еще вопросы...}
{000}{}{Тогда проехали, Монте. Я ухожу.}

# 40. GOT ANYTHING YOU THINK I SHOULD KNOW? NOPE (39)
{550}{}{У тебя приступ глухоты, что ли? Я СКАЗАЛ, 200 монет, значит, 200.}
{000}{}{Хорошо. Держи 200 монет.}
{000}{}{У меня есть еще вопросы...}
{000}{}{Тогда проехали, Монте. Я ухожу.}

# 41. GOT ANYTHING YOU THINK I SHOULD KNOW? YES (39, 40)
{555}{}{Идет. (Монте наклоняется к вам.) Ну... ты знаешь Элдриджа, который заведует оружейным магазином в западном районе? Он говорит, что может усовершенствовать любое оружие, хотя я никогда не видел его за работой. Возможно, тебе стоит осмотреть его заведение повнимательнее... но я тебе этого не говорил.}
{000}{}{У меня есть еще вопросы...}
{000}{}{Понятно. Спасибо, Монте.}

# 42. GOLGOTHA (30)
{560}{}{Могильник к югу от города. Несет аж до самых небес, так вот.}
{000}{}{О... понятно. Теперь насчет сына Райта...}
{000}{}{Забудь о сыне Райта. У меня есть другие вопросы...}
{000}{}{Хорошо, Монте. Спасибо.}

# 43.  O.D. ON JET, BOUGHT INFO 2 (32)
{565}{}{Ставлю на Ренеско, старого засранца, который заведует аптекой в западном районе. Я точно не знаю, продавал ли он парню СПЕЦИАЛЬНО, но он что-то знает. (Оглядывается) Это все, что я тебе скажу.}
{000}{}{У меня есть еще вопросы...}
{000}{}{Хорошо, Монте. Спасибо.}

# 44. WHY DON'T YOU GIVE ME THAT CARD? (19)
{570}{}{(Он оглядывается, нагибается и стаскивает с ноги ботинок. Он отворачивает каблук и вытаскивает карту... на ней изображен человек в странной шляпе, размахивающий битой.) Ну как? Это настоящая довоенная реликвия.}
{000}{}{Нет, у меня вполне достаточно вещей... Я предпочту кое-какую информацию.}
{000}{}{Э, конечно. Почему бы и нет? Это решит все вопросы между нами.}
###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{573}{}{Извини приятель, нет фишек - нет игры. Возвращайся, у тебя будет больше денег.}
{574}{}{Извини дамочка, нет фишек - нет игры. Возвращайся, у тебя будет больше денег.}
{575}{}{Да, может быть следующий раз тогда.}
{576}{}{Вы быстро подменили карты Трех-Карточного Монте на помеченные.}


###.Magnat.###...Added by 1C. May be: a)for female characters (require proper scripts); or b) absent in English version...########################
{000}{}{(Старик улыбается, и вокруг его глаз образуются морщинки.) Хочешь сыграть, герой?}
{000}{}{(Монте улыбается, и вокруг его глаз образуются морщинки.) Хочешь сыграть, друг мой?}
{000}{}{(Монте улыбается, и вокруг его глаз образуются морщинки.) Хочешь сыграть, девочка?}
{000}{}{(Монте улыбается, и вокруг его глаз образуются морщинки.) Хочешь сыграть, герой?}
{000}{}{Если Монте Три Карты встречаешь, то в три карты с ним и играешь. 20 монет кидай и сразу приступай.}
{000}{}{Твоя жулик. Твоя нечестно играть.}
{000}{}{Ланна вот бабки, моя не знать скоки 20, вота куча.}
{000}{}{Э, моя рада слова но моя не хотеть с тобой ниче делать... пока-а-а.}
{000}{}{Хиляй отсюда}
{000}{}{Я не буду играть с таким жуликом, как ты.}
{000}{}{Э, к чему приступать?}
{000}{}{Я знаю правила игры. Вот 20 монет. Давай сыграем.}
{000}{}{Монте Три Карты, а? Ты кладешь три карты рубашкой наверх, перетасовываешь их, а я выбираю карту. Если это правильная карта (которой она быть никак не может, так как ты спрятал ее в руку, пока мешал карты), значит, я выигрываю. Нет, спасибо, приятель.}
{000}{}{Монте Три Карты, а? Ты кладешь три карты рубашкой наверх, перетасовываешь их, а я выбираю карту. Если это правильная карта (которой она быть никак не может, так как ты спрятал ее в руку, пока мешал карты), значит, я выигрываю. Нет, спасибо, приятель.}
{000}{}{Не сегодня, спасибо.}
{000}{}{Видишь... (показывает тебе три карты) одна из них - дама. Я кладу их рубашкой вверх, перетасовываю, а затем ты говоришь, где дама. Если это и правда дама, ты выигрываешь.}
{000}{}{Так все просто, приятель.}
{000}{}{Так все просто, леди.}
{000}{}{Я не буду играть с таким жуликом, как ты.}
{000}{}{Не мог бы ты повторить правила?}
{000}{}{Кажется, все и правда довольно просто. Давай сыграем. Вот 20 монет.}
{000}{}{Не сегодня, спасибо.}
{000}{}{Проехали, Монте. Мы в расчете. Увидимся позже.}
{10205}{}{Э-э-эй! Подруга! Ты в порядке, ты ничего.}
{10000}{}{А ты молодчина, правда. Ты молодчина.}
{10220}{}{Эй, подруга, даже не думай ходить в казино. Сыграй лучше с Монте.}
{10000}{}{Все очень просто. Отгадай, где дама, где красная дама, и ты выиграла. Вот так все просто.}
{10230}{}{Сегодня Монте не играет, подруга. Мои чертовы карты куда-то запропастились.}
