###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите грязного, лохматого мужчину.}
{101}{}{Его одежда грязная и рваная. Руки и ноги его изцарапаны.}

{150}{}{Гав! Гав. Гав.}
{151}{}{Ох, ты в порядке?}
{152}{}{Ох, ладно. Пока.}
{153}{}{Эй, я думаю что я нашел кое-что, что поможет привести вас в чувство.}
{154}{}{Хм... Похоже, вы страдаете от какого-то неврологического расстройства, возможно эпилепсии. К сожалению, я не могу ничего с этим поделать. Прощайте.}

{160}{}{Гав. Гав гав. Гав.}

{250}{}{Гррррр!}
{251}{}{Грррррррр!}
{252}{}{Гррррррррррр!}
{253}{}{Гррррррр!}
{254}{}{[Пшел прочь]}
{255}{}{Гррррррр! Гррр! Гав!}
{256}{}{(Человек вскакивает и уносится прочь.)}
{257}{}{Кхехе. хорошая собачка...}
{258}{}{Кхехе. Моя супер собачка...}

{300}{}{Гав?}
{301}{}{Да. Послушай внимательно эту серию звуков которую я собираюсь сказать...}
{302}{}{(Вы медленно произносите ряд букв, который вы узнали с компьютера EPA убедившись в правильности произношения каждого символа. Вы закончили читать фразу и оглядываетесь назад на мужчину. Он оглядывается на вас и трясется всем телом как собака пытающаяся отряхнуться после дождя.}
{303}{}{[ДАЛЕЕ]}
{304}{}{Ву- Вуа. Эй, я могу говорить нормально! Вау, это здорово. Что ты со мной сделал?}
{305}{}{Я узнал, что если вы прочитаете определенную серию символов, убедившись в правильном ударении на каждом из них, можно вылечить кого-нибудь от аутизма или эпилепсии.}
{306}{}{Звучит как буд-то вы вешаете мне лапшу на уши,но эй, я говорю, так что должно быть что-то в это есть. Во всяком случае, я на самом деле ценю, что вы сделали. Вот, возьмите эти стимпаки. Я нашел их, когда я обшаривал в поисках еды все эти здания.}
{307}{}{Спасибо. Увидимся.}

{350}{}{Гав!}
{351}{}{Гав! Гав!}
{352}{}{*царапает себя*}

{400}{}{Гав! Кхех, я просто шучу. Еще раз спасибо что вылечили меня.}

{500}{}{Вы вылечили лающего человека.}

{600}{}{*унылый*}
{601}{}{Он смотрит на вас большими испуганными глазами.}

