###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Перед вами }
{101}{}{.}

{150}{}{А на вид ничего такого.}
{151}{}{Он выглядит не особо крутым.}
{152}{}{В детстве его наверняка много били.}


###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{200}{}{Вы видите как бы мускулистого белого человека. Он выглядит таким слабым, что кажется, будто его можно убить одним кусочком пиццы.}
{201}{}{Его челюсть блестит, как стекло.}
{202}{}{Он выглядит так, как будто не простоит и семь секунд на ринге.}
{203}{}{Он выглядит таким слабым, что кажется, будто его можно вырубить одним кусочком пиццы.}

{210}{}{Вы видите приземистого черного человека с толстой квадратной челюстью. Его уши, похоже, были страшно истерзаны.}
{211}{}{Его уши, похоже, были страшно истерзаны.}

{220}{}{Его руки похожи на стволы деревьев.}
{221}{}{Каждая рука похожа на две бочки с бензином.}
{222}{}{Когда он движется, это как океан мышц.}
{223}{}{Он жадно смотрит на ухо.}
{224}{}{Его лицо выглядит как сырая мясная отбивная.}


