###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{ѕо мере приближени€ к телу  оди вы начинаете чувствовать подавл€ющий запах одеколона ƒжулса.}
{101}{}{ѕо мере приближени€ к телу  оди вы начинаете чувствовать отвратительный запах одеколона.}

