###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Эй! Где моя тачка?!}
{101}{}{Куда пропала моя машина?..}

###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{110}{}{М-да. Моя не видеть автомобиля здесь!}
{111}{}{М-да. Моя потерял машинку...}

