#############################################################
#  Message File: obj_dude.msg                               #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: April 14, 1998                                  #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{}
{101}{}{}

#############################################################

{110}{}{Ваши ноги очень чешутся.}
{120}{}{На каждой ступне у вас начало развиваться по неприятному наросту.}
{130}{}{Ботинки стали вам малы; эти наросты просто горят.}
{140}{}{Неприятные наросты на ступнях оформились в полноценные дополнительные пальцы. Ну, хотя бы эта проклятая чесотка прошла.}
{141}{}{Бог мой, это же Бесс!}

{150}{}{Вы приобрели }
{151}{}{ опыта за нахождение ГЭККа.}


{400}{}{Вы не можете понять ничего из текста, но иллюстрации достаточно информативны.}
{500}{}{Вы пристрастились к алкоголю. Жажда алкоголя скоро погубит вас.}


