###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите компьютерный терминал.}
{101}{}{Вы видите терминал голосового интерфейса.}
{102}{}{Перед вами стандартный компьютерный терминал, модифицированный на работу с голосовыми командами.}
{103}{}{Вы осматриваете компьютерный терминал, но не можете найти никаких очевидных неисправностей. Что вы будете делать?}
{104}{}{Стукнуть рукой вот эдак.}
{105}{}{Пнуть в этакое "специальное" местечко.}
{106}{}{Запустить программу диагностики.}
{107}{}{Вскрыть и посмотреть, что внутри.}
{108}{}{Уйти.}
{109}{}{Вы некоторое время разглядываете консоль, прикидывая, куда лучше стукнуть. После того как вы отвесили ему свой лучший "наладочный" удар, монитор несколько раз мигает, затем изображение стабилизируется. Больше никакого эффекта. Что вы будете делать?}
{110}{}{Пнуть в этакое "специальное" местечко.}
{111}{}{Запустить программу диагностики.}
{112}{}{Вскрыть и посмотреть, что внутри.}
{113}{}{Уйти.}
{114}{}{Этот широко распространенный метод ремонта дает два результата. Во-первых, изображение на мониторе на несколько секунд превращается в водоворот красок, затем все приходит в норму. Во-вторых, раздается звук ломающегося металла, и панель, которую вы пнули, падает на пол. Что вы будете делать?}
{115}{}{Запустить программу диагностики.}
{116}{}{Ну что, эта хреновина открылась. Можно и внутрь заглянуть.}
{117}{}{Уйти.}
{118}{}{Вы уверены, что в этой системе не может не быть набора диагностических программ. Однако ввод с клавиатуры, похоже, не работает. Устройство реагирует только на голосовые команды. Что вы будете делать?}
{119}{}{Осталось только заглянуть внутрь.}
{120}{}{Уйти.}
{121}{}{Продравшись сквозь нагромождения кабелей и печатных плат, вы выясняете, что поломка была намеренной. Это саботаж. Одна из печатных плат - модуль распознавания речи - пришла в полную негодность и ремонту не подлежит. Ее необходимо заменить новой. Теперь осталось только найти исправный модуль на замену.}
{122}{}{Готово.}
{123}{}{Готово.}
{124}{}{Вы устанавливаете модуль в терминал. Система работает.}
{125}{}{Чтобы терминал заработал, необходимо установить в него модуль распознавания речи.}
{126}{}{Готово.}
{127}{}{Теперь система в полном порядке.}

{128}{}{Доступ к файлам безопасности, загрузка голографической записи...}

{129}{}{Ты последний, Грутар. Скоро от вашего поганого семени и следа не останется.}
{130}{}{Скажи своему так называемому президенту, что гореть ему за это в огне.}
{131}{}{Как скажешь. Ты не более чем говорящее животное.}
{132}{}{Может, и так, но мы появились в результате ваших экспериментов. Вы дали нам жизнь!}
{133}{}{А теперь я даю вам смерть.}
{134}{}{Унесите труп. Доктор хотел получить образчик.}
{135}{}{Их кровь потечет, как Нил!}

#added by killap - RP
{200}{}{Добро пожаловать, Житель Убежища. Для Вашего удобства этот Vault-Tec терминал был изменен, чтобы реагировать на голосовые команды. Пожалуйста, произнесите вашу команду.}
{201}{}{О, вы меня путаете с кем-то еще. Видите ли, я не Житель Убежища, я Избранный.}
{202}{}{Запусить диагностику.}
{203}{}{Переключить в режим ввода с клавиатуры.}
{204}{}{Доступ к защищенной области.}
{205}{}{Отключиться.}

{210}{}{[Огоньки мигают на терминале, он клацает и пиликает. Через несколько секунд на мониторе появляется текст.] Извините, я не распознал вашу команду. Повторите, пожалуйста, команду, удостоверившись, что вы говорите прямо в микрофон четко и громко. Vault-Tec приносит извинения за неудобства. Спасибо.}
{211}{}{Запусить диагностику.}
{212}{}{Переключить в режим ввода с клавиатуры.}
{213}{}{Доступ к защищенной области.}
{214}{}{Отключиться.}

{220}{}{Пожалуйста, подождите, пока я инициирую диагностические проверки... Vault-Tec ценит ваше терпение... Спасибо за ожидание... Диагностика завершена. Все системы функционируют корректно. Все-таки, вы используете оборудование Vault-Tec.}
{221}{}{Назад.}
{222}{}{Отключиться.}

{230}{}{Переключение в ручной режим интерфейса... ручной режим интерфейса запущен. Для удобства других пользователей, этот терминал автоматически вернется к вокальному режиму интерфейса после того, как вы завершите сеанс. Пожалуйста, введите команду.}
{231}{}{Поиск в базе данных чего-нибудь интересного.}
{232}{}{Отключиться.}

{240}{}{После небольшого поиска, вы обнаруживаете три файла, которые наверняка стоит посмотреть: Инструкция по Выживанию Жителя Убежища (сокращенный вариант), Хроники Убежища 13, журналы Смотрителя Убежища.}
{241}{}{Доступ к Инструкции по Выживанию Жителя Убежища (cокращенный вариант). }
{242}{}{Доступ к Хроникам Убежища 13. }
{243}{}{Доступ к журналам Смотрителя Убежища.}
{244}{}{Отключиться.}

#Vault Dweller’s Survival Guide (Abridged Version)
{250}{}{Добро пожаловать в Убежище-13, последнее из серии сооружений общественной защиты от компании Vault-Tec, вашего лучшего подрядчика, когда речь идет о лучших ядерных убежищах. Vault-Tec – окончательный выбор Америки в производстве подземных жилищ.}
{251}{}{[ДАЛЬШЕ]}
{252}{}{Серия укрытий для выживания под названием "Убежища" была разработана с нуля для обеспечения лучшего шанса на хорошую жизнь после ядерного Армагеддона. Это обязанность каждого американского гражданина изучать и применять навыки, необходимые для комфортной жизни в Убежище. Начать лучше всего с описания вашего нового дома.}
{253}{}{[ДАЛЬШЕ]}

{254}{}{ВАЖНАЯ СТАТИСТИКА УБЕЖИЩА 13
                                    Дата начала строительства: Август 2063 г.
                                    Дата окончания строительства: Март 2069 г.
                                    Начальный бюджет: $400 000 000 000
                                    Конечный бюджет, с прибылью: $645 000 000 000
                                    Общее количество жителей: 1000 (максимальное)
                                    Общее время проживания: 10 лет (максимальное)
                                    Количество жилых помещений: 100 (посменный сон при максимальной заселенности)
}

{2541}{}{Толщина двери: 4 ярда, сталь
                                    Охват земли: 3 200 000 тонн грунта на глубине 200 футов
                                    Компьютерная контролирующая система: Мыслящая машина
                                    Основной источник энергии: Геотермальный
                                    Дополнительный источник энергии: Общие резервные системы на атомной энергии
                                    Потребление энергии: 3,98 миллионов КВт/день
                                    Склады: Полный комплект строительного оборудования, гидропонные фермы, система очистки воды из подземных источников, защитное вооружение для 10 человек, коммуникации, общественно-полезные и развлекающие файлы (на весь срок)}



{255}{}{[ДАЛЬШЕ]}

{256}{}{Чтобы помочь Жителям Убежища записывать информацию (а информация является чрезвычайно ценной; на самом деле, это может быть наиболее ценное оружие, которое мы имеем против конца цивилизации, так что будьте внимательны!) Vault-Tec выбрала RobCo Pip-Boy 2000 от компании RobCo Industries в качестве Личного Информационного Процессора для каждого Жителя Убежища.}
{257}{}{[ДАЛЬШЕ]}

{258}{}{RobCo Pip-Boy 2000 является удобным устройством, которое вы носите на запястье. Это небольшой, особенно по сегодняшним меркам, прибор, и он будет хранить хороший объем информации для вас. И он использует современную супер-люкс графику для загрузки! Пожалуйста, обратитесь к вашему руководству по Pip-Boy для получения дополнительной информации.} 
{259}{}{[ДАЛЬШЕ]}

{260}{}{Ключом к успешному возрождению цивилизации после мировой ядерной войны являются люди. Здесь, в Vault-Tec, мы работаем, чтобы довести каждого мужчину (и женщину) до задачи воссоздания Америки из мертвых.}
{261}{}{[ДАЛЬШЕ]}

{262}{}{Мы считаем, что позитивное отношение является одним из лучших инструментов в нашем распоряжении. Если у Вас возникнут какие-либо трения с другим Жителем Убежища, или отношение просто станет отрицательным, рекомендуется сообщить об этом вашему Смотрителю Убежища. Помните, когда двери опечатаны, слово Смотрителя является законом.} 
{263}{}{[ДАЛЬШЕ]}

{264}{}{Убежище-13 укомплектовано новейшим аварийно-спасательным оборудованием. Вещи в контейнерах смогут поддерживать тысячу людей более 10 лет в удобной и современной обстановке. Когда придет время покинуть Убежище и вернуться к восстановлению Америки, ваши друзья из Vault-Tec предоставили вам все, что вам понадобиться.} 
{265}{}{[ДАЛЬШЕ]}

{266}{}{Спасибо, что нашли время прочитать Инструкцию по Выживанию Жителя Убежища (Сокращенный вариант). Мы в Vault-Tec уверены, что вы полюбите ваше новое подземное жилище.}
{267}{}{Доступ к Хроникам Убежища 13. }
{268}{}{Доступ к журналам Смотрителя Убежища.}
{269}{}{Отключиться.}

#Vault 13 Timeline
{270}{}{Читая хроники с самого начала, вы находите интересным, что не было причин не открывать Убежище спустя 10 лет после Великой Войны, как первоначально было задумано. }
{271}{}{[ДАЛЬШЕ]}

{272}{}{Просматривая дальше, вы не находите ничего интересного вплоть до 2161 года, когда сломался единственный рабочий водяной чип Убежища. Вы чувствуете прилив гордости, когда читаете о своем дедушке, избранном для важной задачи покинуть Убежище и обследовать пустыню в поисках нового водяного чипа. Однако, вам кажется немного странным, что самую почитаемую легенду вашего племени сообщили в одном маленьком абзаце.} 
{273}{}{[ДАЛЬШЕ]}

{274}{}{Продолжая читать хроники, вы узнали об успехе вашего дедушки и последующем изгнании, и о том, как несколько других обитателей Убежища решили присоединиться к нему, а не оставаться в относительной безопасности Убежища. Вы также обнаружили, что Смотритель был в конечном счете судим и казнен оставшимися обитателями Убежища.} 
{275}{}{[ДАЛЬШЕ]}

{276}{}{Последняя запись в хрониках датируется маем 2242 года. Кажется, тогда в Убежище 13 был впервые получен сигнал "все чисто" от неизвестного источника извне. После некоторого обсуждения, жители Убежища решили открыть двери и посмотреть, что их ждет на поверхности мира. Записей о том, что случилось с ними после этого, нет.} 
{277}{}{Доступ к Инструкции по Выживанию Жителя Убежища (Сокращенный вариант). }
{278}{}{Доступ к журналам Смотрителя Убежища.}
{279}{}{Отключиться.}

# Overseer Logs
{280}{}{Требуется авторизация. Пожалуйста, введите пароль. }
{281}{}{[НАЗАД]}
{282}{}{[Угадать пароль]}
{283}{}{[Попытаться взломать]}
{284}{}{Отключиться.}

#Guess Password
{290}{}{Неверно. Пожалуйста, введите пароль.}
{291}{}{[НАЗАД]}
{292}{}{[Угадать пароль]}
{293}{}{[Попытаться взломать]}
{294}{}{Отключиться.}

#After 3 Incorrect Guesses
{300}{}{Неверно. Сейчас эти файлы заблокированы. Vault-Tec приносит свои извинения за все неудобства.}
{301}{}{[НАЗАД]}
{302}{}{[Попытаться взломать]}
{303}{}{Отключиться.}

{310}{}{[Вы пробуете все, до чего могли додуматься, но не можете получить доступ. Со вздохом огорчения вы возвращаетесь в главное меню.]}
{311}{}{Запусить диагностику.}
{312}{}{Переключить в режим ввода с клавиатуры.}
{313}{}{Доступ к защищенной области.}
{314}{}{Отключиться.}

{320}{}{Пароль верный. Все записи, кроме одной, были удалены из системы. Последняя запись в журнале Смотрителя по-прежнему доступна.}
{321}{}{[После нескольких долгих минут работы вашего технического гения вам удается взломать журналы Смотрителя. Однако, оказывается, что все записи за исключением последней были удалены.]}
{322}{}{Хорошо, давай посмотрим, что этот смотритель хотел нам сказать. [Читать журнал.] }
{323}{}{Эх, ну и ладно. [Отключиться.]}

{330}{}{Вот оно. Похоже, это мои последние слова - я сомневаюсь, что выживу и сделаю хотя бы еще одну запись. О нет, жители Убежища держали речь, и они выразились совершенно ясно, что жаждут моей смерти. Я знал, что этот день наступит, с тех пор, как ОН стал раздражать их, делая невозможное. Конечно, он спас наши жизни, но он также и разрушил все.} 
{331}{}{[ДАЛЬШЕ]}
{332}{}{Да будет известно, что мало радости было для меня в изгнании нашего "великого героя", но у меня не было выбора в этом вопросе. Его приключения во внешнем мире изменили его слишком сильно. Он стал слишком большой угрозой для проекта. Если бы я позволил ему остаться среди нас, он, возможно, обнаружил бы истинную природу Убежища и поставил бы эксперимент под угрозу. Но даже если бы и не обнаружил, то по крайней мере вдохновлял других к приключениям, и это было бы тоже плохо.} 
{333}{}{[ДАЛЬШЕ]}
{334}{}{Он просто должен был уйти. Не было другого выбора. Но даже этого было недостаточно. Нет, я боюсь, ущерб уже был нанесен. Я позволил его самым упорным сторонникам последовать за ним в изгнание, а затем попытался восстановить контроль над теми, кто остался. Но это было бесполезно - меня уже дискредитировали. Да будет так. Единственное, в чем я виновен, так это пожизненном исполнении требований нашей Великой Нации.}
{335}{}{[ДАЛЬШЕ]}
{336}{}{Я жалею только о том, что Убежище 13 вряд ли закончит социальный эксперимент. Как только от меня избавятся, я уверен, многие оставят Убежище. Не сразу, конечно, - я привил им слишком много страха перед внешним миром. Но в конце концов, они обязаны преодолеть этот страх. Мне совсем не верится, что Убежище 13 останется закрытым до 2277 года, как предписывает эксперимент.}
{337}{}{[ДАЛЬШЕ]}
{338}{}{Боюсь, мне не удалось исполнить свой долг Смотрителя. Мне остается только надеяться, что остальные общественные Убежища, участвующие в Программе Сохранения Социума будут более успешны. Моему начальству, которое, я уверен, в один прекрасный день прочитает журнал: простите меня. И да благословит Бог Америку.}
{339}{}{Искать любые другие файлы, которые содержат информацию о "программах сохранения социума".}
{340}{}{Отключиться.}

{350}{}{Даже после нескольких часов поиска в архивах компьютера вы не можете найти никаких намеков на Программу Сохранения Социума. Вы отказываетесь от своих поисков и обещаете себе никогда больше не тратить так много времени, глядя на монитор компьютера.}
{351}{}{Отключиться.}

{360}{}{После нескольких часов поиска в архивах компьютера вы смогли найти несколько скрытых документов, касающихся Программы Сохранения Социума. Просматривая их, вы раскрываете довольно тревожную правду об Убежищах: они никогда не были предназначены для сохранения населения Соединенных Штатов.}
{361}{}{[ДАЛЬШЕ]}
{362}{}{Невероятно, но все 122 общественных Убежища Vault-Tec были частью великого социального эксперимента, организованного правительством США. Только 17 из этих Убежищ, получившие название "контрольных Убежищ", были разработаны для правильного функционирования (кажется, Убежище 8 было одним из немногих счастливчиков). Остальные должны были иметь различные критические недостатки, для того чтобы правительство могло изучать предварительно отобранных жителей, и увидеть, как они реагируют на стрессовые ситуации, в которые их поместили, и насколько они могут быть способны к повторной колонизации, когда их Убежище откроется.} 
{363}{}{[ДАЛЬШЕ]}
{364}{}{Кажется, Убежище 13 в эксперименте должно было оставаться закрытым в течение 200 лет, чтобы проверить эффекты длительной изоляции. По-видимому, разрушение водяного чипа не было предусмотрено, и это заставило Смотрителя импровизировать и поручить вашему дедушке выйти наружу и достать новый чип. После дополнительных поисков вы находите описания еще нескольких экспериментов Убежищ.} 
{365}{}{[ДАЛЬШЕ]}
{366}{}{Было задумано, что дверь Убежища 12 никогда не сможет закрыться, так чтобы мудаки, ответственные за этот эксперимент, могли "изучить воздействие радиации на некоторой популяции". Если вы припоминаете легенду правильно, Убежище 12 было расположено под населенным гулями городом Некрополисом, где Житель Убежища в конце концов нашел водный чип. Кажется вполне вероятным, что гули были результатом этого эксперимента.}
{367}{}{[ДАЛЬШЕ]}
{368}{}{Убежище 15, еще одна ключевая локация в приключениях Жителя Убежища, должно было быть заселено людьми с "радикально разнообразной идеологией", которые должны были быть все вместе запечатаны в хранилище на 50 лет. Убежище 27 должно было быть целенаправленно переполнено двумя тысячами человек - в два раза больше максимальной емкости. Это не могло быть хорошо. Убежище 29 должно было быть населено только детьми в возрасте до шестнадцати лет, с родителями "нарочно перенаправлеными в другие Убежища".}
{369}{}{[ДАЛЬШЕ]}
{370}{}{Эксперимент, проводившийся в Убежище 34, подразумевал, что оружейная будет переполнена оружием и боеприпасами, и, конечно, не обеспечена замком. Как мило. Убежище 36 пострадало от пищевых синтезаторов, которые были предназначены для производства только "клейкой водянистой каши", в то время как Убежище 42 было оборудовано только тусклым освещением, лампочки более 40 ватт не были предоставлены.}
{371}{}{[ДАЛЬШЕ]}
{372}{}{Оборудование Убежища 53 было разработано, чтобы ломаться каждые несколько месяцев. Ремонты и постоянное аварии были предназначены для проверки стрессоустойчивости его обитателей. Интересно бы знать, сколько экспертов-механиков и техников произвело то Убежище. В Убежище 55 должны были быть удалены все развлекательные записи, а в Убежище 56 из развлекательных записей должно было остаться только одно шоу особенно плохого комедийного актера.}
{373}{}{[ДАЛЬШЕ]}
{374}{}{Убежище 68 должно было быть заселено 999-ю мужчинами и только одной женщиной. Можно только представить себе ужасы, которые там происходили... Убежище 69, с другой стороны, должно было быть заселено 999-ю женщинами и только одним мужчиной. Интересно... В Убежище 70 синтезаторы одежды были запрограммировны на отказ после 6 месяцев работы. И, наконец, Убежище 106 было разработано таким образом, что через 10 дней после запечатывания оно должно было начать выпускать психотропные препараты в систему фильтрации воздуха.}
{375}{}{Отключиться.}

{500}{}{Вы узнаете об Экспериментах в Убежищах и роли различных Убежищ.}
{510}{}{Вы узнаете об истории Убежища 13 и о роли Смотрителя в Экспериментах в Убежищах.}

