###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите робота Мистера Хенди.}
{101}{}{Этот робот похоже предназначен для перевозки тяжелых материалов и оборудования.}
{200}{}{Би-ип.}
{201}{}{*Клик*}
{202}{}{*Би-боп*}
{203}{}{Пересекайте область работ с осторожностью.}

