###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите хорошо одетого грузного человека, который движется нарочито медленно.}
{101}{}{Это Мерк – здешние люди называют его Хозяин.}
{102}{}{Этот человек источает высокомерную холодность, будто вы ему так же безразличны, как и муха, которую он только что сплющил между пальцами.}

{200}{}{Похоже, еще один парень, который больше думает кулаками, чем головой.}
{201}{}{Хм-м. Один из охранников Мерка.}
{202}{}{Большой. Крепкий. Тупой. Телохранитель.}

