###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите красивую молодую женщину в боевом облачении.}
{101}{}{Это Элиза.}
{102}{}{У нее уверенный командирский вид - можно сказать, что она привыкла отдавать приказы и ей подчиняются.}
{103}{}{Что вам надо?}
{104}{}{Опять вы?}
{105}{}{Меня послал Карл.}
{106}{}{Док Юбили сказал, что мне следует поговорить с вами.}
{107}{}{Кто вы?}
{108}{}{Ась?}
{109}{}{Я ищу одну группу. Такую, которая ненавидит рабство. И называет себя Рейнджерами Новой Калифорнии.}
{110}{}{Вы можете починить мою машину?}
{111}{}{Ух - а мне казалось, тут все заброшено.}
{112}{}{Вот как? Что он вам сказал?}
{113}{}{Немного. Что вы хорошие люди и мне вы понравитесь.}
{114}{}{Говорит, что вы платите хорошие деньги.}
{115}{}{Я Элиза. А это Гонд. Мы члены "группы", которая стремится помогать людям.}
{116}{}{Вы не похожи на благотворительное общество или церковь.}
{117}{}{Звучит интересно. А что значит - помогать?}
{118}{}{Я просто хочу привести машину в порядок.}
{119}{}{Убирайтесь отсюда. Салун на главной улице.}
{120}{}{Ненавидит рабство, ага. Интересно. А что вы скажете, если найдете эту группу?}
{121}{}{Я попрошу, чтобы меня приняли.}
{122}{}{Начищу им рыла.}
{123}{}{Ничего.}
{124}{}{Не ваше дело. А теперь вон отсюда.}
{125}{}{Мы больше не занимаемся машинами. Авторемонт закрыт насовсем. До свидания.}
{126}{}{Это не так. До свидания.}
{127}{}{Ладно, тогда скажите мне вот что. Как вы относитесь к работорговцам?}
{128}{}{Я их ненавижу. Как только земля носит этих выродков?}
{129}{}{Они меня не трогают, и я их не трогаю.}
{130}{}{Некоторые мои лучшие друзья промышляют работорговлей.}
{131}{}{Вас интересуют только деньги?}
{132}{}{Нет, конечно. Я верю в правду, справедливость и борьбу за права угнетенных.}
{133}{}{Уже хорошее начало - пока не найдется лучшая идея, за которую можно сражаться.}
{134}{}{А что еще?}
{135}{}{Не надо рассказывать мне сказки. Я вижу, что вы за человек. До свидания.}
{136}{}{Если вы не знаете, значит, я теряю с вами время. До свидания.}
{137}{}{Нет, мы не религиозная организация. Позвольте задать вам вопрос?}
{138}{}{Конечно, пожалуйста.}
{139}{}{Не так быстро. Чтобы стать рейнджером, нужно пройти испытание.}
{140}{}{Прекрасно. Просто скажите, какое.}
{141}{}{Испытание? Тут что, школа с экзаменами?}
{142}{}{Прямо за городскими воротами живет работорговец. Может, вы видели его заведение. Освободите рабов, затем возвращайтесь к нам, поговорим.}
{143}{}{Это я могу.}
{144}{}{Нет и еще раз нет. Я не хочу устраивать волнения.}
{145}{}{Ну, скажите спасибо, что мы сегодня добрые.}
{146}{}{Именно благодаря такой позиции зараза рабства и расползается по земле. Мне очень жаль, но в нашей организации таким, как вы, нет места.}
{147}{}{Ладно.}
{148}{}{Что, передумали? Готовы доказать, что чего-то стоите?}
{149}{}{Конечно.}
{150}{}{А что надо было сделать?}
{151}{}{У вас точно нет никаких дел? Не возвращайтесь, пока не выполните задание.}
{152}{}{Я уже слышала новости. Вы освободили рабов. Прекрасная работа! Ну что, вы готовы стать рейнджером?}
{153}{}{Да.}
{154}{}{Нет.}
{155}{}{Я слышала, это вы освободили рабов за городскими воротами. Вы совершили очень хорошее дело. Позвольте пожать вам руку.}
{156}{}{Спасибо.}
{157}{}{Это просто. Мы считаем, что рабство - это надругательство над сущностью человека, и делаем все, что в наших силах, чтобы бороться с ним. В НКР у нас множество друзей на высоких постах. Благодаря им мы уже искоренили рабство на юге, но теперь надеемся продвинуться и на север.}
{158}{}{Похоже, будь я рейнджером, я мог бы этим только гордиться. Примете меня?}
{159}{}{Интересно... Надо будет подумать над вашими словами.}
{160}{}{Клянешься ли ты бороться с рабством всегда и везде, когда и где представится возможность, и помогать братьям своим рейнджерам в трудную минуту?}
{161}{}{Да.}
{162}{}{Нет,}
{163}{}{Поздравляю, теперь ты рейнджер.}
{164}{}{Здравствуй, рейнджер. Боюсь, сейчас для тебя найдется мало работы. Большинство ребят сейчас в патруле. Я разошлю весточку, что ты теперь один из нас. Еще не хватало, чтобы тебя свои же подстрелили.}
{165}{}{Нам всегда нужны хорошие люди, чтобы бороться за идею. Если передумаете, приходите. Вы уверены, что не хотите стать одним из нас прямо сейчас?}
{166}{}{Уверен.}
{167}{}{Ну, теперь, когда вы об этом заговорили, я думаю, что хотел бы стать рейнджером.}
{168}{}{Понятно. Ну что ж. Я представляю группу, которая называется "Рейнджеры Новой Калифорнии". Люди с такими взглядами, как ваши, могут стать членами нашей группы. Вы заинтересованы?}
{169}{}{Великолепно! Примете меня?}
{170}{}{Звучит интересно. Что вы можете рассказать мне о рейнджерах?}
{171}{}{Понятно. Ну что ж, спасибо за визит, но не думаю, что нам есть о чем говорить дальше. Если вдруг передумаете, приходите ко мне.}
{172}{}{Ладно.}
{173}{}{В таком случае мне придется попросить вас очистить помещение. Марш!}
{174}{}{Ладно.}
{175}{}{Работорговец! Вон отсюда, пока я пулей не сорвала твою татуировку!}
{176}{}{Конечно.}
{177}{}{Только попробуй!}

{178}{}{У нас есть агенты и сочувствующие в некоторых городах на севере. Мы распространяем нашу идею и бьем работорговцев, где только можем.}
{179}{}{Здравствуйте еще раз. Не передумали насчет того, чтобы присоединиться к нам?}
{180}{}{Нет, ничего.}


{181}{}{Это не твое добро. Теперь убирайся, или тебя выведут силой.}
{182}{}{Не знаю, что ты сделал с Гондом, но ты за это заплатишь!}

###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{200}{}{Поздравляю, теперь вы Рейнджер. Ваша обязанность бороться с рабством, где это возможно. Будте осторожны, мой друг.}
{201}{}{Прежде чем я иду, у меня есть информация, которая может вас заинтересовать.}
{202}{}{Ладно, послушаем его.}
{203}{}{Я случайно узнал координаты одного из крупнейших рабовладельческих лагерей Мецгера. Это к северо-западу отсюда, пара дней путешествия от Ямы.}
{204}{}{Вы это серьезно? Наши северные Рейнджеры давно и безуспешно пытались выследить лагеря Мецгера. Это отличная новость, теперь нам нужно разрушить это ужасное место. Знаете ли вы, насколько хорошо оно охраняется?}
{205}{}{Только то, что охрана сейчас в мешках для трупов. Я уже уничтожил весь лагерь.}
{206}{}{Кажется, было около дюжины охранников.}
{207}{}{Я не могу сказать вам, я не был там еще.}
{208}{}{Вы? Это удивительно! Мне нужно рассказать это другим Рейнджерам. Сейчас самое время для нас подняться и ударить, пока они заняты зализыванием своих ран. Я не смогу достаточно отблагодарить вас. Мы действительно в долгу перед вами.}
{209}{}{Ваша благодарность это все что мне нужно. Береги себя.}
{210}{}{Если вы так доволен творением моих рук, то как насчет маленького денежного вознаграждения?}
{211}{}{Мы должны напасть на них одновременно. Хотите снять эти отморозков для нас?}
{212}{}{Я думаю, что сделал достаточно на этот день. Прощайте.}
{213}{}{Это моя обязанность как Рейнджера. Конечно я помогу.}
{214}{}{Отлично! Прошу сообщить, когда вы уничтожите лагерь.}
{215}{}{Дайте мне немного времени. Я вернусь, когда буду готов.}
{216}{}{Конечно. До скорого.}
{217}{}{Я спонтанный человек. Мне не нужна подготовка. Давай покончим с этим шоу на дороге.}
{218}{}{На самом деле, я изменил свое мнение. Я уверен, что вы и другие Рейнджеры можете проделать все отлично и без меня. Удачи.}
{219}{}{На самом деле, я думаю, было бы лучше, если бы некоторые Рейнджеры пошли вместе со мной. Это гарантировало бы больший успех этой битвы и общей борьбы против рабства.}

{220}{}{Нет, я сожалею. У меня нет ресурсов, чтобы вытащить несколько человек из резерва. Это вам придется сделать самостоятельно.}
{221}{}{Хорошо, я попробую сделать это в одиночку. Я сообщу, когда закончу.}
{222}{}{Хорошо, я попробую сделать это в одиночку. Мне нужно время, чтобы подготовиться. Я вернусь.} #not used
{223}{}{Тогда мне придется отказаться. Прощайте.}

{224}{}{Вы правы. Я соберу небольшую группу и отправлю их с вами. Готовы ли вы идти?}
{225}{}{Мне нужно время на подготовку. Я вернусь.}
{226}{}{Я готов. Пойдем.}

{227}{}{деньги? Ну, я полагаю, что это минимум, который мы могли бы сделать. Здесь, $1000 за беспокойство. Еще раз спасибо.}
{228}{}{С удовольствием. Прощайте.}

{229}{}{AВы готовы напасть на лагерь рабовладельцев?}
{230}{}{Мне по-прежнему требуется больше времени.}
{231}{}{Я готов к работе. Давайте сделаем это.}

{232}{}{Ваши товарищи Рейнджеры встретятся с вами в пути. Удачи Вам.}
{233}{}{[Закончить]}
{234}{}{Я слышал новости. Большое вам спасибо за вашу помощь. Это несомненно смертельный удар работорговцам. Мы действительно в долгу перед вами.}
{235}{}{Пожалуйста, не откладывайте это надолго. Эта атака имеет решающее значение в нашей борьбе против рабства.}
{236}{}{Вы помогли Рейнджерам в их постоянной борьбе против рабства.}

{240}{}{Спасибо. Прощайте.}

{250}{}{Есть еще одна вещь. Вы похожи на того, кому можно доверять. Того, кто не любит работорговцев.}
{251}{}{Ну, я как раз уничтожил один из их лагерей. Что вы имеете в виду?}
{252}{}{Я думаю, я сделал достаточно для человечества на сегодня. Увидимся.}

#added in RP 1.3
{260}{}{Что ты здесь делаешь? Это частная- Эй, подожди минутку, я думаю, что я слышал о вас. Вы случайно не тот, кто вытащил рабов из лагерей Мецгера?}
{261}{}{Да. Это я.}
{262}{}{Конечно, я так и сделал. У тебя проблемы с этим?}
{263}{}{Может быть... А что?}
{264}{}{Я не знаю, о чем вы говорите. Теперь, если вы меня извините, я пойду дальше.}

{270}{}{То что вы сделали это прекрасно, и я просто хочу пожать вам руку.}
{271}{}{Вовсе нет. Вообще-то, я хотел бы пожать вам руку.}
{272}{}{Потому что вы сделали хорошую вещь, и я просто хочу пожать вам руку.}
{273}{}{Если вы так довольны моими делами, то как насчет маленького денежного вознаграждения?}
{274}{}{Всегда пожалуйста. Теперь, почему бы вам не сказать мне, кто вы?}

{280}{}{У нас не так много средств в резерве, но вы оказали нам *большую* услугу и я полагаю, мы могли расстаться с кое-чем. Вот $1000.}
{281}{}{Спасибо. Пока.}
{282}{}{Спасибо. Теперь, почему бы вам не сказать мне, кто вы?}

{290}{}{Я Элси. Это Гонда. Мы члены группы по борьбе с рабством под названием Рейнджеры Новый Калифорнии. Мы могли бы использовать такого, как вы. Если вы заинтересованы в присоединении к нам, у меня есть задание для вас.}
{291}{}{Давайте послушаем его.}
{292}{}{Не интересует. Пока.}



###.Magnat.###...Added by 1C. May be: a)for female characters (require proper scripts); or b) absent in English version...########################
#Женские реплики, Андрей
{10158}{}{Похоже, будь я рейнджером, я могла бы этим только гордиться. Примете меня?}
{10164}{}{Здравствуй, рейнджер. Боюсь, сейчас для тебя найдется мало работы. Большинство ребят сейчас в патруле. Я разошлю весточку, что ты теперь одна из нас. Еще не хватало, чтобы тебя свои же подстрелили.}
{10165}{}{Нам всегда нужны хорошие люди, чтобы бороться за идею. Если передумаете, приходите. Вы уверены, что не хотите стать одной из нас прямо сейчас?}
{10166}{}{Уверена.}
{10167}{}{Ну, теперь, когда вы об этом заговорили, я думаю, что хотела бы стать рейнджером.}
{10175}{}{Работорговка! Вон отсюда, пока я пулей не сорвала твою татуировку!}
{10182}{}{Не знаю, что ты сделала с Гондом, но ты за это заплатишь!}
