###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите мужчину, одетого в боевые доспехи.}
{101}{}{Вы видите женщину, одетую в боевые доспехи.}
{102}{}{Он носит значок с надписью NCR Рейнджер.}
{103}{}{Она носит значок с надписью NCR Рейнджер.}

{200}{}{Привет собрат Ренджер. Хочешь провести здесь ночь?}
{201}{}{Убил какого-нибудь работорговца сегодня?}
{202}{}{Мы освободили сегодня десяток рабов.}
{203}{}{Защита пустоши трудная работа, но кто-то должен ее делать.}
{204}{}{Хорошо, что ты на борту. Оставайся столь долго, как пожелаешь.}
{205}{}{Я слышал, что случилось с Мецгером. Отличная работа!}

{300}{}{Это работорговцы, атака!}
{301}{}{Дерьмо, на нас нападали!}

{400}{}{Приветствую, друг.}
{401}{}{Это частная собственность. Не слоняйся здесь без дела слишком долго.}
{402}{}{Вы любите работорговцев? Я очень надеюсь, что нет... ради вас же.}

{500}{}{Что за?! Работорговцы? Откуда они узнали о нас? Мы должны защитить себя. Атака!}
{501}{}{Подожди! Я на вашей стороне. Я как раз привел вам несколько целей попрактиковаться. (Повернувшись к работорговцам.) Извините мальчики, я такой человек. (Атаковать работорговцев)}
{502}{}{Это будет весело! (Атаковать Рейнджеров)}

{600}{}{Вы уничтожить безопасное место Рейнджеров.}

