###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы входите в город Сан-Франциско. Здесь болтается много мужчин и женщин в одеждах восточного покроя.}
