###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы попали в район доков Сан-Франциско. Вы видите большой нефтяной танкер, плавающий на воде впереди. В небе над головой раздаются голоса чаек.}
{200}{}{Вы сумели отключить подводную лодку, уложив охранников Сан-Франциско отдохнуть.}

