###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{¬ы видите моторную лодку.}

{200}{}{¬ы проникаете на моторную лодку, пока охранник смотрит в другую сторону, и пр€четесь. ќколо полуночи ¬ы слышите р€дом голоса и чувствуете, как моторна€ лодка начинает двигатьс€.}
{201}{}{ѕриказав членам вашей группы оставатьс€ на месте, ¬ы проникаете на моторную лодку, пока охранник смотрит в другую сторону, и пр€четесь. ќколо полуночи ¬ы слышите р€дом голоса и чувствуете, как моторна€ лодка начинает двигатьс€.}

{210}{}{ћожет быть, € должен разоружить эту штуку прежде чем уйти.}
{220}{}{—лишком рискованно использовать это снова.}
{221}{}{я не знаю, куда идти.}

