###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Оказывается, к северу от НКР есть несколько стоянок Рейнджеров. Вы отмечаете их расположения в ПипБой.}
{101}{}{Местоположения стоянок Рейнджеров уже были занесены в ваш ПипБой.}

