###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{При входе в лесистую местность вас сбил с ног запах немытых рабов, живущих в грязном сарае на западе. Впереди виден дом с несколькими бродящими около него вооруженными работорговцами.}

{200}{}{Вы уничтожили лагерь работорговцев.}

