###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите пухлого купца с повязкой на глазу.}
{101}{}{Одноглазый Рой пристально наблюдает за вами его глазом и вытирает пот со лба.}

{200}{}{[Когда вы и Кром подходите к месту встречи, вы видите пухлого купца с повязкой на глазу в окружении телохранителей. Хотя продавец обливается потом, он кажется довольно веселым.]}
{201}{}{[Далее]}
{202}{}{[После торговец восторженно приветствует Крома и поворачивается к вам осматривая вас. Хотя его улыбка не сходит с лица, его бегающий взгляд наводит на подозрения.] Так, Кром говорит, чтобы я делал бизнес сегодня с вами.
 [Он пожимает плечами.] Ребята называют меня Одноглазый Рой, но я за всю жизнь не могу понять почему. [Смеется от души своей шутке.] Как тебя зовут, приятель?}
{203}{}{Я }
{204}{}{ из Арройо.}
{205}{}{. Теперь давай продолжим.}

{210}{}{Рад встрчатсься с вами, }
{211}{}{. Если вы не возражаете, я скажу, что ты немного странный для дикаря.}
{212}{}{Я не какой-то обычный дикарь. Я Избранный.}
{213}{}{Я не пойму, чего вы хотите. Я просто обычный индеец Джо, дикарь. Ничего странного во мне нету.}
{214}{}{А, потому что я так одет? Видите ли, я пытаюсь создать новые тенденции моды в племени. Я устал от старых добрых штанов из браминовой кожи с ремнем через грудь. Это смотрится *как* в старом 2240.}
{215}{}{Кого ты называл "странным", ублюдочный одноглазый толстяк? [Атаковать.]}

{220}{}{[Он уверенно улыбается и слегка кивает.] Ладно, тогда к делу. Скажите мне, друг мой, вы когда-нибудь слышали о маленькой штучке, называется... стимпак? [Когда он произносит последнее слово, он достает стимпак из кармана и держит его, как чудесный артефакт.]}
{230}{}{[Глаза его расширились и он испускает тихий свист.] Избранный, да? Ну цвет меня впечатляет. Теперь давай приступим к делу. Скажите мне, друг мой, вы когда-нибудь слышали о маленькой штучке, называется... стимпак? [Когда он произносит последнее слово, он достает стимпак из кармана и держит его, как чудесный артефакт.]}
{240}{}{Как скажешь, друг. Теперь давай приступим к делу, ладно? Скажите мне, друг мой, вы когда-нибудь слышали о маленькой штучке, называется... стимпак? [Когда он произносит последнее слово, он достает стимпак из кармана и держит его, как чудесный артефакт.]}

{241}{}{Да, конечно. На самом деле, они довольно распространены.}
{242}{}{Конечно. В самом деле, я собираю вещи. Черт, да я практически стимпакоман :)}
{243}{}{[Трясешь головой и смотришь на этот предмет в изумлении.] Что... стимуляция-пак?}

{250}{}{[Он нервно хихикает.] Я бы не сказал, что они *распространены*, но они, безусловно, желанный нами, цивилизованными людьми. [Он смотрит на Крома.] И вот почему. Видите ли, эти маленькие штучки содержат магические силы исцеления, которые *поразят* и *удивят* вас. Конечно, слова ничего не значат без доказательств, поэтому позвольте мне показать вам чудеса стимпака в действии.}
{251}{}{[Его взгляд на мгновение застывает, но он быстро восстанавливает спокойствие и смотрит на Крома.] Видите ли, эти маленькие штучки содержат магические силы исцеления, которые *поразят* и *удивят* вас. Конечно, слова
 ничего не значат без доказательств, поэтому позвольте мне показать вам чудеса стимпака в действии.}
{252}{}{Отличный вопрос, мой друг! Стимпаки являются одним из многих великих чудес которые остались нам от старого мира. Видите ли, эти маленькие штучки содержат магические силы исцеления, которые *поразят* и *удивят* вас.
 Конечно, слова ничего не значат без доказательств, поэтому позвольте мне показать вам чудеса стимпака в действии.}
{253}{}{Это должно быть интересно. Давайте посмотрим.}
{254}{}{Я уже знаю, как они работают, я использовал их сам много раз.}

{260}{}{[Он улыбается тебе и Крому, а затем поворачивается к одному из его телохранителей.] Уоррен, дайте мне вашу руку. [Охранник хмурится, но, делает как тот сказал. Рой быстро вынимает нож и режет им верхнюю часть руки Уоррена.
 Уоррен вздрагивает от боли, но не кричит. Рой смеется над вами.] Как вы можете видеть, Уоррен получил довольно неприятную рану вот здесь.}
{261}{}{[ДАЛЬШЕ.]}
{262}{}{Уверяю вас друзья, и рана, и боль Уоррена, являются вполне реальными. Вы можете посмотреть, что это не бутафорский нож. [Протягивает Крому нож, который тщательно осматривает его, кивает и передает обратно.] Но теперь, смотрите. [Он вводит стимпак в руку Уоррену. Почти мгновенно, кровотечение прекращается. Рой использует грязные тряпки, чтобы вытереть кровь, видно что рана почти зажила.]}
{263}{}{[ДАЛЬШЕ.]}
{264}{}{Теперь представьте себе, обладание стимпаками даст вам преимущество перед племенами-соперниками. И в отличие от исцеляющего порошка, который вы ребята варите, стимпаки *не* вызвают сонливость. По сути, это не удивительно, совершенно *без* побочных эффектов. Но я знаю, ты думаешь, что они должны стоить целое состояние, да? Не верно. Потому что я *похож* на вас, я практически отдаю их даром.}

{270}{}{[Игнорируя ваш комментарий, он улыбается Крому, а затем поворачивается к одному из его телохранителей.] Уоррен, дайте мне вашу руку. [Охранник хмурится, но, делает как тот сказал. Рой быстро вынимает нож и режет им верхнюю часть руки Уоррена. Уоррен вздрагивает от боли, но не кричит. Рой смеется над вами.] Как вы можете видеть, Уоррен получил довольно неприятную рану вот здесь.}

{275}{}{Сколько?}
{276}{}{Практически даром? Сколько вы просите?}

{280}{}{Я дам тебе весь этот ящик полный стимпаков - это *пятьдесят* стимпаков и я прошу в обмен жалкие * 20 * золотых шкур гекко. Вы просто не можете сорвать такую сделку.}
{281}{}{[Для Крома.] Он прав, это хорошая сделка, на самом деле. [Для Роя.] По рукам.}
{282}{}{Это правда хорошая сделка. Слишком хорошая. В чем подвох?}
{283}{}{Мы предлагаем вам 10 золотых шкур гекко. И не более.}
{284}{}{Позвольте мне подумать минуту.}
{285}{}{Не пойдет.}

#take deal, no idea fake goods
{290}{}{Лицо Роя засияло.] Отличный выбор! Тогда по рукам. [Быстро обменялись вещами, Рой спешит к его следующей остановке.]}

#10 pelts, barter < 90
{300}{}{[Рой смеется и смотрит на своих телохранителей.] Смотри, один стимпак стоит гораздо больше чем одна золотая шкурка. Таким образом, я уже предлагаю их вам с возмутительной скидкой. Просить меня еще сбросить цены будет грабеж.
 Двадцать шкурок, или я буду ухожу к более разумному племени.}
{301}{}{Хорошо. По рукам.}
{302}{}{Тогда лучше уходи. Сделки не будет.}
{303}{}{Дайте мне подумать об этом минутку.}

#10 pelts, barter >= 90
{305}{}{[Рой хмурится и чешет грязную шею. Наконец, он испускает долгий вздох.] Ты убиваешь меня, ты это знаешь? Но так как это *твое* племя, я принимаю твое предложение. [Быстро обменялись вещами, Рой спешит уйти к своей следующей остановке.]}

#no deal
{310}{}{[Он хмурится.] Я не знаю, какой идиот откажется от подобного предложения. [Он качает головой и поворачивается к своим людям.] Ладно, пойдем. [Он смотрит на тебя обратно.] И пошел на хуй за то что тратил мое время.}
{311}{}{[Давайте оставим его.]}
{312}{}{[Атаковать.]}

#whats the catch
{320}{}{Нет подвоха, мой друг. У меня просто уже есть стимпаков больше чем мне нужно, поэтому я избавляюсь от излишков. Золотые меха, с другой стороны... Их никогда не достаточно. Конечно, 50 стимпаков стоят гораздо больше, чем 20 простых золотых шкур гекко, но я реалист. Я не ожидал что ваше племя - опытные охотники, хотя я уверен, что у вас есть сотня золотых шкур гекко в запасе, поэтому я сделал наиболее разумное предложение. *Вот почему* это хорошая сделка.}
{321}{}{[Для Крома.] Он прав, это хорошая сделка, на самом деле. [Для Роя.] По рукам.}
{322}{}{Прежде чем мы согласимся с чем-нибудь, я хотел бы посмотреть на остальной товар.}

#let me look at the goods
{330}{}{[Его глаза слегка сужаются, затем он улыбается.] Конечно. Они в этом ящике рядом со мной.}
{331}{}{[ЗАКОНЧИТЬ.]}

#I need to think about it
{340}{}{Хорошо, но не слишком долго. У нас еще одна остановка до наступления темноты.}

#re-initiate dialogue
{350}{}{Хорошо, если вы закончили возиться, давайте это шоу на дороге. Я человек занятой.}
{351}{}{Хорошо. Мы соглашается на сделку.}
{352}{}{Не пойдет.}
{353}{}{Я должен подумать об этом немного больше.}
{354}{}{У меня есть новое предложени для Вас: дайте нам стимпаки, и вы сохраните свою жизнь.}

{360}{}{Вы занятой, парень, да? Да вы лжец и обманщик!}
{361}{}{Эти стимпаки подделка. Они не стоят ничего, это кожа брамина наполненая кровью брамина. Вы пытались погубить это племя.}
{362}{}{Я должен подумать об этом немного больше.}
{363}{}{Хорошо. Мы соглашается на сделку.}

#you're a liar and cheat
{370}{}{[он чувствует себя неудобно, и бросает нервный взгляд на Крома.] Оч -о чем ты говоришь?}
{371}{}{Эти стимпаки подделка. Они не стоят ничего, это кожа брамина наполненая кровью брамина. Вы пытались погубить это племя.}
{372}{}{Чт- это невозможно. Вы видели демонстрацию. Они работают хорошо. Я не буду стоять здесь, пока вы попытаетесь погубить мое доброе имя.}
{373}{}{Конечно, стимпак, который Вы использовали во время демонстрации был настоящий. Но я хотел бы увидеть как вы попробуете еще раз, используя один из стимпаков в этом ящике.}
{374}{}{Ебать ваше доброе имя. Оно не будет вам полезно после того как я закончу. [Атаковать.]}


{380}{}{[Он усмехается.] Хорошо! Отлично! Если вы говорите, что они поддельные, то, может быть, так оно и есть. А я почем знаю? Я не делал эти чертов вещи - я купил их. Поэтому я *единственный*, который пострадал здесь - а не вы. Теперь, так как товара, я не собираюсь тратить свое время здесь дальше. Пока.}
{381}{}{[Давайте оставим его.]}
{382}{}{[Атаковать.]}

{390}{}{Кем бля ты себя возомнил??? [телохранителям.] Убить этих сраных дикарей!}

