###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите рыбака.}
{101}{}{Вы видите рыбачку.}

{102}{}{Он несет заостренный шест для рыбалки.}
{103}{}{Она похоже занята приготовлением пищи.}
{104}{}{Привет.}


{200}{}{Тебе здесь не рады.}
{201}{}{Нам не нравится твой вид.}
{202}{}{Уйди, внешник.}
{203}{}{Зачем ты мучаешь нас?}
{204}{}{Здравствуй, товарищ.}
{205}{}{Вам всегда будут рады здесь.}
{206}{}{Ты теперь один из нас.}
{207}{}{Благодарим тебя за помощь.}
{208}{}{Я думал все внешники злые. Это не так ...}
{209}{}{Не делай этого.}

{300}{}{Извините, но не могли бы вы оказать мне небольшую услугу? Я немного занят, и я не знаю, смогу ли я оставить этот котел без присмотра.}
{301}{}{Конечно. Что тебе нужно?}
{302}{}{Я занят слишком. Может быть, немного позже.}
{303}{}{Эй, жизнь полна проблем, и я здесь не для того, чтобы решить их все. Пока.}
{304}{}{Мне не хватает древесины для этого костра. Если бы ты мог собрать для меня побольше, я буду очень признателен. Я бы сделал это сам, но я боюсь котел выкипет, если я оставлю его без присмотра.
 Я уверен, что древесину можно найти в близлежащем лесу. Три полена было бы идеально.}
{305}{}{С удовольствием.}
{306}{}{Вообще-то, по какой-то сумасшедшей причине, у меня случайно есть три полена прямо сейчас. Вот они.}
{307}{}{Вы сможете мне помочь? Отлично! Дайте мне знать, когда вы соберете их.}
{308}{}{Ах, отлично. Это поможет сохранить этот огонь. Спасибо, что нашли время, чтобы помочь мне. Правда у меня нет ничего, чтобы отплатить тебе за помощь.}
{309}{}{Твоей благодарности будет достаточно. Береги себя.}
{310}{}{Нечем заплатить мне? Смотри леди, я мог умереть в этих лесах. Они заполнены всеми видами смертоносных существ. Я рисковал своей шей из-за этих долбаных дров. Не говоря уже о том, что одно из поленьев посадило мне занозу. Я *ненавижу* занозы.}
{311}{}{Ладно, вот, возьми эти деньги. У меня нет пользы от них здесь. Еще раз спасибо.}
{312}{}{Вот так лучше. Пока.}
{313}{}{[Закончить]}
{314}{}{Кхмм. Иди беспокоить кто-нибудь еще.}
{315}{}{Ты принес дров?}
{316}{}{Да, вот они, прямо здесь.}
{317}{}{Нет, пока. Я вернусь, когда я соберу три полена.}
{318}{}{Готовы ли вы мне помочь?}
{319}{}{Конечно. Что тебе нужно?}
{320}{}{Нет, мне по-прежнему не хватает времени. Пока.}
{321}{}{Нет, и не буду. Сами разбирайтесь со своими проблемами. Пока.}

#added in RP 1.3 - Node004
{330}{}{Нет пользы? Тогда почему ты не отдала мне их сразу? (Бормочешь) Тупая сука.}

#dumb dialogue
{400}{}{Чего вам нужно?}
{401}{}{Ooo! Сделай мине любимую еду!}

{410}{}{Я ищу.}
{411}{}{Я имею древесину. Кхе-хе... древесину.}

{420}{}{Все хорошо. Пока!}

{500}{}{Убрать работорговца.}

