###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите гекко.}
{101}{}{Вы видите гекко, засыпанного обломками камней. Он выглядит очень сердито.}

{200}{}{Вы намеренно бросили раненого и беззащитного человека умирать. Зловещая улыбка прицепилась к твоему лицу.}

