###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите старого дикаря.}
{101}{}{Вы видите пожилого вождя племени.}

{102}{}{[старик курит трубку и смотрит на вас тупыми серыми глазами, которые лезут в вашу душу. Он жестом показывает, чтобы вы сели напротив него в прокуренной палатке.] Спасибо, что Курису вернулся в нашу деревню. [Он долго набивает свою трубку.] Духи... они много говорят о вас. Многое подтверждается. Скажите, вам что-то нужно?}
{103}{}{[старик курит трубку и смотрит на вас тупыми серыми глазами, которые лезут в вашу душу. Он жестом показывает, чтобы вы сели напротив него в прокуренной палатке.] Мы весьма признательны за ваши услуги, Странник. [Он долго набивает свою трубку.] Духи... они много говорят о вас. Многое подтверждается. Скажите, что привело вас в нашу деревню?}
{104}{}{С возвращением, дитя. Вам еще что-то нужно?}
{105}{}{Что может старик для вас сделать?}
{106}{}{Я в поисках Святого КоСоГоРа. Знаете ли вы что-нибудь о нем?}
{107}{}{Я ищу пропавшую женщину. Она сестра моего друга, Сулика.}
{108}{}{Есть что-нибудь еще, что мне необходимо сделать тут?}
{109}{}{Забудь. Пока.}

{110}{}{Святой ГЕКК... [Он долго набивает свою трубку.] Геккон. Это существо, на которое мы иногда охотимся, иногда он охотится на нас. Нет, я чувствую это не то, что вы ищете.
 Я боюсь, ваш Святой ГЕКК выходит за рамки моего понимания.}
{111}{}{Позвольте мне спросить вас что-нибудь другое.}
{112}{}{Это все, что мне нужно знать. Пока.}

{120}{}{Сулик? [Он кивает.] Один из наших лучших людей. Очень подкован в искусстве охоты, и искусство общения с костями духов. Он оставил нас, чтобы найти сестру, Курису, когда она не вернулась из соседнего племени. Скажи мне, дитя мое, где Сулик сейчас?}
{121}{}{Ой, да он прямо здесь. Эй Сулик, поди сюда...}
{122}{}{О, он в порядке. Я ему сказал подождать, пока я кое-что сделаю.}
{123}{}{Мне очень жаль, но он мертв.}
{124}{}{[Сулик и глава племени обменялись приветствиями.] Огромное удовольствие для меня видеть Сулика снова. Духи племени сказали мне, что он попал в беду. Но что с его сестрой, Курису?}
{125}{}{Отрадно слышать, что Сулику хорошо. Мы были обеспокоены что он попал в беду. Так, его сестра все еще отсутствует? Она тоже является членом нашего племени.}
{126}{}{[Он хмурится и долго курит трубку в тишине. Когда вы уже решаете уйти, он говорит.] Духи были сильны с Суликом. Я всегда думал, он может в один прекрасный день занять мое место. Теперь, я вижу, у духов были другие планы на Сулика. Но что с его сестрой, Курису?}
{127}{}{Она была захвачена работорговцами. Я предложил Сулику помощь в ее поисках. Знаете ли вы что-нибудь, что могло бы помочь в поиске?}
{128}{}{[Он закрывает глаза на долгое время. Подобно тому, как вы подумали что он заснул, он начинает говорить.] Работорговцев являются возглавляет человек с темной душой. Мецгер.
 Он живет в одном из старых разрушенных городов. Они называют то место Ямой. [Он открывает глаза.] Может быть, он держит ее там. Духи племени больше ничего не сказали.}
{129}{}{Спасибо. Позвольте мне спросить вас что-нибудь другое.}

{130}{}{Спасибо дитя, но я доволен. Может быть, другие не очень. Спросите вокруг деревни.}

#dumb dialgoue
{140}{}{Я ищу ГЕКК.}
{141}{}{Я ищу пропавшую без вести женщину. Она сестра друга Сулика.}
{142}{}{Пока.}

{150}{}{Я спрошу еще.}

{160}{}{О, он прямо здесь. Сулик, шеф племени хочет поговорить.}
{161}{}{О, с ним все в порядке. Он меня ждет.}
{162}{}{Я сожалею. Он мертв.}

{170}{}{Да, плохие люди забрали ее. Я помогаю Сулик. Вы знаете, где она?}

{200}{}{Твое зло закончится здесь, работорговец!}

# PC has beaten the Enclave
{300}{}{[старик курит трубку и смотрит на вас тупыми серыми глазами, которые лезут в вашу душу. Он жестом показывает, чтобы вы сели напротив него в прокуренной палатке.] Вы сделали великое дело, дитя мое. Я слышу крики многих нечестивых духов потеряных в Великой соленой воде. Теперь, когда вы доказали самому себе, я могу поделиться с вами великой тайной.}
{301}{}{Хорошо, наконец-то! Давайте послушаем это.}
{302}{}{Не интересуюсь, старик. Пока.}
{310}{}{[Он вынимает трубку изо рта и закрывает глаза. Через некоторое время, он кивает головой.] Да. Я вижу дух Большой Медведицы руководил вашими поисками, вдохнув новую жизнь в старые кости. Как и других. Может быть, они приходили к вам в видении. Родом из-за тридевять земель... где мутанты запрещены.}
{311}{}{О чем к дьяволу ты толкуешь???}
{312}{}{Да, да, я нашел рендомную локацию 'Звездных войн'. Не говорите мне, что это окончательная великая тайна.}
{320}{}{последняя тайна... величайший секрет во всей игре... есть, [он делает драматические паузы, он берет еще табака для своей трубки. Внезапно трубка выскальзывает из его рук и падает на его одежду, которая мгновенно воспламеняется.]}
{321}{}{БЛЯ!}

