###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Cправа вы видите группу крыс пирующих на трупе молодой девушки. Выглядит так, как если бы она умерла ужасной смертью, ее тело разорвано надвое.}

