###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите недовольного телохранителя.}
{101}{}{Уоррен хмурится на его недавно ампутированную руку.}

{200}{}{Почему он всегда режет *меня*?}
{201}{}{Мне реально надоел этот цирк.}
{202}{}{В следующий раз, он должен просто вырезать одного из этих чертовых дикарей.}

