###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Ааааакккххххх! Как... что... кто же ты?}
{101}{}{Хватит, успокойтесь. Я здесь не причинить вам вред! В чем дело?}
{102}{}{Кто-то быстро раздражает вас. Что у вас за проблема?}

{110}{}{Меня... тут... посетил. Посетили. Ночью - снаружи палатки. Я не могу до конца успокоится.}
{111}{}{Что? Ты мучиться? Я действительно не понимаю.}
{112}{}{Буги-вуги! Смотри, изверг приходит именно к вам!}

{120}{}{ДЕМОНЫ, дитя мое. Демоны! Они приходят по ночам и не дают мне покоя! Они стремятся забрать меня! Конец близок... Я не жилец на этом свете теперь...}
{121}{}{Вы нуждаетесь в помощи.}

{125}{}{Ваахххх! (Человек трясется в испуге)}
{126}{}{Кхех, неудачник...}
{127}{}{шаман слишком напуган, чтобы говорить с вами.}

{130}{}{Пожалуйста, оставьте меня в покое. Нет ничего, что можно сделать, чтобы спасти меня. Спасай себя!!!}
{131}{}{Ладно, тогда до свидания.}

{140}{}{Что вы хотите? Я сказал вам, чтобы вы спасались.}
{141}{}{Да, но я возможно решу ваши проблемы. Я могу остановить твоих демонов!}

{150}{}{*пауза* Вот как! Каким образом? Что вы знаете?}
{151}{}{Ваш так называемый "демон" на самом деле дух молодой женщины, которая была убита буквально за деревней. Она искала тебя, потому что это ваша обязанность, как шамана деревни освободить ее дух из этого мира. Сделайте так, и вы будете свободны.}

{160}{}{*глаза блестят... * Да боже мой, это объясняет все! Видения, плач... призрак... когда вы видели этот призрак?}
{161}{}{В полночь. Сразу за палаткой.}

{170}{}{Да, да, я вижу его сейчас. Хотите остаться со мной? Я не знаю, смогу ли я это сделать без тебя. Вы ведь уже видели призрак...}
{171}{}{Невероятно. Шаман который боится духов. Без проблем. Я останусь с вам.}

{180}{}{Спасибо! Вы сохранили мое здравомыслие. Я не смогу достаточно поблагодарить вас. Пожалуйста, возьмите эти целительные порошки в знак моей признательности.}
{181}{}{Сохранил ваш здравый смысл? Не уверен, что целиком, но вы всегда можете думать более-менее.}

{190}{}{Вы видите человека в лохмотьях.}
{191}{}{Вы видите шамана деревни.}
{192}{}{Этот человек дрожит с головы до ног и продолжает подпрыгивать от всякого шума.}
{193}{}{Шаман стал гораздо спокойнее и больше не дрожит.}

{200}{}{Я призываю духов этой святой земли!}
{201}{}{Пожалуйста, освободите меня. Прошу вас.}
{202}{}{Разрешите этой бедной девушке безопасный проход в другой мир и освободите ее от мук.}
{203}{}{*ВОЙ* Я иду, мама.}
{204}{}{Готова ли ты Карла?}
{205}{}{Я готова.}
{206}{}{Теперь будь освобождена от этой смертельной суеты. Иди на свет.}
{207}{}{Он очень яркий...}


{208}{}{Я не смогу тебя отблагодарить за помощь мне.}
{209}{}{Я навсегда останусь в долгу перед вами.}

{300}{}{Благодарим вас за помощь в спасении Серина. Я дал ему травы, чтобы помочь ему отдохнуть и облегчить его боль. Он должен встать на ноги через несколько дней.}

{301}{}{Это приятно слышать. Что еще я могу сделать?}
{302}{}{Я рад что Серин выздоровеет. Береги себя.}

{303}{}{Вообще-то, да, я полагаю, есть кое-что. Исцеление Серина исчерпало большую часть моего запаса травы. Если бы ты принес 5 Корней зандера и 3 Цветка брока, я был бы весьма признателен.}

{304}{}{Достать пять корней зандера и 3 цветка брока. Я вернусь, как только найду их для Вас.}
{305}{}{Похоже, сегодня ваш счастливый день. У меня уже есть то, что вы ищете. Возьмите, они ваши.}
{306}{}{Извините, но я слишком занят, чтобы пойти прогуливаться по лесу, собирая травы для Вас.}

{307}{}{Вы получили необходимые травы?}
{308}{}{Ага, у меня есть все прямо здесь.}
{309}{}{Я все еще ищу. Пока.}

{310}{}{Позволяет просмотреть... О, отлично. Они хорошо подойдут. Возьми порошок исцеления за твои хлопоты.}
{311}{}{Спасибо. Пока.}

{312}{}{Вы доставить травы для шамана.}

#added in RP 1.3
{320}{}{Почему такая точная цифра?}
{321}{}{Потому что я очень... педантичен в мелочах. Все дело в балансе определенных номеров... [Он хмурится.] Смотри, я не надеюсь, что вы понимаете, но сделаете именно так, как я сказал.
 Мне нужно пять корней зандера и три цветка брока, ни больше, ни меньше. Будете ли вы мне помогать?}

{1000}{}{Вы избавили шамана племени от его проблем.}

#dumb dialgoue
{2000}{}{Буги-вуги!}
{2001}{}{Шо не так?}

{2010}{}{(Вы хихикаете) Кхе-хе ...}

{2020}{}{Че?}

{2030}{}{Я стараюсь помочь.}

{2040}{}{Я найти вашего духа. Она хорошая. Она не плохая.}

{2050}{}{Она просто потерялась и грустная. Она хочет увидеть маму.}

{2060}{}{Когда в прошлый раз спал.}

{2070}{}{Я останусь. Я буду держать за руку.}

{2080}{}{Ее теперь нет. Пока!}

{2090}{}{Я люблю маму.}

# PC has beaten the Enclave
{3000}{}{Я все время знал, что ты великий герой... духи сказали мне об этом.}
{3001}{}{Я рад что мои целительные порошки предохранили вас от Анклава.}

