###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите женщину - дикарку.}
{101}{}{Вы видите Курису, сестру Сулика.}
{102}{}{Вы видите молодую, фигуристую дикарку с несколькими пирсингами и татуировками.}

{150}{}{[КОНЕЦ]}

{200}{}{Сулик! [Она прерывает себя и начинает шептать.] Духи дразнят меня, или это правда ты, брат?}
{201}{}{Я? Нет, я Избранный. Ты должна подумать старой костью в носу.}
{202}{}{[Сулик бросается к двери и хватает протянутые руки его сестры. Вы отворачиваетесь, чтобы дать им побыть наедине. Спустя мгновение двойной щелчое раздается за пределами здания.
 Сулик отпускает свою сестру и тянется за своим оружием, он смотрит на дверь. Больше звуков извне нет.]}
{203}{}{[Дальше]}
{204}{}{[Сестра Сулика обращается к Вам.] Духи говорят что вы руководите Суликом. Меня зовут Курису, но сейчас не время для нормального знаокмства. Пожалуйста, вам нужно вызволить нас из клетки и от нечестивых людей, которыми правит дух похоти. [Она усмехается и плюет в грязь.] Грязные собаки не наложат на нас снова свои лапы. [Услышав об этом, глаза Салик расширяются и лицо корчит от ярости. Он тянется за своим оружием.]}
{205}{}{Погоди, Сулик, нас ведь здесь нет. Дай мне посмотреть, смогу ли я взломать эту дверь, и мы сможем улизнуть отсюда.}
{206}{}{Погоди, Сулик, нас ведь здесь нет. Я получил ключ от этой двери. Давайте мы в тишине просто уберемся отсюда.}
{207}{}{[Вы киваете Сулику] Эти ублюдки заплатят. Lock and load (заряжай оружие), старый приятель.}
{208}{}{[Несколько минут спустя и вы наконец слышите последний клик из замка. Дверь распахивается.]}
{209}{}{[Вы обращаетесь к Курису.] Ладно, держись рядом и держи голову опущенной. [К другим рабам.] Молчите и двигайтесь к лесу.}
{210}{}{[Несколько минут прошло и вы потерпели неуду в разблокировке двери.]}
{211}{}{Должен быть другой способ открыть дверь. Дай мне посмотреть, смогу ли я достать ключ. Подождите здесь, я вернусь к вам.}
{212}{}{Ладно Сулик, настало время для твоего плана. Время вынести мусор.}
{213}{}{[Вы воткнули ключ в замок и открыли ворота. Они скрипят, пока открываются.]}

{214}{}{Есть успехи, друг? Пожалуйста, поторопись.}
{215}{}{Нет еще. Я все еще работаем над этим.}
{216}{}{Я получил ключи. Сваливаем отсюда.}
{217}{}{Почему так много смятения снаружи? Ах, я чувствую, многие из них уходят присоединиться к духам. Кто... Сулик? Духи дразнят, или все-таки это ты, брат?}
{218}{}{Почему так много смятения снаружи? Ах, я чувствую, многие из них уходят присоединиться к духам. И я чувствую, ты один отправил их в этот путь. Что тебе нужно, создатель духов?}
{219}{}{Я пришел, чтобы спасти тебя.}

{221}{}{Слава духам! Пожалуйста, тебе нежно вывести нас из клетки. Прочь от этого злого места.}
{222}{}{Духи хвалят тебя! Теперь я должна вернуться к своему народу. Долго же я отсутствовала. Пожалуйста, зайди в мою деревню. Он находится рядом с Великой соленой водой, несколько дней на юго-запад отсюда. Спасибо, друг.}
{223}{}{[Сулик бросается к двери и хватает протянутые руки его сестры. Вы отворачиваетесь, чтобы дать им побыть наедине. Спустя несколько мгновений сестра Сулика обращается к Вам.] Духи говорят что вы руководите Суликом.
 Меня зовут Курису, но сейчас не время для нормального знаокмства. Работорговцы, они мертвы, да?}
{224}{}{Да, работорговцы мертвы.}
{225}{}{Слава духам! Пожалуйста, откройте дверь. Мы хотим уйти от этого злого места.}
{226}{}{Не волнуйтесь. У меня есть ключ.}
{227}{}{Ладно, попробуем Взломать эту дверь.}

{400}{}{Давайте двигаться дальше.}
{401}{}{Пожалуйста, я хочу домой.}

{410}{}{[Вы обращаетесь к Курису.] Подожди, я не хочу уходить отсюда, пока я не освобожу рабов из других хагонов. Ты подожди здесь, пока я освобожу всех из этого лагеря. [Другим рабам.] Молчите и двигайтесь по лесу. Я буду обрабатывать охранников.}

{500}{}{Если ты выбрал меня чтоб переспать, лучше рассчитывай на бой- подожди, у тебя нет следа демонома на твоей голове. Кто ты?}
{501}{}{Я *Избранный* а ты кто?}
{502}{}{Меня зовут }
{503}{}{. Кто вы?}

{510}{}{Мое имя Курису. Я родом из племени на юго-запад отсюда, что находится рядом с Великой соленой водой. Работорговцы захватили меня. Других тоже захватили, но их уже отослали отсюда. Они говорят, что они не закончили со мной. Держат меня для своих нечестивых удовольствий. Пожалуйста, тебе нужно вызволить нас из клетки и от этих злых людей.}

{511}{}{Не беспокойся, я здесь, чтобы забрать тебя. У меня есть ключ и разрешение увести тебя отсюда.}
{512}{}{Ладно попробуем взломать эту дверь.}

{530}{}{Уже безопасно? Ты послал работорговцев к духам?}
{531}{}{Да, безопасно. Мы можем пойти в твою деревню прямо сейчас.}
{532}{}{Да, но позволь мне освободить всех рабов, прежде чем мы идем.}

{533}{}{Нет, пока нет. Я вернусь, когда будет безопасно.}

{600}{}{Слава духам, мы в конце концов будем дома! Благодарю тебя, друг.}
{601}{}{Всегда пожалуйста. Итак, как именно тебя захватили?}
{602}{}{Торговала вблизи деревни. Работорговцы пришли. Много крови и хаоса. Затем все погрузилось во тьму. Проснулась в запертой клетке пропахшей дерьмом. Вскоре переехала в меньшую клетку, в которой меня потом и держали.
 Видела много рабов - приходят и уходят. Печально видеть, как к людям относятся, как к скоту.}
{603}{}{Да, рабство это конечно ужасно. Очень жаль, что тебе пришлось пережить это, Курису. Итак, что же ты собираешься делать?}
{604}{}{Работорговцы делали мне больно, но я далеко не сломлена. Духи указали путь тебе вернуть мне свободу. Очевидно, духи планируют что-то большое для меня. У духов большие планы на тебя тоже. И на брата Сулика.
 Он много пропустил, но духи говорят, что его место шагать нога в ногу с тобой. Черт, даже Гремпли-кости ты понравился, так что я знаю, Сулик в хороших руках. Будьте осторожны.}
{605}{}{Спасибо Курису, увидимся.}
{606}{}{Работорговцы делали мне больно, но я далеко не сломлена. Духи указали путь тебе вернуть мне свободу. Очевидно, духи планируют что-то большое для меня. Скоро, думаю, я пойду охотиться за брата. Зная Сулика, он точно попал в беду, пытаясь прийти на помощь мне. Теперь, возможно, я помогу ему.}
{607}{}{Вообще-тр, я думаю, что я видел твоего брата. Лицо все в татуировках и большая кость в носу, не так ли?}
{608}{}{Это точно Сулик! И Гремпли-кость тоже! Пожалуйста, не мог бы ты привести Сулика домой? Я очень скучаю но нему.}
{609}{}{Нет проблем, я приведу его сюда. Увидимся Курису.}
{610}{}{Я не думаю, что смогу это сделать. Видишь ли, Сулик мертв.}
{611}{}{Сулик... умер? Действительно, это будет черный день. Я знаю, он с Гремпли сейчас, но Сулик... он будет сильно скучать. [Она смотрит в сторону, слезы заполнили ее глаза.] Пожалуйста... Мне необходимо побыть одной.
 Спасибо... что привели меня домой.}


{650}{}{Здравствуй, друг. Ес-- Сулик!}
{651}{}{[Больше]}
{652}{}{[Курису бросается к Сулику, который заключает ее в объятия. Вы отворачиваетесь, чтобы дать им уединиться во время их эмоционального воссоединения. Несколько минут спустя, Курису обращается к Вам с улыбкой, она вытирает слезы с глаз.] Спасибо друг за нахождение брата. У духов большие планы на тебя тоже. И на брата Сулика. Он много пропустил, но духи говорят, что его место шагать нога в ногу с тобой.
 Черт, даже Гремпли-кости ты понравился, так что я знаю, Сулик в хороших руках. Будьте осторожны.}
{653}{}{Здравствуй, друг. Тебе повезло в поисках брата Сулика?}
{654}{}{Нет, все еще ищу. Я вернусь, когда найду его.}

{700}{}{Еще раз спасибо, друг. Да благословят тебя духи.}
{701}{}{Брата Салик будет много скучать.}

{800}{}{Злые духи ходят за тобой! Уходи!}

{810}{}{Вернись в здание Курису! Я справлюсь с этим.}

{820}{}{Пожалуйста, не дай им причинить нам вред.}

{1000}{}{Вы воссоединили Сулика с его сестрой.}

# dumb dialogue
{900}{}{Я? Нет, я Избранный. Вы говорите Сулик?}
{910}{}{Да, плохие люди мертвы.}

{920}{}{У меня есть ключ.}
{921}{}{Я постараюсь взломать.}
{922}{}{[Вы киваете на Сулика] Мы поборемся с плохими людьми сейчас.}
{923}{}{Я продолжаю работать.}

{930}{}{[Вы обращаетесь к Курису.] Я могу защитить тебю. [Другим рабам.] Гоу хоум!!!}

{940}{}{Взлом не работает. Я искать ключ. Тебю ждать.}
{941}{}{Взлом не работает. [Вы обращаетесь к Сулику] Мы поборемся с плохими людьми сейчас.}


{950}{}{Мню *Избранный*. Кто тыыы?}
{951}{}{Моя }
{952}{}{. Кто тыыы?}

{960}{}{Безопасно. Мы едем домой.}
{961}{}{Не безопасно. Больше плохих людей надо убить.}

{970}{}{Всегда пожалуйста. Как они получили тебю?}
{971}{}{Да, злые люди не хорошо. Что ты теперь делать?}
{972}{}{Пасиба. Пока!}
{973}{}{Я знаю, Сулика. Сулик мне друг. Он говорит, как я. Он говорит с костью в носу.}
{974}{}{Я привел его. Он скучал по тебю.}
{975}{}{Моя жаль. Он мертв.}
{976}{}{Я все еще ищу.}

# PC had defeated the Enclave
{2000}{}{Я *знала*, у духов были большие планы для Вас.}
{2001}{}{Сначала вы спасли меня. Затем вы спасли мир. Вы совершенный герой.}
{2002}{}{Вам больше ненужен Сулик, не так ли?}

