###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите воина.}
{101}{}{Вы видите Серина.}
{102}{}{Он выглядит серьезно раненым и его нога сломана.}
{103}{}{Вы видите Серина. Он серьезно ранен и сломал ногу.}
{104}{}{Вы видите Серина. Его нога забинтована, и он ковыляет.}
{105}{}{Вы видите Серина. Он выглядит лучше и находится в состоянии глубокого сна.}
{106}{}{Вы видите Серин. Похоже, он полностью выздоровел.}

{200}{}{*тьфу* Умри дьявол! Вы не та-}
{201}{}{Успокойся. Ты в безопасности. Гекко мертв.}

{202}{}{Что?! Ну, слава духам, друг. Я боялся, что мне предстоит окончить жизнь здесь.}
{203}{}{Что здесь произошло?}
{204}{}{Джерем и я вышли на неделю охоты. Шли через проходную пещеру в места, где много гекко. Охота пошла плохо. Пришлось бежать. Слишком много гекко с духами ярости. Мы вошли в пещеру. Стали кричать о помощи.
 [Он замолчал на минуту и морщится от боли, поскольку он пытается вытирать ноги.]}
{205}{}{Пожалуйста, продолжай.}
{206}{}{Проход уже был на грани разрушения. Вода просачивалась через трещины в потоке. Опасное место, но это самая короткая дорога до полей. Не более того. Смотри, мы будем кричать, как дураки, а потолок обрушится на нас.}

{207}{}{[Продолжить]}
{208}{}{Бедный Джерем. Я видел как большой камень раздавил его как букашку. Большие камни пролетели мимо меня, но гекко укусил и не промахнулся. Просто, когда я думал, что уже в безопасности, гекко пришел из ниоткуда и сильно укусил за ногу. Сбил меня прямо на землю. Если бы не копье, гекко обедал бы мной, точно. Но у духов были другие планы. Последний большой камень упал прямо на голову гекко. Раздробил его в щебень. Но раздробил и мою ногу тоже.}
{209}{}{[Продолжить]}
{210}{}{Я был придавлен к поверхности земли, без копья. Вдруг я услышал что кто-то идет на меня из темноты. Он был все ближе, и я видел что это большой сердитый гекко. Камнепад только сделал его более шатающимся. Это было когда ты пришел, друг. Действительно, я буду у тебя в долгу.}

{211}{}{Ух ты, какая захватывающая история. Тебе кажется очень повезло, что ты жив. Как твоя нога?}
{212}{}{Не хорошо, друг. Кажется, камень оказался сильнее, чем кости ноги. Я сомневаюсь, что буду вставать и ходить в ближайшее время.}
{213}{}{Не беспокойся, я квалифицированный врач. Позволе мне взглянуть на ногу и я посмотрю, что смогу сделать.}
{214}{}{Не беспокойся, я без проблем вытащу тебя отсюда. Тогда мы сможем попросить шамана взглянуть на твою ногу.}
{215}{}{Нам нужно, вероятно, попросить профессионала приехать сюда и посмотреть на нее. Я быстро попытаюсь найти какую-нибудь помощь. Пещера похоже пуста, поэтому ты будешь в безопасности, пока я не вернусь.}
{216}{}{Кхм... Я не думаю, что достаточно силен вынести тебя отсюда, но я держу пари Сулик смог бы это сделать. [К Сулику] Давай заберем этого парня отсюда.}
{217}{}{Кхм... Я не думаю, что достаточно силен вынести тебя отсюда, но я держу пари Маркус смог это сделать. [К Маркусу] Давай заберем этого парня отсюда.}
{218}{}{[Вы изучили ногу воина. Она сильно разорвана и кости проглядывают в некоторых местах. Вы умело вправили кости на место, остановили кровотечение, наложили шину на ноги, и принялись за работу по исцелению ее.]}
{219}{}{[После примерно 15 минут мучительной работы нога находится в гораздо лучшей форме. Похоже, что этот человек сможет ходить.]}
{220}{}{Хорошо, все что возможно я сделал. Тебе понадобится пара дней отдыха для того, чтобы полностью исцелиться. Не слишком нагружай ногу в течение этого времени, и ты будешь в порядке.}
{221}{}{Святые духи направляют тебя, друг! Я благодарю тебя. Теперь я буду ковылять к шаману. Возьму хороших трав для облегчения боли. Увидимся снова в деревне, друг.}
{222}{}{[Готово]}

{300}{}{Я благодарю Вас, друг. Увидимся снова в деревне.}

{400}{}{Спасибо большое, друг. Действительно, вы блаженны духом.}

{500}{}{zzzZZzzz...}
{501}{}{...zzZZZZzz...zzz...}

{600}{}{Вы исцелили ногу Серина.}

# PC has beaten the Enclave
{1000}{}{Хорошо снова видеть тебя, герой.}
{1001}{}{Я никогда не забуду, что вы сделали для меня, герой.}

{700}{}{Ему нужно больше помощи, чем я могу предложить. Мне лучше пойти дальше.}

