###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите дикаря.}
{101}{}{Вы видите члена племени.}
{102}{}{Один из немногих оставшихся людей в племени.}

{200}{}{Тебе здесь не рады.}
{201}{}{Нам не нравятся такие как ты.}
{202}{}{Уйди, внешник.}
{203}{}{Почему ты мучаешь нас?}
{204}{}{Добро пожаловать, воин.}
{205}{}{Вас всегда будут приветствовать здесь.}
{206}{}{Теперь ты один из нас.}
{207}{}{Благодарим вас за помощь.}
{208}{}{Я думал, внешники это зло. Это не так...}
{209}{}{Не делай этого.}
{210}{}{Работорговцы здесь не нужны!}

# PC has defeated the Enclave
{300}{}{Для нас большая честь видеть Вас здесь, герой.}
{301}{}{Поражение Анклава должно быть воспето в легендах.}

