###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вам что-то нужно?}
{101}{}{Да, мне было интересно, кого вы охраняете.}
{102}{}{Мне? Да нет, мне ничего не нужно. Пока.}

{103}{}{Кого вы охраняете?}
{104}{}{Пока!}

{110}{}{Я охраняю священного вождя племени. Того, кто говорит с духами. Большая честь его охранять. Отсеивать нежелательных, таких как вы. А теперь уходите прочь.}
{111}{}{[Закончить]}

{120}{}{Я говорю уходи, но ты не слушаешь. Я выпускаю духов ярости, когда люди не слушают. Предлагаю вам уйти. Сейчас же.}
{121}{}{[Закончить]}

{130}{}{Слышал о добрых делах, которые вы сделали. Видите, я был неправ в отношении вас. Простите меня за грубость, друг. Войди и встреться с большим человеком. Он будет ждать Вас.}
{131}{}{Слышал о добрых делах, которые вы сделали. Видите, я был неправ в отношении вас. Простите меня за грубость, подруга. Войди и встреться с большим человеком. Он будет ждать Вас.}
{132}{}{Спасибо.}
{133}{}{Благодарю вас.}


{140}{}{Привет, друг.}
{141}{}{Как идут дела, воин?}
{142}{}{Входи.}
{143}{}{Приятно встретиться, воин.}
{144}{}{Полезно заглянуть еще раз, друг.}

{260}{}{Моя убить рабовладельца!}

{300}{}{Вы видите сильного дикаря}
{301}{}{Вы видите охранника вождя племени.}
{302}{}{Этот человек смотрит на тебя пронзительным взглядом. Ясно, что он охраняет кого-то важного.}

# PC has beaten the Enclave
{500}{}{Вы всегда будете желанным гостем здесь, герой.}


