###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы вошли в плотно заросшую лесом местность. Здесь есть узкая тропинка, ведущая на север.}
{101}{}{Вы вошли в маленькую, примитивную деревню.}

{102}{}{Вы узнали, что произошло с пропавшими без вести охотниками.}

{200}{}{Вы спасли сестру Сулика от работорговцев.}

