###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите сильного воина племени.}
{101}{}{Этот дикарь выглядит очень сильным, но не выделяющимся.}

{200}{}{Стой! Шо вы хотите?}
{201}{}{Что ты здесь делаешь?}
{202}{}{Моя охранять пещеру племени. Моя убедиться, что нет плохих людей подкрадывающихся к нам.}
{203}{}{Явижу. Могу ли я осмотреть пещеры?}
{204}{}{Нет. Моя не позволит, чтобы чужие прошли в пещеру. Главный воин сказал так.}
{205}{}{Может быть, позднее.}
{206}{}{Опять ты? Шо НА ЭТОТ раз?}
{207}{}{Просто прохожу мимо. Продолжай хорошо работать.}
{208}{}{Главный воин сказал мне, что мне позволено войти в пещеру, чтобы найти недостающих охотников.}
{209}{}{О, да, моя не видеть этих ребят некоторое время. Надеюсь, что они в порядке. Главный воин разрешил войти? Проходи тогда.}
{210}{}{Спасибо. Я дам тебе знать, если что-нибудь понадобится.}

{300}{}{Эй, почему вы спешите? Вы нашли шонибодь?}
{301}{}{Да, я нашел пропавших охотников. Один из них мертв, а другой тяжело ранен. Мне нужна твоя помощь вытащить его и отнести его к шаману. А я пойду подожду у шамана пока ты спасатешь охотника.}
{302}{}{Члену племени нужна помощь? Моя нужно оказать иму помощь. В пещере? Я иду!}
{303}{}{[Закончить]}

{400}{}{Спасибо за подмогу Серину. Он хороший воин. Ты друг всем дикарям.}
{401}{}{Спасибо. Ну, я должен идти.}
{402}{}{Привет друг. Шо тебе нужно?}
{403}{}{Ничего. Я тут проездом. Береги себя.}

# PC has beaten Enclave
{500}{}{Ты герой! Я тебя обнимаю!}
{501}{}{Научи меня стать героем, как ты!}

