###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите дерганого телохранителя.}
{101}{}{Один из телохранителей Одноглазого Роя. Он выглядит скучно и готов к действию.}

{200}{}{На что ты смотришь, дикарь?}
{201}{}{Собери это дерьмо на дороге, я голоден.}
{202}{}{Когда ж я подстрелю кого-нибудь?}

