###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{}
{101}{}{Вы видите члена племени.}
{102}{}{Вы видите Марли.}
{103}{}{Вы видите воина с нахмуренными бровями.}

{110}{}{Уходите. Я думаю, что он хочет, чтоб его беспокоили незнакомцы. Приходите в другой раз.}
{111}{}{Не надо так грубо. Пока.}

{112}{}{[рычит] Касаешься чужого имущества без разрешения. По крайней мере, колодец работает снова.}
{113}{}{Ага. Благодарности не требуется.}
{114}{}{Как угодно. Неблагодарный.}

{120}{}{Здравствуйте, что вы хотите?}
{121}{}{Я вижу у вас возникли некоторые проблемы с этим колодцем. Что именно случилось?}

{130}{}{[Он состроил гримасу.] Кто-то украл веревку. Я не знаю кто, но я бы задушил их, если б мог. Мы с тех пор зависим от дождевой воды, но этого далеко не достаточно. Нам нужна новая веревка, чтобы мы смогли получить воду. Не думаю, что у Вас есть канат, внешник.}
{131}{}{У меня и правда нет, извините. Впрочем, я много путешествую, так что я могу, скорее всего, достать один для Вас.}
{132}{}{Вообще-то есть. Я посмотрю, смогу ли я исправить этот колодец для вас.}
{133}{}{Нет, но я не думаю, что веревку будет слишком трудно найти. Я уверен, что у вас, ребята, все будет просто отлично. Пока.}

{140}{}{Так ты починил колодец или как?}
{141}{}{Нет, боюсь что нет.}
{142}{}{Для тебя он похож на рабочий? Ты ж стоишь рядом с этой ебаной штукой. Урод.}

{150}{}{Итак, ты уже починил колодец?}
{151}{}{Конечно, я поставил веревку на место. Видишь?}

{160}{}{[Он смотрит на колодец, а потом на свои ноги.] Что хорошего в веревке, если вы не привязали к ней ведро? Или вы, внешники, пьете воду вылизывая мокрую веревку? [Он качает головой и что-то бормочет себе под нос.] Смотри, просто прикрепи ведро, и я вижу, что ты будешь вознагражден.}
{161}{}{Ладно.}
{162}{}{Как насчет того, что *Вы* прикрепите ведро, а я посмотрю, смогу ли я удержаться от надирания твоей задницы?}

{170}{}{Вы прикрепили ведро?}
{171}{}{Нет, пока нет.}
{172}{}{Колодец *выглядит* так, как буд-то в нем есть ведро?}

{180}{}{Так ты починил колодец? Прикрепил ведро и все такое?}
{181}{}{Да, все готово.}
{182}{}{...}

{190}{}{Отлично! Ты знаешь, ты внешник, но не такой плохой, как остальные. Вот, возьмите эти деньги. Я нашел их в тайнике в пустыне и мне они ни к чему.}
{191}{}{Спасибо.}

{200}{}{спасибо, колодец прекрасно работает.}
{201}{}{Спасибо за вашу помощь.}
{202}{}{Рад видеть вас снова.}

{210}{}{Вы не возьмете нас живыми, работорговец!}


{1000}{}{Вы исправили колодец племени.}

#added in RP 1.3
{300}{}{Ладно, нет необходимости так расстраиваться. Я сделаю это сам. [Он бормочет.] Сумасшедший внешник...}
{301}{}{[Закончить]}

{310}{}{[Он смотрит то на вас, то на колодец.] Нет.}
{311}{}{Тогда я думаю больше некому.}

{320}{}{Эй, ты слышишь меня? Я спросил, починен ли колодец?}
{321}{}{. . . [Вы вздыхаете и останавливаетесь у колодца.]}

{330}{}{[Он поворачивается и смотрит на колодец, затем оборачивается обратно к вам.] Да, сейчас он выглядит исправным. Почему бы вам не сказать этого сначала?
 Во всяком случае, вот немного денег. Я нашел их в пустыне, и мне они ни к чему.}
{331}{}{. . . [Вы забираете деньги и уходите.] }

# PC has beaten the Enclave
{2000}{}{Извините, если я был резок к вам, герой. }

