###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите призрак.}
{101}{}{Вы видите Карлу, привидение.}
{102}{}{Вы видите летающего призрака, освещенного холодным сиянием луны.}
{103}{}{ПОМОГИ МНЕ!}
{104}{}{Я не могу отдохнуть.}
{105}{}{Сделайте что-нибудь, пожалуйста.}

{110}{}{Помогите мне! Вы можете мне помочь!?}
{111}{}{Эй, кто вы... что с вами?}

{120}{}{Я тупой призрак! Но я в ловушке здесь.}
{121}{}{Почему? Что случилось?}
{122}{}{Кхе. Вот отстой... Пока!}

{130}{}{Я НЕ ЗНАЮ! Пожалуйста, помогите мне, одиночество меня убивает.}
{131}{}{Ну, я не знаю... как ты умер?}

{140}{}{Я была убита прямо за деревней металлическим парнем со световым пистолетом. Я почувствовала магию в этой палатке, и показалось что человек из нее может мне помочь.
 Но пока мне только удалось свести его с ума!}
{141}{}{Становится понятней. Я поговорю с шаманом. Может быть он в состоянии помочь тебе.}

{150}{}{Пожалуйста. Тишина невыносима.}
{151}{}{[Готово]}

{160}{}{Пожалуйста, сделай что-нибудь...}
{161}{}{Я работаю над этим.}

{200}{}{привидение отказывается говорить с вами.}

#dumb dialogue
{300}{}{Аххх! Бугимен!}

{310}{}{А?}

{320}{}{Я скажу волшебному человеку.}

