###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы входите в западную часть деревни. Местные дикари ходят с удочками.}
{101}{}{Вы входите в небольшую пещеру. Вы слышите шум дальше в пещере.}

