###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Ну, по крайней мере, теперь есть рабочий канат.}
{101}{}{That should just about do it.}
{102}{}{В этом колодце отсутствует веревка и ведро.}
{103}{}{Ты уже это исправил. Помнишь?}

{200}{}{Вы видите колодец.}
{201}{}{Это просто колодец.}
{202}{}{При ближайшем рассмотрении можно заметить, что колодец не работает. Может быть, вы можете это исправить.}
{203}{}{Колодец прекрасно работает снова.}

