###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите воина.}
{101}{}{Вы видите Крома, главного Воина племени.}
{102}{}{Вы видите гигантского мускулистого воина. Его бронзовая кожа несет на себе следы бесчисленных сражений.}

{200}{}{[этой бронзовый гигант выглядит как буд-то его мышцы были высечены из гранита. Под гривой черных волос, его тлеющие голубые глаза видят вас насквозь.] Я Кром, глава воинов этого племени. Кто ты и что привело тебя сюда?}
{201}{}{[этой бронзовый гигант выглядит как буд-то его мышцы были высечены из гранита. Под гривой черных волос, его тлеющие голубые глаза видят вас насквозь.] Я Кром, глава воинов этого племени. О боги, девушка, ваша красота может свести человека с ума.}

{202}{}{Я }
{203}{}{, и я выполняю священную миссию по спасению моей деревни Арройо, от неминуемого уничтожения.}
{204}{}{Я }
{205}{}{, и я выполнял святой квест по спастию моей деревни, Арройо, от неминуемого уничтожения. Я обнаружил, что мне нужно сделать.}
{206}{}{Я простой странник - и больше ничего. Я уже иду дальше.}

#female, CH >= 7
{207}{}{[Улыбка.] Спасибо, Кром.}
{208}{}{Спасибо, но как насчет тебя держать глаза повыше. Ладно, большой парень?}
{209}{}{Избавь меня от комплиментов, хорошо, пресмыкающееся? Я не собираюсь спать с тобой. Черт, я даже не хочу говорить с тобой. Пока.}

{210}{}{Арройо, да знаю, одно из северных племен. Но что значит "от неминуемого уничтожения" как ты говоришь? Ваша деревня за хорошо укрепленным большим каньоном, не правда ли? Конечно, вы можете защититься от враждебных племен или рейдеров.}
{211}{}{Это не внешняя сила, которая нам угрожает. Мое племя умирает изнутри. Мы страдали от страшной засухи, кажется моя деревня обречена чахнуть и умирать, если я не смогу найти святой ГЕКК вовремя.}
{212}{}{Это не внешняя сила, которая нам угрожает. Мое племя умирает изнутри. Мы страдали от страшной засухи, кажется моя деревня обречена чахнуть и умирать, если мы не воспользуемся ГЕККом который я нашел.}

{220}{}{Ах, Комплект по Созданию Города Рая, я читал о нем в старых текстах. [Он мрачно улыбается.] Жаль что в вашем племени наступили тяжелые времена, но глупо возлагать все надежды на нахождение "волшебного артефакта" из довоенного времени.
 Ты уверен, что твое племя не послало тебя на посылки пустышки чтобы просто избавиться от вас?}
{221}{}{Ах, Комплект по Созданию Города Рая, я читал о нем в старых текстах. [Он мрачно улыбается.] Жаль что в вашем племени наступили тяжелые времена, но глупо возлагать все надежды на нахождение "волшебного артефакта" из довоенного времени.
 Как ты можешь быть уверен, что найденное устройство спасет свой народ?}
{222}{}{Конечно, нет. Я успешно покорил храм Жителя Убежища и получил уважаемое звание Избранного. Вот почему я получил этот квест - потому что я доказал что я наиболее квалифицирован. А что ты читал о КоСоГоРе?}
{223}{}{Ты пытаетешься меня обидеть? Я знаю что ты знаешь что я Избранный. Извинись, или я поставлю тебя на место.}
{224}{}{Я не знаю наверняка, но я слишком много рисковал, чтобы остановиться сейчас. Я буду делать все возможное, чтобы спасти мое племеня и не важно каким безумным и опасным это может показаться.}

{230}{}{[Он отмахнулся и пожал своими могучими плечами.] Еще одна ленивая научная старая безделушка, призванная заменить верный и проверенный путь трудового человека против неумолимо перемалывающей его существование Земли - потом и кровью.
 Но если ты действительно веришь что это устройство ваша единственная надежда, то я предлагаю тебе поискать одно из старых подземных убежищ. Я путешествовал далеко и широко, но я не нашел ни одного. Но тогда я особенно и не искал.}
{231}{}{Староста деревни уверена, что найти ГЕКК самый лучший шанс из тех что у нас есть. Поэтому мне была поставлена задача, вот что я собираюсь делать. В любом случае, спасибо за совет.}
{232}{}{Ты говоришь искать убежише? Wow, это *отличный* совет, если бы я только знал раньше. Большое спасибо за совет, большой парень.}

{240}{}{[он смеется от души, затем, со скоростью кажущейся невозможной для человека его размеров, он подносит наконечник копья к твоему горлу.] Избранный, да? Избранный для чего, царствовать над блохастыми собаками? Если ты, дурак, лучший в своем племени то можно предложить, то их гибель будет неизбежной. Теперь, уйди с глаз моих. И если ты бедешь доставлять неприятности, я раскрою твой череп.}
{241}{}{[он смеется от души, затем отвешивает игривый шлепок по твоей заднице - чувствуется что он способен дробить камни.] В тебе горит огонь, девушка. Мне это нравится. Может быть мы найдем огню хорошее применение, что ты на это скажешь?}
{242}{}{Ладно, хорошо, я ухожу.}
{243}{}{Никто не смеет угрожать мне, мудак!}
#PC is female and CH >= 7
{244}{}{И черт с тобой. Я ухожу. Пока.}
{245}{}{Никто не смеет трогать меня, мудак! [Атаковать.]}
{246}{}{Если будешь держать свои руки при себе, тогда я *возможно*, подумаю о помощи.}
{247}{}{Это все зависит от обстоятельств. [Соблазнительно улыбаешься.] Что ты имеешь в виду, большой парень? [Wink.]}

{250}{}{Я хорошо разбираюсь в искусстве сарказма. Унеси-ка свой умный язык в другое место, прежде чем я не отделил его ото рта.}
{251}{}{Ладно, хорошо, я ухожу.}
{252}{}{Никто не смеет угрожать мне, мудак!}

{260}{}{А ты упрямый. Господи, я думаю ты мог бы мне понравиться. [Он смеется и хлопает вас по плечу. Рука, кажется, способна дробить камни.] Пока ты здесь может поможешь нам кое с чем. Что ты на это скажешь?}
{261}{}{А ты упрямая. Господи, я думаю ты могла бы мне понравиться. [Он смеется и хлопает вас по плечу. Рука, кажется, способна дробить камни.] Пока ты здесь может поможешь нам кое с чем. Что ты на это скажешь?}
{262}{}{Конечно, думаю я смогу немного сделать, прежде чем уйду. Что вы хотели от меня?}
{263}{}{Извини, но у меня просто не хватает времени. Я должен уже быть в дороге. Пока.}
#PC is female and CH >= 7
{264}{}{Конечно, думаю я смогу немного сделать, прежде чем уйду. Что вы хотели от меня?}
{265}{}{Если будешь держать свои руки при себе, тогда я *возможно*, подумаю о помощи.}
{266}{}{Извини, но у меня просто не хватает времени. Я должен уже быть в дороге. Пока.}
{267}{}{Никто не смеет трогать меня, мудак! [Атаковать.]}
{268}{}{Это все зависит от обстоятельств. [Соблазнительно улыбаешься.] Что ты имеешь в виду, большой парень? [Wink.]}

# PC is female with Charisma of 7 or higher
# line 200
{270}{}{[Он улыбается по-волчьи. Несмотря на его испуганный и грубый вид, он обладает прочной красотой.] Скажите, девушка, Как вас зовут, и что привело тебя к нам в деревню?}
{280}{}{[удовольствие. [Он смотрит вам в глаза и улыбается волчьи. Несмотря на его испуганный и грубый вид, он обладает прочной красотой.] Скажи мне, девушка, как тебя зовут, и что привело тебя к нам в деревню?}

# Response to “What have you got in mind, big guy?” and “Yeah, big guy. I need something, alright.” (seen further down)
{290}{}{[Кром сделал волчий оскал, а затем взял вас на свои могучие руки.]}
{291}{}{[Сделаем это.]}
{292}{}{Вау! Отпусти меня, ты все неправильно понял!}

# Krom’s response to: “Whoa! Let me go, you got the wrong idea!”
{300}{}{И черт с тобой, искусительница! Уноси свое тело дразнить других. У меня нет времени, чтобы тратить его на тебя.}
{301}{}{Да, ну пошла на хуй тоже. Пока.}
{302}{}{Как угодно. Пока.}

# Get to it.
{310}{}{[несколько часов проходят в дымке потной, жестокой страсти. Наконец, вы лежите на полу в хижине Крома, выдохлись. Кром смотрит на тебя, его глаза пожирают контуры твоего тела.] Бог мой, девочка, ты невероятна!}
{311}{}{Спасибо. Ты тоже не плох.}
{312}{}{Конечно. В конце концов, я Избранная.}

# PC initiates dialog with Krom after having slept with him, but before getting the quest to find the weapons.
{320}{}{[Кром странно усмехается.] Боги знают, что ты делала чудеса для меня, но возможно тебе будет интересно оказать помощь остальной части племени?}
{321}{}{Конечно, думаю я могу помочь немного. Что бы вы хотели от меня?}
{322}{}{Я хотела бы помочь, но мне надо идти. Я сожалею.}
{323}{}{Ты хочешь чтоб меня ебала остальная часть племени? Я что, шлюха?}

# Krom’s response to “You want me to fuck the rest of the tribe?”
{330}{}{[Кром покатывается от смеха.] О Боги, нет! хотя ты можешь делать чудеса для поднятия морального духа моих воинов, я ненавижу разделять такую сладенькую, как ты. Нет, у меня гораздо более прозаическая задача для тебя, если ты готова.}
{331}{}{Это зависит от обстоятельств. Что тебе нужно от меня?}

#trader meeting quest
{340}{}{[Он смотрит на тебя, как будто хочет запомнить эту минуту.] Я скоро встречаюсь с одним из этих проклятых цивилизованных торговцев - пухлой одноглазой собакой - которому доверяю примерно так же, как голодающему радскорпиону.
 Он не обидел нас еще, нет, но у меня нехорошее предчувствие насчет нашей следующей встречи.}
{341}{}{Это почему?}
{342}{}{Я не понимаю, как я вписываюсь в ситуацию. Что у тебя за план?}

{350}{}{Когда мы говорили в прошлый раз, он хвастался что принесет мне что-то действительно чудесное, и я могу тащить все шкурки золотого гекко на встречу. Я не знаю, что это за чудесная штука, но скорее всего это какая-то цивилизованная хрянь и он будет надяться, что я из-за нехватки знаний заплачу гораздо больше, чем она стоит. Вот почему я хочу, чтобы ты вел торг.}
{351}{}{Почему я?}
{352}{}{Извините, но думаю я пасс. Bye.}

{360}{}{Потому что ты моя родня - человек из племени, как они называют нас, - но у тебя есть опыт с общением в цивилизованном мире. Если он попытается провернуть что-нибудь, ты с большей вероятностью чем я это заметишь. Кроме того, я получил хорошее впечатление о тебе и я умею доверять своим инстинктам.}
{361}{}{Потому что ты моя родня - человек из племени, как они называют нас, - но у тебя есть опыт с общением в цивилизованном мире. Если он попытается провернуть что-нибудь, ты с большей вероятностью чем я это заметишь. Кроме того, я получил хорошее впечатление о тебе и я умею доверять своим инстинктам.}
{362}{}{Ладно. Давай сделаем это.}
{363}{}{Ладно, но дай мне минуту, чтобы подготовиться.}
{364}{}{Если я помогу вам, что я за это получу?}

{370}{}{[Он хихикает.] Я предлагаю гостеприимство нашего племени, и возможность произвести на меня впечатление, не более того.}
{371}{}{Ладно. Давай сделаем это.}
{372}{}{Ладно, но дай мне минуту, чтобы подготовиться.}
{373}{}{Не интересует. Пока.}

#give me a moment
{375}{}{Готовы ли вы идти?}
{376}{}{Пока еще нет.}
{377}{}{Ладно. Давай сделаем это.}

#float at trader meeting
{380}{}{Это ваше решение.}

# PC agrees to purchasing the goods
{390}{}{[Кром рассматривает один из недавно приобретенных для племени стимпаков.] Они должны оказаться весьма полезными. [Он подносит стимпак к носу, принюхивается и морщится. Он впрыскивает немного малиновой жидкости
 на руки и осторожно пробует его на вкус.] Проклятие богов! Они наполнены кровью браминов! Это одноглазый негодяй поимел нас. Сейчас он Наверное смеется над нами и упивается своими новыми золотыми шкурами.}
{391}{}{Сожалею об этом. Я не знал, что они были поддельными.}
{392}{}{Ну что ж. Жить и учиться.}

{400}{}{Если я когда-нибудь увижу эту собаку вновь, я с большим удовольствием рассеку его некрасивый череп. Теперь, если вы извините меня, я заберу несколько флаконов крови брамина. Может быть, шаман найдет им применение.}

# PC kills trader, not knowing about the fake goods
{410}{}{Я не люблю уродливых сволочей, но боги, я не планировал разделаться с ним. Конечно, сейчас его товары достались нам бесплатно, но если слух разойдется, что он поехал торговать с нами и не вернулся, мы будем в черном списке торговцев.}
{411}{}{Я не люблю уродливых сволочей, но боги, я не планировал разделаться с ним. Конечно, сейчас его товары достались нам бесплатно, но если слух разойдется, что он поехал торговать с нами и не вернулся, мы будем в черном списке торговцев.}
{412}{}{Извините, похоже я немного увлекся.}
{413}{}{Он был цивилизованной сволочью и заслужил смерть.}
{414}{}{Упс.}

{420}{}{Теперь я вижу, было ошибкой поручать тебе это. Я буду внимательно следить за побой во время пребывания в нашей деревне. Теперь пойдем, позаботимся об этом беспорядке и в путь.}

# PC kills trader, knowing about the fake goods
{430}{}{Лживый ублюдок получил по заслугам. Пусть его судьба станет уроком для любого торговца, который думает, что сможет обманом заполучить наши ценности. Ты правильно поступил, уличив его в обмане. Я вижу, что сделал правильный выбор, доверившись тебе. Ты всегда можешь жить среди нас, теперь наше племя как твое собственное. Тем не менее, я могу попросить тебя о помощи в будущем. А теперь давай оставим эти трупы гнить под солнцем.}
{431}{}{Лживый ублюдок получил по заслугам. Пусть его судьба станет уроком для любого торговца, который думает, что сможет обманом заполучить наши ценности. Ты правильно поступил, уличив его в обмане. Я вижу, что сделал правильный выбор, доверившись тебе. Ты всегда можешь жить среди нас, теперь наше племя как твое собственное. Красивая, обворожительная, и смертельно опасная - девушка, у вас есть все. А теперь давай оставим эти трупы гнить под солнцем.}

# PC does not purchase goods, not knowing they are fake
{440}{}{Я не виню тебя за незаключение сделки. У меня было нехорошее предчувствие по поводу нее. Конечно эти стимпаки были бы полезны племени, но мы жили безбез них, проживем и дальше. Ты всегда можешь жить среди нас, теперь наше племя как твое собственное. Тем не менее, я могу попросить тебя о помощи в будущем. Спасибо за твою помощь.}
{441}{}{Я не виню тебя за незаключение сделки. У меня было нехорошее предчувствие по поводу нее. Конечно эти стимпаки были бы полезны племени, но мы жили безбез них, проживем и дальше. Приглашаем тебя остаться у нас девушка, и жить в нашем 
племени, как в своем собственном. Тем не менее, я могу попросить тебя о помощи в будущем. Спасибо за твою помощь.}
{442}{}{Нет проблем.}
{443}{}{С удовольствием.}
{444}{}{Как угодно. Пока.}

# PC does not purchase goods, knowing they are fake
{450}{}{Если я когда-нибудь снова увижу эту паршивую собаку, я с большим удовольствием рассеку его уродливый череп. Ты правильно поступил, уличив его в обмане. Я вижу, что сделал правильный выбор, доверившись тебе. Ты всегда можешь жить среди нас, теперь наше племя как твое собственное. Тем не менее, я могу попросить тебя о помощи в будущем. Спасибо за твою помощь.}
{451}{}{Если я когда-нибудь снова увижу эту паршивую собаку, я с большим удовольствием рассеку его уродливый череп. Ты правильно поступила, уличив его в обмане. Я вижу, что сделал правильный выбор, доверившись тебе. Ты всегда можешь жить среди нас, теперь наше племя как твое собственное. Тем не менее, я могу попросить тебя о помощи в будущем. Спасибо за твою помощь.}
{452}{}{Нет проблем.}
{453}{}{С удовольствием.}
{454}{}{Как угодно. Пока.}

# PC initiates dialog with Krom after already helping.
{460}{}{[гигантский воин приветственно кивает, когда вы приближаетесь.] Добро пожаловать, друг. Тебе что-то нужно?}
{461}{}{[гигантский воин улыбается и смотрит, как вы подходите.] Клянусь богом, я почти забыл, как ты великолепна. Тебе нужно что-то, девочка?}
{462}{}{Мне было интересно, если бы я мог задать пару вопросов.}
{463}{}{Нет, извините, я подумал, что это было в другой палатке. Я пойду туда сейчас же.}
{464}{}{[[соблазнительно улыбаешься] Да, большой парень. Мне кое-что нужно. [вхдох.]}

# Ask a couple questions
{470}{}{Конечно.}
{471}{}{Ты выглядишь как буд-то тебе пришлось пройти через многое. Мне было интересно, что ты можешь рассказать.}
{472}{}{Что ты можешь рассказать мне об этой деревне?}
{473}{}{Есть что-нибудь в чем я могу вам помочь?}
{474}{}{Кха, это странно. Кажется, я забыл, что я хотел вас спросить. Я вернусь, если я вспомню. Пока.}

# Response to PC asking about Krom’s story.
{480}{}{[Он хихикает.] Да, я полагаю, через многое. Я родом из племени далеко с севера, дальше твоего собственного. Когда мне было 15, мы подверглись нападению со стороны дикарей.
 Я проснулся в тот день мальчишкой, но ко времени захода солнца в этот мрачный день, я уничтожил свой путь к зрелости. Каждый мужчина, женщина и ребенок были мертвы, кроме меня.
 Ах, да что жизнь без боя и борьбы? Она либо сломает человека или закалит его в сталь. Я с гордостью ношу шрамы.}
{481}{}{Так что ты тогда сделал?}
{482}{}{Ладно, я думаю, что я услышал достаточно. Позволь мне спросить что-нибудь другое.}

# Krom’s story, continued
{490}{}{Я свалил тела в кучу и смотрел на них пока они горели в ночи. Потом собрал что мог и пошел бродить. Проводил время с различными племенами, много сражался. Недолго был среди "цивилизованных" людей, но я быстро устал от них. Слишком много дрянных собак прячется за своими пушками. Я предпочитаю наслаждаться хорошей битвой плоти и стали. Я не сложный человек. Дайте мне сражения и пиры, вино и женщин. Что еще можно желать в этом мрачном мире?}
{491}{}{Так как же ты в конечном итоге оказался здесь?}

{500}{}{Я приехал сюда несколько лет назад. Это племя приняло меня и относились ко мне хорошо. Они предложили, чтобы я возглавил их воинов, которых я, естественно, отбирал сам. Я наслаждался этим здесь, рядом с Великой соленой водой. Но я чувствую, страсть к путешествиям растущую внутри меня. Когда-нибудь в ближайшее время, я надеюсь двинуться дальше и посмотрим, что Боги припасли для меня за углом.}
{501}{}{Спасибо за рассказ. Могу ли я спросить тебя что-нибудь другое?}
{502}{}{Спасибо за рассказ. Пока.}

# PC asks Krom about the village.
{510}{}{Давай посмотрим... Большинство членов этой деревни, на самом деле родом из трех небольших племен, которые решили объединиться много лет назад, для того, чтоб спастись от вымирания. Это создает интересное сочетание обычаев и диалектов. Что более важно, создает хорошую смесь женщин. Помимо этого мало что можно рассказать. Это простая деревня, в которой мы боремся, чтобы поддерживать простое существование.}
{511}{}{Хорошо, спасибо. Могу ли я спросить тебя что-нибудь другое?}
{512}{}{Хорошо, спасибо. Пока.}

# PC asks Krom if there’s anything that needs doing
{520}{}{На самом деле, у нас уже возникают проблемы с нашими колодцами. Если ты считаешь, что сможешь помочь, пойди поговори с Мерли, он расскажет об этом.}
{521}{}{Хорошо, спасибо. Пока.}
{522}{}{Хорошо, может быть, я сделаю это. Но сначала можно спросить тебя что-нибудь другое?}

# PC talks to Krom after the hunters go missing and after gathering the weapons.
{530}{}{Рад видеть тебя, приятель. Если у тебя есть минутка, я хотел бы использовать твою помощь снова.}
{531}{}{Рад снова видеть тебя, девочка. Если у тебя есть минутка, я хотел бы использовать твою помощь снова.}
{532}{}{Конечно. Что тебе нужно?}
{533}{}{К сожалению, я сейчас занят. Может быть, позже.}

{540}{}{Двое из наших охотников, Серин и Дером, еще не вернулись с охоты, и некоторые начинают беспокоиться. Они два наших лучших воина, и мне не хотелось бы думать, что с ними что-то случилось. Я бы поискал их сам, но если жители увидят мою личную заинтересованность в этом вопросе, я боюсь, они будут предполагать самое худшее. Я бы не хотел, волновать людей до того как я узнаю, что произошло. Ты сможешь поискать их для меня?}
{541}{}{Хорошо, а где я должен посмотреть?}
{542}{}{Извини, но у меня нет времени искать их. Кроме того, я уверен, они будут появляться в ближайшее время. Пока.}
{543}{}{Я не сиделка для воинов. Пока.}

{550}{}{Проверь охотничьи угодья на севере. Самый быстрый способ добраться туда через пещеры на западе, рядом с Великой соленой водой. Обычно я не советовал бы тот маршрут, так как он под угрозой разрушения, но важно, чтобы ты поторопился. Просто осторожно пройди через пещеру и все должно быть нормально.}
{551}{}{Хорошо, я поспешу и попытаюсь найти их.}
{552}{}{Подожди, ты хочешь, чтобы я прошел через пещеру, которая вот-вот рухнет? Гм... Дерьмо, я вспомнил! Я должен идти спасать мое племя! К сожалению, мне надо бежать.}

{560}{}{Вы принести новости о потерявшихся охотниках?}
{561}{}{Нет еще. Я буду продолжать поиски.}
{562}{}{Нет еще. Я буду продолжать поиски.}

{570}{}{[Кром кивает головой, и лицо его мрачнеет.] Как?}
{571}{}{Был обвал. Один из них был раздавлен падающими камнями, другого придавило обломками, а затем его съел живьем гекко. Было очень жестоко.}

{580}{}{Убиты чертовым обвалом. Проклятие Богов! Я ненавижу терять хороших людей таким образом. Они должны были погибнуть на поле боя, как истинные воины которыми они были.
 [Он качает головой.] Их потеря большой удар для этого племени. Во всяком случае, благодарю тебя за помощь. Твои услуги больше не нужны.}
{581}{}{Конечно, в любое время. Пока.}
{582}{}{Я уверен, что они были великими людьми. Пока.}

# PC rescues Serin.
{590}{}{Спасибо за нахождение охотников. Потеря Джерома велика, так как он был опытным воином. Он должен был умереть на поле битвы, а не под чертовым обвалом. Во всяком случае, Серин должен полностью выздороветь благодаря тебе, друг. Ты всегда будешь желанным гостем здесь.}
{591}{}{Спасибо за нахождение охотников. Потеря Джерома велика, так как он был опытным воином. Он должен был умереть на поле битвы, а не под чертовым обвалом. Во всяком случае, Серин должен полностью выздороветь благодаря тебе, девочка. Ты всегда будешь желанным гостем здесь.}
{592}{}{Спасибо. Береги себя, Кром.}

# PC is dumb
# Response to Krom’s initial dialog
{800}{}{Моя племя, Арройо, нуждаться в помощи. Я могу помочь. Я специально выбранный помошник.}
{801}{}{[Кром хихикает.] Да, вы, безусловно, особенный. [Он улыбается и убирает волосы рукой, кажется способной дробить камни.] Вам нравится помогать, да? Хотели бы вы стать специальным помошником нашего племени?}
{802}{}{Я помогу! Шо вам нужно?}
{803}{}{Нууу... Я помогаю Арройо. Нет времени помогать остальным. Пойду я...}

{810}{}{Нам нужно острое оружие. [Он указывает на его копье.] Пять копий, как это. [Он держит пальцы.] *Пять*. Кроме того, нам нужно *10* ножей, это в два раза больше, чем копий. [Он достает нож и показывает его вам.] Вот так, хорошо? Пять копий, не важно, насколько заточенных. И 10 нормальных ножей. Понял?}
{811}{}{Отей. Я иду найти острые вещи.}
{812}{}{У меня есть много острых вещей. Они все мне не нужны.}

# Dumb PC talks to Krom after denying quest.
{820}{}{Вы передумаете? Хотите быть стать специальным помошником нашего племени?}
{821}{}{Я особенный. Я буду большим помощником для племени.}

# Dumb PC talks to KROM after taking quest.
{830}{}{Вы найдете все острые вещи, которые я просил?}
{831}{}{Я нашел.}
{832}{}{Я все еще ищу.}

# Dumb PC gives Krom the “pointy things”
{840}{}{[Кром быстро проверяет оружие, затем улыбается и похлопывает вас по плечу.] Вы сделали хорошую работу. Спасибо. Теперь беги и держись подальше от неприятностей.}
{841}{}{Пока!}

# Dumb PC talks to Krom after already completing the quest.
{850}{}{[Кром взъерошил ваши волосы.] Там мой специальный помощник. Ты беги и держись подальше от неприятностей.}
{851}{}{Пока!}

# PC has pissed off Krom
{860}{}{Пришел испытать удачу, не так ли?}
{861}{}{Нет, я пришел надрать твою задницу.}
{862}{}{Нет, я просто хотел бы извиниться за то что обидел вас.}
{863}{}{Нет, я просто проходил мимо.}

{870}{}{Ах, кажется я сегодня в настроении прощать, друг. Теперь что я могу для тебя сделать?}
{871}{}{Мне не нравится ссориться с девочонками, но боги, как же я рассердился на такую богиню, как ты? Ну, что я могу для тебя сделать?}
{872}{}{Ничего. Пока.}

# PC has defeated the Enclave
{1000}{}{[гигантский воин кивает вам с уважением] Ну, это ли не великий герой отходов? Это было довольно впечатляющее достижение, послать этих Анклавских собак в ад.
 В самом деле, рассказы о ваших подвигах вдохновили меня на новый поход в себя пустошь.}
{1001}{}{Куда ты пойдешь?}
{1002}{}{Ты просто собирался уехать? Но ты глава воинов племени.}
{1003}{}{Правильно. Желаю удачи на вашем пути, Кром.}

{1010}{}{[Он пожимает плечами.] Восток кажется хорошим направлением, как и любое другое. Да, я думаю пойду на восток и посмотрим, что меня ждет.}
{1020}{}{Они просто выберут другого воина заполнить вакансию. Черт, главные воины обычно не живут дольше, чем пару лет, так что я бы сказал, что я заработал свой уход на пенсию.}

{2000}{}{Вы пополнили племя большим количеством оружия.}

{2500}{}{Вы стали жертвой обмана Роя.}
{2501}{}{Вы напрасно убили купца.}
{2502}{}{Вы разоблачили обман Роя и убедились, что он никогда больше не будет торговать.}
{2503}{}{Вы отказались от торговли с Роем.}
{2504}{}{Вы разоблачили обман Роя.}

{3000}{}{Отойди от гнусного рабовладельца!}

