###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите труп молодой девушки.}
{101}{}{Ее тело было ужасно повреждено мощным оружием. Душа этой девушки, безусловно, в бедственном положении.}

