###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите ящик.}
{101}{}{Ящик похоже полон стимпаков.}
{102}{}{Вы видите ящик, полный бесполезными поддельными стимпаками.}

{200}{}{[После краткого осмотра ящика вы определили, что в нем около 50 стимпаков, так как и сказал торговец.]}
{201}{}{[изучить их дальше.]}
{202}{}{[Закончить.]}
{203}{}{Изучив их внимательно вы не обнаружили ничего необычного.}
{204}{}{[Закончить.]}
{205}{}{При ближайшем рассмотрении эти стимпаки выглядят немного странно. Вы берете один шприц и выдавливаете немного жидкости на ладонь. Нюхая малиновую жидкость вы понимаете, что это действительно кровь брамина.}
{206}{}{[Закончить.]}


