###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите старика, его лицо покрыто глубокими морщинами. Если он и замечает, что вы на него смотрите, то виду не подает.}
{101}{}{Перед вами Кассиди.}
{102}{}{Вы видите старика, его лицо покрыто глубокими морщинами. Он вам кивает.}
{103}{}{Так-так. Раньше я вас тут не видел, незнакомец. Зовут меня Кассиди. Я здесь хозяин. Чем могу служить?}
{104}{}{Так-так, наш таинственный незнакомец. Чем могу быть полезен?}
{105}{}{Ыг ног?}
{106}{}{Хиляй отсюда}
{107}{}{Я ищу Убежище.}
{108}{}{А ты не хочешь уехать отсюда?}
{109}{}{Что тут есть выпить?}
{110}{}{Что тут у вас интересного происходит?}
{111}{}{Сегодня ничем, спасибо.}
{112}{}{Слишком часто били по голове, да? Извини, я по-дебильски не понимаю.}
{113}{}{Деби-ски?}
{114}{}{Убежище? Единственное Убежище, которое я знаю, сейчас внутри города. Здоровенная уродская дыра... не ошибешься, можешь мне поверить.}
{115}{}{Что у вас тут есть выпить?}
{116}{}{Что тут у вас интересного происходит?}
{117}{}{Спасибо за указания. До встречи.}
{118}{}{Пиво по $20, порция виски по $30. Ничего особенного. Что-нибудь закажешь?}
{119}{}{Я ищу Убежище.}
{120}{}{Я выпью пива.}
{121}{}{Я выпью рюмочку.}
{122}{}{Что тут у вас интересного происходит?}
{123}{}{Вообще-то нет, но все равно спасибо.}
{124}{}{"Интересного"? Ха. Дружище, Город Убежища не больно-то "интересное" место... если только охранники не зашевелятся, а тогда лучше спрятаться. А почему ты спрашиваешь? Что тебе понадобилось в этой вонючей дыре?}
{125}{}{Что у вас тут есть выпить?}
{126}{}{Собственно говоря, я ищу Убежище.}
{127}{}{Не может быть, чтобы тут было так уж плохо.}
{128}{}{Вообще-то нет, но все равно спасибо.}
{129}{}{Вот, пожалуйста. Пей. Может, забудешь, где находишься.}
{130}{}{Не может быть, чтобы здесь было так уж плохо.}
{131}{}{Спасибо за выпивку. А мне пора идти.}
{132}{}{Да ну, правда? Черт побери, ну, значит, я ошибся. Думал, ты тут представляешь власть и все такое. А во время налета на прошлой неделе ты дрых, или как?}
{133}{}{Налета?}
{134}{}{Да, такое увлекательное было зрелище. Патруль ворвался сюда в поисках "запрещенных веществ". Сломали дверь, перебили товар, да еще и нескольких клиентов побили.}
{135}{}{А потом что было?}
{136}{}{Грустно слышать это. Мы поговорим об этом позже.}
{137}{}{Потом забрали этого несчастного парня Джошуа - он, мол, сопротивлялся аресту - а потом надрали мне задницу за то, что нашли - только подумайте - НАСТОЯЩИЙ виски. Как будто это не я получил разрешение у Старка три месяца назад. Ублюдки.}
{138}{}{Ух ты. Это серьезно.}
{139}{}{Грустно слышать это. Мы поговорим об этом позже.}
{140}{}{Это еще цветочки. Теперь я должен заплатить штраф охранникам и закупить новый запас алкоголя, чтобы удовлетворить спрос. Думаю, скоро охранники опять заявятся, когда прослышат, что опять есть что громить.}
{141}{}{А в лучшие дни тут как?}
{142}{}{Может, в будущем удача тебе улыбнется. Еще увидимся.}
{143}{}{Да и в лучшие дни тоже погано. Граждане много не пьют, я наливаю в основном торговцам. Следующий сукин сын, который вздумает торговаться, будет носить свою задницу вместо шляпы.}
{144}{}{А зачем ты здесь торчишь, если так ненавидишь это место?}
{145}{}{Грустно слышать это. Я ищу Убежище. Ты можешь мне помочь?}
{146}{}{Грустно слышать это. Надеюсь, все еще наладится.}
{147}{}{У меня больное сердце. Я живу на кардиостимуляторах. Этот город - единственное место, где можно получить медицинскую помощь, так что я решил поселиться здесь.}
{148}{}{Похоже, ты этим местом сыт по горло.}
{149}{}{Понятно. Послушай, я ищу Убежище. Ты не мог бы помочь мне?}
{150}{}{Надеюсь, у тебя все еще наладится. Увидимся.}
{151}{}{Страсть как хочется закрыть магазин, и пусть этот город гниет. Пошли они все в жопу.}
{152}{}{Почему ты не уезжаешь?}
{153}{}{Грустно слышать это. Надеюсь, все еще утрясется.}
{154}{}{Отправиться в пустоши одному? Ха! Меня тошнит от этого места, но не настолько же я глуп.}
{155}{}{Я как раз туда направляюсь. Может быть, пойдем вместе?}
{156}{}{Что ж, тогда удачи.}
{157}{}{Ну, не хочу тебя обижать, но по твоему виду не похоже, что ты можешь кого-то вести. По-моему, пустоши просто сожрут тебя на обед.}
{158}{}{Нет уж, я с работорговцами не якшаюсь. У них отвратительная привычка продавать своих спутников, как только возникнут проблемы с деньгами. Не обижайся.}
{159}{}{Нет уж, мне кажется, ты стоишь одной ногой в могиле, а другой в аду. У меня и без тебя репутация не так чтобы очень.}
{160}{}{Нет уж... похоже, у тебя и без меня народу хватает.}
{161}{}{Хорошо. Ну что ж, удачи.}
{162}{}{Тогда забудь об этом разговоре, старая перечница. Так и торчи тут со своим тупым баром.}
{163}{}{Ну и ладно. Вам же хуже.}
{164}{}{Хе. Ты серьезно?}
{165}{}{Конечно. Почему бы и нет? По виду, ты за себя постоять можешь.}
{166}{}{Если хорошенько подумать, в пустошах чертовски опасно, особенно для человека, у которого проблемы с сердцем. Лучше тебе оставаться здесь.}
{167}{}{Ладно, считай, я с тобой.}
{168}{}{Пора двигаться.}
{169}{}{}
{170}{}{}
{171}{}{В чем дело? Опять у тебя этот вид "Мне надо тебе что-то сказать, но это тебе не понравится".}
{172}{}{Да-а?}
{173}{}{В чем дело? Опять у тебя этот вид "Я начальник, ты дурак".}
{174}{}{Я хочу задать тебе несколько вопросов...}
{175}{}{Похоже, тебе сильно досталось. Возьми стимуляторы и приведи себя в порядок.}
{176}{}{Кэссиди, подожди здесь, пока я не вернусь.}
{177}{}{Убери оружие.}
{178}{}{Стой ближе ко мне.}
{179}{}{Не отходи слишком далеко.}
{180}{}{Нам надо чуть увеличить дистанцию.}
{181}{}{Пойдем, Кэссиди. Нам пора.}
{182}{}{Ничего, спасибо.}

{261}{}{Хочешь, чтобы я всадил Майрону пулю в башку, а? Нет проблем, только скажите.}
{262}{}{Что у тебя на уме?}
{263}{}{Чем тебе помешал Майрон?}
{264}{}{С каким оружием ты умеешь обращаться?}
{265}{}{Вообще-то, у меня была другая просьба...}
{266}{}{Вообще-то, у меня была к тебе просьба...}
{267}{}{Да ладно, пошли.}
{268}{}{Нет, не надо трогать Майрона. По крайней мере, не сегодня. Если что, я тебе скажу.}
{269}{}{Ну, по большей части дробовики и винтовки... ну, это просто личные предпочтения. Я и из пистолета неплохо стреляю.}
{270}{}{Еще что-нибудь?}
{271}{}{Ладно. У меня есть еще вопросы...}
{272}{}{Хорошо. Это была просто проверка.}
{273}{}{Если понадобится поучить кого-нибудь хорошим манерам, дай мне кастет, и я станцую кулаками польку у него на морде.}
{274}{}{Отлично. Еще что-нибудь?}
{275}{}{Ладно. У меня есть еще вопросы...}
{276}{}{Хорошо. Это была просто проверка.}
{277}{}{Ну, хорошо... только между нами, я и с копьем обращаться умею. Мы с приятелями часто охотились с копьями на радскорпионов... ну вот, я жив, а они нет, это ведь о чем-то говорит.}
{278}{}{А что такого зазорного в том, чтобы владеть копьем?}
{279}{}{Ладно. У меня есть еще вопросы...}
{280}{}{Хорошо. Это была просто проверка.}
{281}{}{Как скажете. Только не зови меня дикарем, и все будет в порядке.}
{282}{}{Не хочу, чтобы люди считали меня дикарем с костью в носу. Хе-хе. Никогда не видел дикарей настолько тупых, чтобы ходить с костью в носу, кстати.}
{283}{}{А что в этом такого? Копье - отличное оружие. Масса моих друзей-дикарей пользуется им.}
{284}{}{А ты знаешь, что я тоже "дикарь"?}
{285}{}{Хммм. Слушай, у меня есть еще вопросы...}
{286}{}{Ну, хорошо. Спасибо за информацию.}
{287}{}{Ну вот, не надо шутить шутки со старым Кассиди. Какой же ты дикарь?}
{288}{}{Да, я Избранный.}
{289}{}{Да ладно. Слушай, у меня есть другие вопросы...}
{290}{}{Забудь об этом. Сейчас я не хочу разговаривать на эту тему.}
{291}{}{Ну, черт... к дьяволу, примите мои распроклятые извинения. Я не хотел никого обидеть.}
{292}{}{Все нормально. Слушай, у меня есть и еще вопросы...}
{293}{}{Забудь об этом. Давай двигаться дальше.}
{294}{}{Ну ладно, пока мы никуда не пошли, у меня тоже есть вопрос. Что мы тут делаем? Похоже, мы бегаем с места на место и что-то ищем. Есть у нас какой-то план?}
{295}{}{Мы ищем ГЭКК - Генератор Эдемских Кущ Компактный. Он необходим моей деревне, чтобы она не умерла с голоду.}
{296}{}{Мы идем в Убежище, а потом должны принести ГЭКК в мою деревню.}
{297}{}{Моих односельчан похитили. Я пытаюсь выяснить, что с ними случилось.}
{298}{}{Значит, теперь они бывают компактные, да? Черт, в Библии же об этом ничего нет, правда? Ну, ладно. Пошли охотиться.}
{299}{}{А-а. Ну ладно, просто проверка связи.}
{300}{}{Ой, с удовольствием сделаю пару дырочек в похитителях. Малость пограничного правосудия никому не помешает... ну, по крайней мере не мне.}
{301}{}{Ладно, пойдем.}
{302}{}{То, что говорит этот маленький паршивец, не годится для ушей приличных людей.}
{303}{}{Особенно женских.}
{304}{}{Ну, Кассиди, мне и в голову не приходило, что тебя это волнует. Мое сердце так и трепещет.}
{305}{}{Да? Что ты говоришь?}
{306}{}{Знаешь, ты тоже не образец культурной речи, Кассиди.}
{307}{}{Кто бы говорил. Ладно, пошли.}
{308}{}{Да, но у меня-то есть стиль. А ему просто рот с мылом вымыть надо.}
{309}{}{К тому же, мне не нравится, как он на тебя смотрит.}
{310}{}{Ну, Кассиди, мне и в голову не приходило, что тебя это волнует. Мое сердце так и трепещет.}
{311}{}{Да? Что ты говоришь?}
{312}{}{Кто бы говорил. Ладно, пошли.}
{313}{}{Ну что ты, я совсем не об этом.}
{314}{}{Я только говорю, что в один прекрасный день эта гнусная задница доиграется, и останемся только он, я и дырка в пустыне.}
{315}{}{Что ж, жизнь научит. А у меня есть к тебе другие вопросы...}
{316}{}{Что ж, значит, он в любой момент может получить по полной программе. По-моему, тут не о чем волноваться.}
{317}{}{Успокойся, Кассиди. Оставь Майрона в покое.}
{318}{}{Ненавижу этот город.}
{319}{}{Я-то надеялся, что ноги моей тут больше не будет.}
{320}{}{Город жоп с ручками...}
{321}{}{Это место даже хуже, чем Город Убежища.}
{322}{}{Хорошо, что я проверил оружие до того, как мы сюда притащились.}
{323}{}{Если я отброшу коньки, здесь меня не хорони.}
{324}{}{Тут надо бы поосторожнее. Местные вроде как не слишком дружелюбны.}
{325}{}{Ух ты. Никогда не думал, что увижу Сан-Франциско.}
{326}{}{Никогда не думал, что заставишь старика вроде меня торчать тут столько времени. Давай закончим это дело и пойдем домой.}
{327}{}{Реддинг - шахтерский город. Добывают по большей части золото. В Город Убежища приходило много караванов отсюда.}
{328}{}{Брокен Хиллс - шахтерский город... в основном уран. Тут надо поосторожнее, местечко не ах.}
{329}{}{Меня, похоже, отравили. У тебя есть противоядие?}
{330}{}{Я свечусь, как неоновая вывеска. Есть пилюли от радиации?}
{331}{}{Ох, как меня потрепали. Есть стимуляторы?}
{332}{}{Веди себя как следует, Майрон. Я слежу за тобой.}
{333}{}{Вот только дай мне повод, Майрон...}
{334}{}{Черт побери, Ленни, тебе нужна ванна. Или дезинфекция.}
{335}{}{Слушай, гуль, лучше держись на расстоянии. Тьфу, дрянь какая, до чего ты воняешь.}
{336}{}{Мерзее этой псины я в жизни не видел.}
{337}{}{Спокойно, песик. Кассиди твой друг, ясно?}
{338}{}{Интересно, чем питается этот киберпес. Похоже, людьми.}
{339}{}{Если этот киберпес начнет жрать мою ногу, я его прикончу.}
{340}{}{Аххх. Черт, хорошо, что они наделали миллионы таких штук до того, как сбрасывать бомбу.}
{341}{}{Спасибо.}
{342}{}{Надеюсь, эти стимуляторы не повредят моему сердцу...}
{343}{}{Что з--?! Ой, нет, сердце! Я...*хррррр*}
{344}{}{Извини, я просто любуюсь видом.}
{345}{}{Черт, тогда я просто постою вон там.}
{346}{}{Прошу прощения. Не собирался тебе мешать.}
{347}{}{Аххх. Вот это в самую точку. Спасибо большое.}
{348}{}{*Ик* Хи-хи. Ничего нет лучше старой доброй огненной воды.}
{349}{}{Спасибо. Черт, тебе вроде бы тоже глоточек не помешает.}
{350}{}{Это Убежище. Ну и уродская штуковина, верно?}
{351}{}{Хочешь опять взять меня с собой?}
{352}{}{Я с удовольствием пойду с тобой.}
{353}{}{Моя помощь точно не нужна?}
{354}{}{Все прям чешется, так хочется убраться отсюда.}
{355}{}{Покурить бы.}
{356}{}{Папаша назвал меня в честь какого-то парня из довоенной книжки. Сказал, тот тоже был тот еще сукин сын.}
{357}{}{Хорошо снова пуститься в путь. От жизни в Городе Убежища у меня в голове мутилось.}
{358}{}{Надеюсь, сердце не начнет барахлить, пока мы в дороге...}
{359}{}{Ох, выпить бы.}
{360}{}{Ох, проверю-ка свое снаряжение.}
{361}{}{Распроклятый артрит...}
{362}{}{Если бы я был на двадцать лет моложе, я бы пошел на восток и исследовал Средний Запад. А сейчас, боюсь, слишком поздно.}
{363}{}{Говорят, у них там на Среднем Западе бывают смерчи в милю шириной. Сейчас там здоровенный радиоактивный пыльный котел.}
{364}{}{Интересно, что стало с Техасом...}
{365}{}{Спасибо. Я... ух ты. Что-то перед глазами все плывет.}
{366}{}{Говорят, от этой фигни бывают глю... ух ты! Откуда это сюда понабилось столько змеюк?!}
{367}{}{Каждый раз, как этим пользуюсь, вспоминаю прошлое.}
{368}{}{Ничего похожего на старое дикарское лечение...}
{369}{}{Похоже, скоро мне понадобятся костыли и кресло на колесах.}
{370}{}{Кассиди умирает от сердечного приступа.}
{371}{}{Вы убедили Кассиди присоединиться к вашей группе.}
###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{372}{}{Дай мне сначала принять таблетки от сердца...} # Seraph's Code

###.Magnat.###...Original 1C translation. Need no correction...########################
{1000}{}{Что ж... ну ладно тогда. Я подожду здесь, пока ты не вернешься.}
{1100}{}{Конечно. Но не могу обещать, что не достану его снова, если начнутся проблемы.}
{1200}{}{Ладно, буду держаться поближе. Ты, небось, неприятностей ждешь.}
{1300}{}{Ладно, пойду на расстоянии. Так лучше видно.}
{1400}{}{Ладно, буду тебе спину прикрывать. Если я понадоблюсь, только крикни, я мигом примчусь.}

{2000}{}{Ну, не хочу тебя обижать, но по твоему виду не похоже, что ты можешь кого-то вести. По-моему, пустоши просто сожрут тебя на обед.}
{2100}{}{Нет уж, я с работорговцами не якшаюсь. У них отвратительная привычка продавать своих спутников, как только возникнут проблемы с деньгами. Не обижайся.}
{2200}{}{Нет уж, мне кажется, ты стоишь одной ногой в могиле, а другой в аду. У меня и без тебя репутация не так чтобы очень.}
{2300}{}{Не-а... похоже, у тебя и так народу хватает.}
{2400}{}{Тогда ладно. }

{2999}{}{Ну ладно. Тогда будь осторожен.}
{3000}{}{Пошли.}
{3100}{}{Забудь, что я спрашивал, задница.}
{3200}{}{Тогда ладно. Тебе же хуже.}

{4100}{}{Ну вот, все утряслось. Я могу идти.}
{4200}{}{Ну вот, почти все залатали.}
{4300}{}{Все отлично, но, пожалуй, еще пара стежков мне не помешает.}
{4400}{}{Все, что можно, уже сделано, но чувствую я себя все еще неважно. Если у тебя еще есть стимуляторы, они лишними не будут. Но ходить я все-таки могу.}

{9999}{}{Я хочу задать тебе несколько вопросов...}
{10001}{}{Возьми немного стимуляторов и подлечись.}
{10002}{}{Кэссиди, подожди здесь, пока я не вернусь.}
{10003}{}{Убери оружие.}
{10004}{}{Стой рядом.}
{10005}{}{Не отходи слишком далеко.}
{10006}{}{Нам надо чуть увеличить дистанцию.}
{10100}{}{Пойдем, Кэссиди. Нам пора.}
{10007}{}{Тогда пошли.}

# NEW TOM PARTY MEMBER ADDITIONS

# NODE 1007 WE NEED TO CHANGE DISTANCE
{20000}{}{Ладно, я слушаю.}

# NODE 1008 TALK ABOUT GEAR
{20001}{}{Мое снаряжение? И что с ним не так?}

# NODE 1009 REMOVE ARMOR
{20002}{}{Нет проблем. Все равно слишком жарко. Потею, как шлюха из Нью-Рино.}

# NODE 1010 WHAT WEAPONS CAN YOU USE -- DAN NEEDS TO REPLACE THIS.

# NODE 1100 CAN'T JOIN PARTY BECAUSE LOW CHR -- DAN NEEDS TO REPLACE THIS.

# We need to change our distance from one another
{20003}{}{Попробуем построиться по-другому.}
# I need to talk to you about your gear.
{20004}{}{Нам надо поговорить об оружии и снаряжении.}
# On second thought, I think this distance is OK for now.
{20005}{}{Забудь об этом. Давай ничего не будем менять.}
# Actually, I guess there's nothing I need to really know right about your gear.
{20006}{}{Да ладно. По-хорошему, вопрос вашего снаряжения подождет.}
# I need to remove the armor that you're wearing.
{20007}{}{Сними броню.}
# I need to know what kind of weapons you can use. Transplant original comment from Question Node Line: 264

#added by killap - expansion
###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{30000}{}{О, я на самом деле чувствую себя лучше! Кажется, теперь у меня будет все получаться гораздо лучше!}
{30001}{}{Ого, чувствую изменения! Эти таблетки и правда действуют!}


###.Magnat.###...Added by 1C. May be: a)for female characters (require proper scripts); or b) absent in English version...########################
#женский вариант, Андрей
{10103}{}{Так-так. Раньше я вас тут не видел, незнакомка. Зовут меня Кассиди. Я здесь хозяин. Чем могу служить?}
{10104}{}{Так-так, наша таинственная незнакомка. Чем могу быть полезен?}
{10124}{}{"Интересного"? Ха. Девочка моя, Город Убежища не больно-то "интересное" место... если только охранники не зашевелятся, а тогда лучше спрятаться. А почему ты спрашиваешь? Что тебе понадобилось в этой вонючей дыре?}
{10132}{}{Да ну, правда? Черт побери, ну, значит, я ошибся. Думал, ты тут представляешь власть и все такое. А во время налета на прошлой неделе ты дрыхла, или как?}
