###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите грязного, но сильного на вид человека.}
{101}{}{Вы видите Коннара.}
{102}{}{Эй, ты! Ты что тут делаешь?}
{103}{}{Стой, где стоишь, путник. Что это ты тут делаешь?}
{104}{}{Я тут монстров убиваю.}
{105}{}{А что, тебе какое дело?}
{106}{}{Чего ты верещишь!}
{107}{}{Держу пари, тебя послали эти ублюдки из Города Убежища. Так ты лучше убирайся и оставь в покое остальных.}
{108}{}{Ну, вообще-то уже поздновато.}
{109}{}{Почему?}
{110}{}{Извини, у меня есть работа.}
{111}{}{Только эти существа и не дают Городу Убежища сделать из нас своих так называемых слуг.}
{112}{}{Возможно, но они заплатили мне, чтобы с монстрами было покончено, и я собираюсь покончить с ними.}
{113}{}{Этого они мне не сказали.}
{114}{}{Они заплатили мне, чтобы избавиться от этих монстров, и моя работа уже закончена.}
{115}{}{Идиотина! Ну зачем надо было это делать!}
{116}{}{Мне нужны были деньги.}
{117}{}{Если ты это сделаешь, они придут сюда за нами.}
{118}{}{А мне-то что за дело?}
{119}{}{Надеюсь, эти деньги станут у тебя поперек горла. Они скоро придут за нами.}
{120}{}{Они мне не говорили, зачем им нужно выполнить эту работу.}
{121}{}{Да-а, а я все равно не веду дел с такими мерзавцами.}
{122}{}{Ну, мы не можем позволить тебе сделать это.}
{123}{}{Да делайте, что хотите.}
{124}{}{А ты им так и поверил? Тебе многое предстоит узнать об этом мире, дружище.}
{125}{}{Я могу чем-нибудь помочь?}
{126}{}{Ребят из Города Убежища храбрецами не назовешь. Если показать им пушку, только пятки засверкают. Думаю, если бы у нас было оружие, мы бы с ними справились.}
{127}{}{Какое именно оружие?}
{128}{}{Ну, я неплохо владею дробовиком, а еще у нас есть люди, которые умеют обращаться с винтовкой. Думаю, штуки три будет достаточно.}
{129}{}{Я попробую.}
{130}{}{Тебе здесь не рады. Уходи.}
{131}{}{Мое отношение к этому делу изменилось. Чем я могу помочь?}
{132}{}{Ну что ж, все равно ты тут надолго не задержишься.}
{133}{}{Мне все равно.}
{134}{}{Ты снова здесь! И как там наши пушки?}
{135}{}{Так что конкретно вам было нужно?}
{136}{}{Да, вот они.}
{137}{}{Нам нужно три винтовки и дробовик. И чем скорее ты их нам доставишь, тем лучше.}
{138}{}{Ладно.}
{139}{}{Теперь за следующие несколько месяцев мы сможем что-то сделать с этим местом. И если тебе нужно место, чтобы отдохнуть, здесь тебе всегда будут рады.}
{140}{}{Всегда пожалуйста.}
{141}{}{Добро пожаловать. Все идет хорошо. Мы собираемся расширять нашу деревню.}
{142}{}{Привет еще раз! Как видишь, все идет неплохо. Если у тебя есть время, можешь осмотреться.}
{143}{}{Мы продолжаем строительство. Надеемся к следующему месяцу закончить стены.}
{144}{}{Приветствуем! Как мы и надеялись, деревня снова выросла. А тебе мы всегда рады.}
{145}{}{Мы можем больше не бояться Города Убежища и мирно жить здесь. Еще раз спасибо тебе, странник.}
{146}{}{Только ничего там не убивай, тупица.}
###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{147}{}{Какого черта ты сделал?!?! Сволочь! Scumbag! Я тебя ненавижу!!!}
{148}{}{Ууууппссс...}
{149}{}{Выпустите меня отсюда!!!}
{150}{}{Что сделал я когда-нибудь сделать для вас?}
{151}{}{Помогите!}
{152}{}{Пожалуйста, сделайте то, что я прошу. Вот, это последние наши деньги. [Он отдает вам $ 10000] Если ты не сможешь помочь, они сделают из нас служащих. 
 Поговори с Джо в Городе Убежище. Обычно его можно найти в баре или он там бродит неподалеку. Он знает, что делать.}
{153}{}{Уже иду.}
{154}{}{Могу я задать вам несколько вопросов?}
{155}{}{Разумеется, что вы хотите знать?}
{156}{}{Откуда эти монстры пришли?}
{157}{}{Ничего, до свидания.}
{158}{}{Ну, несколько упырей однажды пришли в нашу деревню. Они что-то бормотали о возрождении... Давали эти амулеты. [Он показывает вам Амулет АНХ] Они говорили, теперь монстры будут защищать нас. Монстры были здесь до сих пор.}
{159}{}{Очень интересно. Могу ли я взять один из этих амулетов?}
{160}{}{Конечно, они дали нам так много! Мы не знаем, что делать с ними. Вот, возьми один.}
{161}{}{Спасибо! До свидания.}
{162}{}{Нет, но я убедил Совет Города не трогать вашу деревню.}
{163}{}{Как это? Убедил? Но... как ты это сделал? Ты мне не врешь, точно?}
{164}{}{Это правда. Неважно, как я смог это сделать, единственное, что важно то, что вы теперь в безопасности.}
{165}{}{Благодарю вас от души... Эх... Кстати, я до сих пор не знаю твоего имени.}
{166}{}{Мое имя - }
{167}{}{Спасибо, }
{168}{}{, о, кстати, те деньги, которые я дал вам купить пушки - вы можете оставить их себе. Еще раз спасибо!}
{169}{}{Мы всегда рады Вам! До свидания.}
{170}{}{Да, но у меня есть лучшая новость. Я убедил Совет Города-Убежища не трогать вашу деревню.}
{171}{}{я это сделаю. У меня есть несколько вопросов, прежде чем отправиться.}
{172}{}{Ничего. Пока.}
{173}{}{Нет еще. Я вернусь, когда достану их.}
{174}{}{Спасибо! До встречи!.}
#additions
{200}{}{Я забрал образцы оружия.}
{201}{}{Я уже позаботился, эти вещи у меня. Но я думаю, что можно обойтись без них. Неужели вы уверены, что это лучший способ решить эту проблему?}
{202}{}{У меня есть то, что вам нужно, но я не чувствую, чтобы это было правильным подходом. Есть разумный человек в совете Города, старший член Совета МакКлюр. 
 Я уверен, что он сможет убедить Совет прийти к мирному решению этой проблемы.}
{203}{}{У меня есть то, что вам нужно, но я не чувствую, что это правильный подход. Есть разумный человек в совете Городе - старший член Совета МакКлюр. 
 Я уверен, что он сможет убедить Совет прийти к мирному урегулированию ситуации.}

{205}{}{Вы знаете кого-то в Совете, которые мог бы выслушать нас? Кхмм... Я не верю этим сволочам из Города. Пожалуйста, вернитесь Город-Убежище и поговори с человеком по имени Джо. 
 Он один из нас, и обычно его можно найти во дворе бара или неподалеку. Он знает, что делать. Пожалуйста, поспеши.}
{206}{}{Ладно. Я доложу, когда у меня будут новости.}

{210}{}{Конечно, это правильный подход. А теперь, отдадите ли вы нам это оружие? Я заплачу вам $10000 за него. Ведь свобода не имеет цены.}
{211}{}{Вы сделали?! Отлично. Я дам тебе $10000 за это оружие. Более чем достаточно, но свобода не имеет цены. Вы оказали нам большую услугу. И вам всегда здесь будут рады.}
{212}{}{Все правильно. Вот оружие.}
{213}{}{Нет, я решил не делать этого. До свидания.}
{214}{}{Нет цены, а? Ну, я знаю, как работает экономика. Повышение спроса ведет к увеличению цены.}
{217}{}{Слушай, я знаю, что Город может быть ханжа, но долго жить в состоянии конфликта у вас не получится. Конечно, вы могли бы отбиваться от них много лет, но такие ситуации никогда не заканчиваются. Позвольте мне найти кого-то в городе и поговорить. Я хорошо заставляю людей слушать так что я уверен, что смогу убедить кого-нибудь в совете Города.}
{218}{}{Хм ... Ладно, я надеюсь у нас одинаковые интересы. Пожалуйста, поговорите с кем-нибудь в Совете и посмотрите, можем ли мы прийти к какому-то соглашению. Я бы предложил поговорить сначала с Джо, один из наших людей, размещенных в Городе Убежище. Ты найдешь его в баре на окрестностях или поблизости. Удачи. Мы все рассчитываем на Вас.}

{220}{}{Что?? Вы пытаетесь надуть нас потратив наши деньги? Нет, мы не будем делать так. Вали отсюда немедленно. Ты тут не нужен.}
{221}{}{Что?? Ох, ладно. Мы можем позволить себе доплатить лишь $1000. Теперь ты отдашь нам пушки?}
{222}{}{Конечно. Одно удовольствие иметь дела с Вами. До свидания.}
{223}{}{Вообзе-то я думаю, что смогу провернуть лучшую сделку в другом месте. До свидания.}
{215}{}{[ЗАКОНЧИТЬ]}
{216}{}{[НАПАСТЬ]}

{225}{}{Отлично. Я дам вам $10000 за этл оружие. Более чем достаточно, но свобода не имеет цены. Вы оказали нам большую услугу. И вам всегда здесь будут рады.}
{226}{}{Все правильно, забирай.}

{300}{}{Любые новости по нашей проблеме?}
{301}{}{Нет еще. Я доложу, когда я что-нибудь найду.}
{302}{}{Я убедил Совет Города не трогать твою деревню.}

{310}{}{Вы готовы расстаться с оружием которое вы несете? Мы готовы заплатить вам $10000 за него.}
{311}{}{Хорошо. Вот это оружие.}
{312}{}{Нет, я по-прежнему не хочу. До свидания.}

{400}{}{Спасибо другу. С этим оружием у нас есть шанс!}
{401}{}{С возвращением. Благодаря вам нам удалось отодвинуть патруль Города. Они не будут больше беспокоить нас.}

{500}{}{Не мешай мне.}

{600}{}{Как говоришь имя твоего контакта в Городе?}
{601}{}{Джо. Он старый парень. Вам надо либо найти его во дворе бара или неподалеку.}
{602}{}{Хорошо, спасибо.}
{603}{}{Итак, кто же он?}
{604}{}{Ну, я не знаю его очень хорошо, но он понастоящему стар. Не очень похоже, но это так. Он несколько раз получил сверху,
 Если вы знаете, что я имею в виду. Всегда говорит о каком-то большом квесте в его молодые годы. Тем не менее, он надежен и следит за ситуацией в Городе.}
{605}{}{Интересно. Я должен идти.}
{606}{}{Он сказал, что помог спасти мир? Вы знаете, у меня самого тоже квест по сохранению мира - по крайней мере я стремлюсь сохранить *мой* мир.}
{610}{}{Правильно. Удачи тебе. Ну, придержите его на потом. Просто не забывайте о помощи нам.}
{611}{}{О, я не буду. Увидимся позже.}
{612}{}{Я, вероятно, будет на самом деле. Я получаю так много квестов, что стало трудно отслеживать. Если бы для жтого не было удобного Пипбоя, кто знает, где бы я был сейчас... Ну, до свидания.}

#RP 1.3
{700}{}{Ах, да. Вот они. [Вручаете ему $10000.]}
{701}{}{Сожалею, мне пришлось потратить их как часть сделки.}
{702}{}{Дерьмо, у меня меньше, чем я должен вернуть вам. Я должно быть потратил их не думая о последствиях. Я достану деньши и верну их обратно вам, как только могу.}

{710}{}{Спасибо. Вот. [Он вручает вам обратно $5000.] Держи. Это все что мы можем сделать, чтобы отплатить тебе.}

{720}{}{О, я вижу. Ну, если эти дениги купили нам свободу, то она стоит каждой монеты. Еще раз спасибо за все, что ты сделал для нас.}

{730}{}{Вот что я скажу - как насчет того, что вы просто отдадите нам обратно половину? У вас есть $ 5000?}
{731}{}{Конечно. Вот [Вы отдаете ему $5,000.]}
{732}{}{К сожалению у меня столько нет.}

{740}{}{Спасибо, }
{741}{}{. Мы не забудем, что ты сделал для нас.}

{750}{}{Я вижу... ну больше не беспокойтесь об этом. Деньги не так важны, как наша свобода. Спасибо.}


