###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите невысокого, веселого человека.}
{101}{}{Вы видите Счастливчика Гарри, владельца магазина.}
{102}{}{О, здравствуйте... Чем могу служить?}
{103}{}{Хочу что-нибудь купить. Можно посмотреть, что у вас есть?}
{104}{}{Вы еще продаете тот плуг, который лежит на улице?}
{105}{}{Моя тор-ГЫ-вацца}
{106}{}{Сегодня ничем, спасибо.}
{107}{}{Извините. Ничем не могу вам помочь, соседушка.}
{108}{}{Ну да, конечно. Я уступлю его, скажем... за восемь сотен.}
{109}{}{Я дам вам за него шестьсот долларов.}
{110}{}{Договорились. Беру.}
{111}{}{Восемьсот? Я вернусь... с деньгами.}
{112}{}{А, ладно, нафиг. Пусть Смиты голодают.}
{113}{}{Он ваш. [Кладет деньги в карман.] Вы его сами заберете или доставить куда-нибудь?}
{114}{}{Доставьте его Смитам.}
{115}{}{Извините, дружище. Это будет стоить вам восемь сотен.}
{119}{}{Дружище, вам нужны деньги, чтобы заплатить мне.}
{120}{}{Я вернусь с деньгами.}
{121}{}{Нет проблем, я прямо сейчас распоряжусь о доставке.}
{122}{}{Думаешь, ты в магазине самообслуживания? Ах ты ворюга... охрана! Охрана!}

###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{123}{}{Торговец Дейв послал Меня. Мы пытаемся починить сломанной водяной насос, и он сказал у тебя есть двигатель на замену.}
{124}{}{Работаешь с Дейвом, а? Да, я знаю этого парня. Вижу, он по-прежнему поручает другим беготню - ленивая сволочь. [Он смеется.] Во всяком случае он получит что хочет, но позвольте мне только проверить наличие. [Гарри идет заднюю комнату, оттуда вы слышите стук передвигаемых ящиков. Он возвращается через минуту.] Да, вот он. $500, и мотор твой.}
{125}{}{Конечно. Вот деньги.}
{126}{}{500? Черт. Я надеюсь получу за это компенсацию. Хорошо, вот деньги.}
{127}{}{Спасибо. Береги себя.}
{128}{}{Пока.}
{1288}{}{Похоже у меня нет достаточно денег. Пока.}

{129}{}{Connar прислал меня за товаром.}
{130}{}{[Гарри быстро стреляет глазами по сторонам нервничая] Да, конечно. Минуточку...}
{131}{}{[Гарри показывает вам винтовки.] Вот, возьмите их. Это будет двенадцать тысяч, и давайте сделаем это побыстрей.}
{132}{}{Конечно, вот деньги.}
{133}{}{Но Коннор только дал мне десять штук.}
{134}{}{Но Коннор только дал мне восемь штук.}
{135}{}{Не мои проблемы. Слушай, мой бизнес борется за жизнь. Если кто-то раскопает, что я продаю Коннору оружие, то все очень быстро станет реально фигово. Кроме того, я уже дал ему скидку.}
{136}{}{Смотри, я за это могу голову сложить... Ах, черт с ним, у меня нет времени, чтобы спорить. Просто забирай их. [Он быстро прячет деньги в карман.] Теперь убирайся отсюда. И помни, ты ничего у меня не покупал.}
{137}{}{Отлично. Но помни, ты не покупал это оружие здесь.}
{138}{}{Это дело. Пока.}
{139}{}{[Больше]}
{140}{}{Ну, подождите немного, пока я не получу денег.}
{141}{}{Ну, ты принес деньги?}
{142}{}{Что если я просто дам вам десять штук?}
{143}{}{А восемь штук?}
{144}{}{Кхмм... двенадцать штук?! У меня нет столько денег, подождите немного, пока я достану деньги.}
{145}{}{Damn! Who could possibly have turned me in?!}
{146}{}{Эй! Мне что в тюрьму за это садиться?}
{147}{}{Ну, по крайней мере там не плохо кормят.}
{148}{}{Что ты смотришь?}
{149}{}{Что теперь будет с моим магазином?}

#added in RP 1.3
{200}{}{$500? Эй, может быть ты дашь мне скидку, я имею в виду, вы и Дейв ведь друзья, не так ли?}
{201}{}{Сказать по правде, мне никогда не нравился этот парень. $500 за мотора. Забирай или вали отсюда.}
{202}{}{Хорошо. Вот деньги.}
{203}{}{Забудь об этом, я ухожу.}
{204}{}{$500!? Забудь об этом, я ухожу.}

