###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите Авто-док}
{101}{}{Перед вами древнего вида Авто-док. Несмотря на его солидный возраст, вам удается привести его в рабочее состояние.}
{102}{}{Вы видите Авто-док.}
{103}{}{Перед вами древнего вида Авто-док. Несмотря на его солидный возраст, вам удается привести его в рабочее состояние.}
{104}{}{Перед вами древнего вида Авто-док. Он как-то нездорово трещит и пощелкивает, от него исходит сильный жар.}
{105}{}{Вы видите Авто-док.}
{106}{}{Перед вами древнего вида Авто-док. Он как-то нездорово трещит и пощелкивает, от него исходит сильный жар.}
{107}{}{Этот древний Авто-док явно остро нуждается в ремонте. Похоже, со времени последнего планового осмотра техником прошло уже несколько десятилетий.}
{108}{}{Повреждения оказались не такими уж серьезными. Пришлось заменить несколько внутренних проводов и почистить диагностическую панель. Нет проблем.}
{109}{}{Вы обследуете Авто-док, но не можете понять, в чем проблема.}
{110}{}{Вы уже исправили Авто-док. Теперь он будет работать лучше. Вы надеетесь.}

