###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите хозяина каравана.}
{101}{}{Вы видите мистера Барона, хозяина каравана.}

{200}{}{Привет путешественник, Роберт Барон меня зовут, хозяином этого каравана являюсь здесь я. Торговать пришел ты?}
{201}{}{Конечно. Давайте посмотрим, что у вас есть.}
{202}{}{На самом деле, я хотел бы поговорить с вами от имени близлежащей деревни.}
{203}{}{Нет. Я сейчас занят своим делом.}
{204}{}{Роберт Барон, да? Часто думаете о походе Бобби Барона? Вот ведь хороший намек, вам не кажется?}

{210}{}{Я думаю, мама ваша может уже вам на голову намекнула раза два. Торговать теперь вы будете, или нет? Я человек занятой.}

{220}{}{Ладно. Что еще?}
{221}{}{Вообще-то, я хотел бы поговорить с вами от имени близлежащей деревни.}
{222}{}{Нет. Я сейчас занят своим делом.}

{230}{}{[Он чешет лоб.] Деревня? Не уверен, что вы-- ах! Вы говорите о той, заполненной кротами-гризли дырке в заднице вниз по дороге?}
{231}{}{Ух, возможно.}
{232}{}{Да, именно.}
{233}{}{Это не дырка в заднице. Они создали сообщество и в некоторых отношениях добились реального прогресса.}

{240}{}{Слушай, я уже встречался с ними, и я скажу вам то же самое я говорил им. Деревня просто слишком мала для ведения дел с ней. Кроме того, это место воняет как ад.}
{241}{}{Правильно. Ну я хотя бы попробовал. Прощай.}
{242}{}{Ну ладно тебе, деревня не так уж далеко от твоей дороги. Постарайся проходить прямо через деревню.}
{243}{}{Есть ли *какой-либо* способ, которым я смогу заставить вас изменить решение?}

{250}{}{И что теперь? Если вы не собираетесь торговать, то прекратите тратить мое ебаное время.}
{251}{}{Давай торговать.}
{252}{}{Извини, я ухожу.}
{253}{}{Я думаю, что буду считать *Вас* мудаком.}
{254}{}{Есть ли *какой-либо* способ, которым я смогу заставить вас изменить решение насчет торговли с деревней?}

{260}{}{Ну и что если я так сделаю? Я не буду волноваться, если потеряю всего лишь *минуту* свернув с моего пути, но если больше - то просто не стоит этого делать.}
{261}{}{Ладно. Я вижу, что бесполезно рассуждать с вами. Прощайте.}
{262}{}{Есть ли *какой-либо* способ, которым я смогу заставить вас передумать?}
{263}{}{Это плохо, потому что умный купец просто накинется на такую возможность. Но если вас это не интересует, я полагаю мне придется на	ти торговца в другом месте...}

{270}{}{Нука подожди минутку. Я не говорил, что я не был заинтересован. Что за возможность о которой вы говорите?}
{271}{}{Видите, село сейчас может и маленькое, но у меня есть инсайдерская информация, гарантирующая, что место будет расти как на дрожжах. Поверьте мне, в ближайшие годы будет бум. И я пришел договориться с вами сейчас, прежде чем они станут слишком большими, и вы упустите свой шанс.}

{280}{}{Кха-ха-ха! Ты думаешь, я считаю, что эта дырка в заднице будет превращаться в что-то стоящее? Я думаю надо прекращать тратить свое время с вами.}
{281}{}{Ладно. Я вижу, что бесполезно рассуждать с вами. Прощайте.}
{282}{}{Есть ли *какой-либо* способ, которым я смогу заставить вас передумать?}

{290}{}{Ты не шутишь, да? Кхм, я полагаю, не мешало бы сделать небольшой крюк там. Черт, это сильно выбивается из моего обычного пути. Спасибо за совет, друг.}
{291}{}{Нет проблем. Увидимся.}
{292}{}{Да. Пока.}

{300}{}{[Он похоже рассмотрит ваш вопрос.] Может быть... о чем именно мы здесь говорим?}
{301}{}{Вы сделаете это село очередной остановкой на маршруте, а в ответ я заплачу вам $500.}
{302}{}{Вы сделаете это село очередной остановкой на маршруте, а в ответ, я сделаю все, чтобы с вашим караваном не случилось *несчастье*.}
{303}{}{Вы сделаете это село очередной остановкой на маршруте, а в ответ, я покажу вам где хорошо провести время, вы такого никогда не забудете.}
{304}{}{Вы сделаете это село очередной остановкой на маршруте, а в ответ вы хорошо проведете время с моей женой, такого вы никогда не забудете.}
{305}{}{Вообще-то ничего. Прощайте.}

{310}{}{Теперь вы говорите на моем языке! Ладно, сделка есть сделка. [Он жадно вырывает у вас деньги и трясет руку.]}
{311}{}{Приятно иметь дело с вами. Пока.}
{312}{}{Пока.}

{320}{}{$500? Не пойдет. Давайте $1000 и по рукам.}
{321}{}{У меня столько нет. Прощайте.}
{322}{}{Ладно, хорошо. Вот $1,000.}
{323}{}{Не пойдет. Счастливо оставаться.}

{330}{}{Теперь вы говорите на моем языке! Вы получили свою сделку. [Он жадно вырывает у вас деньги и трясет руку.]}
{331}{}{Приятно иметь дело с вами. Пока.}
{332}{}{Пока.}

{340}{}{Вы мне угрожаете? Никто не смеет угрожать мне и выжить после этого! (охранникам каравана) Убить эту глупую блядь!}
{341}{}{Только попробуй!}

{350}{}{Слушай, я не хочу неприятностей. Если вы хотите, чтобы я отклонился от маршрута и торговал с той деревней, ладно, не страшно. Черт, это сильно выбивается из моего обычного пути...}
{351}{}{Я рад, что мы договорились. Я буду следить за тобой.}
{352}{}{Вы лучше надйтесь, что это не является проблемой. Потому что если это проблема, то я решу эту проблему. Пока.}
{353}{}{[глядите на него пристально, потом медленно уходите.]}

{360}{}{Ух! О Боже, нет! Перестань кормить меня дерьмом брамина. А теперь убирайся отсюда, и перестань тратить мое время.}
{361}{}{Пошел в жопу, мудак! [Атака.]}
{362}{}{Хорошо, но можно было просто сказать нет. Не нужно быть тупицей о нем.}
{363}{}{Вы еще не знаете, что станете *пропавшим без вести*.}
{364}{}{[Закрываете свое уродливое лицо руками и убегаете плакать.]}

{370}{}{Эх, жаль девушку. Я просто не в настроении сейчас. Можете что-нибудь еще предложить?}
{371}{}{Вы сделаете это село очередной остановкой на маршруте, а в ответ я заплачу вам $500.}
{372}{}{Вы сделаете это село очередной остановкой на маршруте, а в ответ, я сделаю все, чтобы с вашим караваном не случилось *несчастье*.}
{373}{}{Нет. Пока.}

{380}{}{[Он осматривает вас сверху вниз и улыбается.] Я думаю, вы получили свою сделку. Выйдем через черный ход?}
{381}{}{Детка, я получу это в любом случае.}
{382}{}{You'll just have to find out, won't you?}
{383}{}{Угх! Черт, нет! Теперь давай поторопимся и покончим с этим, прежде чем меня вырвет.}

{390}{}{[Торговец улыбается тебе, как пряжка на него на поясе.] Срань господня, Вы знаете, как получить выгодную сделку. Если вы когда-либо станете торговцем, найдите меня. Теперь мне действительно надо идти. Было очень приятно делать бизнес с Вами.}
{391}{}{[Тебя передергивает.] Этого достаточно. Пока.}
{392}{}{В любое время. Пока.}
{393}{}{Пока.}

{400}{}{[Он осматривает Мирию сверху вниз и улыбается.] Я думаю, вы получили свою сделку. [Он жмет вашу руку, затем кладет руку на Мирию и идет с ней в более уединенное место.]}
{401}{}{[Оттаптываете себе ногу во время ожидания.]}
{402}{}{[Свистите пока ждете.]}
{403}{}{[Проверяете свое оружие, пока ждете.]}
{404}{}{[Стоишь тихо и неуклюже рассматриваешь охранников каравана, пока ты слушаешь звуки своей жены оскверненной хозяином каравана.]}

{410}{}{[Через час Роберт Барон и Мирия, теперь потные и взъерошенные от своих сексуальных утех, идут обратно к вам. Вы замечаете, что Мириа прихрамывает. Купец улыбается тебе.] Срань господня, Вы знаете, как получить выгодную сделку. Если вы когда-либо станете торговцем, найдите меня. Теперь мне действительно надо идти. Было очень приятно делать бизнес с Вами.}
{411}{}{Как угодно. Прощай.}
{412}{}{В любое время. Прощай.}
{413}{}{Прощай.}

{500}{}{Вы убедили торговца добавить к своему торговому пути деревню.}
{510}{}{Ты убил купца, лишив тем самым деревню возможности торговать.}

