###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите молодую женщину.}
{101}{}{Вы видите Энн, жену Коннора.}
{102}{}{Она, похоже, занята приготовлением пищи.}

{200}{}{Привет. Меня зовут Анна. Я жена Коннора. Значит, ты тот, кто помогал нам, а? Мы очень ценим все, что ты сделал. Наконец, мы теперь можем жить в мире без опасения, что сволочи из города-Убежища выселят нас из наших домов.}
{201}{}{Рад был оказать помощь. Вы, кажется, очень заняты здесь. Нужна помощь с чем-нибудь?}
{202}{}{Нет проблема. Увидимся.}

{300}{}{На самом деле, я могла бы принять некоторую помощь. Теперь, когда мы более организованы наше население безусловно увеличится. Мы нуждаемся в дополнительных поставках продуктов питания. Скажем, полдюжины яблок и дюжина кусочков сухого мяса.}
{301}{}{Я могу собирать их для вас. Я вернусь, когда я получаю их.}
{302}{}{Не мой тип работы. Пока.}
{303}{}{О, не так ли? Ты такой добрый самаритянин. Дай мне знать, когда ты получишь на руки эти продукты.}

{310}{}{Повезло в сборе продуктов, которые я просила?}
{311}{}{Все еще ищу. Пока.}
{312}{}{Да. Я получил все, что нужно.}
###.Magnat.###...Added by Killap. Need translation...########################
{313}{}{On second thought, you’re going to have to handle this on your own. Sorry.}

###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{320}{}{Отлично. Вот, возьмите это от меня.}
{321}{}{Вот держите.}
{322}{}{Не так быстро. Эти элементы будет стоить вам.}

{330}{}{[Энн смотрит на продукты, которые вы передали ей.] Все выглядит хорошо. Еще раз спасибо.}
{331}{}{Нет проблема. Пока.}
###.Magnat.###...Added by Killap. Need translation...########################
{332}{}{You think I do all this for free? Let's talk money.}

###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{340}{}{[удивление появляется на лице Анны.] Что?! Но, мы бедная деревня. Мы не можем ничего предложить.}
{341}{}{Конечно, у вас есть деньги.}
{342}{}{Похоже, я попридержу этот товар. Тра-та-та.}

{350}{}{А, здравствуйте еще раз. Не думаю, что ты заинтересован в сборе этих продуктов питания для нас, не так ли?}
{351}{}{Да, почему бы и нет. Что вам нужно снова.}
{352}{}{Нет, по-прежнему не интересует.}
{353}{}{О, ты желаешь? Отлично! Нам нужно полдюжины яблок и дюжину кусочков сухого мяса.}

{400}{}{Тебя послал Город?}
{401}{}{Мы имеем право жить здесь и вы это знаете.}
{402}{}{Мне больше нечего вам сказать.}
{403}{}{Еще раз спасибо за все!}
{404}{}{Спасибо!}
{405}{}{Наконец мы в безопасности.}
{406}{}{Спасибо за все! Не забудь зайти еще раз, когда мы расширим это место. Я наконец сделаю кухню и буду готовить дома.}

{410}{}{Здравствуйте еще раз.}
{411}{}{Вы, кажется, очень заняты здесь. Нужна помощь с чем-нибудь?}
{412}{}{Забудь. Пока.}

{420}{}{Как так вышло?}
{421}{}{Как получилось, что ушли? Ах, купец. На самом деле, я потеряла интерес к нему и ушла.}

{430}{}{Что?! Ты понимаешь, это был наш последний шанс достичь соглашения с ним. Мы теперь стоим его и похожи на дураков. Ты обрек нас на смерть.}
{431}{}{Извини, все ошибаются. Прощай.}
{432}{}{Не мои проблемы. Прощай.}
{433}{}{Тебе не нужно беспокоиться о каких-то чертовых торговцах. Потому что я собираюсь убить вас всех.}

{500}{}{Вы убедили торговца добавить деревню к своему торговому маршруту.}
{510}{}{Вы убили торговца тем самым лишив деревню возможности торговать.}
{511}{}{Вы не в состоянии убедить торговца, чтобы он добавил деревню в свой торговый путь.}

