###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите маленького мальчика.}
{101}{}{Вы видите маленькую дувочку.}
{102}{}{Он улыбается увидев вас.}
{103}{}{Она улыбается увидев вас.}
{104}{}{Он смотрит на тебя в неопределенности.}
{105}{}{Она смотрит на тебя в неопределенности.}
{106}{}{Он смотрит на тебя.}
{107}{}{Она смотрит на тебя.}

{200}{}{Спасибо за помощь мистер!}
{201}{}{Ура! Мы спасены!}
{202}{}{Спасибо за помощь мадам!}
{203}{}{Ура! Мы спасены!}
{204}{}{Ты mean (трудный?)!}
{205}{}{Ты здесь, чтобы помочь нам?}

