###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите охрану.}
{101}{}{Вы видите серьезную охрану каравана.}

{200}{}{Поговорите с боссом.}
{201}{}{Я здесь просто для охраны. Поговорите с главным.}

