###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Терминал.}
{101}{}{Терминал управления складом биолаборатории.}
{102}{}{Вы не можете прочитать то, что написано на мониторе.}
{103}{}{Склад биолаборатории
                                              Главное меню
                                                         Извлечь
                                                         Сохранить}
{104}{}{}
{105}{}{}
{106}{}{}
{107}{}{Извлечь}
{108}{}{Сохранить}
{109}{}{Выход}
{110}{}{Гыг.}
{111}{}{[Вы не можете прочитать, что написано на мониторе.]}
{112}{}{Этот терминал не работает
                          Пожалуйста, свяжитесь с системным администратором, чтобы узнать подробности.}
{113}{}{}
{114}{}{Ург}
{115}{}{Выход}
{116}{}{Главное меню извлечения
                                                  Вирусы
                                                    Органы
                                                      Трупы}
{117}{}{}
{118}{}{}
{119}{}{}
{120}{}{Выбрать вирусы}
{121}{}{Выбрать органы}
{122}{}{Выбрать трупы}
{123}{}{Вернуться в Главное Меню}
{124}{}{Выход}
{125}{}{Меню вирусов
                                                            Сибирская язва
                                                              Черная чума (штамм 238)
                                             Черная оспа (штамм 1025)
                                                Лихорадка эбола
                                                         Хантавирус (Штамм 304)}
{126}{}{}
{127}{}{}
{128}{}{}
{129}{}{}
{130}{}{}
{131}{}{Извлечь сибирскую язву}
{132}{}{Извлечь черную чуму}
{133}{}{Извлечь черную оспу}
{134}{}{Извлечь лихорадку эбола}
{135}{}{Извлечь хантавирус}
{137}{}{Вернуться в главное меню извлечения}
{138}{}{Выход}
{139}{}{[Вы видите, как робот проходит мимо стеллажей с биоматериалами и возвращается с крошечным сосудом, который он быстро помещает в отверстие в стене. Вы с интересом наблюдаете, как сосуд перемещается со стерильной территории склада в комнату, где находитесь вы. Ваш интерес быстро сменяется ужасом, когда сосуд падает на землю и разбивается. Похоже, надо бежать.]}
{140}{}{Выход}
{141}{}{Меню органов
                                                  Сердце
                                                      Мозг
                                                   Почка
                                                      Печень
                                                   Легкое}
{142}{}{}
{143}{}{}
{144}{}{}
{145}{}{}
{146}{}{}
{147}{}{Извлечь сердце}
{148}{}{Извлечь мозг}
{149}{}{Извлечь почку}
{150}{}{Извлечь печень}
{151}{}{Извлечь легкое}
{152}{}{Вернуться в главное меню извлечения}
{153}{}{Выход}
{154}{}{Внимание! Ошибка аппарата хранения.
                        [Согласно показаниям приборов, устройства хранения этих органов вышли из строя много лет назад. Бессмысленно извлекать их оттуда, если только вы не собираетесь варить суп.]}
{155}{}{}
{156}{}{Вернуться в меню органов}
{157}{}{Вернуться в главное меню извлечения}
{158}{}{Выход}
{159}{}{Внимание! Ошибка аппарата хранения.
                         Резервуары 101 - 104
                                          Запрашивается коррекция установочных параметров
                                [Чтобы спасти эти мозги, нужен точнейший расчет. Вереницы формул и измерений занимают весь экран. Все это выглядит для вас в высшей степени научно.]}
{160}{}{}
{161}{}{}
{162}{}{}
{163}{}{Попытаться скорректировать параметры}
{164}{}{Вернуться в главное меню извлечения}
{165}{}{Попробовать позже.}
{166}{}{[Из-за вашей глупости все мозги погибли. Возможно, не стоило поднимать температуру до 98.6 по Цельсию. Впрочем, наука никогда не входила в число ваших любимых занятий.]}
{167}{}{Выход.}
{168}{}{[Вы действовали методом проб и ошибок. Вам удалось спасти один из четырех мозгов. В любом случае, наука -- это для ботаников.]}
{169}{}{Извлечь мозг}
{170}{}{[Используя закон больших чисел, вам удалось спасти пятьдесят процентов мозгов. Ученым вас не назовешь.]}
{171}{}{Извлечь мозг}
{172}{}{[Вы, безусловно, знали, что делаете. Вы допустили всего одну ошибку и спасли 3 из 4 мозгов. Вы всегда знали, что когда-нибудь чтение всех этих научных журналов вам пригодится.]}
{173}{}{Извлечь мозг}
{174}{}{[Вы быстро пробежали пальцами по клавишам, и вот кризис миновал: все мозги спасены. Да, наука для вас не просто хобби.]}
{175}{}{Извлечь мозг}
{176}{}{Меню извлечения мозга
                                        Мутировавший мозг
                                        Мозг шимпанзе
                                        Человеческий мозг
                                        Кибермозг}
{177}{}{Меню извлечения мозга
                                        Мутировавший мозг
                                        Мозг шимпанзе
                                        Человеческий мозг
                                        Кибермозг - мертв}
{178}{}{Меню извлечения мозга
                                        Мутировавший мозг
                                        Мозг шимпанзе
                                        Человеческий мозг - мертв
                                        Кибермозг - мертв}
{179}{}{Меню извлечения мозга
                                        Мутировавший мозг
                                        Мозг шимпанзе - мертв
                                        Человеческий мозг - мертв
                                        Кибермозг - мертв}
{180}{}{}
{185}{}{}
{189}{}{}
{193}{}{}
{196}{}{Мутировавший мозг}
{197}{}{Мозг шимпанзе}
{198}{}{Человеческий мозг}
{199}{}{Кибермозг}
{200}{}{[Если судить по показаниям приборов, мозг жив, но уровни нейронной активности гораздо ниже нормальных.]
                                       Извлечь?}
{201}{}{}
{202}{}{Да}
{203}{}{Нет}
{204}{}{[Мозг активен, но графики испускаемых им волн отличаются от человеческого мозга.]
                                       Извлечь?}
{208}{}{[Мозговая активность среднего человека.]
                                       Извлечь?}
{212}{}{[Мозговая деятельность такова, что приборы зашкаливает! Судя по виду сигналов, они имеют одновременно органическое и цифровое происхождение.]
                                       Извлечь?}
{216}{}{[Робот быстро отправляется извлекать нужный мозг. Когда он возвращается, вы замечаете, что у него возникли какие-то проблемы. Ваши опасения подтверждаются, когда робот внезапно взрывается. К счастью для вас, робот успел доставить мозг до взрыва.]}
{217}{}{Выход}
{218}{}{Меню извлечения трупов
                                      Рядовой Доббс}
{219}{}{}
{220}{}{Извлечь рядового Доббса}
{221}{}{Вернуться в главное меню извлечения}
{222}{}{Выход}
{223}{}{[Согласно показаниям приборов, рядовой Доббс жив! Он находится в экспериментальном резервуаре с биогелем.]
        Извлечь?}
{224}{}{}
{225}{}{Да}
{226}{}{Нет}
{227}{}{[Тело рядового Доббса лежит у ваших ног, но, к вашему удивлению, он неожиданно встает и начинает разговаривать с вами. Странно - он совсем не выглядит мертвым.]}
{228}{}{Выход}
{229}{}{В настоящее время на складе нет трупов.}
{230}{}{Вернуться в главное меню извлечения}
{231}{}{Выход}
{232}{}{[Хотя вы своими глазами видите пустые камеры хранения, согласно показаниям приборов все они заполнены. Наверное, ошибка в программе. Ну, что ж.]}
{233}{}{Вернуться в Главное Меню}
{234}{}{Выход}

{300}{}{ не может прочесть то, что написано на мониторе.}
