###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы обнаружили ловушку и едва избежали ее.}
{101}{}{ натыкается на ловушку и едва избегает ее.}

