###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите невезучего сукиного сына.}
{101}{}{Этот человек, кажется, умер очень ужасной смертью.}
{102}{}{Это должно быть, было больно.}


