###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы видите большого кротокрыса.}
{101}{}{Кротокрыс не кажется обеспокоенным твоим присутствием.}
{102}{}{Кротокрыс выглядит очень сердитым.}

{200}{}{Вы уничтожили кротокрысов.}
