###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Need revision...########################
{100}{}{Вы курите сигарету.}
{101}{}{Вы курите другую сигарету.}
{102}{}{Внутри шлема есть предупреждение: "ОПАСНО! - Не курить! '. Вы думаете, что лучше сделать, как написано.}
{103}{}{Вы выкурили их все.}
{104}{}{Сначала вам нужна зажигалка.}


{200}{}{Вы курите сигарету с марихуаной.}
{201}{}{Вы курите еще одну сигарету с марихуаной.}
{203}{}{Вы скурили все сорняки.}

{210}{}{Вау! Эта трава ПРЕВОСХОДНА.}
{211}{}{Хорошо, я просто полежу здесь немного.}
{212}{}{Вы начинаете чувствовать облегдение в голове.}
{213}{}{Я чувствую себя странно сейчас...}
{214}{}{...должно быть так Хакунин чувствует себя в своем саду.}
{215}{}{Это было безумие. Теперь я чувствую себя лучше.}
{216}{}{Вот дерьмо...}
{217}{}{Вы в обмороке.}
{218}{}{Вы просыпаетесь чувствуя себя ошеломленным и сконфуженным.}

{250}{}{Курение - отвратительная привычка для женщины.}

