###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Стальная стена}
{200}{}{Стальная стена}
{300}{}{Стальная стена}
{400}{}{Стальная стена}
{500}{}{Стальная стена}
{600}{}{Стальная стена}
{700}{}{Стальная стена}
{800}{}{Стальная стена}
{900}{}{Стальная стена}
{1000}{}{Стальная стена}
{1100}{}{Стальная стена}
{1200}{}{Стальная стена}
{1300}{}{Стальная стена}
{1400}{}{Стальная стена}
{1500}{}{Стальная стена}
{1600}{}{Стальная стена}
{1700}{}{Стальная стена}
{1800}{}{Стальная стена}
{1801}{}{}
{1900}{}{Стальной угол}
{2000}{}{Стальной угол}
{2100}{}{Стальной угол}
{2200}{}{Стальной угол}
{2300}{}{Стальная стена}
{2400}{}{Стальная стена}
{2500}{}{Стальной угол}
{2600}{}{Стальная стена}
{2700}{}{Стальная стена}
{2800}{}{Стальной угол}
{2900}{}{Стальная стена}
{3000}{}{Стальная стена}
{3001}{}{}
{3100}{}{Стальная Т-образная стена}
{3200}{}{Стальная Т-образная стена}
{3300}{}{Стальная Т-образная стена}
{3400}{}{Стальная перекрестная стена}
{3500}{}{Стальной торец}
{3600}{}{Стальной торец}
{3700}{}{Стальной торец}
{3800}{}{Стальной торец}
{3900}{}{Дверной проем}
{4000}{}{Дверной проем}
{4100}{}{Дверной проем}
{4200}{}{Дверной проем}
{4300}{}{Дверной проем}
{4400}{}{Дверной проем}
{4500}{}{Дверной проем}
{4600}{}{Дверной проем}
{4700}{}{Дверной проем}
{4800}{}{Дверной проем}
{4900}{}{Дверной проем}
{5000}{}{Стена}
{5100}{}{Стена}
{5200}{}{Стена}
{5300}{}{Стена}
{5400}{}{Стена}
{5500}{}{Стальная рама}
{5600}{}{Труба}
{5700}{}{Труба}
{5800}{}{Труба}
{5900}{}{Оборудование}
{5901}{}{}
{6000}{}{Трубы}
{6100}{}{Труба}
{6200}{}{Труба}
{6300}{}{Труба}
{6400}{}{Труба}
{6500}{}{Труба}
{6600}{}{Труба}
{6700}{}{Трубы}
{6800}{}{Трубы}
{6900}{}{Трубы}
{7000}{}{Труба}
{7100}{}{Труба}
{7200}{}{Труба}
{7300}{}{Труба}
{7400}{}{Труба}
{7500}{}{Оборудование}
{7501}{}{}
{7600}{}{Трубы}
{7700}{}{Оборудование}
{7701}{}{}
{7800}{}{Труба}
{7900}{}{Трубы}
{8000}{}{Трубы}
{8100}{}{Труба}
{8200}{}{Трубы}
{8300}{}{Труба}
{8400}{}{Труба}
{8500}{}{Гизмо}
{8600}{}{Деревянный забор}
{8700}{}{Деревянный забор}
{8800}{}{Деревянный забор}
{8900}{}{Деревянный забор}
{9000}{}{Деревянный забор}
{9100}{}{Деревянный забор}
{9200}{}{Стена}
{9300}{}{Стена}
{9400}{}{Стена}
{9500}{}{Стена}
{9600}{}{Жестяная стена}
{9700}{}{Жестяная стена}
{9800}{}{Деревянная стена}
{9900}{}{Деревянная стена}
{10000}{}{Жестяная стена}
{10100}{}{Жестяная стена}
{10200}{}{Деревянная стена}
{10300}{}{Деревянная стена}
{10400}{}{Жестяной дверной проем}
{10500}{}{Жестяной дверной проем}
{10600}{}{Жестяной дверной проем}
{10700}{}{Жестяной дверной проем}
{10800}{}{Стальная стена}
{10900}{}{Стальная стена}
{11000}{}{Деревянная стена}
{11100}{}{Деревянная стена}
{11200}{}{Жестяная стена}
{11300}{}{Деревянная стена}
{11400}{}{Деревянная стена}
{11500}{}{Деревянная стена}
{11600}{}{Деревянная стена}
{11700}{}{Деревянная стена}
{11800}{}{Деревянная стена}
{11900}{}{Деревянная стена}
{12000}{}{Деревянная стена}
{12100}{}{Деревянная стена}
{12200}{}{Деревянная стена}
{12300}{}{Окно}
{12400}{}{Деревянная стена}
{12500}{}{Деревянная стена}
{12600}{}{Деревянная стена}
{12700}{}{Деревянная стена}
{12800}{}{Деревянная стена}
{12900}{}{Деревянная стена}
{13000}{}{Деревянная стена}
{13100}{}{Деревянный дверной проем}
{13200}{}{Деревянный дверной проем}
{13300}{}{Жестяная стена}
{13400}{}{Жестяная стена}
{13500}{}{Стена}
{13600}{}{Жестяная стена}
{13700}{}{Жестяная стена}
{13800}{}{Жестяная стена}
{13900}{}{Жестяная стена}
{14000}{}{Жестяная стена}
{14100}{}{Деревянный забор}
{14200}{}{Деревянный забор}
{14300}{}{Деревянный забор}
{14400}{}{Деревянный забор}
{14500}{}{Деревянный забор}
{14600}{}{Деревянный забор}
{14700}{}{Деревянный забор}
{14800}{}{Деревянный забор}
{14900}{}{Деревянный забор}
{15000}{}{Деревянный забор}
{15100}{}{Деревянный забор}
{15200}{}{Деревянный забор}
{15300}{}{Жестяная стена}
{15400}{}{Жестяная стена}
{15500}{}{Каменная стена}
{15600}{}{Каменный дверной проем}
{15700}{}{Каменный дверной проем}
{15800}{}{Каменная стена}
{15900}{}{Каменная стена}
{16000}{}{Каменная стена}
{16100}{}{Стальные перила}
{16200}{}{Стальные перила}
{16300}{}{Стальные перила}
{16400}{}{Стальные перила}
{16500}{}{Стальные перила}
{16600}{}{Стальные перила}
{16700}{}{Стальные перила}
{16800}{}{Стальные перила}
{16900}{}{Стальные перила}
{17000}{}{Стальные перила}
{17100}{}{Стальные перила}
{17200}{}{Стальные перила}
{17300}{}{Стальные перила}
{17400}{}{Стена пещеры}
{17500}{}{Стена пещеры}
{17600}{}{Стена пещеры}
{17700}{}{Стена пещеры}
{17800}{}{Стена пещеры}
{17900}{}{Стена пещеры}
{18000}{}{Стена пещеры}
{18100}{}{Стена пещеры}
{18200}{}{Стена пещеры}
{18300}{}{Стена пещеры}
{18400}{}{Стена пещеры}
{18500}{}{Стена пещеры}
{18600}{}{Стена пещеры}
{18700}{}{Стена пещеры}
{18800}{}{Стена пещеры}
{18900}{}{Стена пещеры}
{19000}{}{Стена пещеры}
{19100}{}{Стена пещеры}
{19200}{}{Стена пещеры}
{19300}{}{Стена пещеры}
{19400}{}{Стена пещеры}
{19500}{}{Стена пещеры}
{19600}{}{Стена пещеры}
{19700}{}{Стена пещеры}
{19800}{}{Стена пещеры}
{19900}{}{Стена пещеры}
{20000}{}{Стена пещеры}
{20100}{}{Стена пещеры}
{20200}{}{Стена пещеры}
{20300}{}{Стена пещеры}
{20400}{}{Стена пещеры}
{20500}{}{Стена пещеры}
{20600}{}{Стена пещеры}
{20700}{}{Стена пещеры}
{20800}{}{Стена пещеры}
{20900}{}{Стена пещеры}
{21000}{}{Стена пещеры}
{21100}{}{Стена пещеры}
{21200}{}{Стена пещеры}
{21300}{}{Стена пещеры}
{21400}{}{Стена пещеры}
{21500}{}{Стена пещеры}
{21600}{}{Стена пещеры}
{21700}{}{Стена пещеры}
{21800}{}{Стена пещеры}
{21900}{}{Стена пещеры}
{22000}{}{Стена пещеры}
{22100}{}{Стена пещеры}
{22200}{}{Стена пещеры}
{22300}{}{Стена пещеры}
{22400}{}{Стена пещеры}
{22500}{}{Стена пещеры}
{22600}{}{Стена пещеры}
{22700}{}{Стена пещеры}
{22800}{}{Стена пещеры}
{22900}{}{Стена пещеры}
{23000}{}{Стена пещеры}
{23100}{}{Стена пещеры}
{23200}{}{Стена пещеры}
{23300}{}{Стена пещеры}
{23400}{}{Стена пещеры}
{23500}{}{Стена пещеры}
{23600}{}{Стена пещеры}
{23700}{}{Стена пещеры}
{23800}{}{Стена пещеры}
{23900}{}{Стена пещеры}
{24000}{}{Стена пещеры}
{24100}{}{Стена пещеры}
{24200}{}{Стена пещеры}
{24300}{}{Стена пещеры}
{24400}{}{Деревянная стена}
{24500}{}{Деревянная стена}
{24600}{}{Деревянная стена}
{24700}{}{Деревянная стена}
{24800}{}{Деревянная стена}
{24900}{}{Деревянная стена}
{25000}{}{Деревянная стена}
{25100}{}{}
{25200}{}{Стена}
{25300}{}{Стена}
{25400}{}{Стена}
{25500}{}{Стена}
{25600}{}{Стена}
{25700}{}{Стена}
{25800}{}{Стена}
{25900}{}{Стена}
{26000}{}{Стена}
{26100}{}{Стена}
{26200}{}{Стена}
{26300}{}{Стена}
{26400}{}{Стена}
{26500}{}{Стена}
{26600}{}{Стена}
{26700}{}{Стена}
{26800}{}{Стена}
{26900}{}{Стена}
{27000}{}{Стена}
{27100}{}{Стена}
{27200}{}{Стена}
{27300}{}{Стена}
{27400}{}{Стена}
{27500}{}{Стена}
{27600}{}{Стена}
{27700}{}{Стена}
{27800}{}{Стена}
{27900}{}{Стена}
{28000}{}{}
{28100}{}{Стена}
{28200}{}{Стена}
{28300}{}{Стена}
{28400}{}{Стена}
{28500}{}{Стена}
{28600}{}{Стена}
{28700}{}{Стена}
{28800}{}{Стена}
{28900}{}{Стена}
{29000}{}{Стена}
{29100}{}{Стена}
{29200}{}{Стена}
{29300}{}{Стена}
{29400}{}{Стена}
{29500}{}{Стена}
{29600}{}{Стена}
{29700}{}{Стена}
{29800}{}{Стена}
{29900}{}{Стена}
{30000}{}{Стена}
{30100}{}{Стена}
{30200}{}{Стена}
{30300}{}{Стена}
{30400}{}{Стена}
{30500}{}{Стена}
{30600}{}{Стена}
{30700}{}{Стена}
{30800}{}{Стена}
{30900}{}{Стена}
{31000}{}{Стена}
{31100}{}{Стена}
{31200}{}{Стена}
{31300}{}{Стена}
{31400}{}{Стена}
{31500}{}{Стена}
{31600}{}{Стена}
{31700}{}{Стена}
{31800}{}{Стена}
{31900}{}{Стена}
{32000}{}{Стена}
{32100}{}{Стена}
{32200}{}{Стена}
{32300}{}{Стена}
{32400}{}{Стена}
{32500}{}{Стена}
{32600}{}{Стена}
{32700}{}{Стена}
{32800}{}{Стена}
{32900}{}{Стена}
{33000}{}{Стена}
{33100}{}{Стена}
{33200}{}{Стена}
{33300}{}{Стена}
{33400}{}{Стена}
{33500}{}{Стена}
{33600}{}{Стена}
{33700}{}{Стена}
{33800}{}{Стена}
{33900}{}{Стена}
{34000}{}{Стена}
{34100}{}{Стена}
{34200}{}{Стена}
{34300}{}{Стена}
{34400}{}{Стена}
{34500}{}{Стена}
{34600}{}{Стена}
{34700}{}{Стена}
{34800}{}{Стена}
{34900}{}{Стена}
{35000}{}{Стена}
{35100}{}{Стена}
{35200}{}{Стена}
{35300}{}{Стена}
{35400}{}{Стена}
{35500}{}{Стена}
{35600}{}{Стена}
{35700}{}{Стена}
{35800}{}{Стена}
{35900}{}{Стена}
{36000}{}{Стена}
{36100}{}{Стена}
{36200}{}{Стена}
{36300}{}{Стена}
{36400}{}{Стена}
{36500}{}{Стена}
{36600}{}{Деревянная стена}
{36700}{}{Деревянная стена}
{36800}{}{Стена}
{36900}{}{Стена}
{37000}{}{Стена}
{37100}{}{Стена}
{37200}{}{Стена}
{37300}{}{Стена}
{37400}{}{Стена}
{37500}{}{Стена}
{37600}{}{Стена}
{37700}{}{Стена}
{37800}{}{Стена}
{37900}{}{Стена}
{38000}{}{Стена}
{38100}{}{Стена}
{38200}{}{Стена}
{38300}{}{Стена}
{38400}{}{Стена}
{38500}{}{Стена}
{38600}{}{Стена}
{38700}{}{Стена}
{38800}{}{Стена}
{38900}{}{Стена}
{39000}{}{Стена}
{39100}{}{Стена}
{39200}{}{Стена}
{39300}{}{Стена}
{39400}{}{Стена}
{39500}{}{Стена}
{39600}{}{Стена}
{39700}{}{Стена}
{39800}{}{Стена}
{39900}{}{Стена}
{40000}{}{Стена}
{40100}{}{Стена}
{40200}{}{Стена}
{40300}{}{Стена}
{40400}{}{Стена}
{40500}{}{Стена}
{40600}{}{Стена}
{40700}{}{Стена}
{40800}{}{Стена}
{40900}{}{Стена}
{41000}{}{Стена}
{41100}{}{Стена}
{41200}{}{Стена}
{41300}{}{Стена}
{41400}{}{Стена}
{41500}{}{Стена}
{41600}{}{Стена}
{41700}{}{Стена}
{41800}{}{Стена}
{41900}{}{Деревянная стена}
{42000}{}{Деревянная стена}
{42100}{}{Деревянная стена}
{42200}{}{Стена}
{42300}{}{Стена}
{42400}{}{Стена}
{42500}{}{Стена}
{42600}{}{Стена}
{42700}{}{Стена}
{42800}{}{Стена}
{42900}{}{Стена}
{43000}{}{Стена}
{43100}{}{Стена}
{43200}{}{Стена}
{43300}{}{Стена}
{43400}{}{Стена}
{43500}{}{Стена}
{43600}{}{Стена}
{43700}{}{Стена}
{43800}{}{Стена}
{43900}{}{Стена}
{44000}{}{Стена}
{44100}{}{Стена}
{44200}{}{Стена}
{44300}{}{Стена}
{44400}{}{Стена}
{44500}{}{Стена}
{44600}{}{Стена}
{44700}{}{Стена}
{44800}{}{Стена}
{44900}{}{Стена}
{45000}{}{Стена}
{45100}{}{Стена}
{45200}{}{Стена}
{45300}{}{Стена}
{45400}{}{Стена}
{45500}{}{Стена}
{45600}{}{Стена}
{45700}{}{Стена}
{45800}{}{Стена}
{45900}{}{Стена}
{46000}{}{Стена}
{46100}{}{Стена}
{46200}{}{Стена}
{46300}{}{Стена}
{46400}{}{Стена}
{46500}{}{Стена}
{46600}{}{Стена}
{46700}{}{Бар}
{46800}{}{Бар}
{46900}{}{Бар}
{47000}{}{Бар}
{47100}{}{Бар}
{47200}{}{Бар}
{47300}{}{Бар}
{47400}{}{Бар}
{47500}{}{Бар}
{47600}{}{Бар}
{47700}{}{Бар}
{47800}{}{Бар}
{47900}{}{Бар}
{48000}{}{Бар}
{48100}{}{Бар}
{48200}{}{Бар}
{48300}{}{Бар}
{48400}{}{Бар}
{48500}{}{Бар}
{48600}{}{Бар}
{48700}{}{Деревянный забор}
{48800}{}{Деревянный забор}
{48900}{}{Дверная коробка}
{49000}{}{Дверная коробка}
{49100}{}{Дверная коробка}
{49200}{}{Дверная коробка}
{49300}{}{Дверная коробка}
{49400}{}{Дверная коробка}
{49500}{}{Дверная коробка}
{49600}{}{Стена}
{49700}{}{Стена}
{49800}{}{Стена}
{49900}{}{Стена}
{50000}{}{Стена}
{50100}{}{Стена}
{50200}{}{Стена}
{50300}{}{Стена}
{50400}{}{Стена}
{50500}{}{Стена}
{50600}{}{Стена}
{50700}{}{Стена}
{50800}{}{Стена}
{50900}{}{Стена}
{51000}{}{Стена}
{51100}{}{Стена}
{51200}{}{Стена}
{51300}{}{Стена}
{51400}{}{Стена}
{51500}{}{Стена}
{51600}{}{Стена}
{51700}{}{Стена}
{51800}{}{Стена}
{51900}{}{Стена}
{52000}{}{Стена}
{52100}{}{Стена}
{52200}{}{Стена}
{52300}{}{Стена}
{52400}{}{Стена}
{52500}{}{Стена}
{52600}{}{Стена}
{52700}{}{Стена}
{52800}{}{Стена}
{52900}{}{Стена}
{53000}{}{Стена}
{53100}{}{Стена}
{53200}{}{Стена}
{53300}{}{Стена}
{53400}{}{Стена}
{53500}{}{Стена}
{53600}{}{Стена}
{53700}{}{Стена}
{53800}{}{Стена}
{53900}{}{Стена}
{54000}{}{Стена}
{54100}{}{Стена}
{54200}{}{Стена}
{54300}{}{Стена}
{54400}{}{Стена}
{54500}{}{Стена}
{54600}{}{Стена}
{54700}{}{Стена}
{54800}{}{Стена}
{54900}{}{Стена}
{55000}{}{Стена}
{55100}{}{Стена}
{55200}{}{Стена}
{55300}{}{Стена}
{55400}{}{Стена}
{55500}{}{Стена}
{55600}{}{Стена}
{55700}{}{Стена}
{55800}{}{Стена}
{55900}{}{Стена}
{56000}{}{Стена}
{56100}{}{Стена}
{56200}{}{Дверной проем}
{56300}{}{Дверной проем}
{56400}{}{Окно}
{56500}{}{Стена}
{56600}{}{Стена}
{56700}{}{Стена}
{56800}{}{Стена}
{56900}{}{Стена}
{57000}{}{Стена}
{57100}{}{Стена}
{57200}{}{Стена}
{57300}{}{Стена}
{57400}{}{Стена}
{57500}{}{Стена}
{57600}{}{Стена}
{57700}{}{Стена}
{57800}{}{Стена}
{57900}{}{Стена}
{58000}{}{Дверной проем}
{58100}{}{Стена}
{58200}{}{Дверной проем}
{58300}{}{Дверной проем}
{58400}{}{Окно}
{58500}{}{Стена}
{58600}{}{Стена}
{58700}{}{Стена}
{58800}{}{Стена}
{58900}{}{Стена}
{59000}{}{Стена}
{59100}{}{Стена}
{59200}{}{Стена}
{59300}{}{Стена}
{59400}{}{Стена}
{59500}{}{Стена}
{59600}{}{Стена}
{59700}{}{Стена}
{59800}{}{Стена}
{59900}{}{Стена}
{60000}{}{Стена}
{60100}{}{Стена}
{60200}{}{Стена}
{60300}{}{Стена}
{60400}{}{Стена}
{60500}{}{Стена}
{60600}{}{Стена}
{60700}{}{Стена}
{60800}{}{Стена}
{60900}{}{Стена}
{61000}{}{Стена}
{61100}{}{Стена}
{61200}{}{Стена}
{61300}{}{Стена}
{61400}{}{Стена}
{61500}{}{Стена}
{61600}{}{Стена}
{61700}{}{Стена}
{61800}{}{Стена}
{61900}{}{Стена}
{62000}{}{Стена}
{62100}{}{Стена}
{62200}{}{Стена}
{62300}{}{Стена}
{62400}{}{Стена}
{62500}{}{Стена}
{62600}{}{Стена}
{62700}{}{Стена}
{62800}{}{Стена}
{62900}{}{Стена}
{63000}{}{Стена}
{63100}{}{Стена}
{63200}{}{Стена}
{63300}{}{Стена}
{63400}{}{Стена}
{63500}{}{Стена}
{63600}{}{Стена}
{63700}{}{Стена}
{63800}{}{Окно}
{63900}{}{Окно}
{64000}{}{Окно}
{64100}{}{Окно}
{64200}{}{Окно}
{64300}{}{Окно}
{64400}{}{Окно}
{64500}{}{Окно}
{64600}{}{Стена}
{64700}{}{Стена}
{64800}{}{Стена}
{64900}{}{Стена}
{65000}{}{Стена}
{65100}{}{Стена}
{65200}{}{Стена}
{65300}{}{Стена}
{65400}{}{Стена}
{65500}{}{Стена}
{65501}{}{Стена}
{65502}{}{Стена}
{65503}{}{Стена}
{65504}{}{Стена}
{65505}{}{Стена}
{65506}{}{Стена}
{65507}{}{Стена}
{65508}{}{Стена}
{65509}{}{Стена}
{65510}{}{Стена}
{65511}{}{Стена}
{65512}{}{Стена}
{65513}{}{Стена}
{65514}{}{Стена}
{65515}{}{Стена}
{65516}{}{Стена}
{65517}{}{Стена}
{65518}{}{Стена}
{65519}{}{Стена}
{65520}{}{Стена}
{65521}{}{Стена}
{65522}{}{Стена}
{65523}{}{Стена}
{65524}{}{Стена}
{65525}{}{Стена}
{65526}{}{Стена}
{65527}{}{Стена}
{65528}{}{Стена}
{65529}{}{Стена}
{65530}{}{Стена}
{65531}{}{Стена}
{65532}{}{Стена}
{65533}{}{Стена}
{65534}{}{Стена}
{0}{}{Стена}
{1}{}{Стена}
{2}{}{Стена}
{3}{}{Стена}
{4}{}{Стена}
{5}{}{Стена}
{6}{}{Стена}
{7}{}{Стена}
{8}{}{Стена}
{9}{}{Стена}
{10}{}{Стена}
{11}{}{Стена}
{12}{}{Стена}
{13}{}{Стена}
{14}{}{Стена}
{15}{}{Стена}
{16}{}{Стена}
{17}{}{Стена}
{18}{}{Стена}
{19}{}{Стена}
{20}{}{Стена}
{21}{}{Стена}
{22}{}{Стена}
{23}{}{Стена}
{24}{}{Стена}
{25}{}{Стена}
{26}{}{Стена}
{27}{}{Стена}
{28}{}{Стена}
{29}{}{Стена}
{30}{}{Стена}
{31}{}{Стена}
{32}{}{Стена}
{33}{}{Стена}
{34}{}{Стена}
{35}{}{Стена}
{36}{}{Стена}
{37}{}{Стена}
{38}{}{Стена}
{39}{}{Стена}
{40}{}{Стена}
{41}{}{Стена}
{42}{}{Стена}
{43}{}{Стена}
{44}{}{Стена}
{45}{}{Стена}
{46}{}{Стена}
{47}{}{Стена}
{48}{}{Стена}
{49}{}{Стена}
{50}{}{Стена}
{51}{}{Стена}
{52}{}{Стена}
{53}{}{Стена}
{54}{}{Стена}
{55}{}{Стена}
{56}{}{Стена}
{57}{}{Стена}
{58}{}{Стена}
{59}{}{Стена}
{60}{}{Стена}
{61}{}{Стена}
{62}{}{Стена}
{63}{}{Стена}
{64}{}{Стена}
{65}{}{Стена}
{66}{}{Стена}
{67}{}{Стена}
{68}{}{Стена}
{69}{}{Стена}
{70}{}{Стена}
{71}{}{Стена}
{72}{}{Стена}
{73}{}{Стена}
{74}{}{Стена}
{75}{}{Стена}
{76}{}{Стена}
{77}{}{Стена}
{78}{}{Стена}
{79}{}{Стена}
{80}{}{Стена}
{81}{}{Стена}
{82}{}{Стена}
{83}{}{Стена}
{84}{}{Стена}
{85}{}{Стена}
{86}{}{Стена}
{87}{}{Стена}
{88}{}{Стена}
{89}{}{Стена}
{90}{}{Стена}
{91}{}{Стена}
{92}{}{Стена}
{93}{}{Стена}
{94}{}{Стена}
{95}{}{Стена}
{96}{}{Стена}
{97}{}{Стена}
{98}{}{Стена}
{99}{}{Стена}
{100}{}{Стена}
{101}{}{Стена}
{102}{}{Стена}
{103}{}{Стена}
{104}{}{Стена}
{105}{}{Стена}
{106}{}{Стена}
{107}{}{Стена}
{108}{}{Стена}
{109}{}{Стена}
{110}{}{Стена}
{111}{}{Стена}
{112}{}{Стена}
{113}{}{Стена}
{114}{}{Стена}
{115}{}{Стена}
{116}{}{Стена}
{117}{}{Стена}
{118}{}{Стена}
{119}{}{Стена}
{120}{}{Стена}
{121}{}{Стена}
{122}{}{Стена}
{123}{}{Стена}
{124}{}{Стена}
{125}{}{Стена}
{126}{}{Стена}
{127}{}{Стена}
{128}{}{Стена}
{129}{}{Стена}
{130}{}{Стена}
{131}{}{Стена}
{132}{}{Стена}
{133}{}{Стена}
{134}{}{Стена}
{135}{}{Стена}
{136}{}{Стена}
{137}{}{Стена}
{138}{}{Стена}
{139}{}{Стена}
{140}{}{Стена}
{141}{}{Стена}
{142}{}{Стена}
{143}{}{Стена}
{144}{}{Стена}
{145}{}{Стена}
{146}{}{Стена}
{147}{}{Стена}
{148}{}{Стена}
{149}{}{Стена}
{150}{}{Стена}
{151}{}{Стена}
{152}{}{Стена}
{153}{}{Стена}
{154}{}{Стена}
{155}{}{Стена}
{156}{}{Стена}
{157}{}{Стена}
{158}{}{Стена}
{159}{}{Стена}
{160}{}{Стена}
{161}{}{Стена}
{162}{}{Стена}
{163}{}{Стена}
{164}{}{Стена}
{165}{}{Стена}
{166}{}{Стена}
{167}{}{Стена}
{168}{}{Стена}
{169}{}{Стена}
{170}{}{Стена}
{171}{}{Стена}
{172}{}{Стена}
{173}{}{Стена}
{174}{}{Стена}
{175}{}{Стена}
{176}{}{Стена}
{177}{}{Стена}
{178}{}{Стена}
{179}{}{Стена}
{180}{}{Стена}
{181}{}{Стена}
{182}{}{Стена}
{183}{}{Стена}
{184}{}{Стена}
{185}{}{Стена}
{186}{}{Стена}
{187}{}{Стена}
{188}{}{Стена}
{189}{}{Стена}
{190}{}{Стена}
{191}{}{Стена}
{192}{}{Стена}
{193}{}{Стена}
{194}{}{Стена}
{195}{}{Стена}
{196}{}{Стена}
{197}{}{Стена}
{198}{}{Стена}
{199}{}{Стена}
{200}{}{Стена}
{201}{}{Стена}
{202}{}{Стена}
{203}{}{Стена}
{204}{}{Стена}
{205}{}{Стена}
{206}{}{Стена}
{207}{}{Стена}
{208}{}{Стена}
{209}{}{Стена}
{210}{}{Стена}
{211}{}{Стена}
{212}{}{Стена}
{213}{}{Стена}
{214}{}{Стена}
{215}{}{Стена}
{216}{}{Стена}
{217}{}{Стена}
{218}{}{Стена}
{219}{}{Стена}
{220}{}{Стена}
{221}{}{Стена}
{222}{}{Стена}
{223}{}{Стена}
{224}{}{Стена}
{225}{}{Стена}
{226}{}{Стена}
{227}{}{Стена}
{228}{}{Стена}
{229}{}{Стена}
{230}{}{Стена}
{231}{}{Стена}
{232}{}{Стена}
{233}{}{Стена}
{234}{}{Стена}
{235}{}{Стена}
{236}{}{Стена}
{237}{}{Стена}
{238}{}{Стена}
{239}{}{Стена}
{240}{}{Стена}
{241}{}{Стена}
{242}{}{Стена}
{243}{}{Стена}
{244}{}{Стена}
{245}{}{Стена}
{246}{}{Стена}
{247}{}{Стена}
{248}{}{Стена}
{249}{}{Стена}
{250}{}{Стена}
{251}{}{Стена}
{252}{}{Стена}
{253}{}{Стена}
{254}{}{Стена}
{255}{}{Стена}
{256}{}{Стена}
{257}{}{Стена}
{258}{}{Стена}
{259}{}{Стена}
{260}{}{Стена}
{261}{}{Стена}
{262}{}{Стена}
{263}{}{Стена}
{264}{}{Стена}
{265}{}{Стена}
{266}{}{Стена}
{267}{}{Стена}
{268}{}{Стена}
{269}{}{Стена}
{270}{}{Стена}
{271}{}{Стена}
{272}{}{Стена}
{273}{}{Стена}
{274}{}{Стена}
{275}{}{Стена}
{276}{}{Стена}
{277}{}{Стена}
{278}{}{Стена}
{279}{}{Стена}
{280}{}{Стена}
{281}{}{Стена}
{282}{}{Стена}
{283}{}{Стена}
{284}{}{Стена}
{285}{}{Стена}
{286}{}{Стена}
{287}{}{Стена}
{288}{}{Стена}
{289}{}{Стена}
{290}{}{Стена}
{291}{}{Стена}
{292}{}{Стена}
{293}{}{Стена}
{294}{}{Стена}
{295}{}{Стена}
{296}{}{Стена}
{297}{}{Стена}
{298}{}{Стена}
{299}{}{Стена}
{300}{}{Стена}
{301}{}{Стена}
{302}{}{Стена}
{303}{}{Стена}
{304}{}{Стена}
{305}{}{Стена}
{306}{}{Стена}
{307}{}{Стена}
{308}{}{Стена}
{309}{}{Стена}
{310}{}{Стена}
{311}{}{Стена}
{312}{}{Стена}
{313}{}{Стена}
{314}{}{Стена}
{315}{}{Стена}
{316}{}{Стена}
{317}{}{Стена}
{318}{}{Стена}
{319}{}{Стена}
{320}{}{Стена}
{321}{}{Стена}
{322}{}{Стена}
{323}{}{Стена}
{324}{}{Стена}
{325}{}{Стена}
{326}{}{Стена}
{327}{}{Стена}
{328}{}{Стена}
{329}{}{Стена}
{330}{}{Стена}
{331}{}{Стена}
{332}{}{Стена}
{333}{}{Стена}
{334}{}{Стена}
{335}{}{Стена}
{336}{}{Стена}
{337}{}{Стена}
{338}{}{Стена}
{339}{}{Стена}
{340}{}{Стена}
{341}{}{Стена}
{342}{}{Стена}
{343}{}{Стена}
{344}{}{Стена}
{345}{}{Стена}
{346}{}{Стена}
{347}{}{Стена}
{348}{}{Стена}
{349}{}{Стена}
{350}{}{Стена}
{351}{}{Стена}
{352}{}{Стена}
{353}{}{Стена}
{354}{}{Стена}
{355}{}{Стена}
{356}{}{Стена}
{357}{}{Стена}
{358}{}{Стена}
{359}{}{Стена}
{360}{}{Стена}
{361}{}{Стена}
{362}{}{Стена}
{363}{}{Стена}
{364}{}{Стена}
{365}{}{Стена}
{366}{}{Стена}
{367}{}{Стена}
{368}{}{Стена}
{369}{}{Стена}
{370}{}{Стена}
{371}{}{Стена}
{372}{}{Стена}
{373}{}{Стена}
{374}{}{Стена}
{375}{}{Стена}
{376}{}{Стена}
{377}{}{Стена}
{378}{}{Стена}
{379}{}{Стена}
{380}{}{Стена}
{381}{}{Стена}
{382}{}{Стена}
{383}{}{Стена}
{384}{}{Стена}
{385}{}{Стена}
{386}{}{Стена}
{387}{}{Стена}
{388}{}{Стена}
{389}{}{Стена}
{390}{}{Стена}
{391}{}{Стена}
{392}{}{Стена}
{393}{}{Стена}
{394}{}{Стена}
{395}{}{Стена}
{396}{}{Стена}
{397}{}{Стена}
{398}{}{Стена}
{399}{}{Стена}
{400}{}{Стена}
{401}{}{Стена}
{402}{}{Стена}
{403}{}{Стена}
{404}{}{Стена}
{405}{}{Стена}
{406}{}{Стена}
{407}{}{Стена}
{408}{}{Стена}
{409}{}{Стена}
{410}{}{Стена}
{411}{}{Стена}
{412}{}{Стена}
{413}{}{Стена}
{414}{}{Стена}
{415}{}{Стена}
{416}{}{Стена}
{417}{}{Стена}
{418}{}{Стена}
{419}{}{Стена}
{420}{}{Стена}
{421}{}{Стена}
{422}{}{Стена}
{423}{}{Стена}
{424}{}{Стена}
{425}{}{Стена}
{426}{}{Стена}
{427}{}{Стена}
{428}{}{Стена}
{429}{}{Стена}
{430}{}{Стена}
{431}{}{Стена}
{432}{}{Стена}
{433}{}{Стена}
{434}{}{Стена}
{435}{}{Стена}
{436}{}{Стена}
{437}{}{Стена}
{438}{}{Стена}
{439}{}{Стена}
{440}{}{Стена}
{441}{}{Стена}
{442}{}{Стена}
{443}{}{Стена}
{444}{}{Стена}
{445}{}{Стена}
{446}{}{Стена}
{447}{}{Стена}
{448}{}{Стена}
{449}{}{Стена}
{450}{}{Стена}
{451}{}{Стена}
{452}{}{Стена}
{453}{}{Стена}
{454}{}{Стена}
{455}{}{Стена}
{456}{}{Стена}
{457}{}{Стена}
{458}{}{Стена}
{459}{}{Стена}
{460}{}{Стена}
{461}{}{Стена}
{462}{}{Стена}
{463}{}{Стена}
{464}{}{Стена}
{465}{}{Стена}
{466}{}{Стена}
{467}{}{Стена}
{468}{}{Стена}
{469}{}{Стена}
{470}{}{Стена}
{471}{}{Стена}
{472}{}{Стена}
{473}{}{Стена}
{474}{}{Стена}
{475}{}{Стена}
{476}{}{Стена}
{477}{}{Стена}
{478}{}{Стена}
{479}{}{Стена}
{480}{}{Стена}
{481}{}{Стена}
{482}{}{Стена}
{483}{}{Стена}
{484}{}{Стена}
{485}{}{Стена}
{486}{}{Стена}
{487}{}{Стена}
{488}{}{Стена}
{489}{}{Стена}
{490}{}{Стена}
{491}{}{Стена}
{492}{}{Стена}
{493}{}{Стена}
{494}{}{Стена}
{495}{}{Стена}
{496}{}{Стена}
{497}{}{Стена}
{498}{}{Стена}
{499}{}{Стена}
{500}{}{Стена}
{501}{}{Стена}
{502}{}{Стена}
{503}{}{Стена}
{504}{}{Стена}
{505}{}{Стена}
{506}{}{Стена}
{507}{}{Стена}
{508}{}{Стена}
{509}{}{Стена}
{510}{}{Стена}
{511}{}{Стена}
{512}{}{Стена}
{513}{}{Стена}
{514}{}{Стена}
{515}{}{Стена}
{516}{}{Стена}
{517}{}{Стена}
{518}{}{Стена}
{519}{}{Стена}
{520}{}{Стена}
{521}{}{Стена}
{522}{}{Стена}
{523}{}{Стена}
{524}{}{Стена}
{525}{}{Стена}
{526}{}{Стена}
{527}{}{Стена}
{528}{}{Стена}
{529}{}{Стена}
{530}{}{Стена}
{531}{}{Стена}
{532}{}{Стена}
{533}{}{Стена}
{534}{}{Стена}
{535}{}{Стена}
{536}{}{Стена}
{537}{}{Стена}
{538}{}{Стена}
{539}{}{Стена}
{540}{}{Стена}
{541}{}{Стена}
{542}{}{Стена}
{543}{}{Стена}
{544}{}{Стена}
{545}{}{Стена}
{546}{}{Стена}
{547}{}{Стена}
{548}{}{Стена}
{549}{}{Стена}
{550}{}{Стена}
{551}{}{Стена}
{552}{}{Стена}
{553}{}{Стена}
{554}{}{Стена}
{555}{}{Стена}
{556}{}{Стена}
{557}{}{Стена}
{558}{}{Стена}
{559}{}{Стена}
{560}{}{Стена}
{561}{}{Стена}
{562}{}{Стена}
{563}{}{Стена}
{564}{}{Стена}
{565}{}{Стена}
{566}{}{Стена}
{567}{}{Стена}
{568}{}{Стена}
{569}{}{Стена}
{570}{}{Стена}
{571}{}{Стена}
{572}{}{Стена}
{573}{}{Стена}
{574}{}{Стена}
{575}{}{Стена}
{576}{}{Стена}
{577}{}{Стена}
{578}{}{Стена}
{579}{}{Стена}
{580}{}{Стена}
{581}{}{Стена}
{582}{}{Стена}
{583}{}{Стена}
{584}{}{Стена}
{585}{}{Стена}
{586}{}{Стена}
{587}{}{Стена}
{588}{}{Стена}
{589}{}{Стена}
{590}{}{Стена}
{591}{}{Стена}
{592}{}{Стена}
{593}{}{Стена}
{594}{}{Стена}
{595}{}{Стена}
{596}{}{Стена}
{597}{}{Стена}
{598}{}{Стена}
{599}{}{Стена}
{600}{}{Стена}
{601}{}{Стена}
{602}{}{Стена}
{603}{}{Стена}
{604}{}{Стена}
{605}{}{Стена}
{606}{}{Стена}
{607}{}{Стена}
{608}{}{Стена}
{609}{}{Стена}
{610}{}{Стена}
{611}{}{Стена}
{612}{}{Стена}
{613}{}{Стена}
{614}{}{Стена}
{615}{}{Стена}
{616}{}{Стена}
{617}{}{Стена}
{618}{}{Стена}
{619}{}{Стена}
{620}{}{Стена}
{621}{}{Стена}
{622}{}{Стена}
{623}{}{Стена}
{624}{}{Стена}
{625}{}{Стена}
{626}{}{Стена}
{627}{}{Стена}
{628}{}{Стена}
{629}{}{Стена}
{630}{}{Стена}
{631}{}{Стена}
{632}{}{Стена}
{633}{}{Стена}
{634}{}{Стена}
{635}{}{Стена}
{636}{}{Стена}
{637}{}{Стена}
{638}{}{Стена}
{639}{}{Стена}
{640}{}{Стена}
{641}{}{Стена}
{642}{}{Стена}
{643}{}{Стена}
{644}{}{Стена}
{645}{}{Стена}
{646}{}{Стена}
{647}{}{Стена}
{648}{}{Стена}
{649}{}{Стена}
{650}{}{Стена}
{651}{}{Стена}
{652}{}{Стена}
{653}{}{Стена}
{654}{}{Стена}
{655}{}{Стена}
{656}{}{Стена}
{657}{}{Стена}
{658}{}{Стена}
{659}{}{Стена}
{660}{}{Стена}
{661}{}{Стена}
{662}{}{Стена}
{663}{}{Стена}
{664}{}{Стена}
{665}{}{Стена}
{666}{}{Стена}
{667}{}{Стена}
{668}{}{Стена}
{669}{}{Стена}
{670}{}{Стена}
{671}{}{Стена}
{672}{}{Стена}
{673}{}{Стена}
{674}{}{Стена}
{675}{}{Стена}
{676}{}{Стена}
{677}{}{Стена}
{678}{}{Стена}
{679}{}{Стена}
{680}{}{Стена}
{681}{}{Стена}
{682}{}{Стена}
{683}{}{Стена}
{684}{}{Стена}
{685}{}{Стена}
{686}{}{Стена}
{687}{}{Стена}
{688}{}{Стена}
{689}{}{Стена}
{690}{}{Стена}
{691}{}{Стена}
{692}{}{Стена}
{693}{}{Стена}
{694}{}{Стена}
{695}{}{Стена}
{696}{}{Стена}
{697}{}{Стена}
{698}{}{Стена}
{699}{}{Стена}
{700}{}{Стена}
{701}{}{Стена}
{702}{}{Стена}
{703}{}{Стена}
{704}{}{Стена}
{705}{}{Стена}
{706}{}{Стена}
{707}{}{Стена}
{708}{}{Стена}
{709}{}{Стена}
{710}{}{Стена}
{711}{}{Стена}
{712}{}{Стена}
{713}{}{Стена}
{714}{}{Стена}
{715}{}{Стена}
{716}{}{Стена}
{717}{}{Стена}
{718}{}{Стена}
{719}{}{Стена}
{720}{}{Стена}
{721}{}{Стена}
{722}{}{Стена}
{723}{}{Стена}
{724}{}{Стена}
{725}{}{Стена}
{726}{}{Стена}
{727}{}{Стена}
{728}{}{Стена}
{729}{}{Стена}
{730}{}{Стена}
{731}{}{Стена}
{732}{}{Стена}
{733}{}{Стена}
{734}{}{Стена}
{735}{}{Стена}
{736}{}{Стена}
{737}{}{Стена}
{738}{}{Стена}
{739}{}{Стена}
{740}{}{Стена}
{741}{}{Стена}
{742}{}{Стена}
{743}{}{Стена}
{744}{}{Стена}
{745}{}{Стена}
{746}{}{Стена}
{747}{}{Стена}
{748}{}{Стена}
{749}{}{Стена}
{750}{}{Стена}
{751}{}{Стена}
{752}{}{Стена}
{753}{}{Стена}
{754}{}{Стена}
{755}{}{Стена}
{756}{}{Стена}
{757}{}{Стена}
{758}{}{Стена}
{759}{}{Стена}
{760}{}{Стена}
{761}{}{Стена}
{762}{}{Стена}
{763}{}{Стена}
{764}{}{Стена}
{765}{}{Стена}
{766}{}{Стена}
{767}{}{Стена}
{768}{}{Стена}
{769}{}{Стена}
{770}{}{Стена}
{771}{}{Стена}
{772}{}{Стена}
{773}{}{Стена}
{774}{}{Стена}
{775}{}{Стена}
{776}{}{Стена}
{777}{}{Стена}
{778}{}{Стена}
{779}{}{Стена}
{780}{}{Стена}
{781}{}{Стена}
{782}{}{Стена}
{783}{}{Стена}
{784}{}{Стена}
{785}{}{Стена}
{786}{}{Стена}
{787}{}{Стена}
{788}{}{Стена}
{789}{}{Стена}
{790}{}{Стена}
{791}{}{Стена}
{792}{}{Стена}
{793}{}{Стена}
{794}{}{Стена}
{795}{}{Стена}
{796}{}{Стена}
{797}{}{Стена}
{798}{}{Стена}
{799}{}{Стена}
{800}{}{Стена}
{801}{}{Стена}
{802}{}{Стена}
{803}{}{Стена}
{804}{}{Стена}
{805}{}{Стена}
{806}{}{Стена}
{807}{}{Стена}
{808}{}{Стена}
{809}{}{Стена}
{810}{}{Стена}
{811}{}{Стена}
{812}{}{Стена}
{813}{}{Стена}
{814}{}{Стена}
{815}{}{Стена}
{816}{}{Стена}
{817}{}{Стена}
{818}{}{Стена}
{819}{}{Стена}
{820}{}{Стена}
{821}{}{Стена}
{822}{}{Стена}
{823}{}{Стена}
{824}{}{Стена}
{825}{}{Стена}
{826}{}{Стена}
{827}{}{Стена}
{828}{}{Стена}
{829}{}{Стена}
{830}{}{Стена}
{831}{}{Стена}
{832}{}{Стена}
{833}{}{Стена}
{834}{}{Стена}
{835}{}{Стена}
{836}{}{Стена}
{837}{}{Стена}
{838}{}{Стена}
{839}{}{Стена}
{840}{}{Стена}
{841}{}{Стена}
{842}{}{Стена}
{843}{}{Стена}
{844}{}{Стена}
{845}{}{Стена}
{846}{}{Стена}
{847}{}{Стена}
{848}{}{Стена}
{849}{}{Стена}
{850}{}{Стена}
{851}{}{Стена}
{852}{}{Стена}
{853}{}{Стена}
{854}{}{Стена}
{855}{}{Стена}
{856}{}{Стена}
{857}{}{Стена}
{858}{}{Стена}
{859}{}{Стена}
{860}{}{Стена}
{861}{}{Стена}
{862}{}{Стена}
{863}{}{Стена}
{864}{}{Стена}
{865}{}{Стена}
{866}{}{Стена}
{867}{}{Стена}
{868}{}{Стена}
{869}{}{Стена}
{870}{}{Стена}
{871}{}{Стена}
{872}{}{Стена}
{873}{}{Стена}
{874}{}{Стена}
{875}{}{Стена}
{876}{}{Стена}
{877}{}{Стена}
{878}{}{Стена}
{879}{}{Стена}
{880}{}{Стена}
{881}{}{Стена}
{882}{}{Стена}
{883}{}{Стена}
{884}{}{Стена}
{885}{}{Стена}
{886}{}{Стена}
{887}{}{Стена}
{888}{}{Стена}
{889}{}{Стена}
{890}{}{Стена}
{891}{}{Стена}
{892}{}{Стена}
{893}{}{Стена}
{894}{}{Стена}
{895}{}{Стена}
{896}{}{Стена}
{897}{}{Стена}
{898}{}{Стена}
{899}{}{Стена}
{900}{}{Стена}
{901}{}{Стена}
{902}{}{Стена}
{903}{}{Стена}
{904}{}{Стена}
{905}{}{Стена}
{906}{}{Стена}
{907}{}{Стена}
{908}{}{Стена}
{909}{}{Стена}
{910}{}{Стена}
{911}{}{Стена}
{912}{}{Стена}
{913}{}{Стена}
{914}{}{Стена}
{915}{}{Стена}
{916}{}{Стена}
{917}{}{Стена}
{918}{}{Стена}
{919}{}{Стена}
{920}{}{Стена}
{921}{}{Стена}
{922}{}{Стена}
{923}{}{Стена}
{924}{}{Стена}
{925}{}{Стена}
{926}{}{Стена}
{927}{}{Стена}
{928}{}{Стена}
{929}{}{Стена}
{930}{}{Стена}
{931}{}{Стена}
{932}{}{Стена}
{933}{}{Стена}
{934}{}{Стена}
{935}{}{Стена}
{936}{}{Стена}
{937}{}{Стена}
{938}{}{Стена}
{939}{}{Стена}
{940}{}{Стена}
{941}{}{Стена}
{942}{}{Стена}
{943}{}{Стена}
{944}{}{Стена}
{945}{}{Стена}
{946}{}{Стена}
{947}{}{Стена}
{948}{}{Стена}
{949}{}{Стена}
{950}{}{Стена}
{951}{}{Стена}
{952}{}{Стена}
{953}{}{Стена}
{954}{}{Стена}
{955}{}{Стена}
{956}{}{Стена}
{957}{}{Стена}
{958}{}{Стена}
{959}{}{Стена}
{960}{}{Стена}
{961}{}{Стена}
{962}{}{Стена}
{963}{}{Стена}
{964}{}{Стена}
{965}{}{Стена}
{966}{}{Стена}
{967}{}{Стена}
{968}{}{Стена}
{969}{}{Стена}
{970}{}{Стена}
{971}{}{Стена}
{972}{}{Стена}
{973}{}{Стена}
{974}{}{Стена}
{975}{}{Стена}
{976}{}{Стена}
{977}{}{Стена}
{978}{}{Стена}
{979}{}{Стена}
{980}{}{Стена}
{981}{}{Стена}
{982}{}{Стена}
{983}{}{Стена}
{984}{}{Стена}
{985}{}{Стена}
{986}{}{Стена}
{987}{}{Стена}
{988}{}{Стена}
{989}{}{Стена}
{990}{}{Стена}
{991}{}{Стена}
{992}{}{Стена}
{993}{}{Стена}
{994}{}{Стена}
{995}{}{Стена}
{996}{}{Стена}
{997}{}{Стена}
{998}{}{Стена}
{999}{}{Стена}
{1000}{}{Стена}
{1001}{}{Стена}
{1002}{}{Стена}
{1003}{}{Стена}
{1004}{}{Стена}
{1005}{}{Стена}
{1006}{}{Стена}
{1007}{}{Стена}
{1008}{}{Стена}
{1009}{}{Стена}
{1010}{}{Стена}
{1011}{}{Стена}
{1012}{}{Стена}
{1013}{}{Стена}
{1014}{}{Стена}
{1015}{}{Стена}
{1016}{}{Стена}
{1017}{}{Стена}
{1018}{}{Стена}
{1019}{}{Стена}
{1020}{}{Стена}
{1021}{}{Стена}
{1022}{}{Стена}
{1023}{}{Стена}
{1024}{}{Стена}
{1025}{}{Стена}
{1026}{}{Стена}
{1027}{}{Стена}
{1028}{}{Стена}
{1029}{}{Стена}
{1030}{}{Стена}
{1031}{}{Стена}
{1032}{}{Стена}
{1033}{}{Стена}
{1034}{}{Стена}
{1035}{}{Стена}
{1036}{}{Стена}
{1037}{}{Стена}
{1038}{}{Стена}
{1039}{}{Стена}
{1040}{}{Стена}
{1041}{}{Стена}
{1042}{}{Стена}
{1043}{}{Стена}
{1044}{}{Стена}
{1045}{}{Стена}
{1046}{}{Стена}
{1047}{}{Стена}
{1048}{}{Стена}
{1049}{}{Стена}
{1050}{}{Стена}
{1051}{}{Стена}
{1052}{}{Стена}
{1053}{}{Стена}
{1054}{}{Стена}
{1055}{}{Стена}
{1056}{}{Стена}
{1057}{}{Стена}
{1058}{}{Стена}
{1059}{}{Стена}
{1060}{}{Стена}
{1061}{}{Стена}
{1062}{}{Стена}
{1063}{}{Стена}
{1064}{}{Стена}
{1065}{}{Стена}
{1066}{}{Стена}
{1067}{}{Стена}
{1068}{}{Стена}
{1069}{}{Стена}
{1070}{}{Стена}
{1071}{}{Стена}
{1072}{}{Стена}
{1073}{}{Стена}
{1074}{}{Стена}
{1075}{}{Стена}
{1076}{}{Стена}
{1077}{}{Стена}
{1078}{}{Стена}
{1079}{}{Стена}
{1080}{}{Стена}
{1081}{}{Стена}
{1082}{}{Стена}
{1083}{}{Стена}
{1084}{}{Стена}
{1085}{}{Стена}
{1086}{}{Стена}
{1087}{}{Стена}
{1088}{}{Стена}
{1089}{}{Стена}
{1090}{}{Стена}
{1091}{}{Стена}
{1092}{}{Стена}
{1093}{}{Стена}
{1094}{}{Стена}
{1095}{}{Стена}
{1096}{}{Стена}
{1097}{}{Стена}
{1098}{}{Стена}
{1099}{}{Стена}
{1100}{}{Стена}
{1101}{}{Стена}
{1102}{}{Стена}
{1103}{}{Стена}
{1104}{}{Стена}
{1105}{}{Стена}
{1106}{}{Стена}
{1107}{}{Стена}
{1108}{}{Стена}
{1109}{}{Стена}
{1110}{}{Стена}
{1111}{}{Стена}
{1112}{}{Стена}
{1113}{}{Стена}
{1114}{}{Стена}
{1115}{}{Стена}
{1116}{}{Стена}
{1117}{}{Стена}
{1118}{}{Стена}
{1119}{}{Стена}
{1120}{}{Стена}
{1121}{}{Стена}
{1122}{}{Стена}
{1123}{}{Стена}
{1124}{}{Стена}
{1125}{}{Стена}
{1126}{}{Стена}
{1127}{}{Стена}
{1128}{}{Стена}
{1129}{}{Стена}
{1130}{}{Стена}
{1131}{}{Стена}
{1132}{}{Стена}
{1133}{}{Стена}
{1134}{}{Стена}
{1135}{}{Стена}
{1136}{}{Стена}
{1137}{}{Стена}
{1138}{}{Стена}
{1139}{}{Стена}
{1140}{}{Стена}
{1141}{}{Стена}
{1142}{}{Стена}
{1143}{}{Стена}
{1144}{}{Стена}
{1145}{}{Стена}
{1146}{}{Стена}
{1147}{}{Стена}

